# Generated by Django 5.2.1 on 2024-01-01 12:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('protocol', models.CharField(choices=[('websocket', 'WebSocket'), ('mqtt', 'MQTT'), ('http', 'HTTP/REST'), ('mixed', 'Mixed Protocols')], max_length=20)),
                ('endpoint', models.CharField(max_length=200)),
                ('config', models.JSONField(default=dict, help_text='Scenario configuration (rates, jitter, failures)')),
                ('pii_redaction_rules', models.JSONField(default=dict, help_text='PII protection rules - allowlisted fields only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expected_p95_latency_ms', models.FloatField(help_text='Expected 95th percentile latency in milliseconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_error_rate', models.FloatField(help_text='Expected error rate (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRetention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_type', models.CharField(choices=[('raw_payloads', 'Raw Payloads (Never Stored)'), ('sanitized_metadata', 'Sanitized Metadata (14 days)'), ('stack_traces', 'Stack Traces (30 days)'), ('aggregated_metrics', 'Aggregated Metrics (90 days)')], max_length=30, unique=True)),
                ('days_to_keep', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('last_cleanup_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamEventArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archive_date', models.DateField()),
                ('run_ids', models.JSONField(help_text='List of archived run IDs')),
                ('event_count', models.IntegerField()),
                ('compressed_size_bytes', models.IntegerField()),
                ('storage_location', models.CharField(max_length=500)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this archive will be deleted')),
            ],
            options={
                'ordering': ['-archive_date'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('runtime_config', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict, help_text='Runtime metrics and results')),
                ('total_events', models.IntegerField(default=0)),
                ('successful_events', models.IntegerField(default=0)),
                ('failed_events', models.IntegerField(default=0)),
                ('anomalies_detected', models.IntegerField(default=0)),
                ('p50_latency_ms', models.FloatField(blank=True, null=True)),
                ('p95_latency_ms', models.FloatField(blank=True, null=True)),
                ('p99_latency_ms', models.FloatField(blank=True, null=True)),
                ('error_rate', models.FloatField(blank=True, null=True)),
                ('throughput_qps', models.FloatField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='streamlab.testscenario')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('message_correlation_id', models.UUIDField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('endpoint', models.CharField(max_length=200)),
                ('channel_topic', models.CharField(blank=True, max_length=100)),
                ('latency_ms', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('message_size_bytes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('anomaly', 'Anomaly')], default='success', max_length=20)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('payload_sanitized', models.JSONField(help_text='Sanitized payload with PII removed/hashed')),
                ('payload_schema_hash', models.CharField(help_text='Hash of payload schema for anomaly detection', max_length=64)),
                ('stack_trace_hash', models.CharField(blank=True, max_length=64)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='streamlab.testrun')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='testscenario',
            index=models.Index(fields=['protocol', 'is_active'], name='streamlab_testscenario_protocol_active_idx'),
        ),
        migrations.AddIndex(
            model_name='testscenario',
            index=models.Index(fields=['created_at'], name='streamlab_testscenario_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['scenario', 'status'], name='streamlab_testrun_scenario_status_idx'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['started_at'], name='streamlab_testrun_started_at_idx'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['status', 'started_at'], name='streamlab_testrun_status_started_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['run', 'timestamp'], name='streamlab_streamevent_run_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['correlation_id'], name='streamlab_streamevent_correlation_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['outcome', 'timestamp'], name='streamlab_streamevent_outcome_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['latency_ms'], name='streamlab_streamevent_latency_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['payload_schema_hash'], name='streamlab_streamevent_schema_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='streameventarchive',
            index=models.Index(fields=['archive_date'], name='streamlab_streameventarchive_archive_date_idx'),
        ),
        migrations.AddIndex(
            model_name='streameventarchive',
            index=models.Index(fields=['expires_at'], name='streamlab_streameventarchive_expires_at_idx'),
        ),
    ]