# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRetention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "retention_type",
                    models.CharField(
                        choices=[
                            ("raw_payloads", "Raw Payloads (Never Stored)"),
                            ("sanitized_metadata", "Sanitized Metadata (14 days)"),
                            ("stack_traces", "Stack Traces (30 days)"),
                            ("aggregated_metrics", "Aggregated Metrics (90 days)"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "days_to_keep",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("last_cleanup_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Event Retention Policy",
                "verbose_name_plural": "Event Retention Policies",
                "ordering": ["retention_type"],
                "indexes": [
                    models.Index(
                        fields=["retention_type"], name="streamlab_e_retenti_209456_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StreamEventArchive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("archive_date", models.DateField()),
                ("run_ids", models.JSONField(help_text="List of archived run IDs")),
                ("event_count", models.IntegerField()),
                ("compressed_size_bytes", models.IntegerField()),
                ("storage_location", models.CharField(max_length=500)),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this archive will be deleted"),
                ),
            ],
            options={
                "verbose_name": "Stream Event Archive",
                "verbose_name_plural": "Stream Event Archives",
                "ordering": ["-archive_date"],
                "indexes": [
                    models.Index(
                        fields=["archive_date"], name="streamlab_s_archive_4028d6_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="streamlab_s_expires_d8c2a5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TestScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("websocket", "WebSocket"),
                            ("mqtt", "MQTT"),
                            ("http", "HTTP/REST"),
                            ("mixed", "Mixed Protocols"),
                        ],
                        max_length=20,
                    ),
                ),
                ("endpoint", models.CharField(max_length=200)),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Scenario configuration (rates, jitter, failures)",
                    ),
                ),
                (
                    "pii_redaction_rules",
                    models.JSONField(
                        default=dict,
                        help_text="PII protection rules - allowlisted fields only",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expected_p95_latency_ms",
                    models.FloatField(
                        help_text="Expected 95th percentile latency in milliseconds",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "expected_error_rate",
                    models.FloatField(
                        help_text="Expected error rate (0.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("runtime_config", models.JSONField(default=dict)),
                (
                    "metrics",
                    models.JSONField(
                        default=dict, help_text="Runtime metrics and results"
                    ),
                ),
                ("total_events", models.IntegerField(default=0)),
                ("successful_events", models.IntegerField(default=0)),
                ("failed_events", models.IntegerField(default=0)),
                ("anomalies_detected", models.IntegerField(default=0)),
                ("p50_latency_ms", models.FloatField(blank=True, null=True)),
                ("p95_latency_ms", models.FloatField(blank=True, null=True)),
                ("p99_latency_ms", models.FloatField(blank=True, null=True)),
                ("error_rate", models.FloatField(blank=True, null=True)),
                ("throughput_qps", models.FloatField(blank=True, null=True)),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="streamlab.testscenario",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StreamEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("correlation_id", models.UUIDField(db_index=True)),
                ("message_correlation_id", models.UUIDField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                ("endpoint", models.CharField(max_length=200)),
                ("channel_topic", models.CharField(blank=True, max_length=100)),
                (
                    "latency_ms",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "message_size_bytes",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                            ("anomaly", "Anomaly"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("http_status_code", models.IntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                (
                    "payload_sanitized",
                    models.JSONField(
                        help_text="Sanitized payload with PII removed/hashed"
                    ),
                ),
                (
                    "payload_schema_hash",
                    models.CharField(
                        help_text="Hash of payload schema for anomaly detection",
                        max_length=64,
                    ),
                ),
                ("stack_trace_hash", models.CharField(blank=True, max_length=64)),
                (
                    "visual_baseline_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of visual baseline for regression detection",
                        max_length=64,
                    ),
                ),
                (
                    "visual_diff_score",
                    models.FloatField(
                        blank=True,
                        help_text="Visual difference score (0.0 = identical, 1.0 = completely different)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "visual_diff_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Visual diff analysis metadata (regions changed, severity, etc.)",
                        null=True,
                    ),
                ),
                (
                    "performance_metrics",
                    models.JSONField(
                        blank=True,
                        help_text="Extended performance metrics (frame times, memory usage, battery impact)",
                        null=True,
                    ),
                ),
                (
                    "jank_score",
                    models.FloatField(
                        blank=True,
                        help_text="UI jank score - higher values indicate more jank",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "composition_time_ms",
                    models.FloatField(
                        blank=True,
                        help_text="Compose composition time in milliseconds",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "client_app_version",
                    models.CharField(
                        blank=True,
                        help_text="Mobile app version (e.g., 1.2.3)",
                        max_length=50,
                    ),
                ),
                (
                    "client_os_version",
                    models.CharField(
                        blank=True,
                        help_text="Mobile OS version (e.g., Android 13, iOS 16.1)",
                        max_length=50,
                    ),
                ),
                (
                    "client_device_model",
                    models.CharField(
                        blank=True,
                        help_text="Mobile device model (e.g., iPhone 14, Samsung Galaxy S23)",
                        max_length=100,
                    ),
                ),
                (
                    "device_context",
                    models.JSONField(
                        blank=True,
                        help_text="Extended device context (battery, memory, network state)",
                        null=True,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="streamlab.testrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["run", "timestamp"],
                        name="streamlab_s_run_id_99cb45_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="streamlab_s_correla_bd48ed_idx"
                    ),
                    models.Index(
                        fields=["outcome", "timestamp"],
                        name="streamlab_s_outcome_a6c3ca_idx",
                    ),
                    models.Index(
                        fields=["latency_ms"], name="streamlab_s_latency_8bea39_idx"
                    ),
                    models.Index(
                        fields=["payload_schema_hash"],
                        name="streamlab_s_payload_ca537d_idx",
                    ),
                    models.Index(
                        fields=["visual_baseline_hash"],
                        name="streamlab_s_visual__8b27bc_idx",
                    ),
                    models.Index(
                        fields=["visual_diff_score"],
                        name="streamlab_s_visual__656a47_idx",
                    ),
                    models.Index(
                        fields=["visual_diff_score", "timestamp"],
                        name="streamlab_s_visual__676a7d_idx",
                    ),
                    models.Index(
                        fields=["jank_score"], name="streamlab_s_jank_sc_f41faf_idx"
                    ),
                    models.Index(
                        fields=["composition_time_ms"],
                        name="streamlab_s_composi_52eb89_idx",
                    ),
                    models.Index(
                        fields=["client_app_version", "timestamp"],
                        name="streamlab_s_client__0e57a4_idx",
                    ),
                    models.Index(
                        fields=["client_os_version", "timestamp"],
                        name="streamlab_s_client__422dfd_idx",
                    ),
                    models.Index(
                        fields=["client_device_model", "timestamp"],
                        name="streamlab_s_client__1af3d9_idx",
                    ),
                    models.Index(
                        fields=["outcome", "visual_diff_score", "timestamp"],
                        name="streamlab_s_outcome_a533f2_idx",
                    ),
                    models.Index(
                        fields=["client_app_version", "outcome", "timestamp"],
                        name="streamlab_s_client__4d33fd_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="testscenario",
            index=models.Index(
                fields=["protocol", "is_active"], name="streamlab_t_protoco_675722_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testscenario",
            index=models.Index(
                fields=["created_at"], name="streamlab_t_created_5e29f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testrun",
            index=models.Index(
                fields=["scenario", "status"], name="streamlab_t_scenari_c23bb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testrun",
            index=models.Index(
                fields=["started_at"], name="streamlab_t_started_e1e9f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testrun",
            index=models.Index(
                fields=["status", "started_at"], name="streamlab_t_status_15d515_idx"
            ),
        ),
    ]
