# Generated by Django 5.2.1
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('streamlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamevent',
            name='visual_baseline_hash',
            field=models.CharField(blank=True, help_text='Hash of visual baseline for regression detection', max_length=64),
        ),
        migrations.AddField(
            model_name='streamevent',
            name='visual_diff_score',
            field=models.FloatField(blank=True, help_text='Visual difference score (0.0 = identical, 1.0 = completely different)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='streamevent',
            name='visual_diff_metadata',
            field=models.JSONField(blank=True, help_text='Visual diff analysis metadata (regions changed, severity, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='streamevent',
            name='performance_metrics',
            field=models.JSONField(blank=True, help_text='Extended performance metrics (frame times, memory usage, battery impact)', null=True),
        ),
        migrations.AddField(
            model_name='streamevent',
            name='jank_score',
            field=models.FloatField(blank=True, help_text='UI jank score - higher values indicate more jank', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='streamevent',
            name='composition_time_ms',
            field=models.FloatField(blank=True, help_text='Compose composition time in milliseconds', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='streamevent',
            name='client_app_version',
            field=models.CharField(blank=True, help_text='Mobile app version (e.g., 1.2.3)', max_length=50),
        ),
        migrations.AddField(
            model_name='streamevent',
            name='client_os_version',
            field=models.CharField(blank=True, help_text='Mobile OS version (e.g., Android 13, iOS 16.1)', max_length=50),
        ),
        migrations.AddField(
            model_name='streamevent',
            name='client_device_model',
            field=models.CharField(blank=True, help_text='Mobile device model (e.g., iPhone 14, Samsung Galaxy S23)', max_length=100),
        ),
        migrations.AddField(
            model_name='streamevent',
            name='device_context',
            field=models.JSONField(blank=True, help_text='Extended device context (battery, memory, network state)', null=True),
        ),
        # Phase 2: Visual regression indexes
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['visual_baseline_hash'], name='streamlab_s_visual_66a8da_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['visual_diff_score'], name='streamlab_s_visual_bc4c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['visual_diff_score', 'timestamp'], name='streamlab_s_visual_d2f7eb_idx'),
        ),
        # Phase 2: Mobile performance indexes
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['jank_score'], name='streamlab_s_jank_sc_c7d8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['composition_time_ms'], name='streamlab_s_composi_ae9c42_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['client_app_version', 'timestamp'], name='streamlab_s_client__5f2b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['client_os_version', 'timestamp'], name='streamlab_s_client__8a3c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['client_device_model', 'timestamp'], name='streamlab_s_client__1e9f6b_idx'),
        ),
        # Combined indexes for trend analysis
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['outcome', 'visual_diff_score', 'timestamp'], name='streamlab_s_outcome_4d7c29_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['client_app_version', 'outcome', 'timestamp'], name='streamlab_s_client__b8e1a5_idx'),
        ),
    ]