# Generated by Django 5.2.1 on 2025-09-04 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_brands', to='core_onboarding.typeassist', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='asset',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_bus', to='client_onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_categories', to='core_onboarding.typeassist', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='asset',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_clients', to='client_onboarding.bt', verbose_name='Client'),
        ),
    ]
