# Generated by Django 5.2.7 on 2025-11-09 10:20

import apps.activity.managers.job.jobneed_details_manager
import apps.activity.managers.job.jobneed_manager
import apps.activity.models.ppm_schedule
import apps.activity.models.tour
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activity", "0002_initial"),
        ("client_onboarding", "0002_initial"),
        ("core_onboarding", "0001_initial"),
        ("peoples", "0001_initial"),
        ("tenants", "0001_initial"),
        ("y_helpdesk", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.asset",
                verbose_name="Belongs to",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="servprov",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="asset_serv_providers",
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="asset_subcategories",
                to="core_onboarding.typeassist",
                verbose_name="Sub Category",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="asset_types",
                to="core_onboarding.typeassist",
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="asset_units",
                to="core_onboarding.typeassist",
                verbose_name="Unit",
            ),
        ),
        migrations.AddField(
            model_name="assetfieldhistory",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_history",
                to="activity.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="assetfieldhistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Changed By",
            ),
        ),
        migrations.AddField(
            model_name="assetfieldhistory",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="assetfieldhistory",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="assetfieldhistory",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="assethealthscore",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_scores",
                to="activity.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="assethealthscore",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="assethealthscore",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="assethealthscore",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="assetlifecyclestage",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lifecycle_stages",
                to="activity.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="assetlifecyclestage",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="assetlifecyclestage",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="assetlifecyclestage",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="assetlifecyclestage",
            name="transitioned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Transitioned By",
            ),
        ),
        migrations.AddField(
            model_name="assetlog",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="assetlog",
            name="bu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="client_onboarding.bt",
                verbose_name="Bu",
            ),
        ),
        migrations.AddField(
            model_name="assetlog",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assetlog_client",
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="assetlog",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="assetlog",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="assetlog",
            name="people",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="People",
            ),
        ),
        migrations.AddField(
            model_name="assetlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="assetutilizationmetric",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="utilization_metrics",
                to="activity.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="assetutilizationmetric",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="assetutilizationmetric",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="assetutilizationmetric",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="bu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="ownername",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core_onboarding.typeassist",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="deviceeventlog",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="deviceeventlog",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="deviveevents_clients",
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="deviceeventlog",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="deviceeventlog",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="deviceeventlog",
            name="people",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="deviceevent_people",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_bus",
                to="client_onboarding.bt",
                verbose_name="Site",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_clients",
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="geofence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core_onboarding.geofencemaster",
                verbose_name="Geofence",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.job",
                verbose_name="Belongs to",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="people",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_aaatops",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aggresive auto-assign to People",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="pgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_pgroup",
                to="peoples.pgroup",
                verbose_name="People Group",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="sgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_sgroup",
                to="peoples.pgroup",
                verbose_name="Site Group",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="shift",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_shifts",
                to="client_onboarding.shift",
                verbose_name="Shift",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="ticketcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_tktcategories",
                to="core_onboarding.typeassist",
                verbose_name="Notify Category",
            ),
        ),
        migrations.CreateModel(
            name="PPMSchedule",
            fields=[],
            options={
                "verbose_name": "PPM Schedule",
                "verbose_name_plural": "PPM Schedules",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("activity.job",),
            managers=[
                ("objects", apps.activity.models.ppm_schedule.PPMScheduleManager()),
            ],
        ),
        migrations.AddField(
            model_name="jobneed",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="jobneed_assets",
                to="activity.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="jobneedf_bus",
                to="client_onboarding.bt",
                verbose_name="Site",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="jobneed_clients",
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="jobs",
                to="activity.job",
                verbose_name="Job",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.jobneed",
                verbose_name="Belongs to",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="people",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="People",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="performedby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="jobneed_performedby",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Performed by",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="pgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="jobneed_pgroup",
                to="peoples.pgroup",
                verbose_name="People Group",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="remarkstype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="remark_types",
                to="core_onboarding.typeassist",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="sgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="jobneed_sgroup",
                to="peoples.pgroup",
                verbose_name="Site Group",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="jobneed_ticket",
                to="y_helpdesk.ticket",
                verbose_name="Ticket",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="ticketcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core_onboarding.typeassist",
                verbose_name="Notify Category",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("activity.jobneed",),
            managers=[
                (
                    "objects",
                    apps.activity.managers.job.jobneed_manager.JobneedManager(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[],
            options={
                "verbose_name": "Tour",
                "verbose_name_plural": "Tours",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("activity.jobneed",),
            managers=[
                ("objects", apps.activity.models.tour.TourManager()),
            ],
        ),
        migrations.AddField(
            model_name="jobneeddetails",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="jobneeddetails",
            name="jobneed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.jobneed",
                verbose_name="Jobneed",
            ),
        ),
        migrations.AddField(
            model_name="jobneeddetails",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="jobneeddetails",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("activity.jobneeddetails",),
            managers=[
                (
                    "objects",
                    apps.activity.managers.job.jobneed_details_manager.JobneedDetailsManager(),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jobworkflowauditlog",
            name="changed_by",
            field=models.ForeignKey(
                help_text="User or system that made the change",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="job_workflow_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jobworkflowauditlog",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="jobworkflowauditlog",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent job (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_audit_logs",
                to="activity.job",
            ),
        ),
        migrations.AddField(
            model_name="jobworkflowauditlog",
            name="jobneed",
            field=models.ForeignKey(
                help_text="Jobneed that was modified",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_audit_logs",
                to="activity.jobneed",
            ),
        ),
        migrations.AddField(
            model_name="jobworkflowauditlog",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="jobworkflowauditlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="location_bus",
                to="client_onboarding.bt",
                verbose_name="Site",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="location_clients",
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.location",
                verbose_name="Belongs to",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="location_types",
                to="core_onboarding.typeassist",
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.location",
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="maintenancecosttracking",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_costs",
                to="activity.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="maintenancecosttracking",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="maintenancecosttracking",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="maintenancecosttracking",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_work",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Performed By",
            ),
        ),
        migrations.AddField(
            model_name="maintenancecosttracking",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="meterreading",
            name="asset",
            field=models.ForeignKey(
                help_text="Asset this reading belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="activity.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="meterreading",
            name="captured_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who captured/submitted the reading",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Captured By",
            ),
        ),
        migrations.AddField(
            model_name="meterreading",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="meterreading",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="meterreading",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="meterreading",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who validated the reading",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_readings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validated By",
            ),
        ),
        migrations.AddField(
            model_name="meterreadingalert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Acknowledged By",
            ),
        ),
        migrations.AddField(
            model_name="meterreadingalert",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="activity.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="meterreadingalert",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="meterreadingalert",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="meterreadingalert",
            name="reading",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="activity.meterreading",
                verbose_name="Related Reading",
            ),
        ),
        migrations.AddField(
            model_name="meterreadingalert",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nfcdevice",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nfcdevice",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical location of the device",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nfc_devices",
                to="core_onboarding.typeassist",
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="nfcdevice",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nfcdevice",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nfcscanlog",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nfcscanlog",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_logs",
                to="activity.nfcdevice",
                verbose_name="NFC Device",
            ),
        ),
        migrations.AddField(
            model_name="nfcscanlog",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nfcscanlog",
            name="scan_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location where scan occurred",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core_onboarding.typeassist",
                verbose_name="Scan Location",
            ),
        ),
        migrations.AddField(
            model_name="nfcscanlog",
            name="scanned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nfc_scans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Scanned By",
            ),
        ),
        migrations.AddField(
            model_name="nfcscanlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nfctag",
            name="asset",
            field=models.ForeignKey(
                help_text="Asset this tag is bound to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nfc_tags",
                to="activity.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="nfctag",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nfctag",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nfctag",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nfcscanlog",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_logs",
                to="activity.nfctag",
                verbose_name="NFC Tag",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="category_types",
                to="core_onboarding.typeassist",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="unit_types",
                to="core_onboarding.typeassist",
                verbose_name="Unit",
            ),
        ),
        migrations.AddField(
            model_name="jobneeddetails",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.question",
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="questionset",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="qset_bus",
                to="client_onboarding.bt",
                verbose_name="Site",
            ),
        ),
        migrations.AddField(
            model_name="questionset",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="qset_clients",
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="questionset",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="questionset",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="questionset",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.questionset",
                verbose_name="Belongs To",
            ),
        ),
        migrations.AddField(
            model_name="questionset",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="jobneeddetails",
            name="qset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="questions_qset",
                to="activity.questionset",
                verbose_name="Question Set",
            ),
        ),
        migrations.AddField(
            model_name="jobneed",
            name="qset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.questionset",
                verbose_name="QuestionSet",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="qset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.questionset",
                verbose_name="QuestionSet",
            ),
        ),
        migrations.AddField(
            model_name="questionsetbelonging",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="qsetbelong_bu",
                to="client_onboarding.bt",
                verbose_name="Site",
            ),
        ),
        migrations.AddField(
            model_name="questionsetbelonging",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="qsetbelong_client",
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="questionsetbelonging",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="questionsetbelonging",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="questionsetbelonging",
            name="qset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.questionset",
                verbose_name="Question Set",
            ),
        ),
        migrations.AddField(
            model_name="questionsetbelonging",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="activity.question",
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="questionsetbelonging",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="vehicleentry",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Person who approved the entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_vehicle_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved By",
            ),
        ),
        migrations.AddField(
            model_name="vehicleentry",
            name="associated_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee or registered person",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicle_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Associated Person",
            ),
        ),
        migrations.AddField(
            model_name="vehicleentry",
            name="captured_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Security personnel who processed entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captured_vehicle_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Captured By",
            ),
        ),
        migrations.AddField(
            model_name="vehicleentry",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="vehicleentry",
            name="gate_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Gate or entrance where detected",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="activity.location",
                verbose_name="Gate Location",
            ),
        ),
        migrations.AddField(
            model_name="vehicleentry",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="vehicleentry",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="vehiclesecurityalert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Acknowledged By",
            ),
        ),
        migrations.AddField(
            model_name="vehiclesecurityalert",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="vehiclesecurityalert",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="vehiclesecurityalert",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="vehiclesecurityalert",
            name="vehicle_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="activity.vehicleentry",
                verbose_name="Vehicle Entry",
            ),
        ),
        migrations.AddIndex(
            model_name="assetfieldhistory",
            index=models.Index(
                fields=["tenant", "asset", "cdtz"],
                name="activity_as_tenant__dbab3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetfieldhistory",
            index=models.Index(
                fields=["tenant", "field_name", "cdtz"],
                name="activity_as_tenant__e627d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetfieldhistory",
            index=models.Index(
                fields=["tenant", "changed_by", "cdtz"],
                name="activity_as_tenant__ddeee9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetfieldhistory",
            index=models.Index(
                fields=["correlation_id"], name="activity_as_correla_216b62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetfieldhistory",
            index=models.Index(fields=["cdtz"], name="activity_as_cdtz_8581a6_idx"),
        ),
        migrations.AddIndex(
            model_name="assethealthscore",
            index=models.Index(
                fields=["tenant", "asset", "calculated_date"],
                name="activity_as_tenant__b17239_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assethealthscore",
            index=models.Index(
                fields=["tenant", "risk_level"], name="activity_as_tenant__d55563_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assethealthscore",
            index=models.Index(
                fields=["health_score"], name="activity_as_health__6a8817_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assethealthscore",
            unique_together={("tenant", "asset", "calculated_date")},
        ),
        migrations.AddIndex(
            model_name="assetlifecyclestage",
            index=models.Index(
                fields=["tenant", "asset", "is_current"],
                name="activity_as_tenant__486632_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetlifecyclestage",
            index=models.Index(
                fields=["tenant", "stage", "cdtz"],
                name="activity_as_tenant__c78c89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetlifecyclestage",
            index=models.Index(
                fields=["stage_started"], name="activity_as_stage_s_672baa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetlog",
            index=models.Index(
                fields=["tenant", "asset"], name="assetlog_tenant_asset_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetlog",
            index=models.Index(
                fields=["tenant", "cdtz"], name="assetlog_tenant_cdtz_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetutilizationmetric",
            index=models.Index(
                fields=["tenant", "asset", "date"],
                name="activity_as_tenant__0effc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetutilizationmetric",
            index=models.Index(
                fields=["tenant", "date"], name="activity_as_tenant__46225a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetutilizationmetric",
            index=models.Index(
                fields=["utilization_percentage"], name="activity_as_utiliza_e8e43d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assetutilizationmetric",
            unique_together={("tenant", "asset", "date")},
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(fields=["owner"], name="attachment_owner_2d685e_idx"),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["attachmenttype", "datetime"],
                name="attachment_attachm_6b33f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["bu", "datetime"], name="attachment_bu_id_1d9131_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceeventlog",
            index=models.Index(
                fields=["deviceid", "receivedon"], name="deviceevent_devicei_0b469f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceeventlog",
            index=models.Index(
                fields=["eventvalue", "receivedon"],
                name="deviceevent_eventva_9d1855_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deviceeventlog",
            index=models.Index(
                fields=["people", "receivedon"], name="deviceevent_people__d878a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobworkflowauditlog",
            index=models.Index(
                fields=["jobneed", "change_timestamp"], name="audit_jobneed_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobworkflowauditlog",
            index=models.Index(
                fields=["operation_type", "change_timestamp"], name="audit_op_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobworkflowauditlog",
            index=models.Index(
                fields=["changed_by", "change_timestamp"], name="audit_user_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobworkflowauditlog",
            index=models.Index(
                fields=["old_status", "new_status"], name="audit_status_transition_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["locname"], name="location_locname_c2ed0a_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["loccode"], name="location_loccode_8f45ed_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["client", "bu"], name="location_client__62eb8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["locstatus"], name="location_locstat_d0b780_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("loccode", "bu", "client"), name="loccode_bu_client_uk"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["tenant", "cdtz"], name="asset_tenant_cdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["tenant", "identifier"], name="asset_tenant_identifier_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["tenant", "enable"], name="asset_tenant_enable_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("tenant", "assetcode", "bu", "client"),
                name="tenant_assetcode_client_uk",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancecosttracking",
            index=models.Index(
                fields=["tenant", "asset", "maintenance_date"],
                name="activity_ma_tenant__244b25_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancecosttracking",
            index=models.Index(
                fields=["tenant", "cost_type", "maintenance_date"],
                name="activity_ma_tenant__fc6224_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancecosttracking",
            index=models.Index(
                fields=["maintenance_date"], name="activity_ma_mainten_c401d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meterreading",
            index=models.Index(
                fields=["asset", "-reading_timestamp"],
                name="activity_me_asset_i_4d5b38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meterreading",
            index=models.Index(
                fields=["meter_type", "-reading_timestamp"],
                name="activity_me_meter_t_f42945_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meterreading",
            index=models.Index(
                fields=["status", "is_anomaly"], name="activity_me_status_d8aa27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meterreading",
            index=models.Index(
                fields=["image_hash"], name="activity_me_image_h_2cc18f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meterreading",
            index=models.Index(fields=["-cdtz"], name="activity_me_cdtz_4806b6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="meterreading",
            unique_together={("asset", "reading_timestamp")},
        ),
        migrations.AddIndex(
            model_name="meterreadingalert",
            index=models.Index(
                fields=["asset", "-cdtz"], name="activity_me_asset_i_780cf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meterreadingalert",
            index=models.Index(
                fields=["alert_type", "severity"], name="activity_me_alert_t_390170_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meterreadingalert",
            index=models.Index(
                fields=["is_acknowledged", "-cdtz"],
                name="activity_me_is_ackn_f2d95b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nfcdevice",
            index=models.Index(
                fields=["tenant", "device_id"], name="activity_nf_tenant__ef6c58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nfcdevice",
            index=models.Index(
                fields=["tenant", "status"], name="activity_nf_tenant__abd0cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nfcdevice",
            index=models.Index(
                fields=["location"], name="activity_nf_locatio_706c2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nfctag",
            index=models.Index(
                fields=["tenant", "tag_uid"], name="activity_nf_tenant__e6671d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nfctag",
            index=models.Index(
                fields=["tenant", "asset"], name="activity_nf_tenant__a6f3db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nfctag",
            index=models.Index(
                fields=["tenant", "status"], name="activity_nf_tenant__dc6c0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nfctag",
            index=models.Index(
                fields=["last_scan"], name="activity_nf_last_sc_2f46ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nfcscanlog",
            index=models.Index(
                fields=["tenant", "tag", "cdtz"], name="activity_nf_tenant__31fc9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nfcscanlog",
            index=models.Index(
                fields=["tenant", "device", "cdtz"],
                name="activity_nf_tenant__4e0331_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nfcscanlog",
            index=models.Index(
                fields=["tenant", "scanned_by", "cdtz"],
                name="activity_nf_tenant__7881ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nfcscanlog",
            index=models.Index(
                fields=["scan_type"], name="activity_nf_scan_ty_8cb002_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nfcscanlog",
            index=models.Index(fields=["cdtz"], name="activity_nf_cdtz_16030d_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["mdtz"], name="question_mdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["cdtz"], name="question_cdtz_idx"),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("quesname", "answertype", "client"),
                name="ques_name_type_client_uk",
            ),
        ),
        migrations.AddIndex(
            model_name="questionset",
            index=models.Index(fields=["mdtz"], name="questionset_mdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="questionset",
            index=models.Index(fields=["cdtz"], name="questionset_cdtz_idx"),
        ),
        migrations.AddConstraint(
            model_name="questionset",
            constraint=models.UniqueConstraint(
                fields=("qsetname", "parent", "type", "client", "bu"),
                name="name_type_parent_type_client_bu_uk",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionset",
            constraint=models.CheckConstraint(
                condition=models.Q(("seqno__gte", 0)), name="slno_gte_0_ck"
            ),
        ),
        migrations.AddIndex(
            model_name="jobneeddetails",
            index=models.Index(
                fields=["tenant", "jobneed"], name="jnd_tenant_jobneed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobneeddetails",
            index=models.Index(
                fields=["tenant", "question"], name="jnd_tenant_question_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobneeddetails",
            constraint=models.UniqueConstraint(
                fields=("tenant", "jobneed", "question"),
                name="tenant_jobneeddetails_jobneed_question_uk",
                violation_error_message="Duplicate question not allowed for the same jobneed. Each question can only appear once per jobneed.",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobneeddetails",
            constraint=models.UniqueConstraint(
                fields=("tenant", "jobneed", "seqno"),
                name="tenant_jobneeddetails_jobneed_seqno_uk",
                violation_error_message="Duplicate sequence number not allowed for the same jobneed. Each seqno must be unique within a jobneed.",
            ),
        ),
        migrations.AddIndex(
            model_name="jobneed",
            index=models.Index(
                fields=["tenant", "cdtz"], name="jobneed_tenant_cdtz_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobneed",
            index=models.Index(
                fields=["tenant", "jobstatus"], name="jobneed_tenant_jobstatus_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobneed",
            index=models.Index(
                fields=["tenant", "people"], name="jobneed_tenant_people_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobneed",
            constraint=models.CheckConstraint(
                condition=models.Q(("gracetime__gte", 0)),
                name="jobneed_gracetime_gte_0_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["tenant", "cdtz"], name="job_tenant_cdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["tenant", "identifier"], name="job_tenant_identifier_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["tenant", "enable"], name="job_tenant_enable_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["people", "identifier"], name="job_people_identifier_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=(
                    "tenant",
                    "jobname",
                    "asset",
                    "qset",
                    "parent",
                    "identifier",
                    "client",
                ),
                name="tenant_jobname_asset_qset_parent_identifier_client_uk",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("gracetime__gte", 0)), name="gracetime_gte_0_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("planduration__gte", 0)),
                name="planduration_gte_0_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("expirytime__gte", 0)), name="expirytime_gte_0_ck"
            ),
        ),
        migrations.AddIndex(
            model_name="questionsetbelonging",
            index=models.Index(fields=["mdtz"], name="questionsetbelonging_mdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="questionsetbelonging",
            index=models.Index(fields=["cdtz"], name="questionsetbelonging_cdtz_idx"),
        ),
        migrations.AddConstraint(
            model_name="questionsetbelonging",
            constraint=models.UniqueConstraint(
                fields=("qset", "question", "client", "bu"),
                name="qset_question_client_bu_uk",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleentry",
            index=models.Index(
                fields=["license_plate_clean", "-entry_timestamp"],
                name="activity_ve_license_438d9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleentry",
            index=models.Index(
                fields=["entry_type", "-entry_timestamp"],
                name="activity_ve_entry_t_82145c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleentry",
            index=models.Index(
                fields=["status", "is_blacklisted"],
                name="activity_ve_status_13be2f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleentry",
            index=models.Index(
                fields=["gate_location", "-entry_timestamp"],
                name="activity_ve_gate_lo_8e37c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleentry",
            index=models.Index(
                fields=["image_hash"], name="activity_ve_image_h_80eee5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleentry",
            index=models.Index(fields=["-cdtz"], name="activity_ve_cdtz_0cdf00_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclesecurityalert",
            index=models.Index(
                fields=["license_plate", "-cdtz"], name="activity_ve_license_aceae7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclesecurityalert",
            index=models.Index(
                fields=["alert_type", "severity"], name="activity_ve_alert_t_ff680a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclesecurityalert",
            index=models.Index(
                fields=["is_acknowledged", "-cdtz"],
                name="activity_ve_is_ackn_aeb658_idx",
            ),
        ),
    ]
