# Generated by Django 5.2.1 on 2025-09-12 09:51

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsetbelonging',
            name='display_conditions',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON structure for conditional display logic', null=True, verbose_name='Display Conditions'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('QUESTIONSET', 'Question Set'), ('CHECKLIST', 'Checklist'), ('RPCHECKLIST', 'RP Checklist'), ('INCIDENTREPORT', 'Incident Report'), ('SITEREPORT', 'Site Report'), ('WORKPERMIT', 'Work Permit'), ('RETURN_WORK_PERMIT', 'Return Work Permit'), ('KPITEMPLATE', 'Kpi'), ('SCRAPPEDTEMPLATE', 'Scrapped'), ('ASSETAUDIT', 'Asset Audit'), ('ASSETMAINTENANCE', 'Asset Maintenance'), ('WORK_ORDER', 'Work Order'), ('SLA_TEMPLATE', 'Service Level Agreement'), ('POSTING_ORDER', 'Posting Order'), ('SITESURVEY', 'SITESURVEY')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
