# Generated by Django 5.2.1 on 2025-09-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_add_display_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneed',
            name='identifier',
            field=models.CharField(choices=[('TASK', 'Task'), ('TICKET', 'Ticket'), ('INTERNALTOUR', 'Internal Tour'), ('EXTERNALTOUR', 'External Tour'), ('PPM', 'PPM'), ('OTHER', 'Other'), ('SITEREPORT', 'Site Report'), ('INCIDENTREPORT', 'Incident Report'), ('ASSETLOG', 'Asset Log'), ('ASSETAUDIT', 'Asset Audit'), ('ASSETMAINTENANCE', 'Asset Maintenance'), ('POSTING_ORDER', 'Posting Order'), ('SITESURVEY', 'Site Survey')], max_length=50, null=True, verbose_name='Jobneed Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answertype',
            field=models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('EMAILID', 'Email Id'), ('MULTILINE', 'Multiline'), ('NUMERIC', 'Numeric'), ('SIGNATURE', 'Signature'), ('SINGLELINE', 'Single Line'), ('TIME', 'Time'), ('RATING', 'Rating'), ('PEOPLELIST', 'People List'), ('SITELIST', 'Site List'), ('METERREADING', 'Meter Reading'), ('MULTISELECT', 'Multi Select'), ('GPSLOCATION', 'GPSLOCATION')], default='NUMERIC', max_length=55, verbose_name='Type'),
        ),
    ]
