# Generated by Django 5.2.1 on 2025-09-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_jobneed_identifier_alter_question_answertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobneeddetails',
            name='transcript',
            field=models.TextField(blank=True, null=True, verbose_name='Audio Transcript'),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='transcript_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('PENDING', 'Pending'),
                    ('PROCESSING', 'Processing'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                ],
                max_length=20,
                null=True,
                verbose_name='Transcript Status'
            ),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='transcript_language',
            field=models.CharField(
                blank=True,
                default='en-US',
                help_text="Language code used for transcription (e.g., 'en-US', 'hi-IN')",
                max_length=10,
                null=True,
                verbose_name='Transcript Language'
            ),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='transcript_processed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Timestamp when transcript processing completed',
                null=True,
                verbose_name='Transcript Processed At'
            ),
        ),
    ]