# Generated by Django 5.2.7 on 2025-11-11 08:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlagMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_name', models.CharField(db_index=True, help_text='Feature flag name (matches waffle flag)', max_length=100, unique=True)),
                ('rollout_percentage', models.IntegerField(default=0, help_text='Percentage of users with access (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('target_groups', models.JSONField(default=list, help_text='List of user groups with access')),
                ('target_users', models.JSONField(default=list, help_text='List of specific user IDs with access')),
                ('deployment_metadata', models.JSONField(default=dict, help_text='Deployment context (version, date, engineer)')),
                ('impact_metrics', models.JSONField(default=dict, help_text='Measured impact (error_rate, latency, usage)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Feature Flag Metadata',
                'verbose_name_plural': 'Feature Flag Metadata',
                'db_table': 'core_feature_flag_metadata',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_name', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(choices=[('created', 'Created'), ('enabled', 'Enabled'), ('disabled', 'Disabled'), ('rollout_changed', 'Rollout Changed'), ('deleted', 'Deleted')], max_length=50)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flag_changes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Feature Flag Audit Log',
                'verbose_name_plural': 'Feature Flag Audit Logs',
                'db_table': 'core_feature_flag_audit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['flag_name', '-created_at'], name='core_featur_flag_na_0f2e01_idx')],
            },
        ),
    ]
