"""
Core Constants Package

Centralized constants for the application including datetime, validation,
and other shared constants.
"""

# Re-export from datetime_constants module
from .datetime_constants import (
    # Time conversion constants
    SECONDS_IN_MINUTE,
    SECONDS_IN_HOUR,
    SECONDS_IN_DAY,
    SECONDS_IN_WEEK,
    MINUTES_IN_HOUR,
    MINUTES_IN_DAY,
    MINUTES_IN_WEEK,
    HOURS_IN_DAY,
    HOURS_IN_WEEK,
    DAYS_IN_WEEK,
    DAYS_IN_MONTH_APPROX,
    DAYS_IN_YEAR,
    # Format strings
    ISO_DATETIME_FORMAT,
    ISO_DATETIME_NO_MICRO,
    ISO_DATE_FORMAT,
    ISO_TIME_FORMAT,
    DISPLAY_DATETIME_FORMAT,
    DISPLAY_DATE_FORMAT,
    DISPLAY_TIME_FORMAT,
    DB_DATETIME_FORMAT,
    DB_DATE_FORMAT,
    DB_TIME_FORMAT,
    FILE_TIMESTAMP_FORMAT,
    LOG_DATETIME_FORMAT,
    REPORT_DATETIME_FORMAT,
    REPORT_DATE_FORMAT,
    REPORT_TIME_FORMAT,
    DJANGO_DATETIME_INPUT_FORMATS,
    DJANGO_DATE_INPUT_FORMATS,
    # Timedelta constants
    COMMON_TIMEDELTAS,
    BUSINESS_TIMEDELTAS,
    # Timezone constants
    TIMEZONE_OFFSETS,
    # Validation constants
    DATETIME_LIMITS,
    # Utility mappings
    FORMAT_CHOICES,
)

from .sentinel_constants import (
    DatabaseConstants,
    JobConstants,
    AssetConstants,
    PeopleConstants,
    GeofenceConstants,
    TenantConstants,
    SiteGroupConstants,
    ShiftConstants,
)

# Re-export from timeouts module
from .timeouts import (
    REQUEST_TIMEOUT_SHORT,
    REQUEST_TIMEOUT_MEDIUM,
    REQUEST_TIMEOUT_LONG,
    REQUEST_TIMEOUT_WEBHOOK,
    REDIS_OPERATION_TIMEOUT,
    DATABASE_TIMEOUT,
    CACHE_OPERATION_TIMEOUT,
    CELERY_SOFT_TIMEOUT_SHORT,
    CELERY_SOFT_TIMEOUT_MEDIUM,
    CELERY_SOFT_TIMEOUT_LONG,
    CELERY_HARD_TIMEOUT_SHORT,
    CELERY_HARD_TIMEOUT_MEDIUM,
    CELERY_HARD_TIMEOUT_LONG,
    CELERY_HARD_TIMEOUT_EXTRA_LONG,
    TASK_EXPIRES_SHORT,
    TASK_EXPIRES_MEDIUM,
    TASK_EXPIRES_STANDARD,
    TASK_EXPIRES_LONG,
    TASK_EXPIRES_VERY_LONG,
    WEBSOCKET_JWT_CACHE_TIMEOUT,
    WEBSOCKET_PRESENCE_TIMEOUT,
    WEBSOCKET_IDLE_TIMEOUT,
    MESSAGE_VISIBILITY_TIMEOUT,
    DEAD_LETTER_VISIBILITY_TIMEOUT,
    GOOGLE_MAPS_TIMEOUT,
    FRAPPE_TIMEOUT,
    GEOFENCE_VALIDATION_TIMEOUT,
)

# Re-export from cache_ttl module
from .cache_ttl import (
    CACHE_TTL_VERY_SHORT,
    CACHE_TTL_SHORT,
    CACHE_TTL_MEDIUM,
    CACHE_TTL_DEFAULT,
    CACHE_TTL_LONG,
    CACHE_TTL_VERY_LONG,
    CACHE_TTL_DAILY,
    HELPBOT_CACHE_TIMEOUT,
    HELPBOT_ANALYTICS_CACHE_TIMEOUT,
    NOC_TELEMETRY_CACHE_TTL,
    NOC_ALERT_CACHE_TTL,
    REPORT_GENERATION_CACHE_TIMEOUT,
    FRAPPE_CONNECTION_CACHE_TIMEOUT,
    API_RESPONSE_CACHE_TIMEOUT,
    NAV_MENU_CACHE_TIMEOUT,
    IA_CACHE_TIMEOUT,
    LEARNING_FEATURE_CACHE_TIMEOUT,
    RERANK_CACHE_TIMEOUT,
    IDEMPOTENCY_TTL_SHORT,
    IDEMPOTENCY_TTL_MEDIUM,
    IDEMPOTENCY_TTL_STANDARD,
    IDEMPOTENCY_TTL_LONG,
    SITE_AUDIT_IDEMPOTENCY_TTL,
    TICKET_IDEMPOTENCY_TTL,
    REPORT_IDEMPOTENCY_TTL,
    QUERY_RESULT_CACHE_SHORT,
    QUERY_RESULT_CACHE_DEFAULT,
    QUERY_RESULT_CACHE_LONG,
    DATABASE_QUERY_CACHE_TIMEOUT,
    QUERY_OPTIMIZATION_CACHE_TIMEOUT,
    SESSION_CACHE_TIMEOUT,
    API_TOKEN_CACHE_TIMEOUT,
    REFRESH_TOKEN_CACHE_TIMEOUT,
    RATE_LIMIT_WINDOW_SHORT,
    RATE_LIMIT_WINDOW_MEDIUM,
    RATE_LIMIT_WINDOW_STANDARD,
    REPORT_GENERATION_RATE_LIMIT_WINDOW,
    LOG_CACHE_RETENTION,
    METRICS_CACHE_RETENTION,
    ARCHIVE_CACHE_RETENTION,
    HOT_CACHE_TTL,
    WARM_CACHE_TTL,
    COLD_CACHE_TTL,
)

# Re-export from retry module
from .retry import (
    MAX_RETRIES_MINIMAL,
    MAX_RETRIES_SHORT,
    MAX_RETRIES_STANDARD,
    MAX_RETRIES_LONG,
    MAX_RETRIES_VERY_LONG,
    DATABASE_RETRY_COUNT,
    DATABASE_CONNECTION_RETRY_COUNT,
    NETWORK_RETRY_COUNT,
    WEBHOOK_RETRY_COUNT,
    CELERY_TASK_RETRY_COUNT,
    CELERY_CRITICAL_TASK_RETRY_COUNT,
    CELERY_IDEMPOTENT_TASK_RETRY_COUNT,
    CACHE_OPERATION_RETRY_COUNT,
    AUTH_RETRY_COUNT,
    PASSWORD_VERIFICATION_RETRY_COUNT,
    RETRY_BACKOFF_MULTIPLIER,
    RETRY_BACKOFF_MULTIPLIER_GENTLE,
    RETRY_BACKOFF_MULTIPLIER_LINEAR,
    RETRY_INITIAL_DELAY_SHORT,
    RETRY_INITIAL_DELAY_MEDIUM,
    RETRY_INITIAL_DELAY_LONG,
    RETRY_MAX_DELAY_SHORT,
    RETRY_MAX_DELAY_MEDIUM,
    RETRY_MAX_DELAY_LONG,
    RETRY_MAX_DELAY_VERY_LONG,
    RETRY_JITTER_RANGE_SMALL,
    RETRY_JITTER_RANGE_MEDIUM,
    RETRY_JITTER_RANGE_LARGE,
    DATABASE_OPERATION_RETRY,
    DATABASE_CONNECTION_RETRY,
    NETWORK_OPERATION_RETRY,
    RATE_LIMITED_OPERATION_RETRY,
    WEBHOOK_DELIVERY_RETRY,
    CELERY_TASK_RETRY,
    CELERY_CRITICAL_TASK_RETRY,
    CIRCUIT_BREAKER_FAILURE_THRESHOLD,
    CIRCUIT_BREAKER_FAILURE_WINDOW,
    CIRCUIT_BREAKER_RECOVERY_TIMEOUT,
    CIRCUIT_BREAKER_SUCCESS_THRESHOLD,
    RETRY_DEADLINE_EXTENSION,
    MAX_TOTAL_DEADLINE,
)

# Explicit __all__ to control namespace (Rule #16: Wildcard Import Prevention)
__all__ = [
    # From datetime_constants.py - Time conversion constants
    'SECONDS_IN_MINUTE', 'SECONDS_IN_HOUR', 'SECONDS_IN_DAY', 'SECONDS_IN_WEEK',
    'MINUTES_IN_HOUR', 'MINUTES_IN_DAY', 'MINUTES_IN_WEEK',
    'HOURS_IN_DAY', 'HOURS_IN_WEEK',
    'DAYS_IN_WEEK', 'DAYS_IN_MONTH_APPROX', 'DAYS_IN_YEAR',

    # From datetime_constants.py - Format strings
    'ISO_DATETIME_FORMAT', 'ISO_DATETIME_NO_MICRO', 'ISO_DATE_FORMAT', 'ISO_TIME_FORMAT',
    'DISPLAY_DATETIME_FORMAT', 'DISPLAY_DATE_FORMAT', 'DISPLAY_TIME_FORMAT',
    'DB_DATETIME_FORMAT', 'DB_DATE_FORMAT', 'DB_TIME_FORMAT',
    'FILE_TIMESTAMP_FORMAT', 'LOG_DATETIME_FORMAT',
    'REPORT_DATETIME_FORMAT', 'REPORT_DATE_FORMAT', 'REPORT_TIME_FORMAT',
    'DJANGO_DATETIME_INPUT_FORMATS', 'DJANGO_DATE_INPUT_FORMATS',

    # From datetime_constants.py - Timedelta constants
    'COMMON_TIMEDELTAS', 'BUSINESS_TIMEDELTAS',

    # From datetime_constants.py - Timezone constants
    'TIMEZONE_OFFSETS',

    # From datetime_constants.py - Validation constants
    'DATETIME_LIMITS',

    # From datetime_constants.py - Utility mappings
    'FORMAT_CHOICES',

    # From sentinel_constants.py - Sentinel constants
    'DatabaseConstants',
    'JobConstants',
    'AssetConstants',
    'PeopleConstants',
    'GeofenceConstants',
    'TenantConstants',
    'SiteGroupConstants',
    'ShiftConstants',

    # From timeouts.py - HTTP request timeouts
    'REQUEST_TIMEOUT_SHORT',
    'REQUEST_TIMEOUT_MEDIUM',
    'REQUEST_TIMEOUT_LONG',
    'REQUEST_TIMEOUT_WEBHOOK',

    # From timeouts.py - Network operation timeouts
    'REDIS_OPERATION_TIMEOUT',
    'DATABASE_TIMEOUT',
    'CACHE_OPERATION_TIMEOUT',

    # From timeouts.py - Task execution timeouts
    'CELERY_SOFT_TIMEOUT_SHORT',
    'CELERY_SOFT_TIMEOUT_MEDIUM',
    'CELERY_SOFT_TIMEOUT_LONG',
    'CELERY_HARD_TIMEOUT_SHORT',
    'CELERY_HARD_TIMEOUT_MEDIUM',
    'CELERY_HARD_TIMEOUT_LONG',
    'CELERY_HARD_TIMEOUT_EXTRA_LONG',

    # From timeouts.py - Task expiration
    'TASK_EXPIRES_SHORT',
    'TASK_EXPIRES_MEDIUM',
    'TASK_EXPIRES_STANDARD',
    'TASK_EXPIRES_LONG',
    'TASK_EXPIRES_VERY_LONG',

    # From timeouts.py - WebSocket timeouts
    'WEBSOCKET_JWT_CACHE_TIMEOUT',
    'WEBSOCKET_PRESENCE_TIMEOUT',
    'WEBSOCKET_IDLE_TIMEOUT',

    # From timeouts.py - Visibility timeouts
    'MESSAGE_VISIBILITY_TIMEOUT',
    'DEAD_LETTER_VISIBILITY_TIMEOUT',

    # From timeouts.py - API service timeouts
    'GOOGLE_MAPS_TIMEOUT',
    'FRAPPE_TIMEOUT',
    'GEOFENCE_VALIDATION_TIMEOUT',

    # From cache_ttl.py - General cache TTL values
    'CACHE_TTL_VERY_SHORT',
    'CACHE_TTL_SHORT',
    'CACHE_TTL_MEDIUM',
    'CACHE_TTL_DEFAULT',
    'CACHE_TTL_LONG',
    'CACHE_TTL_VERY_LONG',
    'CACHE_TTL_DAILY',

    # From cache_ttl.py - Application-specific timeouts
    'HELPBOT_CACHE_TIMEOUT',
    'HELPBOT_ANALYTICS_CACHE_TIMEOUT',
    'NOC_TELEMETRY_CACHE_TTL',
    'NOC_ALERT_CACHE_TTL',
    'REPORT_GENERATION_CACHE_TIMEOUT',
    'FRAPPE_CONNECTION_CACHE_TIMEOUT',
    'API_RESPONSE_CACHE_TIMEOUT',
    'NAV_MENU_CACHE_TIMEOUT',
    'IA_CACHE_TIMEOUT',
    'LEARNING_FEATURE_CACHE_TIMEOUT',
    'RERANK_CACHE_TIMEOUT',

    # From cache_ttl.py - Idempotency timeouts
    'IDEMPOTENCY_TTL_SHORT',
    'IDEMPOTENCY_TTL_MEDIUM',
    'IDEMPOTENCY_TTL_STANDARD',
    'IDEMPOTENCY_TTL_LONG',
    'SITE_AUDIT_IDEMPOTENCY_TTL',
    'TICKET_IDEMPOTENCY_TTL',
    'REPORT_IDEMPOTENCY_TTL',

    # From cache_ttl.py - Query result caching
    'QUERY_RESULT_CACHE_SHORT',
    'QUERY_RESULT_CACHE_DEFAULT',
    'QUERY_RESULT_CACHE_LONG',
    'DATABASE_QUERY_CACHE_TIMEOUT',
    'QUERY_OPTIMIZATION_CACHE_TIMEOUT',

    # From cache_ttl.py - Session & authentication
    'SESSION_CACHE_TIMEOUT',
    'API_TOKEN_CACHE_TIMEOUT',
    'REFRESH_TOKEN_CACHE_TIMEOUT',

    # From cache_ttl.py - Rate limiting windows
    'RATE_LIMIT_WINDOW_SHORT',
    'RATE_LIMIT_WINDOW_MEDIUM',
    'RATE_LIMIT_WINDOW_STANDARD',
    'REPORT_GENERATION_RATE_LIMIT_WINDOW',

    # From cache_ttl.py - Data retention
    'LOG_CACHE_RETENTION',
    'METRICS_CACHE_RETENTION',
    'ARCHIVE_CACHE_RETENTION',

    # From cache_ttl.py - Temperature-based strategy
    'HOT_CACHE_TTL',
    'WARM_CACHE_TTL',
    'COLD_CACHE_TTL',

    # From retry.py - Retry counts
    'MAX_RETRIES_MINIMAL',
    'MAX_RETRIES_SHORT',
    'MAX_RETRIES_STANDARD',
    'MAX_RETRIES_LONG',
    'MAX_RETRIES_VERY_LONG',
    'DATABASE_RETRY_COUNT',
    'DATABASE_CONNECTION_RETRY_COUNT',
    'NETWORK_RETRY_COUNT',
    'WEBHOOK_RETRY_COUNT',
    'CELERY_TASK_RETRY_COUNT',
    'CELERY_CRITICAL_TASK_RETRY_COUNT',
    'CELERY_IDEMPOTENT_TASK_RETRY_COUNT',
    'CACHE_OPERATION_RETRY_COUNT',
    'AUTH_RETRY_COUNT',
    'PASSWORD_VERIFICATION_RETRY_COUNT',

    # From retry.py - Backoff configuration
    'RETRY_BACKOFF_MULTIPLIER',
    'RETRY_BACKOFF_MULTIPLIER_GENTLE',
    'RETRY_BACKOFF_MULTIPLIER_LINEAR',

    # From retry.py - Initial and maximum delays
    'RETRY_INITIAL_DELAY_SHORT',
    'RETRY_INITIAL_DELAY_MEDIUM',
    'RETRY_INITIAL_DELAY_LONG',
    'RETRY_MAX_DELAY_SHORT',
    'RETRY_MAX_DELAY_MEDIUM',
    'RETRY_MAX_DELAY_LONG',
    'RETRY_MAX_DELAY_VERY_LONG',

    # From retry.py - Jitter
    'RETRY_JITTER_RANGE_SMALL',
    'RETRY_JITTER_RANGE_MEDIUM',
    'RETRY_JITTER_RANGE_LARGE',

    # From retry.py - Operation-specific policies
    'DATABASE_OPERATION_RETRY',
    'DATABASE_CONNECTION_RETRY',
    'NETWORK_OPERATION_RETRY',
    'RATE_LIMITED_OPERATION_RETRY',
    'WEBHOOK_DELIVERY_RETRY',
    'CELERY_TASK_RETRY',
    'CELERY_CRITICAL_TASK_RETRY',

    # From retry.py - Circuit breaker
    'CIRCUIT_BREAKER_FAILURE_THRESHOLD',
    'CIRCUIT_BREAKER_FAILURE_WINDOW',
    'CIRCUIT_BREAKER_RECOVERY_TIMEOUT',
    'CIRCUIT_BREAKER_SUCCESS_THRESHOLD',

    # From retry.py - Deadline extension
    'RETRY_DEADLINE_EXTENSION',
    'MAX_TOTAL_DEADLINE',
]