# Generated by Django 5.2.7 on 2025-11-11 04:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfiguration',
            fields=[
                ('webhook_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable webhook name', max_length=100)),
                ('url', models.URLField(help_text='Webhook endpoint URL', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('secret', models.CharField(help_text='HMAC secret for signature verification (TODO: Encrypt when package available)', max_length=255)),
                ('enabled', models.BooleanField(default=True, help_text='Whether webhook is active')),
                ('retry_count', models.PositiveIntegerField(default=3, help_text='Max retry attempts for failed deliveries', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('timeout_seconds', models.PositiveIntegerField(default=30, help_text='HTTP timeout for webhook delivery', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
                ('webhook_type', models.CharField(choices=[('generic', 'Generic Webhook'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('discord', 'Discord'), ('custom', 'Custom Integration')], default='generic', help_text='Webhook platform type', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of webhook purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Webhook Configuration',
                'verbose_name_plural': 'Webhook Configurations',
                'db_table': 'integrations_webhook_configuration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('http_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('retry_after_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='integrations.webhookconfiguration')),
            ],
            options={
                'verbose_name': 'Webhook Delivery Log',
                'verbose_name_plural': 'Webhook Delivery Logs',
                'db_table': 'integrations_webhook_delivery_log',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified', verbose_name='Updated at')),
                ('ctzoffset', models.IntegerField(default=-1, help_text="User's timezone offset in minutes", verbose_name='Timezone offset')),
                ('event_type', models.CharField(help_text="Event type identifier (e.g., 'ticket.created', 'alert.escalated')", max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='integrations.webhookconfiguration')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'integrations_webhook_event',
            },
        ),
        migrations.AddIndex(
            model_name='webhookconfiguration',
            index=models.Index(fields=['tenant', 'webhook_type', 'enabled'], name='integration_tenant__610d71_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookconfiguration',
            index=models.Index(fields=['enabled', 'created_at'], name='integration_enabled_1404db_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['webhook', 'delivered_at'], name='integration_webhook_063ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['tenant', 'delivered_at'], name='integration_tenant__443915_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['success', 'delivered_at'], name='integration_success_d57fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['delivered_at'], name='integration_deliver_50026e_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type'], name='integration_event_t_2a7133_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['webhook', 'event_type'], name='integration_webhook_0b8aab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webhookevent',
            unique_together={('webhook', 'event_type')},
        ),
    ]
