# Generated by Django 5.2.7 on 2025-11-26 00:00

from django.db import migrations
import apps.core.fields.encrypted_fields


def encrypt_existing_webhook_secrets(apps, schema_editor):
    WebhookConfiguration = apps.get_model('integrations', 'WebhookConfiguration')

    for webhook in WebhookConfiguration.objects.all().iterator():
        secret = getattr(webhook, 'secret', '')
        if not secret:
            continue

        webhook.secret_encrypted = secret
        webhook.save(update_fields=['secret_encrypted'])


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookconfiguration',
            name='secret_encrypted',
            field=apps.core.fields.encrypted_fields.EncryptedCharField(
                default='',
                help_text='Encrypted HMAC secret used for signature verification',
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            encrypt_existing_webhook_secrets,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='webhookconfiguration',
            name='secret',
        ),
        migrations.RenameField(
            model_name='webhookconfiguration',
            old_name='secret_encrypted',
            new_name='secret',
        ),
    ]
