# Generated by Django 5.2.7 on 2025-11-09 10:20

import apps.peoples.models.base_model
import django.contrib.postgres.fields
import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "embedding_vector",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        help_text="Voice embedding vector (voiceprint)",
                        size=512,
                    ),
                ),
                (
                    "source_audio_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "source_audio_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "extraction_model_name",
                    models.CharField(
                        default="google-speaker-recognition",
                        help_text="Model used to extract this voiceprint",
                        max_length=100,
                    ),
                ),
                (
                    "extraction_model_version",
                    models.CharField(default="1.0", max_length=20),
                ),
                (
                    "voice_confidence",
                    models.FloatField(help_text="Confidence of voice detection (0-1)"),
                ),
                (
                    "audio_quality_score",
                    models.FloatField(
                        blank=True,
                        help_text="Quality score of source audio (0-1)",
                        null=True,
                    ),
                ),
                (
                    "snr_db",
                    models.FloatField(
                        blank=True,
                        help_text="Signal-to-noise ratio in decibels",
                        null=True,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        default="en-US",
                        help_text="Language of voice sample",
                        max_length=10,
                    ),
                ),
                (
                    "sample_text",
                    models.TextField(
                        blank=True,
                        help_text="Text spoken in the sample (if available)",
                        null=True,
                    ),
                ),
                (
                    "sample_duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Duration of audio sample in seconds",
                        null=True,
                    ),
                ),
                ("extraction_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_features",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Additional audio features (pitch, tempo, etc.)",
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary voiceprint for the user",
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this voiceprint has been validated",
                    ),
                ),
                ("validation_score", models.FloatField(blank=True, null=True)),
                ("verification_count", models.IntegerField(default=0)),
                ("successful_matches", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_embeddings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Embedding",
                "verbose_name_plural": "Voice Embeddings",
                "db_table": "voice_embedding",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VoiceVerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("verification_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Verification Successful"),
                            ("FAILED", "Verification Failed"),
                            ("ERROR", "Verification Error"),
                            ("REJECTED", "Rejected by Anti-spoofing"),
                            ("NO_VOICE", "No Voice Detected"),
                            ("POOR_QUALITY", "Poor Audio Quality"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        blank=True, help_text="Voice similarity score (0-1)", null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Overall confidence in verification (0-1)",
                        null=True,
                    ),
                ),
                (
                    "liveness_score",
                    models.FloatField(
                        blank=True,
                        help_text="Liveness detection score (0-1)",
                        null=True,
                    ),
                ),
                ("spoof_detected", models.BooleanField(default=False)),
                (
                    "spoof_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of spoofing detected (e.g., PLAYBACK, DEEPFAKE)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "input_audio_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "input_audio_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("audio_quality_score", models.FloatField(blank=True, null=True)),
                ("audio_duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "snr_db",
                    models.FloatField(
                        blank=True, help_text="Signal-to-noise ratio", null=True
                    ),
                ),
                (
                    "challenge_phrase",
                    models.CharField(
                        blank=True,
                        help_text="Challenge phrase used for liveness detection",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "challenge_matched",
                    models.BooleanField(
                        default=False,
                        help_text="Whether spoken phrase matched challenge",
                    ),
                ),
                ("processing_time_ms", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "verification_metadata",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Detailed verification metadata",
                    ),
                ),
                (
                    "fraud_indicators",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Detected fraud indicators",
                        size=None,
                    ),
                ),
                (
                    "fraud_risk_score",
                    models.FloatField(
                        default=0.0, help_text="Calculated fraud risk score (0-1)"
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "device_info",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Device information",
                    ),
                ),
                (
                    "attendance_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.peopleeventlog",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "matched_embedding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voice_recognition.voiceembedding",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Verification Log",
                "verbose_name_plural": "Voice Verification Logs",
                "db_table": "voice_verification_log",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnrollmentPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_name",
                    models.CharField(
                        help_text="Policy name (e.g., 'Standard Security', 'High Security')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Policy is active and enforced"
                    ),
                ),
                (
                    "min_device_trust_score",
                    models.IntegerField(
                        default=70,
                        help_text="Minimum device trust score (0-100) required for enrollment",
                    ),
                ),
                (
                    "require_device_registration",
                    models.BooleanField(
                        default=True,
                        help_text="Device must be pre-registered before enrollment",
                    ),
                ),
                (
                    "location_requirement",
                    models.CharField(
                        choices=[
                            ("any", "Any Location (Least Secure)"),
                            ("approved_network", "Approved Network Only"),
                            ("on_site", "On-Site Only (Most Secure)"),
                            ("geofence", "Within Geofence"),
                        ],
                        default="approved_network",
                        help_text="Location security requirement",
                        max_length=20,
                    ),
                ),
                (
                    "approved_networks",
                    models.JSONField(
                        default=list,
                        help_text="List of approved network CIDRs (e.g., ['192.168.1.0/24'])",
                    ),
                ),
                (
                    "approved_sites",
                    models.JSONField(
                        default=list,
                        help_text="List of approved site IDs for on-site enrollment",
                    ),
                ),
                (
                    "require_supervisor_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Require supervisor approval for enrollment",
                    ),
                ),
                (
                    "supervisor_approval_timeout_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Hours before supervisor approval request expires",
                    ),
                ),
                (
                    "min_reenrollment_interval_days",
                    models.IntegerField(
                        default=365,
                        help_text="Minimum days before re-enrollment allowed",
                    ),
                ),
                (
                    "force_reenrollment_after_days",
                    models.IntegerField(
                        default=730,
                        help_text="Force re-enrollment after N days (biometric refresh)",
                    ),
                ),
                (
                    "require_mfa_for_remote_enrollment",
                    models.BooleanField(
                        default=True,
                        help_text="Require MFA if enrolling from unapproved location",
                    ),
                ),
                (
                    "require_face_biometrics",
                    models.BooleanField(
                        default=True,
                        help_text="Require face biometrics before voice enrollment",
                    ),
                ),
                (
                    "min_voice_samples",
                    models.IntegerField(
                        default=5, help_text="Minimum voice samples required"
                    ),
                ),
                (
                    "max_voice_samples",
                    models.IntegerField(
                        default=7, help_text="Maximum voice samples allowed"
                    ),
                ),
                (
                    "min_voice_quality_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.7,
                        help_text="Minimum voice quality score (0.00-1.00)",
                        max_digits=3,
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created datetime"
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(auto_now=True, help_text="Modified datetime"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Enrollment Policy",
                "verbose_name_plural": "Voice Enrollment Policies",
                "db_table": "voice_enrollment_policy",
                "ordering": ["policy_name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="voice_enrol_is_acti_ad3047_idx"
                    ),
                    models.Index(
                        fields=["policy_name"], name="voice_enrol_policy__048e9f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VoiceAntiSpoofingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("PLAYBACK_DETECTION", "Playback Detection"),
                            ("DEEPFAKE_DETECTION", "Deepfake Detection"),
                            ("CHANNEL_ANALYSIS", "Channel Analysis"),
                            ("ACOUSTIC_FINGERPRINT", "Acoustic Fingerprinting"),
                            ("LIVENESS_CHALLENGE", "Challenge-Response"),
                            ("MULTI_MODAL", "Multi-modal Detection"),
                        ],
                        max_length=30,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "liveness_threshold",
                    models.FloatField(
                        default=0.5, help_text="Threshold for liveness classification"
                    ),
                ),
                (
                    "spoof_threshold",
                    models.FloatField(
                        default=0.7, help_text="Threshold for spoof detection"
                    ),
                ),
                ("true_positive_rate", models.FloatField(blank=True, null=True)),
                ("false_positive_rate", models.FloatField(blank=True, null=True)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                (
                    "model_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "requires_challenge_response",
                    models.BooleanField(
                        default=False,
                        help_text="Whether model requires challenge-response interaction",
                    ),
                ),
                (
                    "supported_languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        default=list,
                        help_text="Supported language codes",
                        size=None,
                    ),
                ),
                ("detection_count", models.BigIntegerField(default=0)),
                ("spoof_detections", models.BigIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Anti-Spoofing Model",
                "verbose_name_plural": "Voice Anti-Spoofing Models",
                "db_table": "voice_anti_spoofing_model",
                "ordering": ["mdtz"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["cdtz"], name="v_antispoof_cdtz_idx"),
                    models.Index(fields=["mdtz"], name="v_antispoof_mdtz_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VoiceBiometricConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System Configuration"),
                            ("SECURITY", "Security Settings"),
                            ("PERFORMANCE", "Performance Settings"),
                            ("USER_PREFERENCE", "User Preferences"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "config_data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Configuration parameters",
                    ),
                ),
                (
                    "applies_to_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Location codes this configuration applies to",
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Configuration priority (lower = higher priority)",
                    ),
                ),
                ("last_validated", models.DateTimeField(blank=True, null=True)),
                (
                    "validation_errors",
                    models.JSONField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Configuration validation errors",
                    ),
                ),
                ("applied_count", models.IntegerField(default=0)),
                ("last_applied", models.DateTimeField(blank=True, null=True)),
                (
                    "applies_to_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users this configuration applies to (empty = all users)",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Biometric Configuration",
                "verbose_name_plural": "Voice Biometric Configurations",
                "db_table": "voice_biometric_config",
                "ordering": ["priority", "name"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["mdtz"], name="voicebiometricconfig_mdtz_idx"),
                    models.Index(fields=["cdtz"], name="voicebiometricconfig_cdtz_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="voiceembedding",
            index=models.Index(
                fields=["user", "is_primary"], name="voice_embed_user_id_9ae7d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voiceembedding",
            index=models.Index(
                fields=["extraction_model_name", "is_validated"],
                name="voice_embed_extract_460b28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="voiceembedding",
            index=models.Index(
                fields=["language_code", "is_validated"],
                name="voice_embed_languag_70dcbd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="voiceverificationlog",
            index=models.Index(
                fields=["user", "verification_timestamp"],
                name="voice_verif_user_id_2d44b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="voiceverificationlog",
            index=models.Index(
                fields=["result", "verification_timestamp"],
                name="voice_verif_result_3e3d20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="voiceverificationlog",
            index=models.Index(
                fields=["fraud_risk_score", "spoof_detected"],
                name="voice_verif_fraud_r_54757d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="voiceverificationlog",
            index=models.Index(
                fields=["device_id", "verification_timestamp"],
                name="voice_verif_device__3d6ba0_idx",
            ),
        ),
    ]
