# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activity", "0003_initial"),
        ("client_onboarding", "0003_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(help_text="Emoji or icon class", max_length=50),
                ),
                (
                    "criteria",
                    models.JSONField(
                        help_text="Unlock criteria (e.g., {'on_time_rate': 100, 'days': 30})"
                    ),
                ),
                ("points", models.IntegerField(default=10, help_text="Points awarded")),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="performance",
                        help_text="Category (performance, attendance, quality, safety)",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "db_table": "perf_achievements",
                "ordering": ["category", "rarity", "name"],
            },
        ),
        migrations.CreateModel(
            name="CoachingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "session_date",
                    models.DateTimeField(
                        db_index=True, help_text="When coaching session occurred"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, help_text="Session duration", null=True
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine Check-in"),
                            ("performance_improvement", "Performance Improvement"),
                            ("goal_setting", "Goal Setting"),
                            ("recognition", "Recognition & Praise"),
                            ("corrective", "Corrective Action"),
                        ],
                        default="routine",
                        max_length=30,
                    ),
                ),
                (
                    "focus_areas",
                    models.JSONField(
                        default=list,
                        help_text="Areas discussed (e.g., ['documentation', 'task_sla', 'attendance'])",
                    ),
                ),
                (
                    "action_items",
                    models.JSONField(
                        default=list,
                        help_text="Action items with due dates and completion status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Coaching session notes (supervisor only)"
                    ),
                ),
                (
                    "worker_feedback",
                    models.TextField(
                        blank=True, help_text="Worker's feedback on session"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, help_text="Scheduled follow-up date", null=True
                    ),
                ),
                (
                    "follow_up_completed",
                    models.BooleanField(
                        default=False, help_text="Whether follow-up occurred"
                    ),
                ),
                (
                    "improvement_observed",
                    models.BooleanField(
                        blank=True,
                        help_text="Was improvement observed in next 2 weeks?",
                        null=True,
                    ),
                ),
                (
                    "effectiveness_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Not Effective"),
                            (2, "Somewhat Effective"),
                            (3, "Moderately Effective"),
                            (4, "Very Effective"),
                            (5, "Extremely Effective"),
                        ],
                        help_text="Coach's rating of session effectiveness",
                        null=True,
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        help_text="Supervisor conducting session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_sessions_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        help_text="Worker being coached",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_sessions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coaching Session",
                "verbose_name_plural": "Coaching Sessions",
                "db_table": "perf_coaching_sessions",
                "ordering": ["-session_date"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "worker", "session_date"],
                        name="perf_coachi_tenant__17b812_idx",
                    ),
                    models.Index(
                        fields=["tenant", "coach", "session_date"],
                        name="perf_coachi_tenant__e8a8f2_idx",
                    ),
                    models.Index(
                        fields=["tenant", "session_type"],
                        name="perf_coachi_tenant__30d05b_idx",
                    ),
                    models.Index(
                        fields=["tenant", "follow_up_date"],
                        name="perf_coachi_tenant__f9cf47_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CohortBenchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "cohort_key",
                    models.CharField(
                        db_index=True,
                        help_text="Format: site_id|role|shift_type|tenure_band|month",
                        max_length=100,
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        db_index=True,
                        help_text="Metric being benchmarked (e.g., 'bpi', 'on_time_rate')",
                        max_length=50,
                    ),
                ),
                ("period_start", models.DateField(help_text="Benchmark period start")),
                ("period_end", models.DateField(help_text="Benchmark period end")),
                (
                    "sample_size",
                    models.IntegerField(
                        default=0, help_text="Number of worker-days in cohort"
                    ),
                ),
                (
                    "worker_count",
                    models.IntegerField(
                        default=0, help_text="Number of unique workers"
                    ),
                ),
                (
                    "mean",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                (
                    "median",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                (
                    "std_dev",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                (
                    "min_value",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                (
                    "max_value",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                (
                    "p10",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="10th percentile",
                        max_digits=8,
                    ),
                ),
                (
                    "p25",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="25th percentile (Q1)",
                        max_digits=8,
                    ),
                ),
                (
                    "p50",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="50th percentile (median)",
                        max_digits=8,
                    ),
                ),
                (
                    "p75",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="75th percentile (Q3)",
                        max_digits=8,
                    ),
                ),
                (
                    "p90",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="90th percentile",
                        max_digits=8,
                    ),
                ),
                (
                    "lower_control_limit",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Mean - 2*std_dev",
                        max_digits=8,
                    ),
                ),
                (
                    "upper_control_limit",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Mean + 2*std_dev",
                        max_digits=8,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cohort Benchmark",
                "verbose_name_plural": "Cohort Benchmarks",
                "db_table": "perf_cohort_benchmarks",
                "ordering": ["-period_end", "cohort_key", "metric_name"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "cohort_key", "metric_name"],
                        name="perf_cohort_tenant__7ad886_idx",
                    ),
                    models.Index(
                        fields=["tenant", "period_start", "period_end"],
                        name="perf_cohort_tenant__4c053f_idx",
                    ),
                ],
                "unique_together": {
                    ("tenant", "cohort_key", "metric_name", "period_start")
                },
            },
        ),
        migrations.CreateModel(
            name="Kudos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "kudos_type",
                    models.CharField(
                        choices=[
                            ("teamwork", "Teamwork"),
                            ("quality", "Quality Work"),
                            ("initiative", "Initiative"),
                            ("safety", "Safety Awareness"),
                            ("customer_service", "Customer Service"),
                            ("mentoring", "Mentoring"),
                            ("innovation", "Innovation"),
                        ],
                        help_text="Category of recognition",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(help_text="Recognition message")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private (recipient only)"),
                            ("team", "Team (site level)"),
                            ("company", "Company-wide"),
                        ],
                        default="team",
                        help_text="Who can see this kudos",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "giver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kudos_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kudos_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related task if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="activity.job",
                    ),
                ),
                (
                    "related_tour",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related tour if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="activity.tour",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kudos",
                "verbose_name_plural": "Kudos",
                "db_table": "perf_kudos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "recipient", "created_at"],
                        name="perf_kudos_tenant__39473c_idx",
                    ),
                    models.Index(
                        fields=["tenant", "giver"], name="perf_kudos_tenant__68c82d_idx"
                    ),
                    models.Index(
                        fields=["tenant", "kudos_type"],
                        name="perf_kudos_tenant__0de006_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "streak_type",
                    models.CharField(
                        choices=[
                            ("on_time", "On-Time Streak"),
                            ("perfect_patrol", "Perfect Patrol Streak"),
                            ("sla_hit", "SLA Hit Streak"),
                            ("zero_ncns", "Zero NCNS Streak"),
                            ("quality_excellence", "Quality Excellence Streak"),
                        ],
                        db_index=True,
                        help_text="Type of streak being tracked",
                        max_length=50,
                    ),
                ),
                (
                    "current_count",
                    models.IntegerField(
                        default=0,
                        help_text="Current streak length (days)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "best_count",
                    models.IntegerField(
                        default=0,
                        help_text="Personal best streak (all-time)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "started_date",
                    models.DateField(help_text="When current streak started"),
                ),
                (
                    "last_updated",
                    models.DateField(help_text="Last date streak was verified"),
                ),
                (
                    "broken_date",
                    models.DateField(
                        blank=True, help_text="When last broken", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_streaks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Streak",
                "verbose_name_plural": "Performance Streaks",
                "db_table": "perf_streaks",
                "indexes": [
                    models.Index(
                        fields=["tenant", "worker", "streak_type"],
                        name="perf_streak_tenant__c815db_idx",
                    ),
                    models.Index(
                        fields=["tenant", "current_count"],
                        name="perf_streak_tenant__b499e7_idx",
                    ),
                ],
                "unique_together": {("tenant", "worker", "streak_type")},
            },
        ),
        migrations.CreateModel(
            name="TeamDailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "shift_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Shift type (day, night, evening) or null for all shifts",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("active_workers", models.IntegerField(default=0)),
                ("scheduled_workers", models.IntegerField(default=0)),
                (
                    "total_worked_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_scheduled_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "team_bpi_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "team_bpi_median",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "team_bpi_std_dev",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "workers_exceptional",
                    models.IntegerField(default=0, help_text="BPI 90+"),
                ),
                (
                    "workers_strong",
                    models.IntegerField(default=0, help_text="BPI 75-89"),
                ),
                (
                    "workers_solid",
                    models.IntegerField(default=0, help_text="BPI 60-74"),
                ),
                (
                    "workers_developing",
                    models.IntegerField(default=0, help_text="BPI 40-59"),
                ),
                (
                    "workers_needs_support",
                    models.IntegerField(default=0, help_text="BPI <40"),
                ),
                (
                    "on_time_rate_avg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "sla_hit_rate_avg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "patrol_coverage_avg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "task_completion_rate_avg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "quality_score_avg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "coverage_gap_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unfilled shift hours",
                        max_digits=6,
                    ),
                ),
                ("total_ncns_incidents", models.IntegerField(default=0)),
                ("total_late_incidents", models.IntegerField(default=0)),
                ("total_geofence_violations", models.IntegerField(default=0)),
                ("total_tasks_completed", models.IntegerField(default=0)),
                ("total_tours_completed", models.IntegerField(default=0)),
                ("total_work_orders_completed", models.IntegerField(default=0)),
                (
                    "incident_rate_per_100h",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Safety incidents per 100 worked hours",
                        max_digits=6,
                    ),
                ),
                ("incidents_total", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_metrics",
                        to="client_onboarding.bt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Daily Metrics",
                "verbose_name_plural": "Team Daily Metrics",
                "db_table": "perf_team_daily_metrics",
                "ordering": ["-date", "site"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "date", "site"],
                        name="perf_team_d_tenant__cea264_idx",
                    ),
                    models.Index(
                        fields=["tenant", "date", "shift_type"],
                        name="perf_team_d_tenant__088ab5_idx",
                    ),
                    models.Index(
                        fields=["tenant", "team_bpi_avg"],
                        name="perf_team_d_tenant__8eac34_idx",
                    ),
                ],
                "unique_together": {("tenant", "date", "site", "shift_type")},
            },
        ),
        migrations.CreateModel(
            name="WorkerAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("earned_date", models.DateField(db_index=True)),
                (
                    "count",
                    models.IntegerField(
                        default=1,
                        help_text="Times earned (for repeatable achievements)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "progress_data",
                    models.JSONField(
                        blank=True,
                        help_text="Progress toward achievement (for tracking)",
                        null=True,
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_by_workers",
                        to="performance_analytics.achievement",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements_earned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker Achievement",
                "verbose_name_plural": "Worker Achievements",
                "db_table": "perf_worker_achievements",
                "ordering": ["-earned_date"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "worker", "earned_date"],
                        name="perf_worker_tenant__c4969b_idx",
                    ),
                    models.Index(
                        fields=["tenant", "achievement"],
                        name="perf_worker_tenant__08664d_idx",
                    ),
                ],
                "unique_together": {("tenant", "worker", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="WorkerDailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("date", models.DateField(db_index=True, help_text="Metric date")),
                (
                    "role",
                    models.CharField(
                        db_index=True,
                        help_text="Worker role (security_guard, supervisor, technician)",
                        max_length=50,
                    ),
                ),
                (
                    "shift_type",
                    models.CharField(
                        db_index=True,
                        help_text="Shift type (day, night, evening, weekend)",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hours scheduled to work",
                        max_digits=5,
                    ),
                ),
                (
                    "worked_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hours actually worked",
                        max_digits=5,
                    ),
                ),
                (
                    "scheduled_shifts",
                    models.IntegerField(
                        default=0, help_text="Number of shifts scheduled"
                    ),
                ),
                ("on_time_punches", models.IntegerField(default=0)),
                ("late_punches", models.IntegerField(default=0)),
                ("total_late_minutes", models.IntegerField(default=0)),
                ("early_departures", models.IntegerField(default=0)),
                ("geofence_violations", models.IntegerField(default=0)),
                ("ncns_incidents", models.IntegerField(default=0)),
                ("tasks_assigned", models.IntegerField(default=0)),
                ("tasks_completed", models.IntegerField(default=0)),
                ("tasks_within_sla", models.IntegerField(default=0)),
                ("tasks_rework", models.IntegerField(default=0)),
                (
                    "task_quality_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("tours_assigned", models.IntegerField(default=0)),
                ("tours_completed", models.IntegerField(default=0)),
                ("checkpoints_expected", models.IntegerField(default=0)),
                ("checkpoints_scanned", models.IntegerField(default=0)),
                ("checkpoints_missed", models.IntegerField(default=0)),
                ("checkpoints_late", models.IntegerField(default=0)),
                ("incidents_detected", models.IntegerField(default=0)),
                ("work_orders_assigned", models.IntegerField(default=0)),
                ("work_orders_completed", models.IntegerField(default=0)),
                ("work_orders_within_sla", models.IntegerField(default=0)),
                (
                    "work_order_quality_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("incidents_reported", models.IntegerField(default=0)),
                ("near_misses_reported", models.IntegerField(default=0)),
                ("daily_reports_submitted", models.IntegerField(default=0)),
                ("daily_reports_expected", models.IntegerField(default=0)),
                ("evidence_photos_uploaded", models.IntegerField(default=0)),
                ("evidence_photos_expected", models.IntegerField(default=0)),
                ("certifications_current", models.IntegerField(default=0)),
                ("certifications_total", models.IntegerField(default=0)),
                (
                    "attendance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Attendance & reliability score (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "task_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Task performance score (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "patrol_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Patrol quality score (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "work_order_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Work order performance score (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "compliance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Compliance & safety score (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "balanced_performance_index",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=0,
                        help_text="Overall BPI score (0-100), weighted average",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "cohort_key",
                    models.CharField(
                        db_index=True,
                        help_text="Cohort identifier: site|role|shift|tenure_band|month",
                        max_length=100,
                    ),
                ),
                (
                    "bpi_percentile",
                    models.IntegerField(
                        default=50,
                        help_text="Percentile within cohort (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "performance_band",
                    models.CharField(
                        choices=[
                            ("exceptional", "Exceptional (90-100)"),
                            ("strong", "Strong (75-89)"),
                            ("solid", "Solid (60-74)"),
                            ("developing", "Developing (40-59)"),
                            ("needs_support", "Needs Support (<40)"),
                        ],
                        default="solid",
                        help_text="Performance classification",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="Primary work site for this day",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_metrics",
                        to="client_onboarding.bt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        help_text="Worker being measured",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker Daily Metrics",
                "verbose_name_plural": "Worker Daily Metrics",
                "db_table": "perf_worker_daily_metrics",
                "ordering": ["-date", "worker"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "date", "worker"],
                        name="perf_worker_tenant__23567c_idx",
                    ),
                    models.Index(
                        fields=["tenant", "date", "site"],
                        name="perf_worker_tenant__caa445_idx",
                    ),
                    models.Index(
                        fields=["tenant", "cohort_key", "date"],
                        name="perf_worker_tenant__06f3d6_idx",
                    ),
                    models.Index(
                        fields=["tenant", "balanced_performance_index"],
                        name="perf_worker_tenant__641879_idx",
                    ),
                    models.Index(
                        fields=["tenant", "performance_band"],
                        name="perf_worker_tenant__c7ae72_idx",
                    ),
                ],
                "unique_together": {("tenant", "date", "worker")},
            },
        ),
    ]
