# Generated by Django 5.2.7 on 2025-11-09 10:20

import apps.client_onboarding.managers
import apps.peoples.models.base_model
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIChangeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "record_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "sequence_order",
                    models.PositiveIntegerField(verbose_name="Sequence Order"),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Model Name"),
                ),
                (
                    "app_label",
                    models.CharField(max_length=100, verbose_name="App Label"),
                ),
                (
                    "object_id",
                    models.CharField(max_length=100, verbose_name="Object ID"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "before_state",
                    models.JSONField(
                        blank=True,
                        help_text="Object state before change (for UPDATE/DELETE)",
                        null=True,
                        verbose_name="Before State",
                    ),
                ),
                (
                    "after_state",
                    models.JSONField(
                        blank=True,
                        help_text="Object state after change (for CREATE/UPDATE)",
                        null=True,
                        verbose_name="After State",
                    ),
                ),
                (
                    "field_changes",
                    models.JSONField(
                        default=dict,
                        help_text="Specific field-level changes",
                        verbose_name="Field Changes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "has_dependencies",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this change affects related objects",
                        verbose_name="Has Dependencies",
                    ),
                ),
                (
                    "dependency_info",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dependency Information"
                    ),
                ),
                (
                    "rollback_attempted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rollback Attempted At"
                    ),
                ),
                (
                    "rollback_success",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Rollback Success"
                    ),
                ),
                (
                    "rollback_error",
                    models.TextField(
                        blank=True, null=True, verbose_name="Rollback Error"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Change Record",
                "verbose_name_plural": "AI Change Records",
                "db_table": "onboarding_ai_change_record",
                "ordering": ["changeset", "sequence_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AIChangeSet",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "changeset_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("rolled_back", "Rolled Back"),
                            ("failed", "Failed"),
                            ("partially_applied", "Partially Applied"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Applied At"
                    ),
                ),
                (
                    "rolled_back_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rolled Back At"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of changes",
                        verbose_name="Description",
                    ),
                ),
                (
                    "total_changes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Changes"
                    ),
                ),
                (
                    "successful_changes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Successful Changes"
                    ),
                ),
                (
                    "failed_changes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Failed Changes"
                    ),
                ),
                (
                    "rollback_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rolling back changes",
                        null=True,
                        verbose_name="Rollback Reason",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional contextual information",
                        verbose_name="Additional Metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Change Set",
                "verbose_name_plural": "AI Change Sets",
                "db_table": "onboarding_ai_changeset",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApprovedLocation",
            fields=[
                (
                    "location_id",
                    models.AutoField(
                        help_text="Unique location identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        help_text="Location name (e.g., 'Mumbai Corporate Office')",
                        max_length=255,
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("CORPORATE_OFFICE", "Corporate Office"),
                            ("CLIENT_SITE", "Client Site"),
                            ("BRANCH_OFFICE", "Branch Office"),
                            ("REMOTE_APPROVED", "Approved Remote Location"),
                            ("TRAINING_CENTER", "Training Center"),
                        ],
                        help_text="Type of location",
                        max_length=50,
                    ),
                ),
                ("address", models.TextField(help_text="Physical address")),
                ("city", models.CharField(help_text="City", max_length=100)),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="State/Province", max_length=100
                    ),
                ),
                ("country", models.CharField(help_text="Country", max_length=100)),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, help_text="Postal/ZIP code", max_length=20
                    ),
                ),
                (
                    "ip_ranges",
                    models.JSONField(
                        default=list,
                        help_text="Approved IP address ranges (CIDR notation)",
                    ),
                ),
                (
                    "requires_vpn",
                    models.BooleanField(
                        default=False, help_text="VPN connection required"
                    ),
                ),
                (
                    "geofence_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="GeoJSON polygon for geofencing",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude (for radius-based geofencing)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude (for radius-based geofencing)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "radius_meters",
                    models.IntegerField(
                        blank=True,
                        help_text="Geofence radius in meters (if using lat/long)",
                        null=True,
                    ),
                ),
                (
                    "trust_level",
                    models.CharField(
                        choices=[
                            ("HIGH", "High Trust"),
                            ("MEDIUM", "Medium Trust"),
                            ("LOW", "Low Trust"),
                        ],
                        default="MEDIUM",
                        help_text="Trust level for enrollment operations",
                        max_length=20,
                    ),
                ),
                (
                    "requires_additional_verification",
                    models.BooleanField(
                        default=False, help_text="Require additional security checks"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Location is active and approved"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When location was approved"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, help_text="When location was deactivated", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or requirements"
                    ),
                ),
            ],
            options={
                "verbose_name": "Approved Location",
                "verbose_name_plural": "Approved Locations",
                "db_table": "approved_location",
                "ordering": ["location_name"],
            },
        ),
        migrations.CreateModel(
            name="AuthoritativeKnowledge",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "knowledge_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_organization",
                    models.CharField(
                        help_text="Organization that published this knowledge",
                        max_length=200,
                        verbose_name="Source Organization",
                    ),
                ),
                (
                    "document_title",
                    models.CharField(
                        help_text="Title of the source document",
                        max_length=500,
                        verbose_name="Document Title",
                    ),
                ),
                (
                    "document_version",
                    models.CharField(
                        blank=True,
                        help_text="Version of the document",
                        max_length=50,
                        verbose_name="Document Version",
                    ),
                ),
                (
                    "authority_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("official", "Official"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Authority Level",
                    ),
                ),
                (
                    "content_vector",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        blank=True,
                        help_text="Vector embedding of the content",
                        null=True,
                        size=None,
                        verbose_name="Content Vector",
                    ),
                ),
                (
                    "content_summary",
                    models.TextField(
                        help_text="Summary of the knowledge content",
                        verbose_name="Content Summary",
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        help_text="When this knowledge was published",
                        verbose_name="Publication Date",
                    ),
                ),
                (
                    "last_verified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this knowledge was last verified",
                        verbose_name="Last Verified",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this knowledge is still current",
                        verbose_name="Is Current",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authoritative Knowledge",
                "verbose_name_plural": "Authoritative Knowledge",
                "db_table": "authoritative_knowledge",
                "ordering": ["mdtz"],
                "get_latest_by": ["publication_date", "mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuthoritativeKnowledgeChunk",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "chunk_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="Sequential chunk number within the document",
                        verbose_name="Chunk Index",
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        help_text="Text content of this chunk",
                        verbose_name="Content Text",
                    ),
                ),
                (
                    "content_vector",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        blank=True,
                        help_text="Vector embedding of the chunk content",
                        null=True,
                        size=None,
                        verbose_name="Content Vector",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata tags for filtering and categorization",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "last_verified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this chunk was last verified for accuracy",
                        verbose_name="Last Verified",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this chunk is still current and valid",
                        verbose_name="Is Current",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Chunk",
                "verbose_name_plural": "Knowledge Chunks",
                "db_table": "authoritative_knowledge_chunk",
                "ordering": ["mdtz"],
                "get_latest_by": ["last_verified", "mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChangeSetApproval",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "approval_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "approval_level",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("escalated", "Escalated"),
                        ],
                        default="primary",
                        max_length=20,
                        verbose_name="Approval Level",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "decision_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Decision At"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                ("conditions", models.TextField(blank=True, verbose_name="Conditions")),
                (
                    "modifications",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Modifications"
                    ),
                ),
                (
                    "request_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Request context (IP, user agent, correlation ID)",
                        verbose_name="Request Metadata",
                    ),
                ),
                (
                    "escalation_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Details if escalated (ticket info, etc.)",
                        verbose_name="Escalation Details",
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Set Approval",
                "verbose_name_plural": "Change Set Approvals",
                "db_table": "onboarding_changeset_approval",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("CLIENT", "Client Onboarding"),
                            ("SITE", "Site Survey"),
                            ("WORKER", "Worker Intake"),
                        ],
                        help_text="Which bounded context this conversation is for",
                        max_length=20,
                        verbose_name="Context Type",
                    ),
                ),
                (
                    "context_object_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of created object (site_id, request_id, client_id)",
                        max_length=100,
                        verbose_name="Context Object ID",
                    ),
                ),
                (
                    "handler_class",
                    models.CharField(
                        blank=True,
                        help_text="Fully qualified handler class name",
                        max_length=200,
                        verbose_name="Handler Class",
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("INITIAL_SETUP", "Initial Setup"),
                            ("CONFIG_UPDATE", "Configuration Update"),
                            ("TROUBLESHOOTING", "Troubleshooting"),
                            ("FEATURE_REQUEST", "Feature Request"),
                        ],
                        default="INITIAL_SETUP",
                        max_length=20,
                        verbose_name="Conversation Type",
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("IN_PROGRESS", "In Progress"),
                            (
                                "GENERATING_RECOMMENDATIONS",
                                "Generating Recommendations",
                            ),
                            ("AWAITING_USER_APPROVAL", "Awaiting User Approval"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("ERROR", "Error"),
                        ],
                        default="STARTED",
                        max_length=30,
                        verbose_name="Current State",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        default=dict,
                        help_text='Initial context: {"client_id": "...", "language": "en"}',
                    ),
                ),
                (
                    "collected_data",
                    models.JSONField(
                        default=dict, help_text="Accumulated data from conversation"
                    ),
                ),
                (
                    "voice_enabled",
                    models.BooleanField(
                        default=False, help_text="Voice input enabled for this session"
                    ),
                ),
                (
                    "audio_transcripts",
                    models.JSONField(
                        default=list,
                        help_text='Array of voice interactions: [{"user": "...", "assistant": "..."}]',
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="ISO 639-1 language code",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_interaction_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Conversation Session",
                "verbose_name_plural": "Conversation Sessions",
                "db_table": "core_onboarding_conversation",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="GeofenceMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("gfcode", models.CharField(max_length=100, verbose_name="Code")),
                ("gfname", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "alerttext",
                    models.CharField(max_length=100, verbose_name="Alert Text"),
                ),
                (
                    "geofence",
                    django.contrib.gis.db.models.fields.PolygonField(
                        geography=True,
                        help_text="Polygon defining the geographic boundary",
                        null=True,
                        srid=4326,
                        verbose_name="GeoFence",
                    ),
                ),
                ("enable", models.BooleanField(default=True, verbose_name="Enable")),
            ],
            options={
                "verbose_name": "Geofence",
                "verbose_name_plural": "Geofences",
                "db_table": "geofencemaster",
                "ordering": ["mdtz"],
                "get_latest_by": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KnowledgeIngestionJob",
            fields=[
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique job identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="Specific document URL to ingest", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("fetching", "Fetching Document"),
                            ("parsing", "Parsing Content"),
                            ("chunking", "Creating Chunks"),
                            ("embedding", "Generating Embeddings"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        help_text="Current pipeline stage",
                        max_length=20,
                    ),
                ),
                (
                    "chunks_created",
                    models.IntegerField(
                        default=0, help_text="Number of chunks created"
                    ),
                ),
                (
                    "embeddings_generated",
                    models.IntegerField(
                        default=0, help_text="Number of embeddings generated"
                    ),
                ),
                (
                    "processing_duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Total processing time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "timings",
                    models.JSONField(
                        default=dict,
                        help_text="Stage-wise timing breakdown (fetch, parse, chunk, embed)",
                    ),
                ),
                (
                    "processing_config",
                    models.JSONField(
                        default=dict,
                        help_text="Processing configuration (chunk size, model, etc.)",
                    ),
                ),
                (
                    "error_log",
                    models.TextField(
                        blank=True, help_text="Error messages and stack traces"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of retry attempts"
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created datetime"
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(auto_now=True, help_text="Modified datetime"),
                ),
            ],
            options={
                "verbose_name": "Knowledge Ingestion Job",
                "verbose_name_plural": "Knowledge Ingestion Jobs",
                "db_table": "knowledge_ingestion_job",
                "ordering": ["-cdtz"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeReview",
            fields=[
                (
                    "review_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique review identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft - Awaiting First Review"),
                            ("first_review", "First Review In Progress"),
                            ("second_review", "Second Review In Progress"),
                            ("approved", "Approved by Both Reviewers"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        help_text="Review status",
                        max_length=20,
                    ),
                ),
                (
                    "provenance_data",
                    models.JSONField(
                        default=dict,
                        help_text="Content provenance: who approved, when, why, changes made",
                    ),
                ),
                (
                    "accuracy_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Accuracy score (0.00-1.00)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "completeness_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Completeness score (0.00-1.00)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "relevance_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Relevance score (0.00-1.00)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(help_text="Reviewer notes and feedback")),
                (
                    "approval_conditions",
                    models.TextField(
                        blank=True, help_text="Conditions for approval (if any)"
                    ),
                ),
                (
                    "approved_for_publication",
                    models.BooleanField(
                        default=False,
                        help_text="Approved for publication to knowledge base",
                    ),
                ),
                (
                    "first_reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When first review was completed",
                        null=True,
                    ),
                ),
                (
                    "second_reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When second review was completed",
                        null=True,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="[DEPRECATED] Use first_reviewed_at/second_reviewed_at",
                        null=True,
                    ),
                ),
                (
                    "feedback_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured feedback (corrections, suggestions)",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created datetime"
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(auto_now=True, help_text="Modified datetime"),
                ),
            ],
            options={
                "verbose_name": "Knowledge Review",
                "verbose_name_plural": "Knowledge Reviews",
                "db_table": "knowledge_review",
                "ordering": ["-cdtz"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                (
                    "source_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique source identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Source name (e.g., 'ISO 27001 Standards Library')",
                        max_length=255,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("iso", "ISO Standards"),
                            ("nist", "NIST Publications"),
                            ("asis", "ASIS International"),
                            ("internal", "Internal Documentation"),
                            ("external", "External Approved Source"),
                        ],
                        help_text="Type of knowledge source",
                        max_length=50,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="Base URL for document fetching",
                        max_length=500,
                    ),
                ),
                (
                    "auth_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Authentication configuration (encrypted)",
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        blank=True,
                        help_text="Legal jurisdiction (e.g., 'India', 'Global')",
                        max_length=100,
                    ),
                ),
                (
                    "industry_tags",
                    models.JSONField(
                        default=list,
                        help_text="Industry categories (e.g., ['security', 'facilities'])",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="Primary language code (ISO 639-1)",
                        max_length=10,
                    ),
                ),
                (
                    "fetch_policy",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Fetch Only"),
                            ("scheduled", "Scheduled Automatic Fetch"),
                            ("on_demand", "On-Demand Fetch"),
                        ],
                        default="manual",
                        help_text="Document fetching policy",
                        max_length=20,
                    ),
                ),
                (
                    "fetch_schedule_cron",
                    models.CharField(
                        blank=True,
                        help_text="Cron expression for scheduled fetching",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Source is active and available"
                    ),
                ),
                (
                    "last_fetch_attempt",
                    models.DateTimeField(
                        blank=True, help_text="Last fetch attempt timestamp", null=True
                    ),
                ),
                (
                    "last_successful_fetch",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful fetch timestamp",
                        null=True,
                    ),
                ),
                (
                    "total_documents_fetched",
                    models.IntegerField(
                        default=0, help_text="Total documents successfully fetched"
                    ),
                ),
                (
                    "fetch_error_count",
                    models.IntegerField(
                        default=0, help_text="Count of consecutive fetch errors"
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(blank=True, help_text="Last fetch error message"),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created datetime"
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(auto_now=True, help_text="Modified datetime"),
                ),
            ],
            options={
                "verbose_name": "Knowledge Source",
                "verbose_name_plural": "Knowledge Sources",
                "db_table": "knowledge_source",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LLMRecommendation",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "recommendation_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "maker_output",
                    models.JSONField(
                        help_text="Raw output from the maker LLM",
                        verbose_name="Maker Output",
                    ),
                ),
                (
                    "checker_output",
                    models.JSONField(
                        blank=True,
                        help_text="Validation output from checker LLM",
                        null=True,
                        verbose_name="Checker Output",
                    ),
                ),
                (
                    "consensus",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Final consensus between maker and checker",
                        verbose_name="Consensus",
                    ),
                ),
                (
                    "authoritative_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="References to authoritative knowledge sources",
                        verbose_name="Authoritative Sources",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Overall confidence score (0.0 to 1.0)",
                        verbose_name="Confidence Score",
                    ),
                ),
                (
                    "user_decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("modified", "Modified"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="User Decision",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why the user rejected the recommendation",
                        null=True,
                        verbose_name="Rejection Reason",
                    ),
                ),
                (
                    "modifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User modifications to the recommendation",
                        verbose_name="Modifications",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("validated", "Validated"),
                            ("needs_review", "Needs Review"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        help_text="Current processing status of the recommendation",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "latency_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Total processing time in milliseconds",
                        null=True,
                        verbose_name="Latency (ms)",
                    ),
                ),
                (
                    "provider_cost_cents",
                    models.IntegerField(
                        blank=True,
                        help_text="Cost of LLM provider calls in cents",
                        null=True,
                        verbose_name="Provider Cost (cents)",
                    ),
                ),
                (
                    "eval_scores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Quality evaluation scores and metrics",
                        verbose_name="Evaluation Scores",
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True,
                        help_text="Distributed tracing ID for request correlation",
                        max_length=50,
                        verbose_name="Trace ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Recommendation",
                "verbose_name_plural": "LLM Recommendations",
                "db_table": "llm_recommendation",
                "ordering": ["mdtz"],
                "get_latest_by": ["mdtz", "cdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OnboardingMedia",
            fields=[
                (
                    "media_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("CLIENT", "Client Setup"),
                            ("SITE", "Site Survey"),
                            ("WORKER", "Worker Documents"),
                        ],
                        help_text="Which onboarding context this media belongs to",
                        max_length=20,
                        verbose_name="Context Type",
                    ),
                ),
                (
                    "context_object_id",
                    models.CharField(
                        help_text="UUID of the related object (site_id, request_id, etc.)",
                        max_length=100,
                        verbose_name="Context Object ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("PHOTO", "Photo"),
                            ("VIDEO", "Video"),
                            ("AUDIO", "Audio Recording"),
                            ("DOCUMENT", "Document Scan"),
                        ],
                        max_length=20,
                        verbose_name="Media Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="onboarding_media/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "mp4",
                                    "webm",
                                    "mov",
                                    "mp3",
                                    "wav",
                                    "ogg",
                                    "pdf",
                                ]
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Auto-generated thumbnail for photos/videos",
                        null=True,
                        upload_to="onboarding_media/thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "gps_latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="GPS Latitude"
                    ),
                ),
                (
                    "gps_longitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="GPS Longitude"
                    ),
                ),
                (
                    "gps_accuracy",
                    models.FloatField(
                        blank=True, null=True, verbose_name="GPS Accuracy (meters)"
                    ),
                ),
                (
                    "compass_direction",
                    models.FloatField(
                        blank=True,
                        help_text="Degrees (0-360) camera was facing",
                        null=True,
                        verbose_name="Compass Direction",
                    ),
                ),
                (
                    "voice_transcript",
                    models.TextField(
                        blank=True,
                        help_text="Speech-to-text transcription if audio",
                        verbose_name="Voice Transcript",
                    ),
                ),
                (
                    "text_description",
                    models.TextField(
                        blank=True,
                        help_text="User-provided text description",
                        verbose_name="Text Description",
                    ),
                ),
                (
                    "translated_description",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Translations: {"es": "...", "hi": "...", "ta": "..."}',
                    ),
                ),
                (
                    "ai_analysis",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Vision API or LLM analysis results",
                    ),
                ),
                (
                    "detected_objects",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Detected objects: ["camera", "door", "person"]',
                    ),
                ),
                (
                    "safety_concerns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Safety issues: ["no fire extinguisher", "blocked exit"]',
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed",
                    models.BooleanField(
                        default=False, help_text="AI analysis completed"
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Media",
                "verbose_name_plural": "Onboarding Media",
                "db_table": "core_onboarding_media",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingObservation",
            fields=[
                (
                    "observation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("CLIENT", "Client Setup"),
                            ("SITE", "Site Survey"),
                            ("WORKER", "Worker Documents"),
                        ],
                        max_length=20,
                        verbose_name="Context Type",
                    ),
                ),
                (
                    "context_object_id",
                    models.CharField(
                        help_text="UUID of related object",
                        max_length=100,
                        verbose_name="Context Object ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="observations/audio/",
                        verbose_name="Audio File",
                    ),
                ),
                (
                    "original_transcript",
                    models.TextField(
                        blank=True,
                        help_text="Raw speech-to-text output",
                        verbose_name="Original Transcript",
                    ),
                ),
                (
                    "text_input",
                    models.TextField(
                        blank=True,
                        help_text="User-typed text (alternative to voice)",
                        verbose_name="Text Input",
                    ),
                ),
                (
                    "english_translation",
                    models.TextField(blank=True, verbose_name="English Translation"),
                ),
                (
                    "enhanced_observation",
                    models.TextField(
                        blank=True,
                        help_text="LLM-enhanced version with context",
                        verbose_name="Enhanced Observation",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical Issue"),
                            ("HIGH", "High Priority"),
                            ("MEDIUM", "Medium Priority"),
                            ("LOW", "Low Priority"),
                            ("INFO", "Informational"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="AI confidence (0.0-1.0)",
                        verbose_name="Confidence Score",
                    ),
                ),
                (
                    "entities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Named entities: {"location": "Gate 3", "asset": "Camera #5"}',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Onboarding Observation",
                "verbose_name_plural": "Onboarding Observations",
                "db_table": "core_onboarding_observation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TypeAssist",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tacode", models.CharField(max_length=50, verbose_name="Code")),
                ("taname", models.CharField(max_length=100, verbose_name="Name")),
                ("enable", models.BooleanField(default=True, verbose_name="Enable")),
            ],
            options={
                "verbose_name": "Type Assist",
                "verbose_name_plural": "Type Assists",
                "db_table": "typeassist",
                "ordering": ["mdtz"],
                "abstract": False,
            },
            managers=[
                ("objects", apps.client_onboarding.managers.TypeAssistManager()),
            ],
        ),
    ]
