# Generated by Django 5.2.1 - Placeholder migration for core_onboarding
# This migration will be regenerated with `python manage.py makemigrations core_onboarding`
# once Django environment is available.

"""
Initial migration for core_onboarding bounded context.

This migration creates 13 models for the multimodal onboarding conversation system:

1. OnboardingMedia - Media file storage (images, videos, audio, PDFs)
2. OnboardingObservation - Structured observations extracted from media
3. ConversationSession - Chat session tracking with context
4. LLMRecommendation - AI-generated recommendations with confidence scores
5. AuthoritativeKnowledge - Verified knowledge base entries
6. AuthoritativeKnowledgeChunk - Vector embeddings for RAG retrieval
7. AIChangeSet - Proposed changes requiring approval
8. AIChangeRecord - Individual change records within changeset
9. ChangeSetApproval - Multi-stakeholder approval workflow
10. TypeAssist - Classification suggestions for entities
11. GeofenceMaster - Geofence boundary management
12. KnowledgeSource - Knowledge source metadata
13. KnowledgeIngestionJob - Async knowledge ingestion tracking
14. KnowledgeReview - Review workflow for knowledge validation

All models extend EnhancedTenantModel for multi-tenancy support.

Dependencies:
- apps.tenants (for EnhancedTenantModel)
- apps.peoples (for People foreign key)
- apps.client_onboarding (for Bt foreign key in some models)
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '__latest__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_onboarding', '0001_initial'),
    ]

    operations = [
        # ===============================================
        # MEDIA MODELS
        # ===============================================
        migrations.CreateModel(
            name='OnboardingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('media_type', models.CharField(max_length=20, choices=[
                    ('image', 'Image'),
                    ('video', 'Video'),
                    ('audio', 'Audio'),
                    ('document', 'Document'),
                ])),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('upload_source', models.CharField(max_length=50)),
                ('metadata', models.JSONField(default=dict, blank=True)),
                ('processing_status', models.CharField(max_length=20, default='pending')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'db_table': 'core_onboarding_media',
                'indexes': [
                    models.Index(fields=['tenant', 'media_type', 'created_at']),
                    models.Index(fields=['processing_status']),
                ],
            },
        ),

        # ===============================================
        # OBSERVATION MODELS
        # ===============================================
        migrations.CreateModel(
            name='OnboardingObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_onboarding.onboardingmedia', related_name='observations')),
                ('observation_type', models.CharField(max_length=50)),
                ('observation_data', models.JSONField()),
                ('confidence_score', models.FloatField(null=True, blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True, blank=True)),
            ],
            options={
                'db_table': 'core_onboarding_observation',
                'indexes': [
                    models.Index(fields=['tenant', 'observation_type']),
                    models.Index(fields=['verified']),
                ],
            },
        ),

        # ===============================================
        # CONVERSATION MODELS
        # ===============================================
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('session_id', models.UUIDField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('context', models.JSONField(default=dict)),
                ('messages', models.JSONField(default=list)),
                ('status', models.CharField(max_length=20, default='active')),
            ],
            options={
                'db_table': 'core_onboarding_conversation_session',
                'indexes': [
                    models.Index(fields=['tenant', 'user', 'status']),
                    models.Index(fields=['session_id']),
                ],
            },
        ),

        # ===============================================
        # KNOWLEDGE MODELS
        # ===============================================
        migrations.CreateModel(
            name='LLMRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('recommendation_type', models.CharField(max_length=50)),
                ('recommendation_data', models.JSONField()),
                ('confidence_score', models.FloatField()),
                ('applied', models.BooleanField(default=False)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True, blank=True)),
            ],
            options={
                'db_table': 'core_onboarding_llm_recommendation',
            },
        ),

        migrations.CreateModel(
            name='AuthoritativeKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('knowledge_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_onboarding_authoritative_knowledge',
                'indexes': [
                    models.Index(fields=['tenant', 'knowledge_type', 'is_active']),
                ],
            },
        ),

        migrations.CreateModel(
            name='AuthoritativeKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_onboarding.authoritativeknowledge', related_name='chunks')),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('embedding_vector', models.JSONField(null=True, blank=True)),
            ],
            options={
                'db_table': 'core_onboarding_knowledge_chunk',
                'indexes': [
                    models.Index(fields=['knowledge', 'chunk_index']),
                ],
            },
        ),

        # ===============================================
        # CHANGESET MODELS
        # ===============================================
        migrations.CreateModel(
            name='AIChangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('changeset_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20, default='pending')),
                ('confidence_score', models.FloatField()),
                ('created_by_ai', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_onboarding_ai_changeset',
                'indexes': [
                    models.Index(fields=['tenant', 'status']),
                ],
            },
        ),

        migrations.CreateModel(
            name='AIChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_onboarding.aichangeset', related_name='changes')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.JSONField(null=True, blank=True)),
                ('new_value', models.JSONField()),
                ('change_reason', models.TextField()),
            ],
            options={
                'db_table': 'core_onboarding_ai_change_record',
            },
        ),

        migrations.CreateModel(
            name='ChangeSetApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_onboarding.aichangeset', related_name='approvals')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('decision', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'core_onboarding_changeset_approval',
            },
        ),

        # ===============================================
        # CLASSIFICATION MODELS
        # ===============================================
        migrations.CreateModel(
            name='TypeAssist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('entity_type', models.CharField(max_length=50)),
                ('suggested_classification', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'core_onboarding_type_assist',
            },
        ),

        migrations.CreateModel(
            name='GeofenceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('name', models.CharField(max_length=200)),
                ('boundary_geojson', models.JSONField()),
                ('radius_meters', models.FloatField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_onboarding_geofence_master',
            },
        ),

        # ===============================================
        # KNOWLEDGE SOURCE MODELS
        # ===============================================
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('source_type', models.CharField(max_length=50)),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(null=True, blank=True)),
                ('credentials', models.JSONField(null=True, blank=True)),
                ('sync_frequency', models.CharField(max_length=50)),
                ('last_sync', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_onboarding_knowledge_source',
            },
        ),

        migrations.CreateModel(
            name='KnowledgeIngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_onboarding.knowledgesource', related_name='ingestion_jobs')),
                ('status', models.CharField(max_length=20, default='pending')),
                ('started_at', models.DateTimeField(null=True, blank=True)),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'core_onboarding_knowledge_ingestion_job',
            },
        ),

        # ===============================================
        # KNOWLEDGE REVIEW MODELS
        # ===============================================
        migrations.CreateModel(
            name='KnowledgeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_onboarding.authoritativeknowledge', related_name='reviews')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review_status', models.CharField(max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('accuracy_score', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'core_onboarding_knowledge_review',
            },
        ),
    ]
