# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client_onboarding", "0003_initial"),
        ("core_onboarding", "0001_initial"),
        ("peoples", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aichangerecord",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="aichangerecord",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="aichangeset",
            name="approved_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_changesets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved By",
            ),
        ),
        migrations.AddField(
            model_name="aichangeset",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="aichangeset",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="aichangeset",
            name="rolled_back_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rolled_back_changesets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Rolled Back By",
            ),
        ),
        migrations.AddField(
            model_name="aichangeset",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="aichangerecord",
            name="changeset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_records",
                to="core_onboarding.aichangeset",
                verbose_name="Change Set",
            ),
        ),
        migrations.AddField(
            model_name="approvedlocation",
            name="approved_by",
            field=models.ForeignKey(
                help_text="User who approved this location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvedlocation",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated business unit/site",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_locations",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="approvedlocation",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="authoritativeknowledge",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="authoritativeknowledge",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="authoritativeknowledge",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="authoritativeknowledgechunk",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="authoritativeknowledgechunk",
            name="knowledge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="core_onboarding.authoritativeknowledge",
                verbose_name="Knowledge Document",
            ),
        ),
        migrations.AddField(
            model_name="authoritativeknowledgechunk",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="authoritativeknowledgechunk",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="changesetapproval",
            name="approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changeset_approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approver",
            ),
        ),
        migrations.AddField(
            model_name="changesetapproval",
            name="changeset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="core_onboarding.aichangeset",
                verbose_name="Change Set",
            ),
        ),
        migrations.AddField(
            model_name="changesetapproval",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="changesetapproval",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client context for this conversation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversation_sessions",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aichangeset",
            name="conversation_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changesets",
                to="core_onboarding.conversationsession",
                verbose_name="Conversation Session",
            ),
        ),
        migrations.AddField(
            model_name="geofencemaster",
            name="alerttogroup",
            field=models.ForeignKey(
                help_text="Group to receive geofence alerts",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="peoples.pgroup",
                verbose_name="Alert to Group",
            ),
        ),
        migrations.AddField(
            model_name="geofencemaster",
            name="alerttopeople",
            field=models.ForeignKey(
                help_text="Individual to receive geofence alerts",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Alert to Person",
            ),
        ),
        migrations.AddField(
            model_name="geofencemaster",
            name="bu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="geofence_sites",
                to="client_onboarding.bt",
                verbose_name="Site",
            ),
        ),
        migrations.AddField(
            model_name="geofencemaster",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="onboarding_geofence_clients",
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="geofencemaster",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="geofencemaster",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeingestionjob",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who initiated ingestion",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_ingestion_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeingestionjob",
            name="document",
            field=models.ForeignKey(
                blank=True,
                help_text="Created/updated document (null until created)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingestion_jobs",
                to="core_onboarding.authoritativeknowledge",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeingestionjob",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="knowledgereview",
            name="document",
            field=models.ForeignKey(
                help_text="Document being reviewed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="core_onboarding.authoritativeknowledge",
            ),
        ),
        migrations.AddField(
            model_name="knowledgereview",
            name="first_reviewer",
            field=models.ForeignKey(
                help_text="First reviewer (subject matter expert)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="first_knowledge_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgereview",
            name="reviewer",
            field=models.ForeignKey(
                help_text="[DEPRECATED] Use first_reviewer instead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_knowledge_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgereview",
            name="second_reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="Second reviewer (quality assurance)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="second_knowledge_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgereview",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="knowledgesource",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeingestionjob",
            name="source",
            field=models.ForeignKey(
                help_text="Knowledge source",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingestion_jobs",
                to="core_onboarding.knowledgesource",
            ),
        ),
        migrations.AddField(
            model_name="llmrecommendation",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="llmrecommendation",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="llmrecommendation",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="core_onboarding.conversationsession",
                verbose_name="Session",
            ),
        ),
        migrations.AddField(
            model_name="llmrecommendation",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="onboardingmedia",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="onboardingmedia",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_media",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="onboardingobservation",
            name="conversation_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations",
                to="core_onboarding.conversationsession",
            ),
        ),
        migrations.AddField(
            model_name="onboardingobservation",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_observations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="onboardingobservation",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                help_text="Photos/videos attached to this observation (0 to N)",
                related_name="observations",
                to="core_onboarding.onboardingmedia",
            ),
        ),
        migrations.AddField(
            model_name="onboardingobservation",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="typeassist",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="ta_bus",
                to="client_onboarding.bt",
                verbose_name="Business Unit",
            ),
        ),
        migrations.AddField(
            model_name="typeassist",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="ta_clients",
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="typeassist",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="typeassist",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="typeassist",
            name="tatype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="children",
                to="core_onboarding.typeassist",
                verbose_name="Parent Type",
            ),
        ),
        migrations.AddField(
            model_name="typeassist",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="aichangerecord",
            index=models.Index(
                fields=["changeset", "status"], name="change_record_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichangerecord",
            index=models.Index(
                fields=["model_name", "object_id"], name="change_record_object_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="aichangerecord",
            constraint=models.UniqueConstraint(
                fields=("changeset", "sequence_order"), name="unique_changeset_sequence"
            ),
        ),
        migrations.AddIndex(
            model_name="approvedlocation",
            index=models.Index(
                fields=["location_type", "is_active"],
                name="approved_lo_locatio_864853_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvedlocation",
            index=models.Index(
                fields=["site", "is_active"], name="approved_lo_site_id_502228_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvedlocation",
            index=models.Index(
                fields=["trust_level"], name="approved_lo_trust_l_24163f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvedlocation",
            index=models.Index(
                fields=["country", "city"], name="approved_lo_country_60e39a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authoritativeknowledge",
            index=models.Index(fields=["cdtz"], name="auth_know_cdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="authoritativeknowledge",
            index=models.Index(fields=["mdtz"], name="auth_know_mdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="authoritativeknowledgechunk",
            index=models.Index(
                fields=["knowledge", "chunk_index"], name="knowledge_chunk_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authoritativeknowledgechunk",
            index=models.Index(fields=["is_current"], name="chunk_current_idx"),
        ),
        migrations.AddIndex(
            model_name="changesetapproval",
            index=models.Index(
                fields=["changeset", "status"], name="approval_changeset_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="changesetapproval",
            index=models.Index(
                fields=["approver", "status"], name="approval_approver_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["context_type", "current_state"], name="conv_context_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(fields=["user"], name="conv_user_idx"),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(fields=["started_at"], name="conv_started_idx"),
        ),
        migrations.AddIndex(
            model_name="aichangeset",
            index=models.Index(
                fields=["status", "cdtz"], name="changeset_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichangeset",
            index=models.Index(
                fields=["conversation_session", "status"],
                name="changeset_session_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="geofencemaster",
            index=models.Index(fields=["mdtz"], name="geofencemaster_mdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="geofencemaster",
            index=models.Index(fields=["cdtz"], name="geofencemaster_cdtz_idx"),
        ),
        migrations.AddConstraint(
            model_name="geofencemaster",
            constraint=models.UniqueConstraint(
                fields=("gfcode", "bu"), name="gfcode_bu_uk"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgereview",
            index=models.Index(
                fields=["status", "cdtz"], name="knowledge_r_status_870bef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgereview",
            index=models.Index(
                fields=["document", "status"], name="knowledge_r_documen_ec79a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgereview",
            index=models.Index(
                fields=["first_reviewer", "first_reviewed_at"],
                name="knowledge_r_first_r_606547_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgereview",
            index=models.Index(
                fields=["second_reviewer", "second_reviewed_at"],
                name="knowledge_r_second__93f317_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgereview",
            index=models.Index(
                fields=["approved_for_publication"],
                name="knowledge_r_approve_c3f40b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgereview",
            index=models.Index(
                fields=["document", "approved_for_publication"],
                name="knowledge_r_documen_696707_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgereview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "approved"),
                    ("second_reviewer__isnull", True),
                    ("second_reviewer__isnull", False),
                    _connector="OR",
                ),
                name="two_person_approval_constraint",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["source_type", "is_active"],
                name="knowledge_s_source__d52d6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["fetch_policy", "is_active"],
                name="knowledge_s_fetch_p_f0fb2d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["last_successful_fetch"], name="knowledge_s_last_su_b3d483_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeingestionjob",
            index=models.Index(
                fields=["status", "cdtz"], name="knowledge_i_status_22d546_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeingestionjob",
            index=models.Index(
                fields=["source", "status"], name="knowledge_i_source__244844_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeingestionjob",
            index=models.Index(
                fields=["created_by", "cdtz"], name="knowledge_i_created_4e347e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeingestionjob",
            index=models.Index(
                fields=["document"], name="knowledge_i_documen_9ab353_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmrecommendation",
            index=models.Index(
                fields=["session", "status"], name="llm_rec_session_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmrecommendation",
            index=models.Index(
                fields=["confidence_score"], name="llm_rec_confidence_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmrecommendation",
            index=models.Index(fields=["trace_id"], name="llm_rec_trace_id_idx"),
        ),
        migrations.AddIndex(
            model_name="llmrecommendation",
            index=models.Index(
                fields=["status", "cdtz"], name="llm_rec_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingmedia",
            index=models.Index(
                fields=["context_type", "context_object_id"], name="media_context_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingmedia",
            index=models.Index(fields=["uploaded_at"], name="media_uploaded_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingmedia",
            index=models.Index(fields=["media_type"], name="media_type_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingobservation",
            index=models.Index(
                fields=["context_type", "context_object_id"], name="obs_context_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingobservation",
            index=models.Index(fields=["created_at"], name="obs_created_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingobservation",
            index=models.Index(fields=["severity"], name="obs_severity_idx"),
        ),
        migrations.AddIndex(
            model_name="typeassist",
            index=models.Index(fields=["mdtz"], name="typeassist_mdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="typeassist",
            index=models.Index(fields=["cdtz"], name="typeassist_cdtz_idx"),
        ),
        migrations.AddConstraint(
            model_name="typeassist",
            constraint=models.UniqueConstraint(
                fields=("tacode", "tatype", "client"), name="code_unique"
            ),
        ),
    ]
