# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ml_training", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="labelingtask",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_labeling_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned To",
            ),
        ),
        migrations.AddField(
            model_name="labelingtask",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="labelingtask",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="labelingtask",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_labeling_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewer",
            ),
        ),
        migrations.AddField(
            model_name="labelingtask",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="trainingdataset",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_datasets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="trainingdataset",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modified_datasets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AddField(
            model_name="trainingdataset",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="trainingdataset",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="labelingtask",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labeling_tasks",
                to="ml_training.trainingdataset",
                verbose_name="Dataset",
            ),
        ),
        migrations.AddField(
            model_name="trainingexample",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="trainingexample",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_examples",
                to="ml_training.trainingdataset",
                verbose_name="Dataset",
            ),
        ),
        migrations.AddField(
            model_name="trainingexample",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="trainingexample",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="labelingtask",
            name="examples",
            field=models.ManyToManyField(
                related_name="labeling_tasks",
                to="ml_training.trainingexample",
                verbose_name="Examples",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingdataset",
            index=models.Index(
                fields=["dataset_type", "status"], name="ml_training_dataset_749d77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingdataset",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="ml_training_created_3c2da8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingdataset",
            index=models.Index(
                fields=["total_examples", "labeled_examples"],
                name="ml_training_total_e_3d7032_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingdataset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("labeled_examples__lte", models.F("total_examples"))
                ),
                name="labeled_examples_not_exceed_total",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingexample",
            index=models.Index(
                fields=["dataset", "labeling_status"],
                name="ml_training_dataset_9a8730_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingexample",
            index=models.Index(
                fields=["is_labeled", "quality_score"],
                name="ml_training_is_labe_1c15da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingexample",
            index=models.Index(
                fields=["selected_for_labeling", "labeling_priority"],
                name="ml_training_selecte_a61e65_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingexample",
            index=models.Index(
                fields=["uncertainty_score", "difficulty_score"],
                name="ml_training_uncerta_b0fbec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingexample",
            index=models.Index(
                fields=["source_system", "source_id"],
                name="ml_training_source__01c72b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="labelingtask",
            index=models.Index(
                fields=["assigned_to", "task_status"],
                name="ml_labeling_assigne_93f786_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="labelingtask",
            index=models.Index(
                fields=["dataset", "task_type"], name="ml_labeling_dataset_531131_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labelingtask",
            index=models.Index(
                fields=["priority", "due_date"], name="ml_labeling_priorit_3bf451_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labelingtask",
            index=models.Index(
                fields=["completed_at", "quality_score"],
                name="ml_labeling_complet_ef1994_idx",
            ),
        ),
    ]
