# Generated by Stream Testbench enhancement
# Adds client version tracking to AnomalyOccurrence for trend analysis

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '__latest__'),  # This will be updated to the actual latest migration
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyoccurrence',
            name='client_app_version',
            field=models.CharField(
                blank=True,
                help_text='Client application version (e.g., 1.2.3)',
                max_length=50
            ),
        ),
        migrations.AddField(
            model_name='anomalyoccurrence',
            name='client_os_version',
            field=models.CharField(
                blank=True,
                help_text='Client OS version (e.g., Android 13, iOS 16.1)',
                max_length=50
            ),
        ),
        migrations.AddField(
            model_name='anomalyoccurrence',
            name='client_device_model',
            field=models.CharField(
                blank=True,
                help_text='Client device model (e.g., iPhone 14, Samsung Galaxy S23)',
                max_length=100
            ),
        ),
        # Add database indexes for efficient querying
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY idx_anomalyoccurrence_app_version_created ON issue_tracker_anomalyoccurrence (client_app_version, created_at);",
            reverse_sql="DROP INDEX idx_anomalyoccurrence_app_version_created;"
        ),
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY idx_anomalyoccurrence_os_version_created ON issue_tracker_anomalyoccurrence (client_os_version, created_at);",
            reverse_sql="DROP INDEX idx_anomalyoccurrence_os_version_created;"
        ),
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY idx_anomalyoccurrence_signature_app_version ON issue_tracker_anomalyoccurrence (signature_id, client_app_version);",
            reverse_sql="DROP INDEX idx_anomalyoccurrence_signature_app_version;"
        ),
    ]