# Generated by Django 5.2.1 on 2024-01-01 12:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalySignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_hash', models.CharField(help_text='SHA-256 hash of anomaly signature', max_length=64, unique=True)),
                ('anomaly_type', models.CharField(help_text='Type of anomaly (latency, error, schema, etc.)', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('ignored', 'Ignored'), ('monitoring', 'Monitoring')], default='active', max_length=20)),
                ('pattern', models.JSONField(help_text='Pattern definition for anomaly detection')),
                ('endpoint_pattern', models.CharField(max_length=200)),
                ('error_class', models.CharField(blank=True, max_length=100)),
                ('schema_signature', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('mttr_seconds', models.IntegerField(blank=True, help_text='Mean Time To Resolution in seconds', null=True)),
                ('mtbf_hours', models.FloatField(blank=True, help_text='Mean Time Between Failures in hours', null=True)),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization and search')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_run_id', models.UUIDField(blank=True, null=True)),
                ('event_ref', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('exception_class', models.CharField(blank=True, max_length=100)),
                ('stack_hash', models.CharField(blank=True, max_length=64)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('payload_sanitized', models.JSONField(blank=True, help_text='Sanitized payload data', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('environment', models.CharField(default='production', max_length=50)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_anomalies', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='issue_tracker.anomalysignature')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FixSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fix_type', models.CharField(choices=[('index', 'Database Index'), ('serializer', 'Serializer Update'), ('rate_limit', 'Rate Limiting'), ('connection_pool', 'Connection Pool'), ('caching', 'Caching Strategy'), ('retry_policy', 'Retry Policy'), ('schema_update', 'Schema Update'), ('configuration', 'Configuration Change'), ('code_fix', 'Code Fix'), ('infrastructure', 'Infrastructure Change')], max_length=30)),
                ('confidence', models.FloatField(help_text='Confidence score from 0.0 to 1.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('priority_score', models.IntegerField(help_text='Priority score from 1 (low) to 10 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('patch_template', models.TextField(blank=True, help_text='Code or configuration patch template')),
                ('implementation_steps', models.JSONField(default=list, help_text='Step-by-step implementation guide')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('verified', 'Verified')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='ai_assistant', help_text='Source of suggestion (ai_assistant, rule_engine, user)', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('auto_applicable', models.BooleanField(default=False, help_text='Can this fix be applied automatically?')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fixes', to=settings.AUTH_USER_MODEL)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_suggestions', to='issue_tracker.anomalysignature')),
            ],
            options={
                'ordering': ['-priority_score', '-confidence', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FixAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('applied', 'Applied'), ('tested', 'Tested'), ('rolled_back', 'Rolled Back'), ('verified', 'Verified')], max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('commit_sha', models.CharField(blank=True, max_length=40)),
                ('pr_link', models.URLField(blank=True)),
                ('deployment_id', models.CharField(blank=True, max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_actions', to='issue_tracker.anomalyoccurrence')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='issue_tracker.fixsuggestion')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_occurrence_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence_count', models.IntegerField(default=0)),
                ('days_since_last_fix', models.IntegerField(blank=True, null=True)),
                ('typical_interval_hours', models.FloatField(blank=True, null=True)),
                ('severity_trend', models.CharField(blank=True, choices=[('improving', 'Improving'), ('stable', 'Stable'), ('worsening', 'Worsening')], max_length=20, null=True)),
                ('fixes_attempted', models.IntegerField(default=0)),
                ('successful_fixes', models.IntegerField(default=0)),
                ('fix_success_rate', models.FloatField(blank=True, null=True)),
                ('requires_attention', models.BooleanField(default=False)),
                ('alert_threshold_exceeded', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_tracker', to='issue_tracker.anomalysignature')),
            ],
        ),
        # Add indexes for issue_tracker
        migrations.AddIndex(
            model_name='anomalysignature',
            index=models.Index(fields=['signature_hash'], name='issue_tracker_anomalysignature_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalysignature',
            index=models.Index(fields=['anomaly_type', 'severity'], name='issue_tracker_anomalysignature_type_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalysignature',
            index=models.Index(fields=['status', 'last_seen'], name='issue_tracker_anomalysignature_status_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalysignature',
            index=models.Index(fields=['endpoint_pattern'], name='issue_tracker_anomalysignature_endpoint_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyoccurrence',
            index=models.Index(fields=['signature', 'status'], name='issue_tracker_anomalyoccurrence_sig_status_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyoccurrence',
            index=models.Index(fields=['created_at'], name='issue_tracker_anomalyoccurrence_created_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyoccurrence',
            index=models.Index(fields=['status', 'created_at'], name='issue_tracker_anomalyoccurrence_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyoccurrence',
            index=models.Index(fields=['correlation_id'], name='issue_tracker_anomalyoccurrence_correlation_idx'),
        ),
        migrations.AddIndex(
            model_name='fixsuggestion',
            index=models.Index(fields=['signature', 'status'], name='issue_tracker_fixsuggestion_sig_status_idx'),
        ),
        migrations.AddIndex(
            model_name='fixsuggestion',
            index=models.Index(fields=['fix_type', 'confidence'], name='issue_tracker_fixsuggestion_type_conf_idx'),
        ),
        migrations.AddIndex(
            model_name='fixsuggestion',
            index=models.Index(fields=['auto_applicable', 'risk_level'], name='issue_tracker_fixsuggestion_auto_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='fixaction',
            index=models.Index(fields=['occurrence', 'action_type'], name='issue_tracker_fixaction_occur_action_idx'),
        ),
        migrations.AddIndex(
            model_name='fixaction',
            index=models.Index(fields=['suggestion', 'result'], name='issue_tracker_fixaction_sugg_result_idx'),
        ),
        migrations.AddIndex(
            model_name='fixaction',
            index=models.Index(fields=['applied_at'], name='issue_tracker_fixaction_applied_idx'),
        ),
        migrations.AddIndex(
            model_name='recurrencetracker',
            index=models.Index(fields=['requires_attention'], name='issue_tracker_recurrencetracker_attention_idx'),
        ),
        migrations.AddIndex(
            model_name='recurrencetracker',
            index=models.Index(fields=['alert_threshold_exceeded'], name='issue_tracker_recurrencetracker_alert_idx'),
        ),
        migrations.AddIndex(
            model_name='recurrencetracker',
            index=models.Index(fields=['updated_at'], name='issue_tracker_recurrencetracker_updated_idx'),
        ),
    ]