# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issue_tracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anomalyoccurrence",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_anomalies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="anomalyoccurrence",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_anomalies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="anomalysignature",
            index=models.Index(
                fields=["signature_hash"], name="issue_track_signatu_2a683c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalysignature",
            index=models.Index(
                fields=["anomaly_type", "severity"],
                name="issue_track_anomaly_1c0b60_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalysignature",
            index=models.Index(
                fields=["status", "last_seen"], name="issue_track_status_bcff17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalysignature",
            index=models.Index(
                fields=["endpoint_pattern"], name="issue_track_endpoin_40e7a0_idx"
            ),
        ),
        migrations.AddField(
            model_name="anomalyoccurrence",
            name="signature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrences",
                to="issue_tracker.anomalysignature",
            ),
        ),
        migrations.AddField(
            model_name="fixaction",
            name="applied_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="fixaction",
            name="occurrence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fix_actions",
                to="issue_tracker.anomalyoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="fixsuggestion",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_fixes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixsuggestion",
            name="signature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fix_suggestions",
                to="issue_tracker.anomalysignature",
            ),
        ),
        migrations.AddField(
            model_name="fixaction",
            name="suggestion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="issue_tracker.fixsuggestion",
            ),
        ),
        migrations.AddField(
            model_name="recurrencetracker",
            name="signature",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurrence_tracker",
                to="issue_tracker.anomalysignature",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalyoccurrence",
            index=models.Index(
                fields=["signature", "status"], name="issue_track_signatu_c71b0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalyoccurrence",
            index=models.Index(
                fields=["created_at"], name="issue_track_created_e82855_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalyoccurrence",
            index=models.Index(
                fields=["status", "created_at"], name="issue_track_status_1e7736_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalyoccurrence",
            index=models.Index(
                fields=["correlation_id"], name="issue_track_correla_613266_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalyoccurrence",
            index=models.Index(
                fields=["client_app_version", "created_at"],
                name="issue_track_client__71bf48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalyoccurrence",
            index=models.Index(
                fields=["client_os_version", "created_at"],
                name="issue_track_client__dc07f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalyoccurrence",
            index=models.Index(
                fields=["signature", "client_app_version"],
                name="issue_track_signatu_4d2d7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fixsuggestion",
            index=models.Index(
                fields=["signature", "status"], name="issue_track_signatu_465ba4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixsuggestion",
            index=models.Index(
                fields=["fix_type", "confidence"], name="issue_track_fix_typ_7126bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixsuggestion",
            index=models.Index(
                fields=["auto_applicable", "risk_level"],
                name="issue_track_auto_ap_cba891_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fixaction",
            index=models.Index(
                fields=["occurrence", "action_type"],
                name="issue_track_occurre_c85bbc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fixaction",
            index=models.Index(
                fields=["suggestion", "result"], name="issue_track_suggest_e3adc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixaction",
            index=models.Index(
                fields=["applied_at"], name="issue_track_applied_9f667f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurrencetracker",
            index=models.Index(
                fields=["requires_attention"], name="issue_track_require_78ff7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurrencetracker",
            index=models.Index(
                fields=["alert_threshold_exceeded"],
                name="issue_track_alert_t_04d0d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recurrencetracker",
            index=models.Index(
                fields=["updated_at"], name="issue_track_updated_a5fcc6_idx"
            ),
        ),
    ]
