# Generated by Django 5.2.7 on 2025-11-26 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('issue_tracker', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixsuggestion',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                help_text='Tenant that owns this record',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='tenants.tenant',
            ),
        ),
        migrations.AddIndex(
            model_name='fixsuggestion',
            index=models.Index(
                fields=['tenant', 'signature'],
                name='issue_track_tenant__d5382a_idx',
            ),
        ),
    ]
