# Generated by Django 5.2.1 on 2025-09-04 06:23

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the request')),
                ('method', models.CharField(help_text='HTTP method used', max_length=10)),
                ('path', models.CharField(help_text='Request path', max_length=500)),
                ('query_params', models.TextField(blank=True, help_text='Query parameters')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('response_status', models.IntegerField(help_text='HTTP response status code', null=True)),
                ('response_time', models.IntegerField(help_text='Response time in milliseconds')),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the request was made')),
            ],
            options={
                'db_table': 'api_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=100)),
                ('key_hash', models.CharField(help_text='SHA-256 hash of the API key', max_length=64, unique=True)),
                ('secret', models.CharField(help_text='Secret for request signing (HMAC)', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is active')),
                ('require_signing', models.BooleanField(default=False, help_text='Whether requests must be signed with HMAC')),
                ('allowed_ips', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), blank=True, help_text='List of allowed IP addresses (null = all allowed)', null=True, size=None)),
                ('permissions', models.JSONField(default=dict, help_text='Permissions granted to this API key')),
                ('rate_limit', models.CharField(default='1000/h', help_text="Rate limit for this API key (e.g., '1000/h')", max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this API key expires (null = never)', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this API key was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this API key was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this API key was last updated')),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CSPViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_uri', models.URLField(help_text='URI of the document where violation occurred', max_length=2000)),
                ('referrer', models.URLField(blank=True, help_text='Referrer of the document', max_length=2000)),
                ('violated_directive', models.CharField(help_text='The directive that was violated', max_length=500)),
                ('effective_directive', models.CharField(help_text='The effective directive after fallback', max_length=500)),
                ('original_policy', models.TextField(help_text='The original CSP policy')),
                ('blocked_uri', models.CharField(help_text='URI that was blocked', max_length=2000)),
                ('source_file', models.URLField(blank=True, help_text='Source file where violation occurred', max_length=2000)),
                ('line_number', models.IntegerField(default=0, help_text='Line number in source file')),
                ('column_number', models.IntegerField(default=0, help_text='Column number in source file')),
                ('status_code', models.IntegerField(default=0, help_text='HTTP status code of the document')),
                ('script_sample', models.TextField(blank=True, help_text='Sample of the violating script')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the client')),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the client')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the violation was reported')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical - Potential Attack'), ('HIGH', 'High - Risky Behavior'), ('MEDIUM', 'Medium - Policy Violation'), ('LOW', 'Low - Minor Issue')], default='MEDIUM', help_text='Severity of the violation', max_length=20)),
                ('reviewed', models.BooleanField(default=False, help_text='Whether this violation has been reviewed')),
                ('false_positive', models.BooleanField(default=False, help_text='Whether this is a false positive')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this violation')),
            ],
            options={
                'db_table': 'security_csp_violations',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the request')),
                ('username', models.CharField(blank=True, help_text='Username attempted (if available)', max_length=150, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('attempt_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the attempt was made')),
                ('attempt_type', models.CharField(choices=[('login', 'Login Attempt'), ('password_reset', 'Password Reset'), ('api_access', 'API Access'), ('form_submission', 'Form Submission')], default='login', help_text='Type of attempt being rate limited', max_length=50)),
                ('success', models.BooleanField(default=False, help_text='Whether the attempt was successful')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure (invalid password, blocked, etc.)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
            ],
            options={
                'db_table': 'auth_rate_limit_attempts',
                'ordering': ['-attempt_time'],
            },
        ),
    ]
