# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("client_onboarding", "0003_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        ("peoples", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adminmentorsession",
            name="admin_user",
            field=models.ForeignKey(
                help_text="Administrator being mentored",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentor_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adminmentorsession",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="adminmentortip",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="agentrecommendation",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant client for multi-tenant isolation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_recommendations_client",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="agentrecommendation",
            name="site",
            field=models.ForeignKey(
                help_text="Site/business unit for this recommendation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_recommendations",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alertthreshold",
            unique_together={("metric_type", "alert_level")},
        ),
        migrations.AddField(
            model_name="apideprecation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="apideprecation",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="apideprecation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="apideprecationusage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="apideprecationusage",
            name="deprecation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_logs",
                to="core.apideprecation",
            ),
        ),
        migrations.AddField(
            model_name="apideprecationusage",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User associated with this API key",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiaccesslog",
            name="api_key",
            field=models.ForeignKey(
                help_text="API key used for this request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_logs",
                to="core.apikey",
            ),
        ),
        migrations.AddField(
            model_name="approvalaction",
            name="approver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approver",
            ),
        ),
        migrations.AddField(
            model_name="approvalaction",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="approvalaction",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="approved_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="People who approved this request",
                related_name="approval_requests_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved By",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="approver_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Which group can approve this",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_requests",
                to="peoples.pgroup",
                verbose_name="Approver Group",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="denied_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Person who denied this request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_requests_denied",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Denied By",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="requester",
            field=models.ForeignKey(
                help_text="Who is asking for approval",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Requested By",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="approvalaction",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="core.approvalrequest",
                verbose_name="Approval Request",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bulkoperationaudit",
            name="audit_log",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulk_operation",
                to="core.auditlog",
            ),
        ),
        migrations.AddField(
            model_name="bulkoperationaudit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="bulkoperationaudit",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddIndex(
            model_name="cacheanomalylog",
            index=models.Index(
                fields=["pattern_name", "-detected_at"], name="idx_anomaly_pattern_time"
            ),
        ),
        migrations.AddIndex(
            model_name="cacheanomalylog",
            index=models.Index(
                fields=["resolved", "-detected_at"], name="idx_anomaly_resolved"
            ),
        ),
        migrations.AddIndex(
            model_name="cacheanomalylog",
            index=models.Index(
                fields=["severity", "-detected_at"], name="idx_anomaly_severity"
            ),
        ),
        migrations.AddIndex(
            model_name="cachemetrics",
            index=models.Index(
                fields=["pattern_name", "-timestamp"], name="idx_cache_pattern_time"
            ),
        ),
        migrations.AddIndex(
            model_name="cachemetrics",
            index=models.Index(
                fields=["interval", "-timestamp"], name="idx_cache_interval_time"
            ),
        ),
        migrations.AddIndex(
            model_name="cachemetrics",
            index=models.Index(fields=["-hit_ratio"], name="idx_cache_hit_ratio"),
        ),
        migrations.AddConstraint(
            model_name="cachemetrics",
            constraint=models.CheckConstraint(
                condition=models.Q(("hit_ratio__gte", 0), ("hit_ratio__lte", 1)),
                name="cache_hit_ratio_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="cachemetrics",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_hits__gte", 0), ("total_misses__gte", 0)),
                name="cache_counts_positive",
            ),
        ),
        migrations.AddField(
            model_name="camerafingerprint",
            name="associated_users",
            field=models.ManyToManyField(
                help_text="Users who have used this camera",
                related_name="camera_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="camerafingerprint",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="conflictresolutionlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflict_logs",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="conflictresolutionlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conflict_resolutions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentrecommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cronjobdefinition",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="cronjobexecution",
            name="job_definition",
            field=models.ForeignKey(
                help_text="Associated cron job definition",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="core.cronjobdefinition",
            ),
        ),
        migrations.AddField(
            model_name="cronjobexecution",
            name="parent_execution",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent execution if this is a retry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retries",
                to="core.cronjobexecution",
            ),
        ),
        migrations.AddField(
            model_name="cronjobexecution",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="cspviolation",
            index=models.Index(
                fields=["reported_at"], name="security_cs_reporte_10af06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cspviolation",
            index=models.Index(
                fields=["severity", "reviewed"], name="security_cs_severit_87790d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cspviolation",
            index=models.Index(
                fields=["ip_address"], name="security_cs_ip_addr_c87208_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cspviolation",
            index=models.Index(
                fields=["blocked_uri"], name="security_cs_blocked_dcf442_idx"
            ),
        ),
        migrations.AddField(
            model_name="dashboardsavedview",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="dashboardsavedview",
            name="email_recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Who receives scheduled emails",
                related_name="subscribed_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Email Recipients",
            ),
        ),
        migrations.AddField(
            model_name="dashboardsavedview",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="dashboardsavedview",
            name="shared_with_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups who can access this view",
                related_name="shared_dashboard_views",
                to="peoples.pgroup",
                verbose_name="Shared With Groups",
            ),
        ),
        migrations.AddField(
            model_name="dashboardsavedview",
            name="shared_with_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific users who can access this view",
                related_name="shared_views_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Shared With Users",
            ),
        ),
        migrations.AddField(
            model_name="dashboardsavedview",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="encryptedsecret",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this secret",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_secrets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="encryptedsecret",
            name="modified_by",
            field=models.ForeignKey(
                help_text="User who last modified this secret",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_secrets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="encryptionkeymetadata",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this key",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_encryption_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fileuploadauditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="healthchecklog",
            index=models.Index(
                fields=["check_name", "-checked_at"],
                name="core_health_check_n_c370e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthchecklog",
            index=models.Index(
                fields=["status", "-checked_at"], name="core_health_status_794a19_idx"
            ),
        ),
        migrations.AddField(
            model_name="imagemetadata",
            name="people",
            field=models.ForeignKey(
                blank=True,
                help_text="User who uploaded the image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="image_metadata",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="imagemetadata",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="imagequalityassessment",
            name="image_metadata",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_assessment",
                to="core.imagemetadata",
            ),
        ),
        migrations.AddField(
            model_name="imagequalityassessment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="llmquota",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this quota applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_quotas",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="llmusagelog",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant making the request",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_usage_logs",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="monitoringapikey",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this API key",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_monitoring_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="monitoringapiaccesslog",
            name="api_key",
            field=models.ForeignKey(
                help_text="The monitoring API key used",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs",
                to="core.monitoringapikey",
            ),
        ),
        migrations.AddField(
            model_name="navigationrecommendation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="permissiondenialaudit",
            name="audit_log",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_denial",
                to="core.auditlog",
            ),
        ),
        migrations.AddField(
            model_name="permissiondenialaudit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="permissiondenialaudit",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="photoauthenticitylog",
            name="image_metadata",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authenticity_logs",
                to="core.imagemetadata",
            ),
        ),
        migrations.AddField(
            model_name="photoauthenticitylog",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photo_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="photoauthenticitylog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="planregressionalert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who acknowledged this alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_plan_regressions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pushdeliverylog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_delivery_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="qualitymetric",
            index=models.Index(
                fields=["timestamp"], name="core_qualit_timesta_057214_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualitymetric",
            index=models.Index(
                fields=["-timestamp"], name="core_qualit_timesta_e5a523_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualitymetric",
            index=models.Index(
                fields=["is_weekly", "-timestamp"],
                name="core_qualit_is_week_92b313_idx",
            ),
        ),
        migrations.AddField(
            model_name="queryexecutionplan",
            name="captured_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who captured this plan (if manual)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planregressionalert",
            name="baseline_plan",
            field=models.ForeignKey(
                help_text="Previous (baseline) execution plan",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regression_alerts_baseline",
                to="core.queryexecutionplan",
            ),
        ),
        migrations.AddField(
            model_name="planregressionalert",
            name="current_plan",
            field=models.ForeignKey(
                help_text="Current (regressed) execution plan",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regression_alerts_current",
                to="core.queryexecutionplan",
            ),
        ),
        migrations.AddIndex(
            model_name="querypattern",
            index=models.Index(
                fields=["pattern_hash"], name="query_patte_pattern_ce2b77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querypattern",
            index=models.Index(
                fields=["query_type", "avg_execution_time"],
                name="query_patte_query_t_582e97_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="querypattern",
            index=models.Index(
                fields=["last_seen"], name="query_patte_last_se_282f35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queryperformancesnapshot",
            index=models.Index(
                fields=["query_hash", "snapshot_time"],
                name="query_perfo_query_h_b6b5b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="queryperformancesnapshot",
            index=models.Index(
                fields=["snapshot_time"], name="query_perfo_snapsho_f72b7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queryperformancesnapshot",
            index=models.Index(
                fields=["mean_exec_time"], name="query_perfo_mean_ex_00ed54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queryperformancesnapshot",
            index=models.Index(fields=["calls"], name="query_perfo_calls_ddd86f_idx"),
        ),
        migrations.AddIndex(
            model_name="queryperformancesnapshot",
            index=models.Index(
                fields=["total_exec_time"], name="query_perfo_total_e_1653d2_idx"
            ),
        ),
        migrations.AddField(
            model_name="quickaction",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="quickaction",
            name="user_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which user groups can execute this action?",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="quickactionchecklist",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="quickactionexecution",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="quickactionexecution",
            name="executed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quick_action_executions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quickactionexecution",
            name="quick_action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="core.quickaction",
            ),
        ),
        migrations.AddField(
            model_name="quickactionexecution",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="quickactionchecklist",
            name="execution",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist",
                to="core.quickactionexecution",
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimitblockedip",
            index=models.Index(
                fields=["ip_address", "is_active"],
                name="core_rate_l_ip_addr_5f4f80_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimitblockedip",
            index=models.Index(
                fields=["blocked_until"], name="core_rate_l_blocked_e35a5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimitblockedip",
            index=models.Index(
                fields=["endpoint_type"], name="core_rate_l_endpoin_1f44d7_idx"
            ),
        ),
        migrations.AddField(
            model_name="ratelimittrustedip",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who added this trusted IP",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trusted_ips_added",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ratelimitviolationlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User if authenticated",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rate_limit_violations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recommendationfeedback",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="recommendationfeedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recommendationimplementation",
            name="implemented_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recommendationimplementation",
            name="recommendation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="implementations",
                to="core.navigationrecommendation",
            ),
        ),
        migrations.AddField(
            model_name="refreshtokenblacklist",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="refreshtokenblacklist",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="refreshtokenblacklist",
            name="user",
            field=models.ForeignKey(
                help_text="User associated with this token",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blacklisted_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="runbook",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="runbook",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="runbook",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="runbookexecution",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="runbookexecution",
            name="executed_by",
            field=models.ForeignKey(
                help_text="Who ran this quick action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runbook_executions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Executed By",
            ),
        ),
        migrations.AddField(
            model_name="runbookexecution",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="runbookexecution",
            name="runbook",
            field=models.ForeignKey(
                help_text="Which quick action was executed",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to="core.runbook",
                verbose_name="Quick Action",
            ),
        ),
        migrations.AddField(
            model_name="sagaexecutionlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="sagastate",
            index=models.Index(
                fields=["status", "created_at"], name="saga_state_status_2bbefc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sagastate",
            index=models.Index(
                fields=["operation_type", "status"],
                name="saga_state_operati_8640ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sagastate",
            index=models.Index(
                fields=["created_at"], name="saga_state_created_37a35c_idx"
            ),
        ),
        migrations.AddField(
            model_name="sessionforensics",
            name="user",
            field=models.ForeignKey(
                help_text="User associated with this session",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_forensics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="slaprediction",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who acknowledged this alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_predictions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Acknowledged By",
            ),
        ),
        migrations.AddField(
            model_name="slaprediction",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="slaprediction",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="slaprediction",
            name="suggested_assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="AI-recommended person to assign this to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggested_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Suggested Assignee",
            ),
        ),
        migrations.AddField(
            model_name="slowqueryalert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who acknowledged this alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_query_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statetransitionaudit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who initiated transition (null for system)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="state_transitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncanalyticssnapshot",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant for multi-tenant filtering",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_snapshots",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="syncdevicehealth",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_health_records",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="syncdevicehealth",
            name="user",
            field=models.ForeignKey(
                help_text="User associated with device",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_health_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="syncidempotencyrecord",
            index=models.Index(
                fields=["user_id", "created_at"], name="sync_idemp_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncidempotencyrecord",
            index=models.Index(
                fields=["device_id", "created_at"], name="sync_idemp_device_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncidempotencyrecord",
            index=models.Index(fields=["expires_at"], name="sync_idemp_expires_idx"),
        ),
        migrations.AddField(
            model_name="taskfailurerecord",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenantconflictpolicy",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this policy",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantconflictpolicy",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this policy applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflict_policies",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="transactionfailurelog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="transactionmetrics",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="user",
            field=models.ForeignKey(
                help_text="User who initiated this upload",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userbehaviorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="behavior_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="devicesyncstate",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_states",
                to="core.userdevice",
            ),
        ),
        migrations.AddField(
            model_name="userscope",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="userscope",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="userscope",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Filter data by shift (null = all shifts)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_scopes",
                to="client_onboarding.shift",
                verbose_name="Selected Shift",
            ),
        ),
        migrations.AddField(
            model_name="userscope",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="userscope",
            name="user",
            field=models.OneToOneField(
                help_text="User this scope belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scope",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="usersimilarity",
            name="user1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="similarities_as_user1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersimilarity",
            name="user2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="similarities_as_user2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="adminhelptopic",
            index=models.Index(
                fields=["category", "difficulty_level"],
                name="core_adminh_categor_ad3963_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminhelptopic",
            index=models.Index(
                fields=["is_active", "-view_count"],
                name="core_adminh_is_acti_879e3a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adminhelptopic",
            unique_together={("tenant", "category", "feature_name")},
        ),
        migrations.AddIndex(
            model_name="adminmentorsession",
            index=models.Index(
                fields=["admin_user", "-session_start"],
                name="core_adminm_admin_u_b83ff5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminmentorsession",
            index=models.Index(
                fields=["skill_level"], name="core_adminm_skill_l_a7a30c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminmentortip",
            index=models.Index(
                fields=["trigger_context", "active"],
                name="core_adminm_trigger_cdc36e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminmentortip",
            index=models.Index(
                fields=["-priority"], name="core_adminm_priorit_677f5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrecommendation",
            index=models.Index(
                fields=["agent_id", "module"], name="core_agent__agent_i_28ba04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrecommendation",
            index=models.Index(
                fields=["site", "status"], name="core_agent__site_id_abdff1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrecommendation",
            index=models.Index(
                fields=["client", "module"], name="core_agent__client__0ec8b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrecommendation",
            index=models.Index(
                fields=["severity", "status"], name="core_agent__severit_140e29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrecommendation",
            index=models.Index(
                fields=["created_at", "expires_at"],
                name="core_agent__created_8a888b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apideprecation",
            index=models.Index(
                fields=["endpoint_pattern", "status"],
                name="api_depreca_endpoin_cda189_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apideprecation",
            index=models.Index(
                fields=["sunset_date"], name="api_depreca_sunset__7e236d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apideprecation",
            index=models.Index(
                fields=["api_type", "status"], name="api_depreca_api_typ_1c6bd3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apideprecation",
            unique_together={("endpoint_pattern", "version_deprecated")},
        ),
        migrations.AddIndex(
            model_name="apideprecationusage",
            index=models.Index(
                fields=["deprecation", "timestamp"],
                name="api_depreca_depreca_359dff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apideprecationusage",
            index=models.Index(
                fields=["client_version"], name="api_depreca_client__7509b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apideprecationusage",
            index=models.Index(
                fields=["-timestamp"], name="api_depreca_timesta_ae461e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["key_hash"], name="api_keys_key_has_8f2f29_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["is_active", "expires_at"], name="api_keys_is_acti_f90a04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiaccesslog",
            index=models.Index(
                fields=["api_key", "timestamp"], name="api_access__api_key_c54d9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiaccesslog",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="api_access__ip_addr_7f2223_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apiaccesslog",
            index=models.Index(
                fields=["response_status"], name="api_access__respons_ecf086_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(fields=["status"], name="approval_status_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["requester", "status"], name="approval_req_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(fields=["expires_at"], name="approval_expiry_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalaction",
            index=models.Index(
                fields=["request", "decision"], name="approval_act_req_dec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "event_type", "-timestamp"],
                name="audit_log_tenant__2ae51e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "user", "-timestamp"],
                name="audit_log_tenant__7b5a6a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["correlation_id"], name="audit_log_correla_e04bb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="audit_log_content_10f046_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["level", "-timestamp"], name="audit_log_level_4d239f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["retention_until", "is_archived"],
                name="audit_log_retenti_3b5b0a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="camerafingerprint",
            index=models.Index(
                fields=["trust_level", "last_seen"], name="idx_camera_trust_activity"
            ),
        ),
        migrations.AddIndex(
            model_name="camerafingerprint",
            index=models.Index(
                fields=["fraud_incidents"], name="idx_camera_fraud_count"
            ),
        ),
        migrations.AddIndex(
            model_name="conflictresolutionlog",
            index=models.Index(
                fields=["mobile_id"], name="sync_confli_mobile__156bbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conflictresolutionlog",
            index=models.Index(
                fields=["domain", "created_at"], name="sync_confli_domain_0cd5d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conflictresolutionlog",
            index=models.Index(
                fields=["tenant", "created_at"], name="sync_confli_tenant__ec4084_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conflictresolutionlog",
            index=models.Index(
                fields=["resolution_result"], name="sync_confli_resolut_3a9d43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentrecommendation",
            index=models.Index(fields=["user"], name="core_conten_user_id_337c41_idx"),
        ),
        migrations.AddIndex(
            model_name="contentrecommendation",
            index=models.Index(
                fields=["content_type"], name="core_conten_content_cd196f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentrecommendation",
            index=models.Index(
                fields=["relevance_score"], name="core_conten_relevan_a44b1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentrecommendation",
            index=models.Index(
                fields=["is_active"], name="core_conten_is_acti_390877_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentrecommendation",
            index=models.Index(
                fields=["created_at"], name="core_conten_created_053c32_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentrecommendation",
            unique_together={("user", "content_url")},
        ),
        migrations.AddIndex(
            model_name="cronjobdefinition",
            index=models.Index(
                fields=["tenant", "status", "is_enabled"],
                name="core_cron_j_tenant__47d1b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cronjobdefinition",
            index=models.Index(
                fields=["next_execution_time"], name="core_cron_j_next_ex_c8da59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cronjobdefinition",
            index=models.Index(
                fields=["job_type"], name="core_cron_j_job_typ_db673a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cronjobdefinition",
            index=models.Index(
                fields=["priority"], name="core_cron_j_priorit_958411_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cronjobdefinition",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="cronjobexecution",
            index=models.Index(
                fields=["tenant", "job_definition", "status"],
                name="core_cron_j_tenant__cab459_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cronjobexecution",
            index=models.Index(
                fields=["scheduled_time"], name="core_cron_j_schedul_e66945_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cronjobexecution",
            index=models.Index(
                fields=["started_at"], name="core_cron_j_started_3124fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cronjobexecution",
            index=models.Index(
                fields=["status", "execution_context"],
                name="core_cron_j_status_a28645_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cronjobexecution",
            index=models.Index(
                fields=["job_definition", "created_at"],
                name="core_cron_j_job_def_d08d22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardsavedview",
            index=models.Index(
                fields=["cuser", "view_type"], name="saved_view_user_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardsavedview",
            index=models.Index(fields=["sharing_level"], name="saved_view_sharing_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboardsavedview",
            index=models.Index(fields=["is_default"], name="saved_view_default_idx"),
        ),
        migrations.AddConstraint(
            model_name="dashboardsavedview",
            constraint=models.UniqueConstraint(
                fields=("cuser", "name"),
                name="unique_view_name_per_user",
                violation_error_message="You already have a saved view with this name",
            ),
        ),
        migrations.AddIndex(
            model_name="encryptedsecret",
            index=models.Index(
                fields=["key_name"], name="core_encryp_key_nam_e9dbe1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encryptedsecret",
            index=models.Index(
                fields=["provider", "is_active"], name="core_encryp_provide_c6bdb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encryptedsecret",
            index=models.Index(
                fields=["secret_type"], name="core_encryp_secret__5a8d77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encryptedsecret",
            index=models.Index(
                fields=["environment"], name="core_encryp_environ_71d33c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encryptedsecret",
            index=models.Index(
                fields=["created_at"], name="core_encryp_created_f7da80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encryptionkeymetadata",
            index=models.Index(fields=["key_id"], name="encryption__key_id_7c0f68_idx"),
        ),
        migrations.AddIndex(
            model_name="encryptionkeymetadata",
            index=models.Index(
                fields=["is_active", "expires_at"],
                name="encryption__is_acti_37e3ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encryptionkeymetadata",
            index=models.Index(
                fields=["rotation_status"], name="encryption__rotatio_5dfa3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encryptionkeymetadata",
            index=models.Index(
                fields=["created_at"], name="encryption__created_8cdc27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileuploadauditlog",
            index=models.Index(
                fields=["-timestamp", "event_type"],
                name="file_upload_timesta_e771fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileuploadauditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="file_upload_user_id_d58c0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileuploadauditlog",
            index=models.Index(
                fields=["severity", "-timestamp"], name="file_upload_severit_188074_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileuploadauditlog",
            index=models.Index(
                fields=["correlation_id"], name="file_upload_correla_39c69e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagemetadata",
            index=models.Index(
                fields=["people", "upload_context"], name="idx_metadata_people_context"
            ),
        ),
        migrations.AddIndex(
            model_name="imagemetadata",
            index=models.Index(
                fields=["validation_status", "manipulation_risk"],
                name="idx_metadata_security",
            ),
        ),
        migrations.AddIndex(
            model_name="imagemetadata",
            index=models.Index(
                fields=["analysis_timestamp"], name="idx_metadata_timestamp"
            ),
        ),
        migrations.AddIndex(
            model_name="imagemetadata",
            index=models.Index(
                fields=["authenticity_score"], name="idx_metadata_authenticity"
            ),
        ),
        migrations.AddIndex(
            model_name="imagemetadata",
            index=models.Index(
                fields=["camera_make", "camera_model"], name="idx_metadata_camera"
            ),
        ),
        migrations.AddIndex(
            model_name="imagemetadata",
            index=models.Index(
                fields=["people", "authenticity_score", "analysis_timestamp"],
                name="idx_metadata_fraud_analysis",
            ),
        ),
        migrations.AddIndex(
            model_name="imagemetadata",
            index=models.Index(
                fields=["upload_context", "validation_status", "manipulation_risk"],
                name="idx_metadata_context_security",
            ),
        ),
        migrations.AddIndex(
            model_name="imagequalityassessment",
            index=models.Index(fields=["quality_level"], name="idx_quality_level"),
        ),
        migrations.AddIndex(
            model_name="imagequalityassessment",
            index=models.Index(
                fields=["overall_quality_score"], name="idx_quality_score"
            ),
        ),
        migrations.AddIndex(
            model_name="llmquota",
            index=models.Index(
                fields=["tenant", "provider"], name="llm_quota_tenant__f10ef3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmquota",
            index=models.Index(fields=["enabled"], name="llm_quota_enabled_a22ebc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="llmquota",
            unique_together={("tenant", "provider")},
        ),
        migrations.AddIndex(
            model_name="llmusagelog",
            index=models.Index(
                fields=["tenant", "created_at"], name="llm_usage_l_tenant__38f415_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmusagelog",
            index=models.Index(
                fields=["provider", "created_at"], name="llm_usage_l_provide_7241fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmusagelog",
            index=models.Index(
                fields=["tenant", "provider", "created_at"],
                name="llm_usage_l_tenant__894ea5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringapikey",
            index=models.Index(
                fields=["key_hash"], name="monitoring__key_has_fd2855_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringapikey",
            index=models.Index(
                fields=["is_active", "expires_at"],
                name="monitoring__is_acti_80a987_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringapikey",
            index=models.Index(
                fields=["next_rotation_at"], name="monitoring__next_ro_773970_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringapikey",
            index=models.Index(
                fields=["monitoring_system"], name="monitoring__monitor_e9e5d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringapiaccesslog",
            index=models.Index(
                fields=["timestamp"], name="monitoring__timesta_9db216_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringapiaccesslog",
            index=models.Index(
                fields=["api_key", "timestamp"], name="monitoring__api_key_a40d02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringapiaccesslog",
            index=models.Index(
                fields=["endpoint", "timestamp"], name="monitoring__endpoin_738484_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringapiaccesslog",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="monitoring__ip_addr_2c33dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringapiaccesslog",
            index=models.Index(
                fields=["response_status"], name="monitoring__respons_d3ba3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="navigationrecommendation",
            index=models.Index(
                fields=["recommendation_type"], name="core_naviga_recomme_6056fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="navigationrecommendation",
            index=models.Index(
                fields=["target_page"], name="core_naviga_target__bf4a48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="navigationrecommendation",
            index=models.Index(
                fields=["priority"], name="core_naviga_priorit_1d24d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="navigationrecommendation",
            index=models.Index(fields=["status"], name="core_naviga_status_2195f0_idx"),
        ),
        migrations.AddIndex(
            model_name="navigationrecommendation",
            index=models.Index(
                fields=["created_at"], name="core_naviga_created_ee0426_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="navigationrecommendation",
            index=models.Index(
                fields=["confidence_score"], name="core_naviga_confide_4c7990_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissiondenialaudit",
            index=models.Index(
                fields=["is_suspicious", "-created_at"],
                name="permission__is_susp_6735a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissiondenialaudit",
            index=models.Index(
                fields=["risk_score"], name="permission__risk_sc_f36f79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photoauthenticitylog",
            index=models.Index(
                fields=["validation_result", "review_timestamp"],
                name="idx_auth_result_time",
            ),
        ),
        migrations.AddIndex(
            model_name="photoauthenticitylog",
            index=models.Index(
                fields=["reviewed_by", "validation_action"],
                name="idx_auth_reviewer_action",
            ),
        ),
        migrations.AddIndex(
            model_name="photoauthenticitylog",
            index=models.Index(fields=["follow_up_required"], name="idx_auth_followup"),
        ),
        migrations.AddIndex(
            model_name="pushdeliverylog",
            index=models.Index(
                fields=["user", "created_at"], name="push_delive_user_id_64bdac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushdeliverylog",
            index=models.Index(
                fields=["device_id", "created_at"],
                name="push_delive_device__ad6b47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pushdeliverylog",
            index=models.Index(
                fields=["delivered"], name="push_delive_deliver_04fd68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushsubscription",
            index=models.Index(
                fields=["user", "device_id"], name="push_subscr_user_id_0945e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushsubscription",
            index=models.Index(fields=["active"], name="push_subscr_active_27ad25_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="pushsubscription",
            unique_together={("user", "device_id", "domain")},
        ),
        migrations.AddIndex(
            model_name="queryexecutionplan",
            index=models.Index(
                fields=["query_hash", "captured_at"],
                name="query_execu_query_h_18f3c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="queryexecutionplan",
            index=models.Index(
                fields=["plan_hash"], name="query_execu_plan_ha_40640e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queryexecutionplan",
            index=models.Index(
                fields=["execution_time"], name="query_execu_executi_2af265_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queryexecutionplan",
            index=models.Index(
                fields=["regression_detected", "captured_at"],
                name="query_execu_regress_ca1ca3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planregressionalert",
            index=models.Index(
                fields=["query_hash", "detected_at"],
                name="plan_regres_query_h_60e108_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planregressionalert",
            index=models.Index(
                fields=["status", "severity"], name="plan_regres_status_9a69b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planregressionalert",
            index=models.Index(
                fields=["regression_type", "status"],
                name="plan_regres_regress_abc73c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quickaction",
            index=models.Index(
                fields=["is_active", "-times_used"],
                name="core_quicka_is_acti_32b899_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quickactionexecution",
            index=models.Index(
                fields=["status", "-created_at"], name="core_quicka_status_43480e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quickactionexecution",
            index=models.Index(
                fields=["executed_by", "-created_at"],
                name="core_quicka_execute_2d083e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimittrustedip",
            index=models.Index(
                fields=["ip_address", "is_active"],
                name="core_rate_l_ip_addr_298204_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimittrustedip",
            index=models.Index(
                fields=["expires_at"], name="core_rate_l_expires_3eff0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimitviolationlog",
            index=models.Index(
                fields=["timestamp", "endpoint_type"],
                name="core_rate_l_timesta_cfa17a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimitviolationlog",
            index=models.Index(
                fields=["client_ip", "timestamp"], name="core_rate_l_client__5e7dec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimitviolationlog",
            index=models.Index(
                fields=["user", "timestamp"], name="core_rate_l_user_id_d0cd0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationfeedback",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="core_recomm_content_41369e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationfeedback",
            index=models.Index(fields=["user"], name="core_recomm_user_id_c0ba4c_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendationfeedback",
            index=models.Index(
                fields=["feedback_type"], name="core_recomm_feedbac_bb381a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationfeedback",
            index=models.Index(
                fields=["created_at"], name="core_recomm_created_a0ad00_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recommendationfeedback",
            unique_together={("content_type", "object_id", "user")},
        ),
        migrations.AddIndex(
            model_name="recommendationimplementation",
            index=models.Index(
                fields=["recommendation"], name="core_recomm_recomme_3ad2e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationimplementation",
            index=models.Index(
                fields=["implemented_by"], name="core_recomm_impleme_46a843_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationimplementation",
            index=models.Index(
                fields=["implementation_date"], name="core_recomm_impleme_08ea89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationimplementation",
            index=models.Index(
                fields=["is_successful"], name="core_recomm_is_succ_82320a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtokenblacklist",
            index=models.Index(fields=["token_jti"], name="idx_token_jti"),
        ),
        migrations.AddIndex(
            model_name="refreshtokenblacklist",
            index=models.Index(
                fields=["blacklisted_at", "reason"], name="idx_blacklist_cleanup"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtokenblacklist",
            index=models.Index(
                fields=["user", "-blacklisted_at"], name="idx_user_blacklist"
            ),
        ),
        migrations.AddIndex(
            model_name="runbook",
            index=models.Index(fields=["is_active"], name="runbook_active_idx"),
        ),
        migrations.AddIndex(
            model_name="runbook",
            index=models.Index(fields=["-usage_count"], name="runbook_popular_idx"),
        ),
        migrations.AddIndex(
            model_name="runbookexecution",
            index=models.Index(
                fields=["target_model", "target_id"], name="runbook_exec_target_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runbookexecution",
            index=models.Index(fields=["executed_by"], name="runbook_exec_user_idx"),
        ),
        migrations.AddIndex(
            model_name="sagaexecutionlog",
            index=models.Index(
                fields=["status", "started_at"], name="saga_execut_status_e607fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sagaexecutionlog",
            index=models.Index(
                fields=["saga_name", "status"], name="saga_execut_saga_na_392074_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionforensics",
            index=models.Index(
                fields=["user", "timestamp"], name="session_for_user_id_56b22b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionforensics",
            index=models.Index(
                fields=["session_key", "event_type"],
                name="session_for_session_1b74e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionforensics",
            index=models.Index(
                fields=["event_type", "timestamp"],
                name="session_for_event_t_e45a09_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionforensics",
            index=models.Index(
                fields=["is_suspicious", "severity"],
                name="session_for_is_susp_13da46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionforensics",
            index=models.Index(
                fields=["correlation_id"], name="session_for_correla_3c3aad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slaprediction",
            index=models.Index(
                fields=["item_type", "item_id"], name="sla_pred_item_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slaprediction",
            index=models.Index(
                fields=["risk_level", "-calculated_at"], name="sla_pred_risk_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slaprediction",
            index=models.Index(fields=["is_acknowledged"], name="sla_pred_ack_idx"),
        ),
        migrations.AddConstraint(
            model_name="slaprediction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_acknowledged", False)),
                fields=("item_type", "item_id"),
                name="unique_active_prediction_per_item",
                violation_error_message="Active prediction already exists for this item",
            ),
        ),
        migrations.AddIndex(
            model_name="slowqueryalert",
            index=models.Index(
                fields=["status", "severity"], name="slow_query__status_100322_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slowqueryalert",
            index=models.Index(
                fields=["alert_time", "severity"], name="slow_query__alert_t_ee41e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slowqueryalert",
            index=models.Index(
                fields=["query_hash", "alert_time"],
                name="slow_query__query_h_c4f6c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="slowqueryalert",
            index=models.Index(
                fields=["alert_type", "status"], name="slow_query__alert_t_0c570b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statetransitionaudit",
            index=models.Index(
                fields=["entity_type", "entity_id", "-timestamp"],
                name="audit_entity_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="statetransitionaudit",
            index=models.Index(
                fields=["to_state", "-timestamp"], name="audit_state_lookup"
            ),
        ),
        migrations.AddIndex(
            model_name="statetransitionaudit",
            index=models.Index(fields=["user", "-timestamp"], name="audit_user_lookup"),
        ),
        migrations.AddIndex(
            model_name="statetransitionaudit",
            index=models.Index(
                fields=["success", "-timestamp"], name="audit_failure_lookup"
            ),
        ),
        migrations.AddIndex(
            model_name="syncanalyticssnapshot",
            index=models.Index(
                fields=["timestamp"], name="sync_analyt_timesta_e5477a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncanalyticssnapshot",
            index=models.Index(
                fields=["tenant", "timestamp"], name="sync_analyt_tenant__ecb2cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncdevicehealth",
            index=models.Index(
                fields=["device_id"], name="sync_device_device__bd8f85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncdevicehealth",
            index=models.Index(
                fields=["user", "tenant"], name="sync_device_user_id_adcb38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncdevicehealth",
            index=models.Index(
                fields=["health_score"], name="sync_device_health__0602c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncdevicehealth",
            index=models.Index(
                fields=["last_sync_at"], name="sync_device_last_sy_f6f5f4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="syncdevicehealth",
            unique_together={("device_id", "user")},
        ),
        migrations.AddIndex(
            model_name="taskfailurerecord",
            index=models.Index(
                fields=["status", "next_retry_at"], name="task_fail_dlq_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskfailurerecord",
            index=models.Index(
                fields=["task_name", "status"], name="task_fail_analysis_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskfailurerecord",
            index=models.Index(
                fields=["failure_type", "status"], name="task_fail_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantconflictpolicy",
            index=models.Index(
                fields=["tenant", "domain"], name="sync_tenant_tenant__245319_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantconflictpolicy",
            index=models.Index(
                fields=["auto_resolve"], name="sync_tenant_auto_re_b57e1c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenantconflictpolicy",
            unique_together={("tenant", "domain")},
        ),
        migrations.AddIndex(
            model_name="transactionfailurelog",
            index=models.Index(
                fields=["operation_name", "occurred_at"],
                name="transaction_operati_c6717b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionfailurelog",
            index=models.Index(
                fields=["error_type", "is_resolved"],
                name="transaction_error_t_aa21dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionfailurelog",
            index=models.Index(
                fields=["user_id", "occurred_at"], name="transaction_user_id_3041cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionmetrics",
            index=models.Index(
                fields=["operation_name", "metric_date"],
                name="transaction_operati_cd82e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionmetrics",
            index=models.Index(
                fields=["metric_date", "hour_of_day"],
                name="transaction_metric__72edd0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactionmetrics",
            unique_together={
                ("operation_name", "metric_date", "hour_of_day", "tenant")
            },
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(
                fields=["user", "status"], name="upload_sess_user_id_73c91f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(
                fields=["status", "expires_at"], name="upload_sess_status_bb43bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(
                fields=["created_at"], name="upload_sess_created_3de5bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbehaviorprofile",
            index=models.Index(fields=["user"], name="core_user_b_user_id_174ad3_idx"),
        ),
        migrations.AddIndex(
            model_name="userbehaviorprofile",
            index=models.Index(
                fields=["preferred_device_type"], name="core_user_b_preferr_ef3f33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbehaviorprofile",
            index=models.Index(
                fields=["last_updated"], name="core_user_b_last_up_e519f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdevice",
            index=models.Index(
                fields=["user", "is_active"], name="user_device_user_id_1b0ebe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdevice",
            index=models.Index(
                fields=["device_type"], name="user_device_device__2744f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicesyncstate",
            index=models.Index(
                fields=["device", "domain"], name="device_sync_device__ae58f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicesyncstate",
            index=models.Index(
                fields=["domain", "entity_id"], name="device_sync_domain_65340e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicesyncstate",
            index=models.Index(
                fields=["is_dirty"], name="device_sync_is_dirt_dd6b77_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="devicesyncstate",
            unique_together={("device", "domain", "entity_id")},
        ),
        migrations.AddIndex(
            model_name="userscope",
            index=models.Index(fields=["user"], name="user_scope_user_idx"),
        ),
        migrations.AddIndex(
            model_name="userscope",
            index=models.Index(fields=["tenant"], name="user_scope_tenant_idx"),
        ),
        migrations.AddIndex(
            model_name="usersimilarity",
            index=models.Index(
                fields=["user1", "similarity_score"],
                name="core_user_s_user1_i_1c4359_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersimilarity",
            index=models.Index(
                fields=["user2", "similarity_score"],
                name="core_user_s_user2_i_3bf7cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersimilarity",
            index=models.Index(
                fields=["calculated_at"], name="core_user_s_calcula_f50377_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usersimilarity",
            unique_together={("user1", "user2")},
        ),
    ]
