# Generated by Django 5.2.1 on 2025-09-04 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User associated with this API key', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apiaccesslog',
            name='api_key',
            field=models.ForeignKey(help_text='API key used for this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='core.apikey'),
        ),
        migrations.AddIndex(
            model_name='cspviolation',
            index=models.Index(fields=['reported_at'], name='security_cs_reporte_10af06_idx'),
        ),
        migrations.AddIndex(
            model_name='cspviolation',
            index=models.Index(fields=['severity', 'reviewed'], name='security_cs_severit_87790d_idx'),
        ),
        migrations.AddIndex(
            model_name='cspviolation',
            index=models.Index(fields=['ip_address'], name='security_cs_ip_addr_c87208_idx'),
        ),
        migrations.AddIndex(
            model_name='cspviolation',
            index=models.Index(fields=['blocked_uri'], name='security_cs_blocked_dcf442_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitattempt',
            index=models.Index(fields=['ip_address', 'attempt_time'], name='auth_rate_l_ip_addr_b7fc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitattempt',
            index=models.Index(fields=['username', 'attempt_time'], name='auth_rate_l_usernam_88c490_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitattempt',
            index=models.Index(fields=['success', 'attempt_time'], name='auth_rate_l_success_cb275b_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_hash'], name='api_keys_key_has_8f2f29_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['is_active', 'expires_at'], name='api_keys_is_acti_f90a04_idx'),
        ),
        migrations.AddIndex(
            model_name='apiaccesslog',
            index=models.Index(fields=['api_key', 'timestamp'], name='api_access__api_key_c54d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='apiaccesslog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='api_access__ip_addr_7f2223_idx'),
        ),
        migrations.AddIndex(
            model_name='apiaccesslog',
            index=models.Index(fields=['response_status'], name='api_access__respons_ecf086_idx'),
        ),
    ]
