# Generated by Django 5.2.1 on 2025-09-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateLimitAttempt',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='rate_limit',
        ),
    ]
