# Generated by Django 5.2.7 on 2025-11-11 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('client_event_id', models.CharField(blank=True, help_text='Id supplied by the client for deduplication', max_length=100, null=True)),
                ('event_type', models.CharField(help_text='Behavioral event type label', max_length=64)),
                ('timestamp', models.DateTimeField(help_text='Client-side event timestamp')),
                ('session_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('interaction_count', models.IntegerField(default=0)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('schema_hash', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_sync_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_behavioral_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'timestamp'], name='sync_behavi_tenant__e6dc22_idx'), models.Index(fields=['device_id', 'timestamp'], name='sync_behavi_device__c7b55b_idx'), models.Index(fields=['client_event_id'], name='sync_behavi_client__2a5df2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'client_event_id'), name='behavioral_sync_user_client_event_uk')],
            },
        ),
        migrations.CreateModel(
            name='DeviceMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('aggregation_type', models.CharField(blank=True, max_length=32)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('schema_hash', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_metric_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_device_metric_snapshot',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['tenant', 'recorded_at'], name='sync_device_tenant__8f542f_idx'), models.Index(fields=['device_id', 'recorded_at'], name='sync_device_device__5c9dd7_idx'), models.Index(fields=['metric_name'], name='sync_device_metric__fb92ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('session_start', models.DateTimeField(blank=True, null=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('event_count', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('schema_hash', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_sync_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_session_event',
                'ordering': ['-session_start', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'session_start'], name='sync_sessio_tenant__48d7e6_idx'), models.Index(fields=['device_id', 'session_start'], name='sync_sessio_device__6dfaf7_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'session_id'), name='session_sync_user_session_id_uk')],
            },
        ),
    ]
