# Generated by Django 5.2.7 on 2025-11-11 13:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_behavioralsyncevent_devicemetricsnapshot_and_more"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Entity type (e.g., 'Task', 'WorkOrder', 'Asset')",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(
                        db_index=True, help_text="ID of the synced entity"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        db_index=True,
                        help_text="Type of operation",
                        max_length=20,
                    ),
                ),
                (
                    "field_changes",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Changed fields with old/new values.\n        Format: {"field_name": {"old": value, "new": value}}\n        Example: {"title": {"old": "Old Title", "new": "New Title"}}\n        ',
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the sync operation occurred",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="Device identifier (for mobile clients)",
                        max_length=100,
                    ),
                ),
                (
                    "sync_session_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Session ID grouping related sync operations",
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True,
                        help_text="Client app version (e.g., '2.1.0')",
                        max_length=50,
                    ),
                ),
                (
                    "network_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wifi", "WiFi"),
                            ("cellular", "Cellular"),
                            ("unknown", "Unknown"),
                        ],
                        help_text="Network type during sync",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the sync operation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_sync_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ConflictResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("concurrent_edit", "Concurrent Edit"),
                            ("stale_update", "Stale Update"),
                            ("field_collision", "Field Collision"),
                            ("delete_conflict", "Delete Conflict"),
                        ],
                        db_index=True,
                        help_text="Type of conflict detected",
                        max_length=50,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When conflict was detected",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When conflict was resolved (null if unresolved)",
                        null=True,
                    ),
                ),
                (
                    "resolution_strategy",
                    models.CharField(
                        choices=[
                            ("last_write_wins", "Last Write Wins"),
                            ("manual_merge", "Manual Merge"),
                            ("auto_merge", "Auto Merge"),
                            ("first_write_wins", "First Write Wins"),
                            ("unresolved", "Unresolved"),
                        ],
                        default="unresolved",
                        help_text="Strategy used to resolve conflict",
                        max_length=50,
                    ),
                ),
                (
                    "resolution_data",
                    models.JSONField(
                        default=dict,
                        help_text="\n        Resolution details including:\n        - merged_fields: Fields that were merged\n        - discarded_changes: Changes that were discarded\n        - manual_intervention: User who resolved manually\n        ",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Conflict severity based on data importance",
                        max_length=20,
                    ),
                ),
                (
                    "notified_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users notified about this conflict",
                        related_name="conflict_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "sync_logs",
                    models.ManyToManyField(
                        help_text="Sync operations involved in this conflict",
                        related_name="conflicts",
                        to="core.synclog",
                    ),
                ),
            ],
            options={
                "db_table": "core_conflict_resolution",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["entity_type", "entity_id", "timestamp"],
                name="synclog_entity_time",
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(fields=["user", "timestamp"], name="synclog_user_time"),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(fields=["sync_session_id"], name="synclog_session"),
        ),
        migrations.AddIndex(
            model_name="conflictresolution",
            index=models.Index(
                fields=["conflict_type", "detected_at"], name="conflict_type_time"
            ),
        ),
        migrations.AddIndex(
            model_name="conflictresolution",
            index=models.Index(
                fields=["resolution_strategy"], name="conflict_strategy"
            ),
        ),
    ]
