# Generated by Django 5.2.1 on 2024-09-29

from django.db import migrations, models
from django.contrib.postgres.indexes import GinIndex, BrinIndex


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_upload_session_model'),
        ('peoples', '0003_add_performance_indexes'),
        ('activity', '0012_add_mobile_sync_fields'),
        ('y_helpdesk', '0011_add_mobile_sync_fields'),
        ('onboarding', '0007_add_voice_fields_to_conversation_session'),
    ]

    operations = [
        # Note: Skipped indexes for non-existent tables:
        # - api_access_logs
        # - security_csp_violations
        # - encryption_key_metadata
        # - core_uploadsession
        # These should be created in the migrations that create those tables

        # Note: Cross-model indexes moved - some tables referenced don't exist at this migration point
        # These indexes should be created in later migrations after all tables are created

        # Enable required PostgreSQL extensions
        migrations.RunSQL(
            sql=[
                "CREATE EXTENSION IF NOT EXISTS pg_trgm;",  # For trigram indexes
                "CREATE EXTENSION IF NOT EXISTS btree_gin;",  # For GIN indexes on btree types
            ],
            reverse_sql=[
                # Don't drop extensions as they might be used by other applications
            ]
        ),
    ]

    # Required for CONCURRENTLY operations - cannot run in transaction
    atomic = False