# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0002_initial"),
        ("client_onboarding", "0003_initial"),
        ("noc", "0002_initial"),
        ("noc_security_intelligence", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceanomalylog",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="attendanceanomalylog",
            name="expected_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Expected person (for WRONG_PERSON)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expected_at_site",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendanceanomalylog",
            name="investigated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Investigator",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigated_anomalies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendanceanomalylog",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="attendanceanomalylog",
            name="noc_alert",
            field=models.ForeignKey(
                blank=True,
                help_text="Related NOC alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_anomalies",
                to="noc.nocalertevent",
            ),
        ),
        migrations.AddField(
            model_name="attendanceanomalylog",
            name="person",
            field=models.ForeignKey(
                help_text="Person involved in anomaly",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_anomalies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendanceanomalylog",
            name="site",
            field=models.ForeignKey(
                help_text="Site where anomaly occurred",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_anomalies",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="attendanceanomalylog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="auditfinding",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who acknowledged the finding",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_findings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditfinding",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="auditfinding",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="auditfinding",
            name="noc_alert",
            field=models.ForeignKey(
                blank=True,
                help_text="NOC alert created for this finding",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_findings",
                to="noc.nocalertevent",
            ),
        ),
        migrations.AddField(
            model_name="auditfinding",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who resolved the finding",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_findings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditfinding",
            name="site",
            field=models.ForeignKey(
                help_text="Site where finding was detected",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_findings",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="auditfinding",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="baselineprofile",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="baselineprofile",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="baselineprofile",
            name="site",
            field=models.ForeignKey(
                help_text="Site for this baseline",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baseline_profiles",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="baselineprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="behavioralprofile",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="behavioralprofile",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="behavioralprofile",
            name="person",
            field=models.OneToOneField(
                help_text="Guard whose behavior is profiled",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="behavioral_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="behavioralprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="biometricverificationlog",
            name="attendance_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Related attendance event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biometric_verifications",
                to="attendance.peopleeventlog",
            ),
        ),
        migrations.AddField(
            model_name="biometricverificationlog",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="biometricverificationlog",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="biometricverificationlog",
            name="person",
            field=models.ForeignKey(
                help_text="Person being verified",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biometric_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="biometricverificationlog",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Reviewer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_biometric_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="biometricverificationlog",
            name="site",
            field=models.ForeignKey(
                help_text="Site where verification occurred",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biometric_verifications",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="biometricverificationlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="findingrunbook",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="findingrunbook",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="findingrunbook",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="auditfinding",
            name="runbook_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Runbook for remediation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="noc_security_intelligence.findingrunbook",
            ),
        ),
        migrations.AddField(
            model_name="frauddetectionmodel",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="frauddetectionmodel",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="frauddetectionmodel",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="fraudpredictionlog",
            name="actual_attendance_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Actual attendance event (if occurred)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fraud_predictions",
                to="attendance.peopleeventlog",
            ),
        ),
        migrations.AddField(
            model_name="fraudpredictionlog",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="fraudpredictionlog",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="fraudpredictionlog",
            name="person",
            field=models.ForeignKey(
                help_text="Person for whom prediction was made",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fraud_predictions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fraudpredictionlog",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Predicted site",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fraud_predictions",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="fraudpredictionlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="gpsvalidationlog",
            name="attendance_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Related attendance event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gps_validations",
                to="attendance.peopleeventlog",
            ),
        ),
        migrations.AddField(
            model_name="gpsvalidationlog",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="gpsvalidationlog",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="gpsvalidationlog",
            name="noc_alert",
            field=models.ForeignKey(
                blank=True,
                help_text="Related NOC alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gps_validations",
                to="noc.nocalertevent",
            ),
        ),
        migrations.AddField(
            model_name="gpsvalidationlog",
            name="person",
            field=models.ForeignKey(
                help_text="Person whose location was validated",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gps_validations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gpsvalidationlog",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Reviewer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_gps_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gpsvalidationlog",
            name="site",
            field=models.ForeignKey(
                help_text="Expected site",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gps_validations",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="gpsvalidationlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="guardactivitytracking",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="guardactivitytracking",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="guardactivitytracking",
            name="person",
            field=models.ForeignKey(
                help_text="Guard being tracked",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_tracking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guardactivitytracking",
            name="site",
            field=models.ForeignKey(
                help_text="Current site assignment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guard_activities",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="guardactivitytracking",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="inactivityalert",
            name="activity_tracking",
            field=models.ForeignKey(
                help_text="Related activity tracking record",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="noc_security_intelligence.guardactivitytracking",
            ),
        ),
        migrations.AddField(
            model_name="inactivityalert",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="inactivityalert",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="inactivityalert",
            name="noc_alert",
            field=models.ForeignKey(
                blank=True,
                help_text="Related NOC alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inactivity_alerts",
                to="noc.nocalertevent",
            ),
        ),
        migrations.AddField(
            model_name="inactivityalert",
            name="person",
            field=models.ForeignKey(
                help_text="Guard with detected inactivity",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inactivity_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inactivityalert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who resolved the alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_inactivity_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inactivityalert",
            name="site",
            field=models.ForeignKey(
                help_text="Site where inactivity detected",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inactivity_alerts",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="inactivityalert",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="mltrainingdataset",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="mltrainingdataset",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="mltrainingdataset",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nonnegotiablesscorecard",
            name="client",
            field=models.ForeignKey(
                help_text="Client/business unit",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="non_negotiables_scorecards",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="nonnegotiablesscorecard",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nonnegotiablesscorecard",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nonnegotiablesscorecard",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="securityanomalyconfig",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client for CLIENT/SITE scope",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_configs_as_client",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="securityanomalyconfig",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="securityanomalyconfig",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="securityanomalyconfig",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Site for SITE scope",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_configs_as_site",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="securityanomalyconfig",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="shiftschedulecache",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="shiftschedulecache",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="shiftschedulecache",
            name="original_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Original person if this is substitute",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_for_shifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shiftschedulecache",
            name="person",
            field=models.ForeignKey(
                help_text="Assigned person",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cached_shifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shiftschedulecache",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Shift definition",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cached_schedules",
                to="client_onboarding.shift",
            ),
        ),
        migrations.AddField(
            model_name="shiftschedulecache",
            name="site",
            field=models.ForeignKey(
                help_text="Assigned site",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cached_shifts",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="shiftschedulecache",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="siteauditschedule",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="siteauditschedule",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="siteauditschedule",
            name="site",
            field=models.OneToOneField(
                help_text="Site (business unit) to audit",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_schedule",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="siteauditschedule",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="taskcomplianceconfig",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client for CLIENT/SITE scope",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_compliance_configs_as_client",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="taskcomplianceconfig",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="taskcomplianceconfig",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="taskcomplianceconfig",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Site for SITE scope",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_compliance_configs_as_site",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="taskcomplianceconfig",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tourcompliancelog",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="tourcompliancelog",
            name="investigated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Investigator",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigated_tours",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tourcompliancelog",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="tourcompliancelog",
            name="noc_alert",
            field=models.ForeignKey(
                blank=True,
                help_text="Related NOC alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tour_compliance_logs",
                to="noc.nocalertevent",
            ),
        ),
        migrations.AddField(
            model_name="tourcompliancelog",
            name="person",
            field=models.ForeignKey(
                help_text="Assigned guard",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tour_compliance_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tourcompliancelog",
            name="site",
            field=models.ForeignKey(
                help_text="Site where tour scheduled",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tour_compliance_logs",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="tourcompliancelog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceanomalylog",
            index=models.Index(
                fields=["tenant", "detected_at"], name="noc_attenda_tenant__41bef0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceanomalylog",
            index=models.Index(
                fields=["person", "detected_at"], name="noc_attenda_person__014229_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceanomalylog",
            index=models.Index(
                fields=["site", "anomaly_type", "detected_at"],
                name="noc_attenda_site_id_6b7080_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceanomalylog",
            index=models.Index(
                fields=["status", "severity"], name="noc_attenda_status_ec7fb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceanomalylog",
            index=models.Index(
                fields=["anomaly_type", "status"], name="noc_attenda_anomaly_4ffeb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="baselineprofile",
            index=models.Index(
                fields=["site", "metric_type", "hour_of_week"],
                name="noc_baselin_site_id_9e06ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselineprofile",
            index=models.Index(
                fields=["is_stable", "metric_type"],
                name="noc_baselin_is_stab_197d0e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="baselineprofile",
            unique_together={("tenant", "site", "metric_type", "hour_of_week")},
        ),
        migrations.AddIndex(
            model_name="behavioralprofile",
            index=models.Index(
                fields=["tenant", "person"], name="noc_behavio_tenant__3e73dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="behavioralprofile",
            index=models.Index(
                fields=["baseline_fraud_score"], name="noc_behavio_baselin_e85a16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="behavioralprofile",
            index=models.Index(
                fields=["last_trained_at"], name="noc_behavio_last_tr_50e411_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricverificationlog",
            index=models.Index(
                fields=["tenant", "verified_at"], name="noc_biometr_tenant__083675_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricverificationlog",
            index=models.Index(
                fields=["person", "verified_at"], name="noc_biometr_person__b30bb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricverificationlog",
            index=models.Index(
                fields=["site", "result", "verified_at"],
                name="noc_biometr_site_id_84caa4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="biometricverificationlog",
            index=models.Index(
                fields=["is_concurrent", "is_suspicious_pattern"],
                name="noc_biometr_is_conc_59271e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="biometricverificationlog",
            index=models.Index(
                fields=["fraud_score"], name="noc_biometr_fraud_s_019e26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricverificationlog",
            index=models.Index(
                fields=["flagged_for_review"], name="noc_biometr_flagged_b71da0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="findingrunbook",
            index=models.Index(
                fields=["category", "severity"], name="noc_finding_categor_2e7d54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="findingrunbook",
            index=models.Index(
                fields=["finding_type"], name="noc_finding_finding_bea065_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditfinding",
            index=models.Index(
                fields=["tenant", "site", "detected_at"],
                name="noc_audit_f_tenant__d7eedb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditfinding",
            index=models.Index(
                fields=["category", "severity", "status"],
                name="noc_audit_f_categor_65bfe6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditfinding",
            index=models.Index(
                fields=["finding_type", "status"], name="noc_audit_f_finding_7fcec1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditfinding",
            index=models.Index(
                fields=["detected_at"], name="noc_audit_f_detecte_ec0e7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frauddetectionmodel",
            index=models.Index(
                fields=["tenant", "is_active"], name="noc_fraud_d_tenant__25b0ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frauddetectionmodel",
            index=models.Index(
                fields=["model_version"], name="noc_fraud_d_model_v_b075c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frauddetectionmodel",
            index=models.Index(fields=["pr_auc"], name="noc_fraud_d_pr_auc_4b360d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="frauddetectionmodel",
            unique_together={("tenant", "model_version")},
        ),
        migrations.AddIndex(
            model_name="fraudpredictionlog",
            index=models.Index(
                fields=["tenant", "predicted_at"], name="noc_fraud_p_tenant__72e8ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudpredictionlog",
            index=models.Index(
                fields=["person", "predicted_at"], name="noc_fraud_p_person__de1e3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudpredictionlog",
            index=models.Index(
                fields=["risk_level", "predicted_at"],
                name="noc_fraud_p_risk_le_2ad8d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fraudpredictionlog",
            index=models.Index(
                fields=["fraud_probability"], name="noc_fraud_p_fraud_p_6fd4df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudpredictionlog",
            index=models.Index(
                fields=["actual_fraud_detected"], name="noc_fraud_p_actual__34a9b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudpredictionlog",
            index=models.Index(
                fields=["confidence_interval_width"], name="fraud_pred_log_ci_width_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gpsvalidationlog",
            index=models.Index(
                fields=["tenant", "validated_at"], name="noc_gps_val_tenant__f40d7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gpsvalidationlog",
            index=models.Index(
                fields=["person", "validated_at"], name="noc_gps_val_person__0e0e9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gpsvalidationlog",
            index=models.Index(
                fields=["site", "result", "validated_at"],
                name="noc_gps_val_site_id_bc559d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gpsvalidationlog",
            index=models.Index(
                fields=["is_impossible_speed", "is_within_geofence"],
                name="noc_gps_val_is_impo_9bf35b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gpsvalidationlog",
            index=models.Index(
                fields=["fraud_score"], name="noc_gps_val_fraud_s_ec94b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guardactivitytracking",
            index=models.Index(
                fields=["tenant", "tracking_start"],
                name="noc_guard_a_tenant__befb76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guardactivitytracking",
            index=models.Index(
                fields=["person", "tracking_start"],
                name="noc_guard_a_person__ee8efe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guardactivitytracking",
            index=models.Index(
                fields=["site", "shift_type", "tracking_start"],
                name="noc_guard_a_site_id_ef1c3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guardactivitytracking",
            index=models.Index(
                fields=["is_inactive", "alert_generated"],
                name="noc_guard_a_is_inac_564ac2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inactivityalert",
            index=models.Index(
                fields=["tenant", "detected_at"], name="noc_inactiv_tenant__d5dcb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inactivityalert",
            index=models.Index(
                fields=["person", "detected_at"], name="noc_inactiv_person__535eea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inactivityalert",
            index=models.Index(
                fields=["site", "severity", "detected_at"],
                name="noc_inactiv_site_id_178cab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inactivityalert",
            index=models.Index(
                fields=["status", "is_deep_night"], name="noc_inactiv_status_96f0d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mltrainingdataset",
            index=models.Index(
                fields=["tenant", "dataset_type", "status"],
                name="noc_ml_trai_tenant__37ce9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mltrainingdataset",
            index=models.Index(
                fields=["is_active_model"], name="noc_ml_trai_is_acti_21af17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mltrainingdataset",
            index=models.Index(
                fields=["version"], name="noc_ml_trai_version_66139d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nonnegotiablesscorecard",
            index=models.Index(
                fields=["client", "check_date"], name="scorecard_client_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nonnegotiablesscorecard",
            index=models.Index(
                fields=["overall_health_status", "check_date"],
                name="scorecard_health_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nonnegotiablesscorecard",
            index=models.Index(fields=["check_date"], name="scorecard_date_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="nonnegotiablesscorecard",
            unique_together={("tenant", "client", "check_date")},
        ),
        migrations.AddIndex(
            model_name="securityanomalyconfig",
            index=models.Index(
                fields=["tenant", "scope", "is_active"],
                name="noc_securit_tenant__dfb32f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityanomalyconfig",
            index=models.Index(
                fields=["client", "is_active"], name="noc_securit_client__dc2529_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityanomalyconfig",
            index=models.Index(
                fields=["site", "is_active"], name="noc_securit_site_id_d09003_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="securityanomalyconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scope", "TENANT"), ("client__isnull", False), _connector="OR"
                ),
                name="client_required_for_client_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="securityanomalyconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scope__in", ["TENANT", "CLIENT"]),
                    ("site__isnull", False),
                    _connector="OR",
                ),
                name="site_required_for_site_scope",
            ),
        ),
        migrations.AddIndex(
            model_name="shiftschedulecache",
            index=models.Index(
                fields=["tenant", "shift_date"], name="noc_shift_s_tenant__52318f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftschedulecache",
            index=models.Index(
                fields=["person", "shift_date"], name="noc_shift_s_person__8c3820_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftschedulecache",
            index=models.Index(
                fields=["site", "shift_date"], name="noc_shift_s_site_id_9f578e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftschedulecache",
            index=models.Index(
                fields=["shift_date", "shift_type"],
                name="noc_shift_s_shift_d_2ac3de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shiftschedulecache",
            index=models.Index(
                fields=["cache_valid_until"], name="noc_shift_s_cache_v_835c00_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftschedulecache",
            constraint=models.UniqueConstraint(
                fields=("tenant", "person", "site", "shift_date"),
                name="unique_person_site_date_shift",
            ),
        ),
        migrations.AddIndex(
            model_name="siteauditschedule",
            index=models.Index(
                fields=["tenant", "enabled"], name="noc_site_au_tenant__15aeb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="siteauditschedule",
            index=models.Index(
                fields=["site", "enabled"], name="noc_site_au_site_id_662825_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="siteauditschedule",
            index=models.Index(
                fields=["last_audit_at"], name="noc_site_au_last_au_6c4e02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskcomplianceconfig",
            index=models.Index(
                fields=["tenant", "scope", "is_active"],
                name="noc_task_co_tenant__3a46bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskcomplianceconfig",
            index=models.Index(
                fields=["client", "is_active"], name="noc_task_co_client__587175_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskcomplianceconfig",
            index=models.Index(
                fields=["site", "is_active"], name="noc_task_co_site_id_02a570_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tourcompliancelog",
            index=models.Index(
                fields=["tenant", "scheduled_date"],
                name="noc_tour_co_tenant__37ff79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tourcompliancelog",
            index=models.Index(
                fields=["person", "scheduled_date"],
                name="noc_tour_co_person__da9064_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tourcompliancelog",
            index=models.Index(
                fields=["site", "status", "scheduled_date"],
                name="noc_tour_co_site_id_1ed015_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tourcompliancelog",
            index=models.Index(
                fields=["compliance_status", "is_mandatory"],
                name="noc_tour_co_complia_3a3964_idx",
            ),
        ),
    ]
