# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenantname",
                    models.CharField(max_length=50, verbose_name="tenantname"),
                ),
                (
                    "subdomain_prefix",
                    models.CharField(
                        help_text="Lowercase alphanumeric string with hyphens only. Used for tenant identification and routing. Example: intelliwiz-django",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_subdomain_prefix",
                                message="Subdomain prefix can only contain lowercase letters, numbers, and hyphens. No spaces or special characters allowed.",
                                regex="^[a-z0-9-]+$",
                            )
                        ],
                        verbose_name="subdomain_prefix",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this tenant is currently active and can access the system",
                        verbose_name="is_active",
                    ),
                ),
                (
                    "suspended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when tenant was suspended (if applicable)",
                        null=True,
                        verbose_name="suspended_at",
                    ),
                ),
                (
                    "suspension_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for suspension (for audit trail)",
                        verbose_name="suspension_reason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["tenantname"],
            },
        ),
    ]
