# Generated by Django 5.2.7 on 2025-11-09 10:20

import apps.peoples.models.base_model
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journal", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "thread_type",
                    models.CharField(
                        choices=[
                            ("gratitude_journey", "Gratitude Practice Journey"),
                            ("stress_management", "Stress Management Path"),
                            ("three_good_things", "Three Good Things Evolution"),
                            ("cbt_cognitive", "Cognitive Behavioral Insights"),
                            ("crisis_recovery", "Crisis Recovery Narrative"),
                            ("workplace_wellness", "Workplace Wellness Journey"),
                            ("motivational_growth", "Motivational Growth Story"),
                            ("preventive_care", "Preventive Mental Health"),
                            (
                                "achievement_celebration",
                                "Achievement & Milestone Celebrations",
                            ),
                            ("reflection_insights", "Deep Reflection Insights"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of this conversation thread",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "priority_level",
                    models.IntegerField(
                        default=1,
                        help_text="1=Low, 5=Critical (for crisis threads)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("conversation_count", models.PositiveIntegerField(default=0)),
                (
                    "first_conversation_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_conversation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "narrative_style",
                    models.CharField(
                        choices=[
                            ("warm_supportive", "Warm & Supportive"),
                            ("professional_clinical", "Professional Clinical"),
                            ("gentle_encouraging", "Gentle Encouraging"),
                            ("motivational_energetic", "Motivational Energetic"),
                            ("crisis_stabilizing", "Crisis Stabilizing"),
                        ],
                        default="warm_supportive",
                        max_length=30,
                    ),
                ),
                (
                    "personalization_data",
                    models.JSONField(
                        default=dict,
                        help_text="User preferences and effectiveness data for this thread type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wellness_conversation_threads",
            },
        ),
        migrations.CreateModel(
            name="MentalHealthIntervention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("three_good_things", "Three Good Things Exercise"),
                            ("gratitude_letter", "Gratitude Letter Writing"),
                            ("gratitude_journal", "Daily Gratitude Practice"),
                            ("strength_spotting", "Character Strengths Identification"),
                            ("best_self", "Best Possible Self Visualization"),
                            ("kindness", "Random Acts of Kindness"),
                            ("behavioral_activation", "Behavioral Activation Exercise"),
                            ("thought_record", "CBT Thought Record"),
                            ("activity_scheduling", "Pleasant Activity Scheduling"),
                            ("cognitive_reframing", "Cognitive Reframing Exercise"),
                            ("progressive_relaxation", "Progressive Muscle Relaxation"),
                            ("breathing_exercise", "Guided Breathing Exercise"),
                            ("mindful_moment", "Mindful Awareness Exercise"),
                            ("stress_reappraisal", "Stress Reappraisal Technique"),
                            ("motivational_checkin", "Motivational Check-in"),
                            ("values_clarification", "Personal Values Reflection"),
                            ("change_readiness", "Change Readiness Assessment"),
                            ("crisis_resource", "Crisis Support Resource"),
                            ("safety_planning", "Safety Planning Tool"),
                            ("professional_referral", "Professional Help Information"),
                        ],
                        help_text="Specific intervention technique",
                        max_length=50,
                    ),
                ),
                (
                    "evidence_base",
                    models.CharField(
                        choices=[
                            (
                                "seligman_validated",
                                "Seligman Positive Psychology Research",
                            ),
                            ("cbt_evidence", "CBT Clinical Evidence Base"),
                            ("who_recommended", "WHO Mental Health Guidelines"),
                            ("workplace_validated", "Workplace Mental Health Research"),
                            ("meta_analysis", "Meta-Analysis Evidence"),
                            ("rct_validated", "Randomized Controlled Trial"),
                        ],
                        help_text="Research evidence supporting this intervention",
                        max_length=30,
                    ),
                ),
                (
                    "expected_benefit_duration",
                    models.CharField(
                        help_text="Research-backed duration of benefits (e.g., '6 months post-intervention')",
                        max_length=100,
                    ),
                ),
                (
                    "effectiveness_percentage",
                    models.IntegerField(
                        help_text="Research-reported effectiveness percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "optimal_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate (Crisis Response)"),
                            ("within_hour", "Within 1 Hour"),
                            ("same_day", "Same Day"),
                            ("weekly", "Weekly (Optimal for Gratitude)"),
                            ("bi_weekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("pattern_triggered", "Pattern-Triggered"),
                        ],
                        help_text="Research-optimal delivery frequency",
                        max_length=30,
                    ),
                ),
                (
                    "intervention_duration_minutes",
                    models.IntegerField(
                        help_text="Time required to complete intervention",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "mood_trigger_threshold",
                    models.IntegerField(
                        blank=True,
                        help_text="Mood rating that triggers this intervention (≤ threshold)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "stress_trigger_threshold",
                    models.IntegerField(
                        blank=True,
                        help_text="Stress level that triggers this intervention (≥ threshold)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "energy_trigger_threshold",
                    models.IntegerField(
                        blank=True,
                        help_text="Energy level that triggers this intervention (≤ threshold)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "crisis_escalation_level",
                    models.IntegerField(
                        default=0,
                        help_text="Urgency level for crisis escalation (0=none, 10=immediate professional help)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "workplace_context_tags",
                    models.JSONField(
                        default=list,
                        help_text="Workplace contexts where this is most effective (equipment_failure, deadline_pressure, etc.)",
                    ),
                ),
                (
                    "guided_questions",
                    models.JSONField(
                        default=list,
                        help_text="Step-by-step questions to guide user through intervention",
                    ),
                ),
                (
                    "template_structure",
                    models.JSONField(
                        default=dict,
                        help_text="Template for structured interventions (thought records, gratitude formats, etc.)",
                    ),
                ),
                (
                    "follow_up_prompts",
                    models.JSONField(
                        default=list, help_text="Follow-up questions for next session"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mental Health Intervention",
                "verbose_name_plural": "Mental Health Interventions",
            },
        ),
        migrations.CreateModel(
            name="InterventionDeliveryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_trigger",
                    models.CharField(
                        choices=[
                            ("daily_tip", "Daily Wellness Tip"),
                            ("pattern_triggered", "Pattern-Based Delivery"),
                            ("stress_response", "High Stress Response"),
                            ("mood_support", "Low Mood Support"),
                            ("energy_boost", "Low Energy Response"),
                            ("shift_transition", "Shift Start/End"),
                            ("streak_milestone", "Milestone Reward"),
                            ("seasonal", "Seasonal Health"),
                            ("workplace_specific", "Workplace Guidance"),
                            (
                                "gratitude_enhancement",
                                "Positive Psychology Reinforcement",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user_mood_at_delivery",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "user_stress_at_delivery",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "user_energy_at_delivery",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("was_viewed", models.BooleanField(default=False)),
                ("was_completed", models.BooleanField(default=False)),
                ("completion_time_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "user_response",
                    models.JSONField(
                        default=dict, help_text="User's responses to guided questions"
                    ),
                ),
                (
                    "follow_up_mood_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User's mood rating after intervention (if provided)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "follow_up_stress_level",
                    models.IntegerField(
                        blank=True,
                        help_text="User's stress level after intervention (if provided)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "perceived_helpfulness",
                    models.IntegerField(
                        blank=True,
                        help_text="User's rating of intervention helpfulness",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "triggering_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_interventions",
                        to="journal.journalentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="wellness.mentalhealthintervention",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention Delivery Log",
                "verbose_name_plural": "Intervention Delivery Logs",
                "ordering": ["-delivered_at"],
            },
        ),
        migrations.CreateModel(
            name="WellnessContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Content title - clear and actionable", max_length=200
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Brief summary for quick scanning", max_length=500
                    ),
                ),
                ("content", models.TextField(help_text="Main educational content")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mental_health", "Mental Health"),
                            ("physical_wellness", "Physical Wellness"),
                            ("workplace_health", "Workplace Health"),
                            ("substance_awareness", "Substance Awareness"),
                            ("preventive_care", "Preventive Care"),
                            ("sleep_hygiene", "Sleep Hygiene"),
                            ("nutrition_basics", "Nutrition Basics"),
                            ("stress_management", "Stress Management"),
                            ("physical_activity", "Physical Activity"),
                            ("mindfulness", "Mindfulness"),
                        ],
                        help_text="Primary wellness category",
                        max_length=50,
                    ),
                ),
                (
                    "delivery_context",
                    models.CharField(
                        choices=[
                            ("daily_tip", "Daily Wellness Tip"),
                            ("pattern_triggered", "Pattern-Based Delivery"),
                            ("stress_response", "High Stress Response"),
                            ("mood_support", "Low Mood Support"),
                            ("energy_boost", "Low Energy Response"),
                            ("shift_transition", "Shift Start/End"),
                            ("streak_milestone", "Milestone Reward"),
                            ("seasonal", "Seasonal Health"),
                            ("workplace_specific", "Workplace Guidance"),
                            (
                                "gratitude_enhancement",
                                "Positive Psychology Reinforcement",
                            ),
                        ],
                        help_text="When/how this content should be delivered",
                        max_length=50,
                    ),
                ),
                (
                    "content_level",
                    models.CharField(
                        choices=[
                            ("quick_tip", "Quick Tip (1 min)"),
                            ("short_read", "Short Read (3 min)"),
                            ("deep_dive", "Deep Dive (7 min)"),
                            ("interactive", "Interactive (5 min)"),
                            ("video_content", "Video Content (4 min)"),
                        ],
                        help_text="Content complexity and time requirement",
                        max_length=20,
                    ),
                ),
                (
                    "evidence_level",
                    models.CharField(
                        choices=[
                            ("who_cdc", "WHO/CDC Guideline"),
                            ("peer_reviewed", "Peer-Reviewed Research"),
                            ("professional", "Professional Consensus"),
                            ("established", "Established Practice"),
                            ("educational", "General Education"),
                        ],
                        help_text="Quality of evidence backing this content",
                        max_length=30,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="Tags for pattern matching with journal entries",
                    ),
                ),
                (
                    "trigger_patterns",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Complex trigger conditions for content delivery",
                    ),
                ),
                (
                    "workplace_specific",
                    models.BooleanField(
                        default=False,
                        help_text="Content specifically adapted for workplace contexts",
                    ),
                ),
                (
                    "field_worker_relevant",
                    models.BooleanField(
                        default=False,
                        help_text="Relevant for field workers and mobile contexts",
                    ),
                ),
                (
                    "action_tips",
                    models.JSONField(
                        default=list, help_text="Concrete, actionable advice points"
                    ),
                ),
                (
                    "key_takeaways",
                    models.JSONField(
                        default=list, help_text="Key learning points and insights"
                    ),
                ),
                (
                    "related_topics",
                    models.JSONField(
                        default=list,
                        help_text="IDs of related content for progressive learning",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        help_text="Source organization (WHO, CDC, Mayo Clinic, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Original source URL for verification",
                        null=True,
                    ),
                ),
                (
                    "evidence_summary",
                    models.TextField(
                        blank=True, help_text="Summary of evidence backing this content"
                    ),
                ),
                (
                    "citations",
                    models.JSONField(
                        default=list, help_text="Academic citations and references"
                    ),
                ),
                (
                    "last_verified_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time content accuracy was verified",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether content is available for delivery",
                    ),
                ),
                (
                    "priority_score",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "seasonal_relevance",
                    models.JSONField(
                        default=list,
                        help_text="Months when content is most relevant (1-12)",
                    ),
                ),
                (
                    "frequency_limit_days",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum days between showings to same user",
                    ),
                ),
                (
                    "estimated_reading_time",
                    models.IntegerField(
                        help_text="Estimated reading/consumption time in minutes"
                    ),
                ),
                (
                    "complexity_score",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "content_version",
                    models.CharField(
                        default="1.0",
                        help_text="Version for content updates and tracking",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Content creator/editor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wellness Content",
                "verbose_name_plural": "Wellness Content Items",
                "ordering": ["-priority_score", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mentalhealthintervention",
            name="wellness_content",
            field=models.OneToOneField(
                help_text="Links to base wellness content",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mental_health_intervention",
                to="wellness.wellnesscontent",
            ),
        ),
        migrations.CreateModel(
            name="WellnessContentInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("viewed", "Viewed"),
                            ("completed", "Completed Reading"),
                            ("bookmarked", "Bookmarked"),
                            ("shared", "Shared"),
                            ("dismissed", "Dismissed"),
                            ("rated", "Rated"),
                            ("acted_upon", "Took Action"),
                            ("requested_more", "Requested More Info"),
                        ],
                        help_text="Type of interaction performed",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_context",
                    models.CharField(
                        choices=[
                            ("daily_tip", "Daily Wellness Tip"),
                            ("pattern_triggered", "Pattern-Based Delivery"),
                            ("stress_response", "High Stress Response"),
                            ("mood_support", "Low Mood Support"),
                            ("energy_boost", "Low Energy Response"),
                            ("shift_transition", "Shift Start/End"),
                            ("streak_milestone", "Milestone Reward"),
                            ("seasonal", "Seasonal Health"),
                            ("workplace_specific", "Workplace Guidance"),
                            (
                                "gratitude_enhancement",
                                "Positive Psychology Reinforcement",
                            ),
                        ],
                        help_text="Context in which content was delivered",
                        max_length=50,
                    ),
                ),
                (
                    "time_spent_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Time spent engaging with content",
                        null=True,
                    ),
                ),
                (
                    "completion_percentage",
                    models.IntegerField(
                        blank=True,
                        help_text="Percentage of content consumed (0-100)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User rating of content (1-5 stars)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "user_feedback",
                    models.TextField(
                        blank=True, help_text="Optional user feedback or comments"
                    ),
                ),
                (
                    "action_taken",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user indicated they took recommended action",
                    ),
                ),
                (
                    "user_mood_at_delivery",
                    models.IntegerField(
                        blank=True,
                        help_text="User's mood rating when content was delivered",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "user_stress_at_delivery",
                    models.IntegerField(
                        blank=True,
                        help_text="User's stress level when content was delivered",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("interaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Additional context and metadata",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        help_text="Content that was interacted with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="wellness.wellnesscontent",
                    ),
                ),
                (
                    "trigger_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Journal entry that triggered this content delivery",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_wellness_content",
                        to="journal.journalentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who interacted with content",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellness_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wellness Content Interaction",
                "verbose_name_plural": "Wellness Content Interactions",
                "ordering": ["-interaction_date"],
            },
        ),
        migrations.CreateModel(
            name="WellnessUserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_streak_days",
                    models.IntegerField(
                        default=0, help_text="Current consecutive days of engagement"
                    ),
                ),
                (
                    "longest_streak_days",
                    models.IntegerField(default=0, help_text="Personal best streak"),
                ),
                ("total_content_viewed", models.IntegerField(default=0)),
                ("total_content_completed", models.IntegerField(default=0)),
                ("total_time_spent_minutes", models.IntegerField(default=0)),
                (
                    "category_progress",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Progress by category",
                    ),
                ),
                (
                    "category_preferences",
                    models.JSONField(
                        default=dict, help_text="User preferences by category"
                    ),
                ),
                (
                    "achievements_earned",
                    models.JSONField(
                        default=list, help_text="List of achievement IDs earned"
                    ),
                ),
                ("milestone_alerts_enabled", models.BooleanField(default=True)),
                ("last_activity_date", models.DateTimeField(blank=True, null=True)),
                ("onboarding_completed", models.BooleanField(default=False)),
                (
                    "personalization_profile",
                    models.JSONField(default=dict, help_text="ML personalization data"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellness_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Wellness Progress",
                "verbose_name_plural": "User Wellness Progress Records",
            },
        ),
        migrations.CreateModel(
            name="WisdomConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_text",
                    models.TextField(
                        help_text="The main conversational text that feels like a continuous book narrative"
                    ),
                ),
                (
                    "conversation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "conversation_tone",
                    models.CharField(
                        choices=[
                            ("celebratory", "Celebratory"),
                            ("supportive", "Supportive"),
                            ("encouraging", "Encouraging"),
                            ("reflective", "Reflective"),
                            ("motivational", "Motivational"),
                            ("crisis_stabilizing", "Crisis Stabilizing"),
                            ("gentle_guidance", "Gentle Guidance"),
                            ("professional_clinical", "Professional Clinical"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("intervention_delivery", "Mental Health Intervention"),
                            ("crisis_response", "Crisis Response"),
                            ("milestone_celebration", "Milestone Achievement"),
                            ("weekly_reflection", "Weekly Reflection"),
                            ("contextual_bridge", "Contextual Bridge"),
                            ("manual_entry", "Manual Entry"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "contextual_bridge_text",
                    models.TextField(
                        blank=True,
                        help_text="Bridging text that connects this conversation to the previous one seamlessly",
                    ),
                ),
                ("word_count", models.PositiveIntegerField(default=0)),
                (
                    "estimated_reading_time_seconds",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "personalization_score",
                    models.FloatField(
                        default=0.0,
                        help_text="How well personalized this conversation is (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "conversation_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata like intervention techniques used, keywords, etc.",
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        help_text="Position in the chronological conversation sequence for this thread"
                    ),
                ),
                (
                    "is_milestone_conversation",
                    models.BooleanField(
                        default=False,
                        help_text="Marks significant conversations (achievements, breakthroughs, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bridges_from_conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous conversation this bridges from for narrative continuity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bridges_to_conversations",
                        to="wellness.wisdomconversation",
                    ),
                ),
                (
                    "source_intervention_delivery",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source intervention delivery that was transformed into this conversation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wellness.interventiondeliverylog",
                    ),
                ),
                (
                    "source_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Journal entry that triggered this conversation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="journal.journalentry",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wisdom_conversations",
                        to="wellness.conversationthread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wisdom_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wellness_wisdom_conversations",
                "ordering": ["thread", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="ConversationEngagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "engagement_type",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("read_complete", "Read Completely"),
                            ("bookmark", "Bookmarked"),
                            ("share", "Shared"),
                            ("reflection_note", "Added Reflection Note"),
                            ("positive_feedback", "Positive Feedback"),
                            ("request_more", "Requested More"),
                            ("skip", "Skipped"),
                            ("negative_feedback", "Negative Feedback"),
                        ],
                        max_length=30,
                    ),
                ),
                ("engagement_date", models.DateTimeField(auto_now_add=True)),
                (
                    "time_spent_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Time user spent reading/engaging with this conversation",
                    ),
                ),
                (
                    "scroll_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of conversation text scrolled through",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "effectiveness_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User rating of conversation effectiveness (1-5)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "user_reflection_note",
                    models.TextField(
                        blank=True,
                        help_text="Optional user reflection or notes about this conversation",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("desktop", "Desktop"),
                        ],
                        default="mobile",
                        max_length=20,
                    ),
                ),
                (
                    "access_context",
                    models.CharField(
                        choices=[
                            ("routine_check", "Routine Check"),
                            ("notification_prompt", "Notification Prompt"),
                            ("crisis_support", "Crisis Support"),
                            ("milestone_celebration", "Milestone Celebration"),
                            ("search_discovery", "Search Discovery"),
                            ("manual_browse", "Manual Browse"),
                        ],
                        default="routine_check",
                        max_length=30,
                    ),
                ),
                (
                    "engagement_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional engagement context and analytics data",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="wellness.wisdomconversation",
                    ),
                ),
            ],
            options={
                "db_table": "wellness_conversation_engagements",
            },
        ),
        migrations.CreateModel(
            name="ConversationBookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("breakthrough", "Breakthrough Moment"),
                            ("inspiration", "Inspiration"),
                            ("practical_tool", "Practical Tool"),
                            ("crisis_help", "Crisis Help"),
                            ("milestone", "Personal Milestone"),
                            ("daily_reminder", "Daily Reminder"),
                            ("professional_reference", "Professional Reference"),
                            ("share_worthy", "Worth Sharing"),
                        ],
                        default="inspiration",
                        max_length=30,
                    ),
                ),
                (
                    "personal_note",
                    models.TextField(
                        blank=True,
                        help_text="Personal note about why this conversation was bookmarked",
                    ),
                ),
                (
                    "reminder_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to send periodic reminders about this bookmarked conversation",
                    ),
                ),
                (
                    "reminder_frequency_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="How often to remind user about this bookmark (in days)",
                    ),
                ),
                ("last_reminder_sent", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="wellness.wisdomconversation",
                    ),
                ),
            ],
            options={
                "db_table": "wellness_conversation_bookmarks",
            },
        ),
        migrations.CreateModel(
            name="WisdomConversationTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        choices=[
                            ("hi", "हिन्दी (Hindi)"),
                            ("te", "తెలుగు (Telugu)"),
                            ("es", "Español (Spanish)"),
                            ("fr", "Français (French)"),
                            ("ar", "العربية (Arabic)"),
                            ("zh", "中文 (Chinese)"),
                        ],
                        help_text="Language code for the translation",
                        max_length=10,
                        verbose_name="Target Language",
                    ),
                ),
                (
                    "translated_text",
                    models.TextField(
                        help_text="Full translated conversation text",
                        verbose_name="Translated Text",
                    ),
                ),
                (
                    "warning_message",
                    models.CharField(
                        help_text="Localized warning message about translation quality",
                        max_length=500,
                        verbose_name="Translation Warning",
                    ),
                ),
                (
                    "translation_backend",
                    models.CharField(
                        choices=[
                            ("google", "Google Translate"),
                            ("azure", "Azure Translator"),
                            ("openai", "OpenAI GPT Translation"),
                            ("manual", "Manual Translation"),
                            ("hybrid", "Hybrid (Multiple Backends)"),
                        ],
                        default="google",
                        help_text="Service used for translation",
                        max_length=20,
                        verbose_name="Translation Backend",
                    ),
                ),
                (
                    "quality_level",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified (Auto-translated)"),
                            ("reviewed", "Reviewed by Human"),
                            ("professional", "Professional Translation"),
                            ("native", "Native Speaker Verified"),
                        ],
                        default="unverified",
                        help_text="Translation quality assessment",
                        max_length=20,
                        verbose_name="Quality Level",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Translation Pending"),
                            ("processing", "Translation in Progress"),
                            ("completed", "Translation Completed"),
                            ("failed", "Translation Failed"),
                            ("expired", "Translation Cache Expired"),
                        ],
                        default="pending",
                        help_text="Current processing status",
                        max_length=20,
                        verbose_name="Translation Status",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI confidence in translation quality (0.0-1.0)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Confidence Score",
                    ),
                ),
                (
                    "word_count_original",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of words in original text",
                        null=True,
                        verbose_name="Original Word Count",
                    ),
                ),
                (
                    "word_count_translated",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of words in translated text",
                        null=True,
                        verbose_name="Translated Word Count",
                    ),
                ),
                (
                    "translation_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time taken for translation in milliseconds",
                        null=True,
                        verbose_name="Translation Time (ms)",
                    ),
                ),
                (
                    "cache_hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this translation was served from cache",
                        verbose_name="Cache Hit Count",
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this translation was last retrieved",
                        null=True,
                        verbose_name="Last Accessed",
                    ),
                ),
                (
                    "source_content_hash",
                    models.CharField(
                        help_text="SHA-256 hash of original content for version tracking",
                        max_length=64,
                        verbose_name="Source Content Hash",
                    ),
                ),
                (
                    "translation_version",
                    models.CharField(
                        default="1.0",
                        help_text="Version number for translation revisions",
                        max_length=20,
                        verbose_name="Translation Version",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this translation cache should expire",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from human reviewers about translation quality",
                        verbose_name="Review Notes",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if translation failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of translation retry attempts",
                        verbose_name="Retry Count",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "original_conversation",
                    models.ForeignKey(
                        help_text="Original English conversation being translated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="wellness.wisdomconversation",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who reviewed this translation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_translations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wisdom Conversation Translation",
                "verbose_name_plural": "Wisdom Conversation Translations",
                "db_table": "wellness_conversation_translation",
                "ordering": ["-quality_level", "-cdtz"],
            },
        ),
        migrations.CreateModel(
            name="TranslationQualityFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("rating", "Quality Rating"),
                            ("correction", "Text Correction"),
                            ("complaint", "Quality Complaint"),
                            ("compliment", "Quality Compliment"),
                        ],
                        help_text="Type of feedback provided",
                        max_length=20,
                        verbose_name="Feedback Type",
                    ),
                ),
                (
                    "quality_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Very Poor - Incomprehensible"),
                            (2, "Poor - Many Errors"),
                            (3, "Fair - Some Errors"),
                            (4, "Good - Minor Issues"),
                            (5, "Excellent - Perfect Translation"),
                        ],
                        help_text="1-5 star rating of translation quality",
                        null=True,
                        verbose_name="Quality Rating",
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(
                        blank=True,
                        help_text="Detailed feedback or suggested corrections",
                        verbose_name="Feedback Text",
                    ),
                ),
                (
                    "suggested_translation",
                    models.TextField(
                        blank=True,
                        help_text="User's suggested improved translation",
                        verbose_name="Suggested Translation",
                    ),
                ),
                (
                    "is_helpful",
                    models.BooleanField(
                        default=False,
                        help_text="Whether feedback was marked as helpful by administrators",
                        verbose_name="Marked as Helpful",
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(
                        blank=True,
                        help_text="Administrator response to feedback",
                        verbose_name="Admin Response",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User providing feedback",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        help_text="Translation being rated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_feedback",
                        to="wellness.wisdomconversationtranslation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation Quality Feedback",
                "verbose_name_plural": "Translation Quality Feedback",
                "db_table": "wellness_translation_feedback",
            },
        ),
        migrations.AddIndex(
            model_name="conversationthread",
            index=models.Index(
                fields=["user", "thread_type"], name="wellness_co_user_id_c3bf2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationthread",
            index=models.Index(
                fields=["status", "priority_level"],
                name="wellness_co_status_2b4a4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationthread",
            index=models.Index(
                fields=["last_conversation_date"], name="wellness_co_last_co_8e9572_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversationthread",
            unique_together={("user", "thread_type")},
        ),
        migrations.AddIndex(
            model_name="interventiondeliverylog",
            index=models.Index(
                fields=["user", "delivered_at"], name="wellness_in_user_id_ad7b62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interventiondeliverylog",
            index=models.Index(
                fields=["intervention", "delivery_trigger"],
                name="wellness_in_interve_f57721_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interventiondeliverylog",
            index=models.Index(
                fields=["was_completed"], name="wellness_in_was_com_bf3e3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wellnesscontent",
            index=models.Index(
                fields=["category", "delivery_context"],
                name="wellness_we_categor_4d9239_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wellnesscontent",
            index=models.Index(
                fields=["is_active", "priority_score"],
                name="wellness_we_is_acti_d27772_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wellnesscontent",
            index=models.Index(
                fields=["workplace_specific", "field_worker_relevant"],
                name="wellness_we_workpla_d044b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wellnesscontent",
            index=models.Index(
                fields=["tenant", "category"], name="wellness_we_tenant__71c9e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wellnesscontent",
            index=models.Index(
                fields=["evidence_level"], name="wellness_we_evidenc_354fd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wellnesscontent",
            index=models.Index(fields=["tags"], name="wellness_we_tags_a5b4d5_idx"),
        ),
        migrations.AddIndex(
            model_name="wellnesscontent",
            index=models.Index(
                fields=["created_at"], name="wellness_we_created_3f1b6b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wellnesscontent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("priority_score__gte", 1), ("priority_score__lte", 100)
                ),
                name="valid_wellness_priority_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="wellnesscontent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("complexity_score__gte", 1), ("complexity_score__lte", 5)
                ),
                name="valid_wellness_complexity_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="wellnesscontent",
            constraint=models.CheckConstraint(
                condition=models.Q(("estimated_reading_time__gte", 1)),
                name="valid_reading_time",
            ),
        ),
        migrations.AddIndex(
            model_name="mentalhealthintervention",
            index=models.Index(
                fields=["intervention_type"], name="wellness_me_interve_2d6691_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mentalhealthintervention",
            index=models.Index(
                fields=["evidence_base"], name="wellness_me_evidenc_decc13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mentalhealthintervention",
            index=models.Index(
                fields=["mood_trigger_threshold"], name="wellness_me_mood_tr_cce650_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mentalhealthintervention",
            index=models.Index(
                fields=["stress_trigger_threshold"],
                name="wellness_me_stress__083a8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mentalhealthintervention",
            index=models.Index(
                fields=["crisis_escalation_level"],
                name="wellness_me_crisis__3c20cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mentalhealthintervention",
            index=models.Index(
                fields=["optimal_frequency"], name="wellness_me_optimal_0ae954_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wellnesscontentinteraction",
            index=models.Index(
                fields=["user", "interaction_date"],
                name="wellness_we_user_id_3b293e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wellnesscontentinteraction",
            index=models.Index(
                fields=["content", "interaction_type"],
                name="wellness_we_content_a5eb31_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wellnesscontentinteraction",
            index=models.Index(
                fields=["trigger_journal_entry"], name="wellness_we_trigger_783e01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wellnesscontentinteraction",
            index=models.Index(
                fields=["delivery_context"], name="wellness_we_deliver_bf5244_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wellnesscontentinteraction",
            index=models.Index(
                fields=["interaction_type"], name="wellness_we_interac_48775b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wellnesscontentinteraction",
            index=models.Index(
                fields=["user_rating"], name="wellness_we_user_ra_701448_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wellnesscontentinteraction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completion_percentage__gte", 0),
                        ("completion_percentage__lte", 100),
                    ),
                    ("completion_percentage__isnull", True),
                    _connector="OR",
                ),
                name="valid_completion_percentage",
            ),
        ),
        migrations.AddConstraint(
            model_name="wellnesscontentinteraction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user_rating__gte", 1), ("user_rating__lte", 5)),
                    ("user_rating__isnull", True),
                    _connector="OR",
                ),
                name="valid_user_rating",
            ),
        ),
        migrations.AddIndex(
            model_name="wellnessuserprogress",
            index=models.Index(
                fields=["user", "current_streak_days"],
                name="wellness_we_user_id_b7183a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wellnessuserprogress",
            index=models.Index(
                fields=["tenant", "last_activity_date"],
                name="wellness_we_tenant__1cd463_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wisdomconversation",
            index=models.Index(
                fields=["user", "conversation_date"],
                name="wellness_wi_user_id_3c79f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wisdomconversation",
            index=models.Index(
                fields=["thread", "sequence_number"],
                name="wellness_wi_thread__026016_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wisdomconversation",
            index=models.Index(
                fields=["source_type", "conversation_date"],
                name="wellness_wi_source__22888b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wisdomconversation",
            index=models.Index(
                fields=["is_milestone_conversation"],
                name="wellness_wi_is_mile_2d85bf_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wisdomconversation",
            unique_together={("thread", "sequence_number")},
        ),
        migrations.AddIndex(
            model_name="conversationengagement",
            index=models.Index(
                fields=["user", "engagement_date"],
                name="wellness_co_user_id_92e376_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationengagement",
            index=models.Index(
                fields=["conversation", "engagement_type"],
                name="wellness_co_convers_612eb1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationengagement",
            index=models.Index(
                fields=["effectiveness_rating"], name="wellness_co_effecti_59bf9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationengagement",
            index=models.Index(
                fields=["access_context", "engagement_date"],
                name="wellness_co_access__49bb9e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationbookmark",
            index=models.Index(
                fields=["user", "category"], name="wellness_co_user_id_632e5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationbookmark",
            index=models.Index(
                fields=["reminder_enabled", "last_reminder_sent"],
                name="wellness_co_reminde_56cd10_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversationbookmark",
            unique_together={("user", "conversation")},
        ),
        migrations.AddIndex(
            model_name="wisdomconversationtranslation",
            index=models.Index(
                fields=["original_conversation", "target_language"],
                name="wellness_conv_trans_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wisdomconversationtranslation",
            index=models.Index(
                fields=["status", "quality_level"],
                name="wellness_conv_trans_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wisdomconversationtranslation",
            index=models.Index(
                fields=["last_accessed", "expires_at"],
                name="wellness_conv_trans_cache_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wisdomconversationtranslation",
            index=models.Index(
                fields=["translation_backend", "cdtz"],
                name="wellness_conv_trans_perf_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wisdomconversationtranslation",
            unique_together={
                ("original_conversation", "target_language", "translation_version")
            },
        ),
        migrations.AddIndex(
            model_name="translationqualityfeedback",
            index=models.Index(
                fields=["quality_rating", "cdtz"], name="w_trans_fb_rating_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="translationqualityfeedback",
            index=models.Index(
                fields=["feedback_type", "is_helpful"], name="w_trans_fb_type_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="translationqualityfeedback",
            unique_together={("translation", "user")},
        ),
    ]
