# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="user",
            field=models.ForeignKey(
                help_text="Owner of this journal entry",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalmediaattachment",
            name="journal_entry",
            field=models.ForeignKey(
                help_text="Associated journal entry",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_attachments",
                to="journal.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalprivacysettings",
            name="user",
            field=models.OneToOneField(
                help_text="User these privacy settings belong to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_privacy_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["user", "-timestamp"], name="journal_jou_user_id_8cf5c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entry_type", "-timestamp"],
                name="journal_jou_entry_t_445d9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["privacy_scope", "user"], name="journal_jou_privacy_a8c1ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["mood_rating", "timestamp"],
                name="journal_jou_mood_ra_e93f52_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["stress_level", "timestamp"],
                name="journal_jou_stress__1f8b44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["sync_status", "mobile_id"],
                name="journal_jou_sync_st_bf097a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["is_deleted", "is_draft"], name="journal_jou_is_dele_8cbc4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["tenant", "timestamp"], name="journal_jou_tenant__c0e835_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["created_at"], name="journal_jou_created_41a2c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["tags"], name="journal_jou_tags_27952f_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["timestamp", "is_deleted"],
                name="journal_jou_timesta_e6f7a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["user", "timestamp", "is_deleted"],
                name="journal_jou_user_id_c05559_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mood_rating__gte", 1), ("mood_rating__lte", 10)),
                    ("mood_rating__isnull", True),
                    _connector="OR",
                ),
                name="valid_mood_rating_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("stress_level__gte", 1), ("stress_level__lte", 5)),
                    ("stress_level__isnull", True),
                    _connector="OR",
                ),
                name="valid_stress_level_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("energy_level__gte", 1), ("energy_level__lte", 10)),
                    ("energy_level__isnull", True),
                    _connector="OR",
                ),
                name="valid_energy_level_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completion_rate__gte", 0.0), ("completion_rate__lte", 1.0)
                    ),
                    ("completion_rate__isnull", True),
                    _connector="OR",
                ),
                name="valid_completion_rate_range",
            ),
        ),
        migrations.AddIndex(
            model_name="journalmediaattachment",
            index=models.Index(
                fields=["journal_entry", "display_order"],
                name="journal_jou_journal_83d846_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalmediaattachment",
            index=models.Index(
                fields=["media_type"], name="journal_jou_media_t_89edcf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalmediaattachment",
            index=models.Index(
                fields=["sync_status"], name="journal_jou_sync_st_1139cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalmediaattachment",
            index=models.Index(
                fields=["is_deleted"], name="journal_jou_is_dele_263f3b_idx"
            ),
        ),
    ]
