# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HelpArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=250)),
                ("summary", models.TextField(max_length=500)),
                ("content", models.TextField()),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                        ],
                        db_index=True,
                        default="BEGINNER",
                        max_length=20,
                    ),
                ),
                (
                    "target_roles",
                    models.JSONField(
                        default=list,
                        help_text="List of permission group names that can view this article",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        help_text="384-dim embedding for semantic search (pgvector)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "Under Review"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("view_count", models.IntegerField(db_index=True, default=0)),
                ("helpful_count", models.IntegerField(default=0)),
                ("not_helpful_count", models.IntegerField(default=0)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("last_reviewed_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "help_center_article",
                "ordering": ["-published_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HelpArticleInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("VIEW", "Viewed"),
                            ("BOOKMARK", "Bookmarked"),
                            ("SHARE", "Shared"),
                            ("VOTE_HELPFUL", "Voted Helpful"),
                            ("VOTE_NOT_HELPFUL", "Voted Not Helpful"),
                            ("FEEDBACK_INCORRECT", "Reported Incorrect"),
                            ("FEEDBACK_OUTDATED", "Reported Outdated"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "time_spent_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Time spent reading article (seconds)",
                        null=True,
                    ),
                ),
                (
                    "scroll_depth_percent",
                    models.IntegerField(
                        blank=True,
                        help_text="How far user scrolled (0-100%)",
                        null=True,
                    ),
                ),
                (
                    "feedback_comment",
                    models.TextField(
                        blank=True, help_text="Optional comment for votes/feedback"
                    ),
                ),
                ("session_id", models.UUIDField(db_index=True)),
                (
                    "referrer_url",
                    models.CharField(
                        blank=True,
                        help_text="Page user was on when accessing help",
                        max_length=500,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "help_center_interaction",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="HelpCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class (e.g., 'fa-wrench', 'material-icons:build')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#1976d2",
                        help_text="Hex color code for category badge",
                        max_length=7,
                    ),
                ),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name_plural": "Help Categories",
                "db_table": "help_center_category",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HelpSearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=500)),
                ("results_count", models.IntegerField(db_index=True, default=0)),
                (
                    "click_position",
                    models.IntegerField(
                        blank=True,
                        help_text="Position of clicked result (1-based)",
                        null=True,
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Link to HelpArticleInteraction.session_id",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "help_center_search_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="HelpTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50)),
                ("slug", models.SlugField(max_length=60, unique=True)),
            ],
            options={
                "db_table": "help_center_tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HelpTicketCorrelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "help_attempted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Did user view any help articles before creating ticket?",
                    ),
                ),
                (
                    "help_session_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Link to help session if help was attempted",
                        null=True,
                    ),
                ),
                (
                    "search_queries",
                    models.JSONField(
                        default=list,
                        help_text="List of search queries attempted before ticket creation",
                    ),
                ),
                (
                    "relevant_article_exists",
                    models.BooleanField(
                        blank=True,
                        help_text="Based on ticket analysis, does relevant help content exist?",
                        null=True,
                    ),
                ),
                (
                    "content_gap",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Should content team create new article for this topic?",
                    ),
                ),
                (
                    "resolution_time_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Time from ticket creation to resolution (minutes)",
                        null=True,
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When correlation analysis was performed",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "help_center_ticket_correlation",
            },
        ),
    ]
