# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("help_center", "0001_initial"),
        ("tenants", "0001_initial"),
        ("y_helpdesk", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="helparticle",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="help_articles_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="last_updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="help_articles_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_versions",
                to="help_center.helparticle",
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="helparticleinteraction",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="help_center.helparticle",
            ),
        ),
        migrations.AddField(
            model_name="helparticleinteraction",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="helparticleinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="help_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="help_center.helpcategory",
            ),
        ),
        migrations.AddField(
            model_name="helpcategory",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="help_center.helpcategory",
            ),
        ),
        migrations.AddField(
            model_name="helpsearchhistory",
            name="clicked_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_clicks",
                to="help_center.helparticle",
            ),
        ),
        migrations.AddField(
            model_name="helpsearchhistory",
            name="refinement_of",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is a refined search, link to original",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refinements",
                to="help_center.helpsearchhistory",
            ),
        ),
        migrations.AddField(
            model_name="helpsearchhistory",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="helpsearchhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="help_searches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="helptag",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="tags",
            field=models.ManyToManyField(blank=True, to="help_center.helptag"),
        ),
        migrations.AddField(
            model_name="helpticketcorrelation",
            name="articles_viewed",
            field=models.ManyToManyField(
                blank=True,
                related_name="ticket_correlations",
                to="help_center.helparticle",
            ),
        ),
        migrations.AddField(
            model_name="helpticketcorrelation",
            name="suggested_article",
            field=models.ForeignKey(
                blank=True,
                help_text="Article to show in ticket view",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggested_for_tickets",
                to="help_center.helparticle",
            ),
        ),
        migrations.AddField(
            model_name="helpticketcorrelation",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="helpticketcorrelation",
            name="ticket",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="help_correlation",
                to="y_helpdesk.ticket",
            ),
        ),
        migrations.AddIndex(
            model_name="helparticleinteraction",
            index=models.Index(
                fields=["article", "interaction_type"], name="help_interaction_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helparticleinteraction",
            index=models.Index(
                fields=["user", "timestamp"], name="help_interaction_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helparticleinteraction",
            index=models.Index(
                fields=["session_id"], name="help_interaction_session_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="helpcategory",
            unique_together={("tenant", "slug")},
        ),
        migrations.AddIndex(
            model_name="helpsearchhistory",
            index=models.Index(
                fields=["query", "results_count"], name="help_search_zero_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpsearchhistory",
            index=models.Index(
                fields=["user", "timestamp"], name="help_search_user_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="helptag",
            unique_together={("tenant", "slug")},
        ),
        migrations.AddIndex(
            model_name="helparticle",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="help_article_search_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helparticle",
            index=models.Index(
                fields=["status", "published_date"], name="help_article_published_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helparticle",
            index=models.Index(
                fields=["category", "status"], name="help_article_category_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helparticle",
            index=models.Index(
                fields=["view_count"], name="help_article_popularity_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="helparticle",
            unique_together={("tenant", "slug")},
        ),
        migrations.AddIndex(
            model_name="helpticketcorrelation",
            index=models.Index(
                fields=["help_attempted", "content_gap"], name="help_ticket_gap_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpticketcorrelation",
            index=models.Index(fields=["ticket"], name="help_ticket_correlation_idx"),
        ),
    ]
