# Generated by Django 5.2.1 - Placeholder migration for people_onboarding
# This migration will be regenerated with `python manage.py makemigrations people_onboarding`
# once Django environment is available.

"""
Initial migration for people_onboarding bounded context.

This migration creates 8 models + 5 enums for the people onboarding workflow:

Models:
1. OnboardingRequest - Core onboarding request with workflow state
2. CandidateProfile - Personal information and contact details
3. DocumentSubmission - Document uploads (resume, ID, certificates)
4. ApprovalWorkflow - Multi-stakeholder approval chain
5. BackgroundCheck - Verification and compliance tracking
6. AccessProvisioning - Biometric, device, and site access setup
7. TrainingAssignment - Mandatory training and orientation
8. OnboardingTask - Checklist items with due dates

Enums:
- DocumentType - Document classification
- ApprovalDecision - Approval workflow decisions
- VerificationStatus - Background check status
- AccessType - Access provision types
- TaskPriority - Task priority levels

All models extend EnhancedTenantModel for multi-tenancy support.

Dependencies:
- apps.tenants (for EnhancedTenantModel)
- apps.peoples (for People foreign key)
- apps.client_onboarding (for Bt foreign key)
- apps.site_onboarding (for OnboardingSite foreign key)
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '__latest__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_onboarding', '0001_initial'),
        ('site_onboarding', '0001_initial'),
    ]

    operations = [
        # ===============================================
        # ONBOARDING REQUEST MODEL
        # ===============================================
        migrations.CreateModel(
            name='OnboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('bt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_onboarding.bt', related_name='onboarding_requests')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_onboarding.onboardingsite', related_name='onboarding_requests')),
                ('request_code', models.CharField(max_length=50, unique=True)),
                ('position_title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, related_name='requested_onboardings')),
                ('status', models.CharField(max_length=20, default='draft')),
                ('priority', models.CharField(max_length=20, default='medium')),
                ('target_start_date', models.DateField(null=True, blank=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'people_onboarding_request',
                'indexes': [
                    models.Index(fields=['tenant', 'bt', 'status']),
                    models.Index(fields=['request_code']),
                ],
            },
        ),

        # ===============================================
        # CANDIDATE PROFILE MODEL
        # ===============================================
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('onboarding_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people_onboarding.onboardingrequest', related_name='candidate_profile')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField()),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(null=True, blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100, blank=True)),
                ('state', models.CharField(max_length=100, blank=True)),
                ('country', models.CharField(max_length=100, blank=True)),
                ('postal_code', models.CharField(max_length=20, blank=True)),
                ('emergency_contact_name', models.CharField(max_length=200, blank=True)),
                ('emergency_contact_phone', models.CharField(max_length=20, blank=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'people_onboarding_candidate_profile',
            },
        ),

        # ===============================================
        # DOCUMENT SUBMISSION MODEL
        # ===============================================
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('onboarding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_onboarding.onboardingrequest', related_name='documents')),
                ('document_type', models.CharField(max_length=50, choices=[
                    ('resume', 'Resume/CV'),
                    ('id_proof', 'ID Proof'),
                    ('address_proof', 'Address Proof'),
                    ('education', 'Educational Certificate'),
                    ('experience', 'Experience Letter'),
                    ('police_clearance', 'Police Clearance'),
                    ('medical', 'Medical Certificate'),
                    ('other', 'Other'),
                ])),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('verification_status', models.CharField(max_length=20, default='pending')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True, blank=True, related_name='verified_documents')),
                ('verified_at', models.DateTimeField(null=True, blank=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'people_onboarding_document_submission',
                'indexes': [
                    models.Index(fields=['tenant', 'onboarding_request', 'document_type']),
                ],
            },
        ),

        # ===============================================
        # APPROVAL WORKFLOW MODEL
        # ===============================================
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('onboarding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_onboarding.onboardingrequest', related_name='approvals')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('approval_stage', models.CharField(max_length=50)),
                ('decision', models.CharField(max_length=20, choices=[
                    ('pending', 'Pending'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                    ('needs_info', 'Needs More Information'),
                ], default='pending')),
                ('comments', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'people_onboarding_approval_workflow',
                'indexes': [
                    models.Index(fields=['tenant', 'onboarding_request', 'decision']),
                ],
            },
        ),

        # ===============================================
        # BACKGROUND CHECK MODEL
        # ===============================================
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('onboarding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_onboarding.onboardingrequest', related_name='background_checks')),
                ('check_type', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=100, blank=True)),
                ('reference_number', models.CharField(max_length=100, blank=True)),
                ('status', models.CharField(max_length=20, choices=[
                    ('pending', 'Pending'),
                    ('in_progress', 'In Progress'),
                    ('completed', 'Completed'),
                    ('verified', 'Verified'),
                    ('failed', 'Failed'),
                ], default='pending')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True, blank=True, related_name='initiated_bg_checks')),
                ('initiated_at', models.DateTimeField(null=True, blank=True)),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('result', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'people_onboarding_background_check',
                'indexes': [
                    models.Index(fields=['tenant', 'onboarding_request', 'status']),
                ],
            },
        ),

        # ===============================================
        # ACCESS PROVISIONING MODEL
        # ===============================================
        migrations.CreateModel(
            name='AccessProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('onboarding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_onboarding.onboardingrequest', related_name='access_provisions')),
                ('access_type', models.CharField(max_length=50, choices=[
                    ('biometric', 'Biometric Access'),
                    ('card', 'Access Card'),
                    ('device', 'Mobile Device'),
                    ('site', 'Site Access'),
                    ('system', 'System Access'),
                ])),
                ('status', models.CharField(max_length=20, default='pending')),
                ('provisioned_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True, blank=True, related_name='provisioned_access')),
                ('provisioned_at', models.DateTimeField(null=True, blank=True)),
                ('access_details', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'people_onboarding_access_provisioning',
                'indexes': [
                    models.Index(fields=['tenant', 'onboarding_request', 'access_type']),
                ],
            },
        ),

        # ===============================================
        # TRAINING ASSIGNMENT MODEL
        # ===============================================
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('onboarding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_onboarding.onboardingrequest', related_name='training_assignments')),
                ('training_name', models.CharField(max_length=200)),
                ('training_type', models.CharField(max_length=50)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('due_date', models.DateField(null=True, blank=True)),
                ('status', models.CharField(max_length=20, choices=[
                    ('not_started', 'Not Started'),
                    ('in_progress', 'In Progress'),
                    ('completed', 'Completed'),
                    ('overdue', 'Overdue'),
                ], default='not_started')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True, blank=True, related_name='assigned_training')),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('completion_certificate', models.CharField(max_length=500, blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'people_onboarding_training_assignment',
                'indexes': [
                    models.Index(fields=['tenant', 'onboarding_request', 'status']),
                ],
            },
        ),

        # ===============================================
        # ONBOARDING TASK MODEL
        # ===============================================
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('onboarding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_onboarding.onboardingrequest', related_name='tasks')),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(max_length=20, choices=[
                    ('low', 'Low'),
                    ('medium', 'Medium'),
                    ('high', 'High'),
                    ('critical', 'Critical'),
                ], default='medium')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True, blank=True, related_name='onboarding_tasks')),
                ('due_date', models.DateField(null=True, blank=True)),
                ('status', models.CharField(max_length=20, default='pending')),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'people_onboarding_task',
                'indexes': [
                    models.Index(fields=['tenant', 'onboarding_request', 'status']),
                    models.Index(fields=['assigned_to', 'status']),
                ],
            },
        ),

        # ===============================================
        # WORKER DOCUMENT MODEL (from legacy onboarding)
        # ===============================================
        migrations.CreateModel(
            name='WorkerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, related_name='worker_documents')),
                ('document_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(null=True, blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True, blank=True, related_name='verified_worker_documents')),
                ('verified_at', models.DateTimeField(null=True, blank=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'people_onboarding_worker_document',
                'indexes': [
                    models.Index(fields=['tenant', 'worker']),
                    models.Index(fields=['document_type']),
                ],
            },
        ),
    ]
