# Generated by Django 5.2.7 on 2025-11-09 10:20

import apps.peoples.fields.secure_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client_onboarding", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "approval_level",
                    models.CharField(
                        choices=[
                            ("HR", "HR Approval"),
                            ("MANAGER", "Manager Approval"),
                            ("SECURITY", "Security Approval"),
                            ("IT", "IT Approval"),
                            ("FINANCE", "Finance Approval"),
                            ("EXECUTIVE", "Executive Approval"),
                        ],
                        max_length=20,
                        verbose_name="Approval Level",
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveSmallIntegerField(
                        help_text="Order in the approval chain (1, 2, 3...)",
                        verbose_name="Sequence Number",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ESCALATED", "Escalated"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Decision",
                    ),
                ),
                (
                    "decision_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Decision Date"
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(blank=True, verbose_name="Decision Notes"),
                ),
                (
                    "escalation_reason",
                    models.TextField(blank=True, verbose_name="Escalation Reason"),
                ),
                (
                    "request_sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Request Sent At"
                    ),
                ),
                (
                    "reminder_sent_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Reminder Count"
                    ),
                ),
                (
                    "last_reminder_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Reminder Sent"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
            ],
            options={
                "verbose_name": "Approval Workflow",
                "verbose_name_plural": "Approval Workflows",
                "db_table": "people_onboarding_approval_workflow",
                "ordering": ["onboarding_request", "sequence_number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BackgroundCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("CRIMINAL", "Criminal Background Check"),
                            ("EMPLOYMENT", "Employment History"),
                            ("EDUCATION", "Educational Qualification"),
                            ("LICENSE", "Professional License"),
                            ("REFERENCE", "Reference Check"),
                            ("CREDIT", "Credit Check"),
                            ("DRUG_TEST", "Drug Testing"),
                            ("ADDRESS", "Address Verification"),
                            ("IDENTITY", "Identity Verification"),
                        ],
                        max_length=20,
                        verbose_name="Verification Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "verification_provider",
                    models.CharField(
                        blank=True,
                        help_text="External agency or internal department",
                        max_length=200,
                        verbose_name="Verification Provider",
                    ),
                ),
                (
                    "provider_reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Provider Reference"
                    ),
                ),
                (
                    "requested_date",
                    models.DateField(auto_now_add=True, verbose_name="Requested Date"),
                ),
                (
                    "expected_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected Completion"
                    ),
                ),
                (
                    "actual_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual Completion"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when this verification expires (e.g., drug test validity)",
                        null=True,
                        verbose_name="Expiry Date",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLEAR", "Clear"),
                            ("DISCREPANCY", "Discrepancy Found"),
                            ("FAIL", "Failed"),
                            ("PENDING_REVIEW", "Pending Review"),
                        ],
                        max_length=20,
                        verbose_name="Result",
                    ),
                ),
                (
                    "result_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed verification results",
                        verbose_name="Result Details",
                    ),
                ),
                ("findings", models.TextField(blank=True, verbose_name="Findings")),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Recommendations"),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="people_onboarding/background_checks/",
                        verbose_name="Verification Report",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "requires_manual_review",
                    models.BooleanField(
                        default=False, verbose_name="Requires Manual Review"
                    ),
                ),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this check must pass before proceeding",
                        verbose_name="Is Blocking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Background Check",
                "verbose_name_plural": "Background Checks",
                "db_table": "people_onboarding_background_check",
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                            ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                        ],
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "primary_email",
                    apps.peoples.fields.secure_fields.EnhancedSecureString(
                        max_length=500, verbose_name="Primary Email"
                    ),
                ),
                (
                    "secondary_email",
                    apps.peoples.fields.secure_fields.EnhancedSecureString(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Secondary Email",
                    ),
                ),
                (
                    "primary_phone",
                    apps.peoples.fields.secure_fields.EnhancedSecureString(
                        max_length=500, verbose_name="Primary Phone"
                    ),
                ),
                (
                    "secondary_phone",
                    apps.peoples.fields.secure_fields.EnhancedSecureString(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Secondary Phone",
                    ),
                ),
                (
                    "current_address",
                    models.TextField(blank=True, verbose_name="Current Address"),
                ),
                (
                    "permanent_address",
                    models.TextField(blank=True, verbose_name="Permanent Address"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="State/Province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postal Code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="India", max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "aadhaar_number",
                    apps.peoples.fields.secure_fields.EnhancedSecureString(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Aadhaar Number",
                    ),
                ),
                (
                    "pan_number",
                    apps.peoples.fields.secure_fields.EnhancedSecureString(
                        blank=True, max_length=500, null=True, verbose_name="PAN Number"
                    ),
                ),
                (
                    "passport_number",
                    apps.peoples.fields.secure_fields.EnhancedSecureString(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Passport Number",
                    ),
                ),
                (
                    "driving_license",
                    apps.peoples.fields.secure_fields.EnhancedSecureString(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Driving License",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Emergency Contact Name",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    apps.peoples.fields.secure_fields.EnhancedSecureString(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Emergency Contact Phone",
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Relationship"
                    ),
                ),
                (
                    "highest_education",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Highest Education"
                    ),
                ),
                (
                    "total_experience_years",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Total Experience (Years)",
                    ),
                ),
                (
                    "current_company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Current Company"
                    ),
                ),
                (
                    "current_designation",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Current Designation"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="LinkedIn Profile"
                    ),
                ),
                (
                    "skills",
                    models.JSONField(blank=True, default=list, verbose_name="Skills"),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Certifications"
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "हिन्दी (Hindi)"),
                            ("te", "తెలుగు (Telugu)"),
                            ("ta", "தமிழ் (Tamil)"),
                            ("kn", "ಕನ್ನಡ (Kannada)"),
                            ("ml", "മലയാളം (Malayalam)"),
                        ],
                        default="en",
                        max_length=10,
                        verbose_name="Preferred Language",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="people_onboarding/photos/",
                        verbose_name="Photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Profile",
                "verbose_name_plural": "Candidate Profiles",
                "db_table": "people_onboarding_candidate_profile",
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("RESUME", "Resume/CV"),
                            ("AADHAAR", "Aadhaar Card"),
                            ("PAN", "PAN Card"),
                            ("PASSPORT", "Passport"),
                            ("DRIVING_LICENSE", "Driving License"),
                            ("EDUCATIONAL_CERTIFICATE", "Educational Certificate"),
                            ("EXPERIENCE_CERTIFICATE", "Experience Certificate"),
                            ("OFFER_LETTER", "Offer Letter"),
                            ("SIGNED_CONTRACT", "Signed Contract"),
                            ("BANK_DETAILS", "Bank Account Details"),
                            ("ADDRESS_PROOF", "Address Proof"),
                            ("PHOTO", "Photograph"),
                            ("MEDICAL_CERTIFICATE", "Medical Fitness Certificate"),
                            ("POLICE_CLEARANCE", "Police Clearance Certificate"),
                            ("NDA", "NDA/Confidentiality Agreement"),
                            ("PROFESSIONAL_LICENSE", "Professional License"),
                            ("INSURANCE", "Insurance Documents"),
                            ("OTHER", "Other"),
                        ],
                        max_length=40,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        upload_to="people_onboarding/documents/%Y/%m/",
                        verbose_name="Document File",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="File Size (bytes)"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="File Hash"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("REQUIRES_REUPLOAD", "Requires Re-upload"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="Verification Status",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, verbose_name="Verification Notes"),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data extracted via OCR/AI",
                        verbose_name="Extracted Data",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(blank=True, null=True, verbose_name="Issue Date"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=False, verbose_name="Is Mandatory"),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Contains PII/sensitive information",
                        verbose_name="Is Sensitive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Submission",
                "verbose_name_plural": "Document Submissions",
                "db_table": "people_onboarding_document",
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OnboardingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "request_number",
                    models.CharField(
                        help_text="Auto-generated unique request identifier",
                        max_length=50,
                        unique=True,
                        verbose_name="Request Number",
                    ),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE_FULLTIME", "Full-Time Employee"),
                            ("EMPLOYEE_PARTTIME", "Part-Time Employee"),
                            ("CONTRACTOR", "Contractor"),
                            ("CONSULTANT", "Consultant"),
                            ("VENDOR_PERSONNEL", "Vendor Personnel"),
                            ("TEMPORARY_WORKER", "Temporary Worker"),
                        ],
                        help_text="Type of person being onboarded",
                        max_length=30,
                        verbose_name="Person Type",
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("DOCUMENT_VERIFICATION", "Document Verification"),
                            ("BACKGROUND_CHECK", "Background Check"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("PROVISIONING", "Provisioning Access"),
                            ("TRAINING", "Training Phase"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=30,
                        verbose_name="Current State",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "expected_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected Completion"
                    ),
                ),
                (
                    "actual_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual Completion"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Cancellation Reason"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Onboarding Request",
                "verbose_name_plural": "Onboarding Requests",
                "db_table": "people_onboarding_request",
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OnboardingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DOCUMENTATION", "Documentation"),
                            ("VERIFICATION", "Verification"),
                            ("APPROVAL", "Approval"),
                            ("PROVISIONING", "Provisioning"),
                            ("TRAINING", "Training"),
                            ("EQUIPMENT", "Equipment"),
                            ("ADMINISTRATIVE", "Administrative"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("BLOCKED", "Blocked"),
                            ("COMPLETED", "Completed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="TODO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "blocker_reason",
                    models.TextField(blank=True, verbose_name="Blocker Reason"),
                ),
                (
                    "skip_reason",
                    models.TextField(blank=True, verbose_name="Skip Reason"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="Is Mandatory"),
                ),
                (
                    "requires_evidence",
                    models.BooleanField(
                        default=False,
                        help_text="Requires document/photo proof of completion",
                        verbose_name="Requires Evidence",
                    ),
                ),
                (
                    "evidence_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="people_onboarding/task_evidence/",
                        verbose_name="Evidence",
                    ),
                ),
                (
                    "completion_notes",
                    models.TextField(blank=True, verbose_name="Completion Notes"),
                ),
            ],
            options={
                "verbose_name": "Onboarding Task",
                "verbose_name_plural": "Onboarding Tasks",
                "db_table": "people_onboarding_task",
                "ordering": ["priority", "due_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrainingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("SAFETY_ORIENTATION", "Safety Orientation"),
                            ("POLICY_TRAINING", "Company Policies"),
                            ("COMPLIANCE", "Compliance Training"),
                            ("EQUIPMENT_OPERATION", "Equipment Operation"),
                            ("SITE_INDUCTION", "Site Induction"),
                            ("DEPARTMENT_ORIENTATION", "Department Orientation"),
                            ("SECURITY_AWARENESS", "Security Awareness"),
                            ("IT_SYSTEMS", "IT Systems Training"),
                            ("SOFT_SKILLS", "Soft Skills"),
                            ("TECHNICAL_SKILLS", "Technical Skills"),
                        ],
                        max_length=30,
                        verbose_name="Training Type",
                    ),
                ),
                (
                    "training_title",
                    models.CharField(max_length=200, verbose_name="Training Title"),
                ),
                (
                    "training_description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateField(auto_now_add=True, verbose_name="Assigned Date"),
                ),
                ("due_date", models.DateField(verbose_name="Due Date")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completion Date"
                    ),
                ),
                (
                    "requires_assessment",
                    models.BooleanField(
                        default=False, verbose_name="Requires Assessment"
                    ),
                ),
                (
                    "assessment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Score out of 100",
                        max_digits=5,
                        null=True,
                        verbose_name="Assessment Score",
                    ),
                ),
                (
                    "passing_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=70.0,
                        help_text="Minimum score to pass",
                        max_digits=5,
                        verbose_name="Passing Score",
                    ),
                ),
                (
                    "certificate_issued",
                    models.BooleanField(
                        default=False, verbose_name="Certificate Issued"
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="people_onboarding/certificates/",
                        verbose_name="Certificate",
                    ),
                ),
                (
                    "estimated_duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Estimated Duration (Hours)",
                    ),
                ),
                (
                    "actual_duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Actual Duration (Hours)",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="Is Mandatory"),
                ),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=False,
                        help_text="Blocks onboarding completion if not done",
                        verbose_name="Is Blocking",
                    ),
                ),
                (
                    "completion_notes",
                    models.TextField(blank=True, verbose_name="Completion Notes"),
                ),
            ],
            options={
                "verbose_name": "Training Assignment",
                "verbose_name_plural": "Training Assignments",
                "db_table": "people_onboarding_training_assignment",
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkerDocument",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "document_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PHOTO_ID", "Government Photo ID"),
                            ("CERTIFICATE", "Training Certificate"),
                            ("BACKGROUND_CHECK", "Background Check Results"),
                            ("MEDICAL", "Medical Clearance"),
                            ("UNIFORM_PHOTO", "Uniform Photo"),
                            ("REFERENCE_LETTER", "Reference Letter"),
                            ("POLICE_VERIFICATION", "Police Verification"),
                            ("ADDRESS_PROOF", "Address Proof"),
                        ],
                        max_length=30,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Verification Status",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expiration date for certificates/clearances",
                        null=True,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Worker Document",
                "verbose_name_plural": "Worker Documents",
                "db_table": "people_onboarding_worker_document",
            },
        ),
        migrations.CreateModel(
            name="AccessProvisioning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("BIOMETRIC_FACE", "Face Recognition Enrollment"),
                            ("BIOMETRIC_VOICE", "Voice Biometric Enrollment"),
                            ("BIOMETRIC_FINGERPRINT", "Fingerprint Enrollment"),
                            ("LOGIN_CREDENTIALS", "System Login Credentials"),
                            ("EMAIL_ACCOUNT", "Email Account"),
                            ("VPN_ACCESS", "VPN Access"),
                            ("DEVICE_ASSIGNMENT", "Device Assignment"),
                            ("BADGE_ID", "Badge/ID Card"),
                            ("SITE_ACCESS", "Physical Site Access"),
                            ("PARKING_SPACE", "Parking Space"),
                            ("LOCKER", "Locker Assignment"),
                            ("SOFTWARE_LICENSE", "Software License"),
                        ],
                        max_length=30,
                        verbose_name="Access Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "provisioned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Provisioned At"
                    ),
                ),
                (
                    "access_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Details like device ID, badge number, email address, etc.",
                        verbose_name="Access Details",
                    ),
                ),
                (
                    "access_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Access Start Date"
                    ),
                ),
                (
                    "access_end_date",
                    models.DateField(
                        blank=True,
                        help_text="For contractors/temporary workers",
                        null=True,
                        verbose_name="Access End Date",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revoked At"
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(blank=True, verbose_name="Revocation Reason"),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="Failure Reason"),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Retry Count"
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(default=True, verbose_name="Requires Approval"),
                ),
                (
                    "is_temporary",
                    models.BooleanField(default=False, verbose_name="Is Temporary"),
                ),
                (
                    "allowed_sites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="onboarded_personnel_access",
                        to="client_onboarding.bt",
                        verbose_name="Allowed Sites",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Provisioning",
                "verbose_name_plural": "Access Provisionings",
                "db_table": "people_onboarding_access_provisioning",
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
    ]
