# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_onboarding", "0002_initial"),
        ("people_onboarding", "0001_initial"),
        ("tenants", "0001_initial"),
        ("work_order_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accessprovisioning",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="accessprovisioning",
            name="provisioned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provisioned_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accessprovisioning",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="accessprovisioning",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="approvalworkflow",
            name="approver",
            field=models.ForeignKey(
                help_text="Person responsible for this approval",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="onboarding_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalworkflow",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="approvalworkflow",
            name="escalated_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Person to whom approval was escalated",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalated_onboarding_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalworkflow",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="approvalworkflow",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="backgroundcheck",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="backgroundcheck",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="backgroundcheck",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_onboarding_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="onboardingrequest",
            name="changeset",
            field=models.ForeignKey(
                blank=True,
                help_text="Changeset for rollback capability",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="people_onboarding_changesets",
                to="core_onboarding.aichangeset",
            ),
        ),
        migrations.AddField(
            model_name="onboardingrequest",
            name="conversation_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated conversational AI session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="people_onboarding_requests",
                to="core_onboarding.conversationsession",
            ),
        ),
        migrations.AddField(
            model_name="onboardingrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="onboardingrequest",
            name="people",
            field=models.OneToOneField(
                blank=True,
                help_text="Created People record after successful onboarding",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="onboarding_record",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="onboardingrequest",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="onboardingrequest",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="onboardingrequest",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated vendor company (for vendor personnel)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="work_order_management.vendor",
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="onboarding_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_documents",
                to="people_onboarding.onboardingrequest",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="onboarding_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_profile",
                to="people_onboarding.onboardingrequest",
            ),
        ),
        migrations.AddField(
            model_name="backgroundcheck",
            name="onboarding_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="background_checks",
                to="people_onboarding.onboardingrequest",
            ),
        ),
        migrations.AddField(
            model_name="approvalworkflow",
            name="onboarding_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_workflows",
                to="people_onboarding.onboardingrequest",
            ),
        ),
        migrations.AddField(
            model_name="accessprovisioning",
            name="onboarding_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_provisions",
                to="people_onboarding.onboardingrequest",
            ),
        ),
        migrations.AddField(
            model_name="onboardingtask",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Person responsible for completing this task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_onboarding_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="onboardingtask",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_onboarding_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="onboardingtask",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="onboardingtask",
            name="depends_on",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tasks that must be completed before this one",
                related_name="dependent_tasks",
                to="people_onboarding.onboardingtask",
                verbose_name="Depends On",
            ),
        ),
        migrations.AddField(
            model_name="onboardingtask",
            name="onboarding_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="people_onboarding.onboardingrequest",
            ),
        ),
        migrations.AddField(
            model_name="onboardingtask",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="onboardingtask",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="onboarding_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_assignments",
                to="people_onboarding.onboardingrequest",
            ),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conducted_onboarding_trainings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trainingassignment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="workerdocument",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="workerdocument",
            name="media",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="core_onboarding.onboardingmedia",
            ),
        ),
        migrations.AddField(
            model_name="workerdocument",
            name="onboarding_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worker_documents",
                to="people_onboarding.onboardingrequest",
            ),
        ),
        migrations.AddField(
            model_name="workerdocument",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="workerdocument",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="workerdocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingrequest",
            index=models.Index(
                fields=["request_number"], name="people_onbo_request_609c6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingrequest",
            index=models.Index(
                fields=["current_state", "created_at"],
                name="people_onbo_current_19c23c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingrequest",
            index=models.Index(
                fields=["person_type"], name="people_onbo_person__74b9d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingrequest",
            index=models.Index(
                fields=["start_date"], name="people_onbo_start_d_498682_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentsubmission",
            index=models.Index(
                fields=["onboarding_request", "document_type"],
                name="people_onbo_onboard_c13c04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentsubmission",
            index=models.Index(
                fields=["verification_status"], name="people_onbo_verific_0e4fea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentsubmission",
            index=models.Index(
                fields=["expiry_date"], name="people_onbo_expiry__e0c99b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateprofile",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="people_onbo_first_n_46c8fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="candidateprofile",
            index=models.Index(
                fields=["primary_email"], name="people_onbo_primary_ad4d4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundcheck",
            index=models.Index(
                fields=["onboarding_request", "verification_type"],
                name="people_onbo_onboard_165963_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundcheck",
            index=models.Index(
                fields=["status", "created_at"], name="people_onbo_status_26800d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundcheck",
            index=models.Index(
                fields=["expiry_date"], name="people_onbo_expiry__9b8cb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalworkflow",
            index=models.Index(
                fields=["onboarding_request", "sequence_number"],
                name="people_onbo_onboard_6fd86f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalworkflow",
            index=models.Index(
                fields=["approver", "decision"], name="people_onbo_approve_3af4f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalworkflow",
            index=models.Index(
                fields=["decision", "created_at"], name="people_onbo_decisio_b96cec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalworkflow",
            constraint=models.UniqueConstraint(
                fields=("onboarding_request", "sequence_number"),
                name="unique_onboarding_sequence",
            ),
        ),
        migrations.AddIndex(
            model_name="accessprovisioning",
            index=models.Index(
                fields=["onboarding_request", "access_type"],
                name="people_onbo_onboard_05c8c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accessprovisioning",
            index=models.Index(fields=["status"], name="people_onbo_status_96a296_idx"),
        ),
        migrations.AddIndex(
            model_name="accessprovisioning",
            index=models.Index(
                fields=["access_end_date"], name="people_onbo_access__6e2ae9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingtask",
            index=models.Index(
                fields=["onboarding_request", "status"],
                name="people_onbo_onboard_02db6c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingtask",
            index=models.Index(
                fields=["assigned_to", "status"], name="people_onbo_assigne_a13c53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingtask",
            index=models.Index(
                fields=["due_date", "status"], name="people_onbo_due_dat_39bbdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingassignment",
            index=models.Index(
                fields=["onboarding_request", "training_type"],
                name="people_onbo_onboard_afb315_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingassignment",
            index=models.Index(
                fields=["status", "due_date"], name="people_onbo_status_ef39ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workerdocument",
            index=models.Index(
                fields=["onboarding_request"], name="workerdoc_request_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workerdocument",
            index=models.Index(
                fields=["verification_status"], name="workerdoc_status_idx"
            ),
        ),
    ]
