# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "report_data",
                    models.JSONField(
                        default=dict,
                        help_text="All field values filled by user and auto-populated",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ai_interactions",
                    models.JSONField(
                        default=list, help_text="Q&A history with AI mentor"
                    ),
                ),
                (
                    "quality_score",
                    models.IntegerField(
                        default=0,
                        help_text="Overall quality score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "completeness_score",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "clarity_score",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("supervisor_feedback", models.TextField(blank=True)),
                (
                    "is_exemplar",
                    models.BooleanField(
                        default=False,
                        help_text="High-quality report used for AI learning",
                    ),
                ),
                (
                    "exemplar_category",
                    models.CharField(
                        blank=True,
                        help_text="Category for exemplar classification",
                        max_length=100,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Report",
                "verbose_name_plural": "Generated Reports",
                "db_table": "generated_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportQualityMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "completeness_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("required_fields_filled", models.IntegerField()),
                ("total_required_fields", models.IntegerField()),
                ("narrative_word_count", models.IntegerField(default=0)),
                ("minimum_narrative_length", models.IntegerField(default=100)),
                (
                    "clarity_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "readability_score",
                    models.FloatField(
                        help_text="Flesch-Kincaid readability (0-100, higher is easier)"
                    ),
                ),
                (
                    "jargon_density",
                    models.FloatField(help_text="Percentage of jargon/vague words"),
                ),
                ("assumption_count", models.IntegerField(default=0)),
                (
                    "causal_chain_strength",
                    models.IntegerField(
                        default=0,
                        help_text="Quality of cause-effect reasoning",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "actionability_score",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "smart_criteria_met",
                    models.IntegerField(
                        default=0, help_text="How many SMART criteria met (0-5)"
                    ),
                ),
                (
                    "improvement_suggestions",
                    models.JSONField(
                        default=list, help_text="Specific suggestions for improvement"
                    ),
                ),
                (
                    "jargon_examples",
                    models.JSONField(
                        default=list,
                        help_text="Examples of jargon/vague language found",
                    ),
                ),
                (
                    "missing_details",
                    models.JSONField(
                        default=list, help_text="Required details not provided"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_quality_metrics",
                        to="report_generation.generatedreport",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Quality Metrics",
                "verbose_name_plural": "Report Quality Metrics",
                "db_table": "report_quality_metrics",
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("incident", "Incident Report"),
                            ("rca", "Root Cause Analysis"),
                            ("capa", "Corrective/Preventive Action"),
                            ("near_miss", "Near-Miss Report"),
                            ("shift_handover", "Shift Handover"),
                            ("safety", "Safety Report"),
                            ("quality", "Quality Report"),
                            ("environmental", "Environmental Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "mentor_domain",
                    models.CharField(
                        choices=[
                            ("security", "Security Mentor (7 Pillars)"),
                            ("facility", "Facility Mentor (Asset Lifecycle)"),
                            ("hybrid", "Hybrid (Both Mentors)"),
                            ("auto", "Auto-Detect Domain"),
                        ],
                        default="auto",
                        help_text="Which AI mentor should handle this report type",
                        max_length=20,
                    ),
                ),
                (
                    "domain_specific_config",
                    models.JSONField(
                        default=dict,
                        help_text="Domain-specific frameworks: 7_pillars for security, asset_lifecycle for facility",
                    ),
                ),
                (
                    "evidence_requirements",
                    models.JSONField(
                        default=list,
                        help_text="Required photo/video types: damage, scene, before_after, equipment",
                    ),
                ),
                (
                    "critical_unknowns_list",
                    models.JSONField(
                        default=list,
                        help_text="Domain-specific critical fields that cannot be unknown",
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        default=dict,
                        help_text="Field definitions: name, type, required, validation rules, conditional logic",
                    ),
                ),
                (
                    "questioning_strategy",
                    models.JSONField(
                        default=dict,
                        help_text="AI frameworks to use: 5_whys, sbar, 5w1h, ishikawa, star",
                    ),
                ),
                (
                    "quality_gates",
                    models.JSONField(
                        default=dict,
                        help_text="Validation rules: minimum scores, required fields, clarity thresholds",
                    ),
                ),
                (
                    "is_system_template",
                    models.BooleanField(
                        default=False,
                        help_text="System templates cannot be deleted, only customized",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.IntegerField(default=1)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
                "db_table": "report_templates",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_reports",
                to="report_generation.reporttemplate",
            ),
        ),
        migrations.CreateModel(
            name="ReportAIInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("5_whys", "5 Whys"),
                            ("sbar", "SBAR Framework"),
                            ("5w1h", "5W1H Analysis"),
                            ("ishikawa", "Ishikawa/Fishbone"),
                            ("star", "STAR Method"),
                            ("clarification", "Clarification"),
                            ("validation", "Validation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "iteration",
                    models.IntegerField(
                        default=1, help_text="Question number in sequence"
                    ),
                ),
                (
                    "depth",
                    models.IntegerField(
                        default=0, help_text="Depth level for frameworks like 5 Whys"
                    ),
                ),
                (
                    "improved_clarity",
                    models.BooleanField(
                        default=False, help_text="Did this Q&A improve report clarity?"
                    ),
                ),
                (
                    "quality_feedback",
                    models.TextField(
                        blank=True, help_text="What specific improvement resulted"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "parent_interaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups",
                        to="report_generation.reportaiinteraction",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_interactions_detailed",
                        to="report_generation.generatedreport",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report AI Interaction",
                "verbose_name_plural": "Report AI Interactions",
                "db_table": "report_ai_interactions",
                "ordering": ["report", "iteration"],
                "indexes": [
                    models.Index(
                        fields=["report", "iteration"],
                        name="report_ai_i_report__589fe8_idx",
                    ),
                    models.Index(
                        fields=["question_type"], name="report_ai_i_questio_e1bb76_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to="reports/attachments/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "pdf",
                                    "mp4",
                                ]
                            )
                        ],
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("sensor", "Sensor Log"),
                            ("other", "Other"),
                        ],
                        default="photo",
                        max_length=20,
                    ),
                ),
                (
                    "evidence_category",
                    models.CharField(
                        choices=[
                            ("scene", "Scene Evidence"),
                            ("damage", "Damage Photo"),
                            ("before", "Before Remediation"),
                            ("after", "After Remediation"),
                            ("equipment", "Equipment"),
                            ("document", "Supporting Document"),
                        ],
                        default="scene",
                        max_length=30,
                    ),
                ),
                ("file_size", models.PositiveIntegerField(default=0)),
                (
                    "mime_type",
                    models.CharField(
                        default="application/octet-stream", max_length=100
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("user_description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_attachments_captured",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="report_generation.generatedreport",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_attachments_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Attachment",
                "verbose_name_plural": "Report Attachments",
                "db_table": "report_attachments",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["report", "attachment_type"],
                        name="report_atta_report__839da6_idx",
                    ),
                    models.Index(
                        fields=["report", "evidence_category"],
                        name="report_atta_report__7f92de_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportExemplar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "exemplar_category",
                    models.CharField(
                        help_text="Incident type, industry, severity, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "why_exemplar",
                    models.TextField(help_text="What makes this report exemplary?"),
                ),
                (
                    "learning_points",
                    models.JSONField(
                        default=list,
                        help_text="Key lessons to extract from this report",
                    ),
                ),
                (
                    "demonstrates_frameworks",
                    models.JSONField(
                        default=list,
                        help_text="Which frameworks are well-executed (5 Whys, SBAR, etc.)",
                    ),
                ),
                (
                    "narrative_quality",
                    models.IntegerField(
                        help_text="Narrative quality rating (1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "root_cause_depth",
                    models.IntegerField(
                        help_text="Depth of root cause analysis (1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("approval_date", models.DateTimeField(auto_now_add=True)),
                (
                    "times_referenced",
                    models.IntegerField(
                        default=0, help_text="How often shown as example to users"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_exemplars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exemplar_details",
                        to="report_generation.generatedreport",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Exemplar",
                "verbose_name_plural": "Report Exemplars",
                "db_table": "report_exemplars",
                "ordering": ["-approval_date"],
                "indexes": [
                    models.Index(
                        fields=["exemplar_category"],
                        name="report_exem_exempla_9ddb66_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportIncidentTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "trend_type",
                    models.CharField(
                        help_text="Type of pattern (recurring_cause, location_risk, temporal, etc.)",
                        max_length=100,
                    ),
                ),
                ("pattern_description", models.TextField()),
                ("occurrence_count", models.IntegerField(default=1)),
                (
                    "severity_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "predicted_recurrence_probability",
                    models.FloatField(help_text="Likelihood of recurrence (0-1)"),
                ),
                (
                    "recommended_actions",
                    models.JSONField(
                        default=list, help_text="Preventive actions suggested by AI"
                    ),
                ),
                ("first_occurrence", models.DateTimeField()),
                ("last_occurrence", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_addressed", models.BooleanField(default=False)),
                ("addressed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "addressed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="addressed_trends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "related_reports",
                    models.ManyToManyField(
                        blank=True,
                        related_name="incident_trends",
                        to="report_generation.generatedreport",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_trends",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Trend",
                "verbose_name_plural": "Incident Trends",
                "db_table": "report_incident_trends",
                "ordering": ["-last_occurrence"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="report_inci_tenant__74ca86_idx",
                    ),
                    models.Index(
                        fields=["tenant", "severity_level"],
                        name="report_inci_tenant__dbfcfb_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["tenant", "category"], name="report_temp_tenant__ad97c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["tenant", "is_active"], name="report_temp_tenant__0fe67b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["tenant", "status"], name="generated_r_tenant__b0d7c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["tenant", "author"], name="generated_r_tenant__f96cbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["tenant", "is_exemplar"], name="generated_r_tenant__caa0d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["template", "status"], name="generated_r_templat_cfc204_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["related_content_type", "related_object_id"],
                name="generated_r_related_acd77c_idx",
            ),
        ),
    ]
