# Generated by Django 5.2.7 on 2025-11-09 10:20

import apps.peoples.constants
import apps.peoples.fields.secure_fields
import apps.peoples.managers
import apps.peoples.mixins.capability_mixin
import apps.peoples.mixins.compatibility_mixin
import apps.peoples.mixins.organizational_mixin
import apps.peoples.models.base_model
import apps.peoples.services.file_upload_service
import django.contrib.auth.models
import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activity", "0002_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("client_onboarding", "0002_initial"),
        ("core_onboarding", "0001_initial"),
        ("sessions", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        help_text="Unique identifier for external system integration",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "peoplecode",
                    models.CharField(
                        help_text="Internal user identification code",
                        max_length=50,
                        verbose_name="User Code",
                    ),
                ),
                (
                    "peoplename",
                    models.CharField(
                        help_text="User's complete name",
                        max_length=120,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "loginid",
                    models.CharField(
                        blank=True,
                        help_text="Unique login identifier for authentication",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Login ID",
                    ),
                ),
                (
                    "isadmin",
                    models.BooleanField(default=False, verbose_name="Administrator"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Staff Status"),
                ),
                (
                    "isverified",
                    models.BooleanField(default=False, verbose_name="Verified"),
                ),
                ("enable", models.BooleanField(default=True, verbose_name="Enabled")),
                (
                    "deviceid",
                    models.CharField(
                        default=apps.peoples.constants.default_device_id,
                        help_text="Associated device identifier for mobile access",
                        max_length=50,
                        verbose_name="Device ID",
                    ),
                ),
                (
                    "email",
                    apps.peoples.fields.secure_fields.EnhancedSecureString(
                        max_length=500, verbose_name="Email"
                    ),
                ),
                (
                    "mobno",
                    apps.peoples.fields.secure_fields.EnhancedSecureString(
                        max_length=500, null=True, verbose_name="Mobile Number"
                    ),
                ),
                (
                    "dateofbirth",
                    models.DateField(
                        blank=True,
                        help_text="User's date of birth",
                        null=True,
                        verbose_name="Date of Birth",
                    ),
                ),
                (
                    "dateofjoin",
                    models.DateField(
                        blank=True,
                        help_text="Employment start date",
                        null=True,
                        verbose_name="Date of Joining",
                    ),
                ),
                (
                    "people_extras",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Additional user preferences and legacy data",
                        verbose_name="User Extras",
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True,
                        default=apps.peoples.constants.default_capabilities,
                        help_text="JSON field storing user capabilities and permissions for AI features",
                        verbose_name="User Capabilities",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "हिन्दी (Hindi)"),
                            ("te", "తెలుగు (Telugu)"),
                            ("es", "Español (Spanish)"),
                            ("fr", "Français (French)"),
                            ("ar", "العربية (Arabic)"),
                            ("zh", "中文 (Chinese)"),
                        ],
                        default="en",
                        help_text="User's preferred language for conversations and content",
                        max_length=10,
                        verbose_name="Preferred Language",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
                "db_table": "people",
            },
            bases=(
                apps.peoples.mixins.capability_mixin.PeopleCapabilityMixin,
                apps.peoples.mixins.compatibility_mixin.PeopleCompatibilityMixin,
                models.Model,
            ),
            managers=[
                ("objects", apps.peoples.managers.PeopleManager()),
            ],
        ),
        migrations.CreateModel(
            name="PermissionGroup",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Group",
                "verbose_name_plural": "Permission Groups",
                "db_table": "permissiongroup",
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="AccountLockout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        help_text="Locked username",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address that triggered lockout (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "lockout_type",
                    models.CharField(
                        choices=[
                            ("ip", "IP Address Lockout"),
                            ("username", "Username Lockout"),
                            ("manual", "Manual Lockout"),
                        ],
                        help_text="Type of lockout",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for lockout")),
                ("locked_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "locked_until",
                    models.DateTimeField(
                        db_index=True, help_text="When lockout expires"
                    ),
                ),
                (
                    "attempt_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of failed attempts that triggered lockout",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether lockout is still active",
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When lockout was manually removed",
                        null=True,
                    ),
                ),
                (
                    "unlocked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who manually unlocked",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unlocked_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Lockout",
                "verbose_name_plural": "Account Lockouts",
                "db_table": "account_lockout",
                "ordering": ["-locked_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "skill_level",
                    models.IntegerField(
                        choices=[
                            (1, "⭐ Learning (can handle basic tasks)"),
                            (2, "⭐⭐ Good (can work independently)"),
                            (3, "⭐⭐⭐ Expert (go-to person)"),
                            (4, "⭐⭐⭐⭐ Master (can train others)"),
                        ],
                        default=2,
                        help_text="How skilled are they?",
                    ),
                ),
                (
                    "certified",
                    models.BooleanField(
                        default=False,
                        help_text="Have they completed official training?",
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time they worked on this type of task",
                        null=True,
                    ),
                ),
                (
                    "total_handled",
                    models.IntegerField(
                        default=0,
                        help_text="Total tasks of this type they've completed",
                    ),
                ),
                (
                    "avg_completion_time",
                    models.DurationField(
                        blank=True,
                        help_text="Average time to complete this type of task",
                        null=True,
                    ),
                ),
                (
                    "success_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="% of tasks completed successfully first time",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="Who has this skill",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="What type of task",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_onboarding.typeassist",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Skill",
                "verbose_name_plural": "Agent Skills",
            },
        ),
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "capscode",
                    models.CharField(
                        help_text="Unique code identifying this capability",
                        max_length=50,
                        verbose_name="Capability Code",
                    ),
                ),
                (
                    "capsname",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable name of the capability",
                        max_length=1000,
                        null=True,
                        verbose_name="Capability Name",
                    ),
                ),
                (
                    "cfor",
                    models.CharField(
                        choices=[
                            ("WEB", "WEB"),
                            ("PORTLET", "PORTLET"),
                            ("REPORT", "REPORT"),
                            ("MOB", "MOB"),
                            ("NOC", "NOC"),
                        ],
                        default="WEB",
                        help_text="Platform type this capability applies to",
                        max_length=10,
                        verbose_name="Platform Type",
                    ),
                ),
                (
                    "enable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this capability is active",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Client organization this capability belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="client_onboarding.bt",
                        verbose_name="Client",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent capability in the hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="children",
                        to="peoples.capability",
                        verbose_name="Parent Capability",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capability",
                "verbose_name_plural": "Capabilities",
                "db_table": "capability",
                "ordering": ["mdtz"],
                "get_latest_by": ["mdtz", "cdtz"],
                "abstract": False,
            },
            managers=[
                ("objects", apps.peoples.managers.CapabilityManager()),
            ],
        ),
        migrations.CreateModel(
            name="DeviceRegistration",
            fields=[
                (
                    "device_id",
                    models.CharField(
                        help_text="SHA256 hash of device fingerprint",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "device_fingerprint",
                    models.JSONField(
                        default=dict, help_text="Browser/device fingerprint data"
                    ),
                ),
                ("user_agent", models.TextField(help_text="User agent string")),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="Last known IP address"),
                ),
                (
                    "trust_score",
                    models.IntegerField(
                        default=0,
                        help_text="Trust score (0-100, threshold: 70 for enrollment)",
                    ),
                ),
                (
                    "trust_factors",
                    models.JSONField(
                        default=dict, help_text="Breakdown of trust score components"
                    ),
                ),
                (
                    "is_trusted",
                    models.BooleanField(
                        default=False, help_text="Device meets trust threshold"
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False, help_text="Device blocked due to security events"
                    ),
                ),
                (
                    "block_reason",
                    models.TextField(blank=True, help_text="Reason for blocking"),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, help_text="First registration timestamp"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, help_text="Last activity timestamp"
                    ),
                ),
                (
                    "last_location",
                    models.CharField(
                        blank=True,
                        help_text="Last known location (city/country)",
                        max_length=255,
                    ),
                ),
                (
                    "biometric_enrolled",
                    models.BooleanField(
                        default=False, help_text="Device used for biometric enrollment"
                    ),
                ),
                (
                    "enrollment_count",
                    models.IntegerField(
                        default=0, help_text="Number of enrollment attempts"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Device owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Registration",
                "verbose_name_plural": "Device Registrations",
                "db_table": "device_registration",
            },
        ),
        migrations.CreateModel(
            name="DeviceRiskEvent",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ENROLLMENT_FAIL", "Enrollment Failed"),
                            ("SPOOFING_DETECTED", "Spoofing Detected"),
                            ("LOCATION_ANOMALY", "Unusual Location"),
                            ("EXCESSIVE_ATTEMPTS", "Too Many Attempts"),
                            ("DEVICE_CHANGE", "Device Characteristics Changed"),
                            ("NETWORK_RISK", "Risky Network"),
                        ],
                        help_text="Type of security event",
                        max_length=50,
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(help_text="Risk score for this event (0-100)"),
                ),
                (
                    "event_data",
                    models.JSONField(
                        default=dict, help_text="Detailed event information"
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When event was detected"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address at time of event", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent at time of event"
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        blank=True, help_text="Automated action taken", max_length=100
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, help_text="Event resolved/cleared"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        help_text="When event was resolved", null=True
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Associated device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_events",
                        to="peoples.deviceregistration",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Risk Event",
                "verbose_name_plural": "Device Risk Events",
                "db_table": "device_risk_event",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginAttemptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, help_text="Username attempted", max_length=255
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, help_text="Client IP address"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether login was successful",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invalid_credentials", "Invalid Credentials"),
                            ("user_not_found", "User Not Found"),
                            ("account_locked", "Account Locked"),
                            ("ip_throttled", "IP Address Throttled"),
                            ("username_throttled", "Username Throttled"),
                            ("authentication_exception", "Authentication Exception"),
                            ("access_denied", "Access Denied"),
                        ],
                        help_text="Reason for failure",
                        max_length=100,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser user agent string"),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[("Web", "Web"), ("Mobile", "Mobile"), ("API", "API")],
                        default="Web",
                        help_text="Access method",
                        max_length=20,
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        help_text="Correlation ID for tracing",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Login Attempt Log",
                "verbose_name_plural": "Login Attempt Logs",
                "db_table": "login_attempt_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["username", "created_at"],
                        name="login_attem_usernam_e33959_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="login_attem_ip_addr_e7f6ea_idx",
                    ),
                    models.Index(
                        fields=["success", "created_at"],
                        name="login_attem_success_0ce651_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Pgroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "groupname",
                    models.CharField(
                        help_text="Name of the people group",
                        max_length=250,
                        verbose_name="Group Name",
                    ),
                ),
                (
                    "enable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this group is active",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "bu",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated business unit",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pgroup_bus",
                        to="client_onboarding.bt",
                        verbose_name="Business Unit",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated client organization",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pgroup_clients",
                        to="client_onboarding.bt",
                        verbose_name="Client",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "grouplead",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who leads this group",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pgroup_groupleads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Group Leader",
                    ),
                ),
                (
                    "identifier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type/category identifier for the group",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pgroup_identifiers",
                        to="core_onboarding.typeassist",
                        verbose_name="Group Type",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "People Group",
                "verbose_name_plural": "People Groups",
                "db_table": "pgroup",
                "ordering": ["mdtz"],
                "get_latest_by": ["mdtz", "cdtz"],
                "abstract": False,
            },
            managers=[
                ("objects", apps.peoples.managers.PgroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="Pgbelonging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "isgrouplead",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this person is a leader of the group",
                        verbose_name="Group Leader",
                    ),
                ),
                (
                    "assignsites",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sites assigned to this person through this group membership",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pgbelongs_assignsites",
                        to="client_onboarding.bt",
                        verbose_name="Assigned Sites",
                    ),
                ),
                (
                    "bu",
                    models.ForeignKey(
                        blank=True,
                        help_text="Business unit for this membership",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pgbelonging_sites",
                        to="client_onboarding.bt",
                        verbose_name="Business Unit",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Client organization for this membership",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pgbelonging_clients",
                        to="client_onboarding.bt",
                        verbose_name="Client",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "people",
                    models.ForeignKey(
                        blank=True,
                        help_text="The person who is a member of this group",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pgbelongs_peoples",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Person",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "pgroup",
                    models.ForeignKey(
                        blank=True,
                        help_text="The group this membership belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pgbelongs_grps",
                        to="peoples.pgroup",
                        verbose_name="Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Membership",
                "verbose_name_plural": "Group Memberships",
                "db_table": "pgbelonging",
                "ordering": ["mdtz"],
                "get_latest_by": ["mdtz", "cdtz"],
                "abstract": False,
            },
            managers=[
                ("objects", apps.peoples.managers.PgblngManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Unique device fingerprint hash",
                        max_length=64,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="User-friendly device name (e.g., 'iPhone 14', 'Chrome on Windows')",
                        max_length=255,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        help_text="Device type",
                        max_length=20,
                    ),
                ),
                ("user_agent", models.TextField(help_text="Full user agent string")),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("browser_version", models.CharField(blank=True, max_length=50)),
                ("os", models.CharField(blank=True, max_length=50)),
                ("os_version", models.CharField(blank=True, max_length=50)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, help_text="IP address at session creation"
                    ),
                ),
                (
                    "last_ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Last known IP address", null=True
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_activity", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="When session expires"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Whether this is the current session"
                    ),
                ),
                (
                    "is_suspicious",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flagged for suspicious activity",
                    ),
                ),
                (
                    "suspicious_reason",
                    models.TextField(
                        blank=True, help_text="Reason for suspicious flag"
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether session was manually revoked",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, help_text="When session was revoked", null=True
                    ),
                ),
                (
                    "revoke_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user_action", "User Revoked"),
                            ("admin_action", "Admin Revoked"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("device_lost", "Device Lost/Stolen"),
                            ("security_breach", "Security Breach"),
                            ("expired", "Session Expired"),
                        ],
                        help_text="Reason for revocation",
                        max_length=100,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User or admin who revoked session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        help_text="Django session object",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_session",
                        to="sessions.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "user_session",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="SessionActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("api_call", "API Call"),
                            ("page_view", "Page View"),
                            ("data_access", "Data Access"),
                            ("permission_escalation", "Permission Escalation"),
                            ("suspicious_action", "Suspicious Action"),
                            ("ip_change", "IP Address Changed"),
                        ],
                        db_index=True,
                        help_text="Type of activity",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Activity description"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address at time of activity"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, help_text="URL accessed", max_length=500
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional activity metadata",
                    ),
                ),
                (
                    "is_suspicious",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Flagged as suspicious"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session that performed the activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="peoples.usersession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Activity Log",
                "verbose_name_plural": "Session Activity Logs",
                "db_table": "session_activity_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PeopleOrganizational",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "people",
                    models.OneToOneField(
                        help_text="Associated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="organizational",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "bu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="org_people_bus",
                        to="client_onboarding.bt",
                        verbose_name="Business Unit",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="org_people_clients",
                        to="client_onboarding.bt",
                        verbose_name="Client",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="org_people_departments",
                        to="core_onboarding.typeassist",
                        verbose_name="Department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="org_people_designations",
                        to="core_onboarding.typeassist",
                        verbose_name="Designation",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary work location",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="activity.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "peopletype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="org_people_types",
                        to="core_onboarding.typeassist",
                        verbose_name="People Type",
                    ),
                ),
                (
                    "reportto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="direct_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reports To",
                    ),
                ),
                (
                    "worktype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="org_work_types",
                        to="core_onboarding.typeassist",
                        verbose_name="Work Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "People Organizational Info",
                "verbose_name_plural": "People Organizational Info",
                "db_table": "people_organizational",
            },
            bases=(
                apps.peoples.mixins.organizational_mixin.OrganizationalQueryMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PeopleProfile",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "people",
                    models.OneToOneField(
                        help_text="Associated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "peopleimg",
                    models.ImageField(
                        blank=True,
                        default="master/people/blank.png",
                        help_text="User profile image (max 5MB, JPG/PNG/GIF/WebP)",
                        null=True,
                        upload_to=apps.peoples.services.file_upload_service.SecureFileUploadService.generate_secure_upload_path,
                        verbose_name="Profile Image",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        max_length=15,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "dateofbirth",
                    models.DateField(
                        help_text="User's date of birth", verbose_name="Date of Birth"
                    ),
                ),
                (
                    "dateofjoin",
                    models.DateField(
                        blank=True,
                        help_text="Employment start date",
                        null=True,
                        verbose_name="Date of Joining",
                    ),
                ),
                (
                    "dateofreport",
                    models.DateField(
                        blank=True,
                        help_text="Reporting start date",
                        null=True,
                        verbose_name="Date of Reporting",
                    ),
                ),
                (
                    "people_extras",
                    models.JSONField(
                        blank=True,
                        default=apps.peoples.constants.peoplejson,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="JSON field storing user preferences and legacy capabilities",
                        verbose_name="User Preferences",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "People Profile",
                "verbose_name_plural": "People Profiles",
                "db_table": "people_profile",
            },
        ),
        migrations.AddIndex(
            model_name="people",
            index=models.Index(fields=["peoplecode"], name="people_peoplecode_idx"),
        ),
        migrations.AddIndex(
            model_name="people",
            index=models.Index(fields=["loginid"], name="people_loginid_idx"),
        ),
        migrations.AddIndex(
            model_name="people",
            index=models.Index(
                fields=["isverified", "enable"], name="people_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="people",
            index=models.Index(fields=["email"], name="people_email_idx"),
        ),
        migrations.AddIndex(
            model_name="people",
            index=models.Index(
                fields=["tenant", "cdtz"], name="people_tenant_cdtz_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="people",
            index=models.Index(
                fields=["tenant", "enable"], name="people_tenant_enable_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountlockout",
            index=models.Index(
                fields=["username", "is_active"], name="account_loc_usernam_8acdea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountlockout",
            index=models.Index(
                fields=["lockout_type", "is_active"],
                name="account_loc_lockout_485da2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accountlockout",
            index=models.Index(
                fields=["locked_until"], name="account_loc_locked__a3d40c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentskill",
            index=models.Index(
                fields=["agent", "category"], name="peoples_age_agent_i_5949de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentskill",
            index=models.Index(
                fields=["skill_level"], name="peoples_age_skill_l_7a0df6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentskill",
            index=models.Index(
                fields=["certified"], name="peoples_age_certifi_7599d6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentskill",
            unique_together={("agent", "category", "tenant")},
        ),
        migrations.AddIndex(
            model_name="capability",
            index=models.Index(fields=["capscode"], name="capability_capscode_idx"),
        ),
        migrations.AddIndex(
            model_name="capability",
            index=models.Index(fields=["cfor"], name="capability_cfor_idx"),
        ),
        migrations.AddIndex(
            model_name="capability",
            index=models.Index(fields=["enable"], name="capability_enable_idx"),
        ),
        migrations.AddConstraint(
            model_name="capability",
            constraint=models.UniqueConstraint(
                fields=("capscode", "cfor", "client"),
                name="capability_capscode_cfor_client_uk",
            ),
        ),
        migrations.AddIndex(
            model_name="deviceregistration",
            index=models.Index(
                fields=["user", "is_trusted"], name="device_regi_user_id_df55a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceregistration",
            index=models.Index(
                fields=["last_seen"], name="device_regi_last_se_24e97a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceregistration",
            index=models.Index(
                fields=["is_blocked"], name="device_regi_is_bloc_b23330_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceriskevent",
            index=models.Index(
                fields=["device", "detected_at"], name="device_risk_device__f7a7ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceriskevent",
            index=models.Index(
                fields=["event_type"], name="device_risk_event_t_f3c25b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceriskevent",
            index=models.Index(
                fields=["resolved", "detected_at"],
                name="device_risk_resolve_a05237_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pgroup",
            index=models.Index(fields=["groupname"], name="pgroup_groupname_idx"),
        ),
        migrations.AddIndex(
            model_name="pgroup",
            index=models.Index(fields=["enable"], name="pgroup_enable_idx"),
        ),
        migrations.AddIndex(
            model_name="pgroup",
            index=models.Index(fields=["client", "bu"], name="pgroup_org_idx"),
        ),
        migrations.AddConstraint(
            model_name="pgroup",
            constraint=models.UniqueConstraint(
                fields=("groupname", "identifier", "client"),
                name="pgroup_groupname_identifier_client_uk",
            ),
        ),
        migrations.AddIndex(
            model_name="pgbelonging",
            index=models.Index(
                fields=["pgroup", "people"], name="pgbelonging_group_person_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pgbelonging",
            index=models.Index(fields=["isgrouplead"], name="pgbelonging_leader_idx"),
        ),
        migrations.AddIndex(
            model_name="pgbelonging",
            index=models.Index(fields=["assignsites"], name="pgbelonging_sites_idx"),
        ),
        migrations.AddConstraint(
            model_name="pgbelonging",
            constraint=models.UniqueConstraint(
                fields=("pgroup", "people", "assignsites", "client"),
                name="pgbelonging_pgroup_people_assignsites_client_uk",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "revoked"], name="user_sessio_user_id_b36834_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["device_fingerprint", "user"],
                name="user_sessio_device__2e6acb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["is_suspicious"], name="user_sessio_is_susp_b0dc96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["expires_at"], name="user_sessio_expires_85bda6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionactivitylog",
            index=models.Index(
                fields=["session", "timestamp"], name="session_act_session_c2c5cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionactivitylog",
            index=models.Index(
                fields=["activity_type", "timestamp"],
                name="session_act_activit_593965_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionactivitylog",
            index=models.Index(
                fields=["is_suspicious", "timestamp"],
                name="session_act_is_susp_cd15e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="peopleorganizational",
            index=models.Index(fields=["client", "bu"], name="org_client_bu_idx"),
        ),
        migrations.AddIndex(
            model_name="peopleorganizational",
            index=models.Index(fields=["department"], name="org_department_idx"),
        ),
        migrations.AddIndex(
            model_name="peopleorganizational",
            index=models.Index(fields=["designation"], name="org_designation_idx"),
        ),
        migrations.AddIndex(
            model_name="peopleorganizational",
            index=models.Index(fields=["reportto"], name="org_reportto_idx"),
        ),
        migrations.AddIndex(
            model_name="peopleprofile",
            index=models.Index(fields=["dateofbirth"], name="profile_dob_idx"),
        ),
        migrations.AddIndex(
            model_name="peopleprofile",
            index=models.Index(fields=["dateofjoin"], name="profile_join_idx"),
        ),
    ]
