# Generated by Django 5.2.1 on 2025-09-26 12:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field storing user capabilities and permissions for AI features', verbose_name='User Capabilities'),
        ),
    ]