# Generated by Django 5.2.7 on 2025-11-12 14:15

from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models import Q


def backfill_capabilities(apps, schema_editor):
    """Backfill all existing users with default capabilities."""
    People = apps.get_model('peoples', 'People')

    default_caps = {
        'canAccessPeople': True,
        'canAccessAttendance': True,
        'canAccessOperations': True,
        'canAccessHelpdesk': True,
        'canAccessJournal': True,
        'canAccessReports': False,
        'canAccessCalendar': True,
        'canAccessOnboarding': False,
        'canUseVoiceFeatures': False,
        'canUseVoiceBiometrics': False,
        'canApproveJobs': False,
        'canManageTeam': False,
        'canViewAnalytics': False,
    }

    batch_size = 1000
    users_to_update = People.objects.filter(
        Q(capabilities__isnull=True) | Q(capabilities={})
    )

    total = users_to_update.count()
    updated = 0

    print(f"Starting capability backfill for {total} users...")

    for user in users_to_update.iterator(chunk_size=batch_size):
        user.capabilities = default_caps
        user.save(update_fields=['capabilities'])
        updated += 1

        if updated % batch_size == 0:
            print(f"Updated {updated}/{total} users...")

    print(f"Backfill complete: {updated} users updated")


def reverse_backfill(apps, schema_editor):
    """No-op on reverse (we don't remove capabilities on rollback)."""
    print("Rollback: Capabilities backfill reversed (no-op)")


class Migration(migrations.Migration):

    dependencies = [
        ("peoples", "0001_initial"),
    ]

    operations = [
        # Add People fields
        migrations.AddField(
            model_name='people',
            name='first_login_completed',
            field=models.BooleanField(
                default=False,
                db_index=True,
                help_text='True if user has completed their first login session'
            ),
        ),
        migrations.AddField(
            model_name='people',
            name='onboarding_completed_at',
            field=models.DateTimeField(
                null=True,
                blank=True,
                db_index=True,
                help_text='Timestamp when user completed onboarding flow'
            ),
        ),
        migrations.AddField(
            model_name='people',
            name='onboarding_skipped',
            field=models.BooleanField(
                default=False,
                help_text='True if user explicitly skipped onboarding'
            ),
        ),

        # Add PeopleProfile field
        migrations.AddField(
            model_name='peopleprofile',
            name='profile_completion_percentage',
            field=models.IntegerField(
                default=0,
                validators=[MinValueValidator(0), MaxValueValidator(100)],
                help_text='Calculated profile completion percentage (0-100)'
            ),
        ),

        # Backfill capabilities for all existing users
        migrations.RunPython(backfill_capabilities, reverse_backfill),
    ]
