# Generated by Django 5.2.1 on 2025-09-15 06:58

from django.db import migrations
import logging

logger = logging.getLogger(__name__)

# Migration-specific exceptions for encryption operations
ENCRYPTION_EXCEPTIONS = (
    ValueError,  # Invalid encryption input
    TypeError,  # Type mismatch in encryption
    UnicodeDecodeError,  # Decoding errors
    UnicodeEncodeError,  # Encoding errors
    AttributeError,  # Missing encryption attributes
)


def encrypt_existing_data(apps, schema_editor):
    """
    Encrypt existing plain text email and phone number data.
    """
    People = apps.get_model('peoples', 'People')

    # Import encryption function
    try:
        from apps.core.utils_new.string_utils import encrypt
    except ImportError:
        logger.error("Cannot import encryption function")
        return

    updated_count = 0

    for person in People.objects.all():
        needs_update = False

        # Encrypt email if it's plain text
        if person.email and person.email != "":
            # Check if already encrypted (simple heuristic)
            if not (len(person.email) > 20 and person.email.replace('-', '').replace('_', '').isalnum()):
                try:
                    person.email = encrypt(person.email).decode('utf-8')
                    needs_update = True
                except ENCRYPTION_EXCEPTIONS as e:
                    logger.warning(f"Failed to encrypt email for person {person.id}: {e}", exc_info=True)

        # Encrypt phone number if it's plain text
        if person.mobno and person.mobno != "":
            # Check if already encrypted (simple heuristic)
            if not (len(person.mobno) > 20 and person.mobno.replace('-', '').replace('_', '').isalnum()):
                try:
                    person.mobno = encrypt(person.mobno).decode('utf-8')
                    needs_update = True
                except ENCRYPTION_EXCEPTIONS as e:
                    logger.warning(f"Failed to encrypt phone for person {person.id}: {e}", exc_info=True)

        if needs_update:
            person.save(update_fields=['email', 'mobno'])
            updated_count += 1

    logger.info(f"Encrypted data for {updated_count} people records")


def decrypt_existing_data(apps, schema_editor):
    """
    Reverse migration: decrypt data back to plain text.
    """
    People = apps.get_model('peoples', 'People')

    # Import decryption function
    try:
        from apps.core.utils_new.string_utils import decrypt
    except ImportError:
        logger.error("Cannot import decryption function")
        return

    updated_count = 0

    for person in People.objects.all():
        needs_update = False

        # Decrypt email if it's encrypted
        if person.email and len(person.email) > 20:
            try:
                person.email = decrypt(person.email)
                needs_update = True
            except ENCRYPTION_EXCEPTIONS as e:
                logger.warning(f"Failed to decrypt email for person {person.id}: {e}", exc_info=True)

        # Decrypt phone number if it's encrypted
        if person.mobno and len(person.mobno) > 20:
            try:
                person.mobno = decrypt(person.mobno)
                needs_update = True
            except ENCRYPTION_EXCEPTIONS as e:
                logger.warning(f"Failed to decrypt phone for person {person.id}: {e}", exc_info=True)

        if needs_update:
            person.save(update_fields=['email', 'mobno'])
            updated_count += 1

    logger.info(f"Decrypted data for {updated_count} people records")


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            encrypt_existing_data,
            decrypt_existing_data,
        ),
    ]
