"""
Django settings for intelliwiz_config project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import logging
from datetime import datetime
import getpass
import environ
from typing import Union, Optional, Dict, Any

env = environ.Env()
import dj_database_url

ENVPATH = os.path.join(os.path.abspath("intelliwiz_config/envs"))

# ENVIRONMENT CONFIGURATION - Change this line to switch between environments:
# For development (insecure, easy to use):
# ENV_FILE = '.env.dev'
# For development with security testing:
# ENV_FILE = '.env.dev.secure'
# For current production:
# ENV_FILE = '.env.prod'
# For secure production:
# ENV_FILE = '.env.prod.secure'

ENV_FILE = ".env.dev.secure"  # <-- Change this line to switch environments
environ.Env.read_env(os.path.join(ENVPATH, ENV_FILE), overwrite=True)


HOST = env("HOST")
# GOOGLE MAP API KEY...
GOOGLE_MAP_SECRET_KEY = env("GOOGLE_MAP_SECRET_KEY")


# BULK IMPORT API KEY...
BULK_IMPORT_GOOGLE_DRIVE_API_KEY = env("BULK_IMPORT_GOOGLE_DRIVE_API_KEY")


def check_path(path: Union[str, Path]) -> bool:
    path = Path(path)
    if not os.path.exists(path):
        path.mkdir(parents=True, exist_ok=True)
    return bool(os.access(path, os.R_OK) and os.access(path, os.W_OK))


# Build paths inside the project like this: BASE_DIR / 'subdir'.p
BASE_DIR = Path(__file__).resolve().parent.parent


# Email Verification CONF...
def verified_callback(user: Any) -> None:
    # When multiple users have the same email, verify all of them
    from apps.peoples.models import People
    import logging

    logger = logging.getLogger("django")

    # Get all users with this email
    users_with_email = People.objects.filter(email=user.email)
    logger.info(
        f"[VERIFY] Found {users_with_email.count()} users with email {user.email}"
    )

    # Verify all users with this email
    for u in users_with_email:
        if not u.isverified:
            logger.info(f"[VERIFY] Verifying user ID {u.id}, loginid: {u.loginid}")
            u.isverified = True
            u.is_staff = True
            u.save()

    # Also update the passed user object
    user.isverified = True
    user.is_staff = True
    user.save()


EMAIL_TOKEN_LIFE = 60**2
EMAIL_MAIL_TOKEN_LIFE = 60**2
EMAIL_VERIFIED_CALLBACK = verified_callback
EMAIL_MAIL_CALLBACK = verified_callback
EMAIL_FROM_ADDRESS = env("EMAIL_FROM_ADDRESS")
EMAIL_MAIL_SUBJECT = "Confirm your email"
EMAIL_MAIL_HTML = "email.html"
EMAIL_MAIL_PLAIN = "mail_body.txt"
CUSTOM_SALT = env("CUSTOM_SALT", default="django-email-verification-salt")

EMAIL_MAIL_PAGE_TEMPLATE = "email_verify.html"
EMAIL_PAGE_DOMAIN = env("EMAIL_PAGE_DOMAIN")
EMAIL_MULTI_USER = True  # optional (defaults to False)

# SECURITY WARNING: keep the secret key used in production secret!
# CRITICAL: Apply Rule 4 validation - Secure Secret Management
from apps.core.validation import validate_secret_key, validate_encryption_key, validate_admin_password

# Validate all critical secrets at startup - fail fast if compromised
try:
    SECRET_KEY = validate_secret_key("SECRET_KEY", env("SECRET_KEY"))
    ENCRYPT_KEY = validate_encryption_key("ENCRYPT_KEY", env("ENCRYPT_KEY"))
    SUPERADMIN_PASSWORD = validate_admin_password("SUPERADMIN_PASSWORD", env("SUPERADMIN_PASSWORD"))
except Exception as e:
    import sys
    print(f"\n🚨 CRITICAL SECURITY ERROR: {e}")
    if hasattr(e, 'remediation') and e.remediation:
        print(f"🔧 REMEDIATION: {e.remediation}")
    print("\n❌ Application startup aborted due to invalid secrets.")
    print("Fix the above issues and restart the application.")
    sys.exit(1)
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# Production security validation
if 'prod' in ENV_FILE.lower() and DEBUG:
    raise ValueError("DEBUG must be False in production environments")

USE_L10N = False
ALLOWED_HOSTS = [
    "django5.youtility.in",
    "127.0.0.1:8005",
    "127.0.0.1",
    "localhost",
    "192.168.1.243",
]

# SENTRY CONFIGURATION - REMOVED

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    # third_party_apps
    "graphene_django",
    "graphene_gis",
    "django_email_verification",
    "import_export",
    "django_extensions",
    "django_select2",
    "django_filters",
    "graphql_jwt.refresh_token.apps.RefreshTokenConfig",
    "rest_framework",
    "django_celery_beat",
    "django_celery_results",
    "corsheaders",
    # WebSocket and real-time communication
    "channels",
    "daphne",
    # local apps
    'apps.core',
    'apps.peoples',
    'apps.onboarding',
    'apps.onboarding_api',  # Conversational Onboarding API (Phase 1 MVP)
    'apps.tenants',
    'apps.attendance',
    'apps.activity',
    'apps.schedhuler',
    'apps.reminder',
    'apps.reports',
    'apps.service',
    'apps.y_helpdesk',
    'apps.work_order_management',
    'apps.mqtt',
    'apps.face_recognition',

    # Journal & Wellness System (Complete Integration)
    'apps.journal',     # Personal journal with privacy controls and wellbeing tracking
    'apps.wellness',    # Evidence-based wellness education with ML personalization

    # Stream Testbench System
    'apps.streamlab',   # Stream testing with PII protection and anomaly detection
    'apps.issue_tracker',  # Issue Knowledge Base with anomaly detection and fix suggestions
    'apps.ai_testing',  # AI-Powered Intelligent Testing Platform (Phase 3)

    # third-party apps
    "django_cleanup.apps.CleanupConfig",
]

# Add debug toolbar only in DEBUG mode
if DEBUG:
    INSTALLED_APPS.append("debug_toolbar")

# Add AI Mentor system only in development with explicit enablement
if DEBUG and os.environ.get('MENTOR_ENABLED') == '1':
    INSTALLED_APPS.append("apps.mentor")
    INSTALLED_APPS.append("apps.mentor_api")
    print("🤖 AI Mentor system enabled - Development mode only")

    # AI Mentor LLM Configuration
    MENTOR_LLM_CONFIG = {
        'default_provider': env('MENTOR_DEFAULT_LLM', default='mock'),
        'maker_provider': env('MENTOR_MAKER_LLM', default='mock'),
        'checker_provider': env('MENTOR_CHECKER_LLM', default='mock'),
        'providers': {
            'openai': {
                'name': 'openai',
                'api_key': env('OPENAI_API_KEY', default=''),
                'model': env('OPENAI_MODEL', default='gpt-4'),
                'base_url': env('OPENAI_BASE_URL', default='https://api.openai.com/v1')
            },
            'anthropic': {
                'name': 'anthropic',
                'api_key': env('ANTHROPIC_API_KEY', default=''),
                'model': env('ANTHROPIC_MODEL', default='claude-3-sonnet-20240229')
            },
            'mock': {
                'name': 'mock',
                'responses': {}
            }
        }
    }

MIDDLEWARE = [
    #'apps.tenants.middlewares.TenantMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "apps.core.error_handling.CorrelationIDMiddleware",
    "apps.core.sql_security.SQLInjectionProtectionMiddleware",
    "apps.core.xss_protection.XSSProtectionMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "apps.onboarding.middlewares.TimezoneMiddleware",
    "apps.core.middleware.csp_nonce.CSPNonceMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.onboarding_api.middleware.OnboardingAPIMiddleware",
    "apps.onboarding_api.middleware.OnboardingAuditMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'apps.core.xss_protection.CSRFHeaderMiddleware',
    "apps.core.error_handling.GlobalExceptionMiddleware",
]

# Add debug toolbar middleware only in DEBUG mode
if DEBUG:
    MIDDLEWARE.insert(2, "debug_toolbar.middleware.DebugToolbarMiddleware")

# CORS Configuration - Secure CORS settings
CORS_ALLOWED_ORIGINS = [
    "https://django5.youtility.in",
]

# Add localhost origins only in DEBUG mode
if DEBUG:
    CORS_ALLOWED_ORIGINS.extend(
        [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "http://localhost:8000",
            "http://127.0.0.1:8000",
        ]
    )

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://\w+\.youtility\.in$",  # Allow subdomains of youtility.in
]

CORS_ALLOW_CREDENTIALS = True  # Allow cookies to be included in CORS requests

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_EXPOSE_HEADERS = [
    "Content-Type",
    "X-CSRFToken",
]

CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# customize the message tags to match Bootstrap's CSS classes
from django.contrib.messages import constants as message_constants

MESSAGE_TAGS = {
    message_constants.DEBUG: "alert-info",
    message_constants.INFO: "alert-info",
    message_constants.SUCCESS: "alert-success",
    message_constants.WARNING: "alert-warning",
    message_constants.ERROR: "alert-danger",
}

ROOT_URLCONF = "intelliwiz_config.urls"

JINJA_TEMPLATES = os.path.join(BASE_DIR, "frontend/templates")
import jinja2

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "apps.peoples.context_processors.app_settings",
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
        },
    },
    # jinja2 configuration
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "DIRS": [JINJA_TEMPLATES],
        "APP_DIRS": True,
        "OPTIONS": {
            "extensions": [
                "jinja2.ext.loopcontrols",
            ],
            "autoescape": False,
            "auto_reload": True,
            "undefined": jinja2.StrictUndefined,
            "environment": "intelliwiz_config.jinja.env.JinjaEnvironment",
            "context_processors": [
                "apps.peoples.context_processors.app_settings",
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
        },
    },
]

from intelliwiz_config.settings_ia import apply_ia_settings

apply_ia_settings(locals())

WSGI_APPLICATION = "intelliwiz_config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/# databases
"""
NOTE: Client bucode should match the database alias name.
"""

# Legacy database configuration - REMOVED for security
# All database credentials are now configured via environment variables
# DATABASE CONFIGURATION - Environment driven
DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "USER": env("DBUSER"),
        "NAME": env("DBNAME"),
        "PASSWORD": env("DBPASS"),
        "HOST": env("DBHOST"),
        "PORT": "5432",
        "CONN_MAX_AGE": 0,
    }
}


# SELECT2 CONF...
SELECT2_CACHE_BACKEND = "select2"
SELECT2_JS = ""
SELECT2_CSS = ""
SELECT2_I18N_PATH = "assets/plugins/custom/select2-4.x/js/i18n"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": "youtility4",
    },
    # Removed redis_session_cache - now using pure PostgreSQL sessions
    "select2": {
        "BACKEND": "apps.core.cache.materialized_view_select2.MaterializedViewSelect2Cache",
        "LOCATION": "",  # PostgreSQL connection used
        "OPTIONS": {
            "MAX_ENTRIES": 10000,
            "CULL_FREQUENCY": 3,
        },
        "TIMEOUT": 900,  # 15 minutes default timeout
        "KEY_PREFIX": "select2_mv",
    },
}

# CHANNEL LAYERS - WebSocket support with Redis DB 2 for isolation
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": ["redis://127.0.0.1:6379/2"],  # DB 2 for isolation from cache
            "capacity": 10000,  # Number of messages to store in channel
            "expiry": 60,       # How long to store messages (seconds)
            "group_expiry": 86400,  # How long to remember group memberships (24h)
        },
    },
}

# ASGI Configuration
ASGI_APPLICATION = "intelliwiz_config.asgi.application"

# SESSION SETTINGS - PostgreSQL-first approach (MD approved for 20ms trade-off)
# Optimized for security-performance balance

SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Pure PostgreSQL sessions
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # close the session when user closes the browser
SESSION_COOKIE_AGE = 8 * 60 * 60  # 8 hours - balance between security and usability
SESSION_SAVE_EVERY_REQUEST = False  # Performance optimization - only save when session data changes

# PostgreSQL session optimization
DATABASE_SESSION_OPTIMIZATIONS = {
    "USE_INDEX_ON_SESSION_KEY": True,
    "USE_INDEX_ON_EXPIRE_DATE": True,
    "ENABLE_SESSION_CLEANUP": True,
}



# PostgreSQL Task Queue Configuration (replacement for Celery)
POSTGRESQL_TASK_QUEUE = {
    "DEFAULT_QUEUE": "default",
    "MAX_RETRIES": 3,
    "RETRY_DELAY": 60,
    "WORKER_CONCURRENCY": 4,
    "HEARTBEAT_INTERVAL": 30,
    "CLEANUP_INTERVAL": 86400,  # 24 hours
    "QUEUES": ["default", "high_priority", "email", "reports", "mqtt", "maintenance"],
}


# Cache time to live is 15 minutes.
CACHE_TTL = 60 * 1

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/# auth-password-validators

# PASSWORD VALIDATORS - ENABLED FOR SECURITY
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'email', 'first_name', 'last_name'),
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

USE_I18N = True

USE_TZ = True
TIME_ZONE = "UTC"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/# default-auto-field

# Media Files CONF..
MEDIA_ROOT = env("MEDIA_ROOT")
if not check_path(MEDIA_ROOT):
    raise ValueError(f"`{MEDIA_ROOT}` not readable and writable")

MEDIA_URL = "/youtility4_media/"
# DATETIME INPUTS CONF...
DATETIME_INPUT_FORMATS = [
    "%d-%b-%Y %H:%M:%S",  # 22-May-1998 13:01#
    "%Y-%m-%d %H:%M:%S",  # 1998-05-18 13:01:00
    "%d-%b-%Y %H:%M",
]
DATE_INPUT_FORMATS = [
    "%d-%b-%Y",
    "%d/%b/%Y",
    "%d/%m/%Y",
    "%Y-%m-%d",
    "%Y/%m/%d",
    "%Y-%m-%dT%H:%M:%S%z",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = env("STATIC_ROOT")

STATICFILES_DIRS = [os.path.join(BASE_DIR, "frontend/static")]


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/# default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DATABASE_ROUTERS = ["apps.tenants.middlewares.TenantDbRouter"]

# Media Files


AUTH_USER_MODEL = "peoples.People"
# AUTHENTICATION BACKENDS CONF...
AUTHENTICATION_BACKENDS = [
    "graphql_jwt.backends.JSONWebTokenBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# GRAPHENE CONF...
GRAPHENE = {
    # ...
    "ATOMIC_MUTATIONS": True,
    "SCHEMA": "apps.service.schema.schema",
    "MIDDLEWARE": [
        "graphql_jwt.middleware.JSONWebTokenMiddleware",
    ],
}

# GRAPHQL JWT CONF...
from datetime import timedelta

GRAPHQL_JWT = {
    "JWT_VERIFY_EXPIRATION": False,
    "JWT_REFRESH_EXPIRATION_DELTA": timedelta(days=2),
    # optional
    "JWT_LONG_RUNNING_REFRESH_TOKEN": True,
}

ADMINS = [
    ("wed_dev", "satyam.warghat@youtility.in"),
    ("wed_dev", "pankaj.pal@youtility.in"),
    ("wed_dev", "manohar.lagishetty@youtility.in"),
    ("business_manger", "namrata.shahid@youtility.in"),
    ("business_manager", "ashish.mhashilkar@youtility.in"),
]

username = getpass.getuser()

# username = "satyam"

LOGGER_PATH = f"/home/redmine/DJANGO5"

# LOGGER_PATH = '/app/logs'

import logging.config

LOGGING_CONFIG = None
# Optimized logging configuration with reduced overlap and better performance
LOGGING_CONFIG_ = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "detailed": {
            "format": "%(asctime)s | %(name)s | %(levelname)s | %(funcName)s:%(lineno)d | %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S"
        },
        "simple": {
            "format": "%(levelname)s | %(name)s | %(message)s"
        },
        "coloured": {
            "()": "colorlog.ColoredFormatter",
            "format": "%(log_color)s%(asctime)s | %(levelname)-8s | %(name)s | %(funcName)s | %(message)s",
            "datefmt": "%H:%M:%S"
        },
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(name)s %(levelname)s %(funcName)s %(lineno)d %(message)s"
        }
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        # Console handler - optimized for development
        "console": {
            "level": "INFO",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "coloured",
            "stream": "ext://sys.stdout",
        },

        # Production console handler - minimal output
        "console_prod": {
            "level": "WARNING",
            "filters": ["require_debug_false"],
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },

        # Consolidated application logs - replaces multiple overlapping handlers
        "app_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": f"{LOGGER_PATH}/youtility4_logs/application.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 30,  # Keep 30 days
            "formatter": "detailed",
            "encoding": "utf-8",
        },

        # Error logs - only ERROR and CRITICAL
        "error_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": f"{LOGGER_PATH}/youtility4_logs/errors.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 60,  # Keep errors longer
            "formatter": "detailed",
            "level": "ERROR",
            "encoding": "utf-8",
        },

        # Security logs - separate and longer retention
        "security_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": f"{LOGGER_PATH}/youtility4_logs/security.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 90,  # Keep security logs for 90 days
            "formatter": "detailed",
            "level": "INFO",
            "encoding": "utf-8",
        },

        # High-volume specialized logs with size-based rotation
        "background_tasks": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": f"{LOGGER_PATH}/youtility4_logs/background_tasks.log",
            "maxBytes": 50*1024*1024,  # 50MB for high-volume tasks
            "backupCount": 5,
            "formatter": "detailed",
            "encoding": "utf-8",
        },

        "database_queries": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": f"{LOGGER_PATH}/youtility4_logs/db_queries.log",
            "maxBytes": 100*1024*1024,  # 100MB for database logs
            "backupCount": 3,
            "formatter": "detailed",
            "level": "DEBUG",
            "encoding": "utf-8",
        },

        # Email notifications for critical issues
        "mail_admins": {
            "level": "CRITICAL",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
            "formatter": "detailed",
            "include_html": True,
        },

        # Null handler for noisy loggers
        "null": {
            "class": "logging.NullHandler",
        },
    },
    "loggers": {
        # Root logger - minimal console output
        "": {
            "handlers": ["console", "console_prod"],
            "level": "INFO",
            "propagate": False,
        },

        # Django framework logs
        "django": {
            "handlers": ["app_file", "console"],
            "level": "INFO",
            "propagate": False,
        },

        # Django database queries - separate handler for performance analysis
        "django.db.backends": {
            "handlers": ["database_queries"],
            "level": "DEBUG",
            "propagate": False,
        },

        # Security-related logs
        "security": {
            "handlers": ["security_file", "console", "mail_admins"],
            "level": "INFO",
            "propagate": False,
        },

        "security.csp": {
            "handlers": ["security_file"],
            "level": "INFO",
            "propagate": False,
        },

        # Application-specific loggers
        "background_tasks": {
            "handlers": ["background_tasks", "error_file"],
            "level": "INFO",
            "propagate": False,
        },

        "apps": {
            "handlers": ["app_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },

        # Legacy loggers mapped to new handlers
        "mobile_service_log": {
            "handlers": ["app_file", "error_file", "mail_admins"],
            "level": "INFO",
            "propagate": False,
        },

        "message_q": {
            "handlers": ["background_tasks", "error_file"],
            "level": "INFO",
            "propagate": False,
        },

        "tracking": {
            "handlers": ["background_tasks", "error_file"],
            "level": "INFO",
            "propagate": False,
        },

        "reports": {
            "handlers": ["app_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },

        # Noisy third-party loggers - suppress unless important
        "requests": {
            "handlers": ["null"],
            "level": "WARNING",
            "propagate": False,
        },

        "urllib3": {
            "handlers": ["null"],
            "level": "WARNING",
            "propagate": False,
        },

        # Onboarding API specialized loggers
        "audit": {
            "handlers": ["security_file", "app_file"],
            "level": "INFO",
            "propagate": False,
        },

        "metrics": {
            "handlers": ["app_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


def check_and_create_log_paths():
    """
    Ensure log directory exists and create if necessary.
    Optimized version that handles directory creation properly.
    """
    import os

    log_dir = f"{LOGGER_PATH}/youtility4_logs"

    try:
        # Create log directory if it doesn't exist
        os.makedirs(log_dir, exist_ok=True)

        # Set appropriate permissions for log files
        if hasattr(os, 'chmod'):
            os.chmod(log_dir, 0o755)

    except Exception as e:
        print(f"Warning: Could not prepare log directory {log_dir}: {e}")
        # Fallback to current directory for logs
        for handler_name, handler_config in LOGGING_CONFIG_["handlers"].items():
            if isinstance(handler_config, dict) and "filename" in handler_config:
                # Update log paths to current directory if original path fails
                original_path = handler_config["filename"]
                filename = os.path.basename(original_path)
                LOGGING_CONFIG_["handlers"][handler_name]["filename"] = f"./{filename}"

# Setup logging with error handling
try:
    check_and_create_log_paths()
    logging.config.dictConfig(LOGGING_CONFIG_)
except Exception as e:
    print(f"Error configuring logging: {e}")
    # Use basic logging as fallback
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s | %(levelname)s | %(name)s | %(message)s'
    )

# LOGIN URL NAME...
LOGIN_URL = "login"


# DJANGO_IMPORT_EXPORT CONF...
IMPORT_EXPORT_USE_TRANSACTIONS = True

# DJANGO-EXTENSIONS CONF...
SHELL_PLUS_PRINT_SQL = True
GRAPH_MODELS = {
    "all_applications": True,
    "group_models": True,
}


# For Django Email Backend - AWS SES via SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")

# AWS SES SMTP Configuration
EMAIL_HOST = "email-smtp.us-east-1.amazonaws.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("AWS_SES_SMTP_USER")
EMAIL_HOST_PASSWORD = env("AWS_SES_SMTP_PASSWORD")

# For backward compatibility - many files use EMAIL_HOST_USER as sender email
# This is the actual email address that will be used as the sender
EMAIL_FROM_ADDRESS = env("DEFAULT_FROM_EMAIL")
DJANGO_SETTINGS_MODULE = "intelliwiz_config.settings"


# DJANGO TAGGIT CONF...
TAGGIT_CASE_INSENSITIVE = True


# SECURITY SETTINGS - Production-grade security configuration
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)

# CSP (Content Security Policy) Settings
CSP_ENABLE_NONCE = True  # Enable nonce-based CSP for secure inline execution
CSP_NONCE_LENGTH = 32
CSP_REPORT_ONLY = False  # Set to True for testing
CSP_REPORT_URI = "/api/csp-report/"
CSP_STORE_VIOLATIONS = True

# Enhanced CSP Monitoring Configuration
CSP_MONITORING = {
    'ENABLE_ALERTING': True,
    'ALERT_THRESHOLD_PER_HOUR': 10,  # Alert if more than 10 violations per hour
    'ALERT_THRESHOLD_UNIQUE_VIOLATIONS': 5,  # Alert for 5+ unique violation sources
    'ENABLE_DAILY_REPORTS': True,
    'MAX_VIOLATION_AGE_DAYS': 30,  # Cleanup violations older than 30 days
    'BLOCKED_USER_AGENTS': [  # Don't log violations from these (bots, crawlers)
        'googlebot', 'bingbot', 'slurp', 'duckduckbot', 'baiduspider',
        'yandexbot', 'facebookexternalhit', 'twitterbot'
    ]
}

# CSP Directives - Secure nonce-based approach
# Using CSPNonceMiddleware for secure inline script/style execution
# In production, convert all inline styles to external stylesheets or use nonces
CSP_DIRECTIVES = {
    "default-src": ["'self'"],
    "script-src": [
        "'self'",
        "https://fonts.googleapis.com",
        "https://ajax.googleapis.com",
        "https://cdn.jsdelivr.net",
        "https://cdnjs.cloudflare.com",
    ],
    "style-src": [
        "'self'",
        "https://fonts.googleapis.com",
        "https://cdn.jsdelivr.net",
        "https://cdnjs.cloudflare.com",
    ],
    "img-src": ["'self'", "data:", "https:", "blob:"],
    "font-src": [
        "'self'",
        "data:",
        "https://fonts.googleapis.com",
        "https://fonts.gstatic.com",
        "https://cdn.jsdelivr.net",
        "https://cdnjs.cloudflare.com",
    ],
    "connect-src": ["'self'", "https:"],
    "frame-ancestors": ["'none'"],
    "base-uri": ["'self'"],
    "form-action": ["'self'"],
}

# API Authentication Settings
ENABLE_API_AUTH = True
API_AUTH_PATHS = ["/api/", "/graphql/"]
API_REQUIRE_SIGNING = False  # Set to True for high-security APIs

# Conversational Onboarding Settings (Phase 1 MVP - Feature Flag)
ENABLE_CONVERSATIONAL_ONBOARDING = env.bool('ENABLE_CONVERSATIONAL_ONBOARDING', default=False)

# Phase 2 Enhanced Features (Feature Flags)
# Support both environment variable names for backward compatibility
ENABLE_CONVERSATIONAL_ONBOARDING_CHECKER = (
    env.bool('ENABLE_CONVERSATIONAL_ONBOARDING_CHECKER', default=False) or
    env.bool('ENABLE_LLM_CHECKER', default=False)
)
ENABLE_ONBOARDING_KB = env.bool('ENABLE_ONBOARDING_KB', default=False)
ENABLE_ONBOARDING_SSE = env.bool('ENABLE_ONBOARDING_SSE', default=False)

# Consensus Engine Configuration
ONBOARDING_APPROVE_THRESHOLD = env.float('ONBOARDING_APPROVE_THRESHOLD', default=0.7)
ONBOARDING_ESCALATE_THRESHOLD = env.float('ONBOARDING_ESCALATE_THRESHOLD', default=0.4)

# Translation Configuration
TRANSLATION_PROVIDER = env('TRANSLATION_PROVIDER', default='noop')  # 'google', 'noop'
ENABLE_TRANSLATION_CACHING = env.bool('ENABLE_TRANSLATION_CACHING', default=True)
TRANSLATION_CACHE_TIMEOUT = env.int('TRANSLATION_CACHE_TIMEOUT', default=3600)
TRANSLATION_DAILY_CHAR_LIMIT = env.int('TRANSLATION_DAILY_CHAR_LIMIT', default=100000)
TRANSLATION_REQUEST_CHAR_LIMIT = env.int('TRANSLATION_REQUEST_CHAR_LIMIT', default=5000)

# Google Translate API Configuration (when provider=google)
GOOGLE_TRANSLATE_API_KEY = env('GOOGLE_TRANSLATE_API_KEY', default='')
GOOGLE_CLOUD_PROJECT_ID = env('GOOGLE_CLOUD_PROJECT_ID', default='')

# Knowledge Base Configuration
EMBEDDING_CACHE_TIMEOUT = env.int('EMBEDDING_CACHE_TIMEOUT', default=3600)
KNOWLEDGE_CHUNK_SIZE = env.int('KNOWLEDGE_CHUNK_SIZE', default=1000)
KNOWLEDGE_CHUNK_OVERLAP = env.int('KNOWLEDGE_CHUNK_OVERLAP', default=200)

# Production-grade Knowledge Base Settings
ONBOARDING_VECTOR_BACKEND = env('ONBOARDING_VECTOR_BACKEND', default='postgres_array')  # postgres_array|pgvector|chroma
KB_MAX_CHUNK_TOKENS = env.int('KB_MAX_CHUNK_TOKENS', default=512)
KB_TOP_K = env.int('KB_TOP_K', default=10)
KB_DAILY_EMBED_LIMIT = env.int('KB_DAILY_EMBED_LIMIT', default=100000)  # chars per tenant per day
KB_MAX_FILE_SIZE = env.int('KB_MAX_FILE_SIZE', default=50 * 1024 * 1024)  # 50MB
KB_MAX_TEXT_LENGTH = env.int('KB_MAX_TEXT_LENGTH', default=1_000_000)  # 1MB of text
KB_FETCH_TIMEOUT = env.int('KB_FETCH_TIMEOUT', default=30)  # seconds
KB_RATE_LIMIT_DELAY = env.float('KB_RATE_LIMIT_DELAY', default=1.0)  # seconds between requests

# Knowledge Base Security Settings
KB_ALLOWED_SOURCES = [
    'iso.org',
    'nist.gov',
    'asis.org',
    'wikipedia.org',  # For testing
    'example.com',    # For testing
    'docs.python.org',
    'developer.mozilla.org',
    'djangoproject.com',
    'github.com'
]

# Override with environment variable if provided
KB_ALLOWED_SOURCES_ENV = env('KB_ALLOWED_SOURCES', default='')
if KB_ALLOWED_SOURCES_ENV:
    KB_ALLOWED_SOURCES = [domain.strip() for domain in KB_ALLOWED_SOURCES_ENV.split(',') if domain.strip()]

# ChromaDB Configuration (when ONBOARDING_VECTOR_BACKEND=chroma)
CHROMA_HOST = env('CHROMA_HOST', default='localhost')
CHROMA_PORT = env.int('CHROMA_PORT', default=8000)
CHROMA_COLLECTION_NAME = env('CHROMA_COLLECTION_NAME', default='intelliwiz_knowledge')

# =============================================================================
# PRODUCTION EMBEDDING SERVICE CONFIGURATION
# =============================================================================

# Enable production-grade embedding service (with real LLM providers)
ENABLE_PRODUCTION_EMBEDDINGS = env.bool('ENABLE_PRODUCTION_EMBEDDINGS', default=False)

# Embedding provider configurations
EMBEDDING_PROVIDERS = {
    'openai': {
        'api_key': env('OPENAI_API_KEY', default=''),
        'model': env('OPENAI_EMBEDDING_MODEL', default='text-embedding-3-small'),
        'max_tokens': env.int('OPENAI_EMBEDDING_MAX_TOKENS', default=8192),
        'cost_per_token': env.float('OPENAI_EMBEDDING_COST_PER_TOKEN', default=0.00002),  # text-embedding-3-small cost
        'daily_budget_cents': env.int('OPENAI_EMBEDDING_DAILY_BUDGET_CENTS', default=1000),  # $10/day
        'timeout_seconds': env.int('OPENAI_EMBEDDING_TIMEOUT', default=30),
        'retry_attempts': env.int('OPENAI_EMBEDDING_RETRIES', default=3)
    },
    'azure': {
        'api_key': env('AZURE_OPENAI_API_KEY', default=''),
        'model': env('AZURE_OPENAI_EMBEDDING_MODEL', default='text-embedding-3-small'),
        'max_tokens': env.int('AZURE_OPENAI_EMBEDDING_MAX_TOKENS', default=8192),
        'cost_per_token': env.float('AZURE_OPENAI_EMBEDDING_COST_PER_TOKEN', default=0.00002),
        'daily_budget_cents': env.int('AZURE_OPENAI_EMBEDDING_DAILY_BUDGET_CENTS', default=750),  # $7.50/day
        'timeout_seconds': env.int('AZURE_OPENAI_EMBEDDING_TIMEOUT', default=30),
        'retry_attempts': env.int('AZURE_OPENAI_EMBEDDING_RETRIES', default=3)
    },
    'local': {
        'api_key': '',  # Not needed for local models
        'model': env('LOCAL_EMBEDDING_MODEL', default='all-MiniLM-L6-v2'),  # Fast, good quality
        'max_tokens': env.int('LOCAL_EMBEDDING_MAX_TOKENS', default=8192),
        'cost_per_token': 0.0,  # Local models are free
        'daily_budget_cents': 0,  # No budget limit for local
        'timeout_seconds': env.int('LOCAL_EMBEDDING_TIMEOUT', default=60),  # Local can be slower
        'retry_attempts': env.int('LOCAL_EMBEDDING_RETRIES', default=2)
    }
}

# Provider fallback order (first is preferred)
EMBEDDING_FALLBACK_ORDER = env.list('EMBEDDING_FALLBACK_ORDER', default=['openai', 'azure', 'local'])

# Azure OpenAI specific settings (if using azure provider)
AZURE_OPENAI_ENDPOINT = env('AZURE_OPENAI_ENDPOINT', default='')
AZURE_OPENAI_API_VERSION = env('AZURE_OPENAI_API_VERSION', default='2024-02-01')

# Global embedding settings
EMBEDDING_CACHE_TIMEOUT = env.int('EMBEDDING_CACHE_TIMEOUT', default=86400)  # 24 hours
EMBEDDING_MAX_BATCH_SIZE = env.int('EMBEDDING_MAX_BATCH_SIZE', default=100)
EMBEDDING_RATE_LIMIT_PER_MINUTE = env.int('EMBEDDING_RATE_LIMIT_PER_MINUTE', default=60)

# Cost control settings
EMBEDDING_DAILY_SPEND_ALERT_CENTS = env.int('EMBEDDING_DAILY_SPEND_ALERT_CENTS', default=500)  # Alert at $5/day
EMBEDDING_MONTHLY_SPEND_LIMIT_CENTS = env.int('EMBEDDING_MONTHLY_SPEND_LIMIT_CENTS', default=10000)  # $100/month limit

# =============================================================================
# NOTIFICATION SERVICE CONFIGURATION
# =============================================================================

# Enable webhook notifications for approvals and escalations
ENABLE_WEBHOOK_NOTIFICATIONS = env.bool('ENABLE_WEBHOOK_NOTIFICATIONS', default=False)

# Notification provider configurations
NOTIFICATION_PROVIDERS = {
    'slack': {
        'type': 'slack',
        'webhook_url': env('SLACK_WEBHOOK_URL', default=''),
        'channel': env('SLACK_CHANNEL', default='#onboarding-alerts'),
        'username': env('SLACK_USERNAME', default='IntelliWiz AI'),
        'timeout_seconds': env.int('SLACK_TIMEOUT', default=10)
    },
    'discord': {
        'type': 'discord',
        'webhook_url': env('DISCORD_WEBHOOK_URL', default=''),
        'username': env('DISCORD_USERNAME', default='IntelliWiz AI'),
        'timeout_seconds': env.int('DISCORD_TIMEOUT', default=10)
    },
    'email': {
        'type': 'email',
        'recipients': env.list('NOTIFICATION_EMAIL_RECIPIENTS', default=[]),
        'from_email': env('NOTIFICATION_FROM_EMAIL', default=DEFAULT_FROM_EMAIL),
        'template_dir': 'onboarding/notifications/'
    },
    'webhook_alerts': {
        'type': 'webhook',
        'webhook_url': env('CUSTOM_WEBHOOK_URL', default=''),
        'secret': env('CUSTOM_WEBHOOK_SECRET', default=''),
        'auth_header': env('CUSTOM_WEBHOOK_AUTH', default=''),
        'timeout_seconds': env.int('CUSTOM_WEBHOOK_TIMEOUT', default=10),
        'headers': {
            'User-Agent': 'IntelliWiz-Notifications/1.0'
        }
    }
}

# Notification routing configuration (which providers handle which events)
NOTIFICATION_ROUTING = {
    'approval_pending': env.list('NOTIFICATION_APPROVAL_PENDING_PROVIDERS', default=['slack', 'email']),
    'approval_granted': env.list('NOTIFICATION_APPROVAL_GRANTED_PROVIDERS', default=['slack']),
    'approval_rejected': env.list('NOTIFICATION_APPROVAL_REJECTED_PROVIDERS', default=['slack', 'email']),
    'escalation_created': env.list('NOTIFICATION_ESCALATION_PROVIDERS', default=['slack', 'discord', 'email']),
    'changeset_applied': env.list('NOTIFICATION_CHANGESET_APPLIED_PROVIDERS', default=['slack']),
    'changeset_rollback': env.list('NOTIFICATION_CHANGESET_ROLLBACK_PROVIDERS', default=['slack', 'email']),
    'system_error': env.list('NOTIFICATION_SYSTEM_ERROR_PROVIDERS', default=['email', 'webhook_alerts'])
}

# =============================================================================
# PRODUCTION LLM SERVICE CONFIGURATION
# =============================================================================

# Enable production-grade LLM service (with real AI providers)
ENABLE_PRODUCTION_LLM = env.bool('ENABLE_PRODUCTION_LLM', default=False)

# LLM provider configurations
LLM_PROVIDERS = {
    'openai': {
        'api_key': env('OPENAI_API_KEY', default=''),
        'model': env('OPENAI_LLM_MODEL', default='gpt-3.5-turbo'),
        'max_tokens': env.int('OPENAI_LLM_MAX_TOKENS', default=2048),
        'cost_per_input_token': env.float('OPENAI_LLM_COST_PER_INPUT_TOKEN', default=0.0015),
        'cost_per_output_token': env.float('OPENAI_LLM_COST_PER_OUTPUT_TOKEN', default=0.002),
        'daily_budget_cents': env.int('OPENAI_LLM_DAILY_BUDGET_CENTS', default=2000),  # $20/day
        'timeout_seconds': env.int('OPENAI_LLM_TIMEOUT', default=30),
        'retry_attempts': env.int('OPENAI_LLM_RETRIES', default=3)
    },
    'anthropic': {
        'api_key': env('ANTHROPIC_API_KEY', default=''),
        'model': env('ANTHROPIC_LLM_MODEL', default='claude-3-sonnet-20240229'),
        'max_tokens': env.int('ANTHROPIC_LLM_MAX_TOKENS', default=2048),
        'cost_per_input_token': env.float('ANTHROPIC_LLM_COST_PER_INPUT_TOKEN', default=0.003),
        'cost_per_output_token': env.float('ANTHROPIC_LLM_COST_PER_OUTPUT_TOKEN', default=0.015),
        'daily_budget_cents': env.int('ANTHROPIC_LLM_DAILY_BUDGET_CENTS', default=1500),  # $15/day
        'timeout_seconds': env.int('ANTHROPIC_LLM_TIMEOUT', default=30),
        'retry_attempts': env.int('ANTHROPIC_LLM_RETRIES', default=3)
    },
    'azure': {
        'api_key': env('AZURE_OPENAI_API_KEY', default=''),
        'model': env('AZURE_OPENAI_LLM_MODEL', default='gpt-35-turbo'),
        'azure_endpoint': env('AZURE_OPENAI_ENDPOINT', default=''),
        'api_version': env('AZURE_OPENAI_API_VERSION', default='2024-02-01'),
        'max_tokens': env.int('AZURE_OPENAI_LLM_MAX_TOKENS', default=2048),
        'cost_per_input_token': env.float('AZURE_OPENAI_LLM_COST_PER_INPUT_TOKEN', default=0.0015),
        'cost_per_output_token': env.float('AZURE_OPENAI_LLM_COST_PER_OUTPUT_TOKEN', default=0.002),
        'daily_budget_cents': env.int('AZURE_OPENAI_LLM_DAILY_BUDGET_CENTS', default=1800),  # $18/day
        'timeout_seconds': env.int('AZURE_OPENAI_LLM_TIMEOUT', default=30),
        'retry_attempts': env.int('AZURE_OPENAI_LLM_RETRIES', default=3)
    }
}

# LLM provider fallback order (first is preferred)
LLM_FALLBACK_ORDER = env.list('LLM_FALLBACK_ORDER', default=['openai', 'anthropic', 'azure'])

# Global LLM settings
LLM_REQUEST_TIMEOUT = env.int('LLM_REQUEST_TIMEOUT', default=30)
LLM_MAX_RETRIES = env.int('LLM_MAX_RETRIES', default=3)
LLM_CACHE_TIMEOUT = env.int('LLM_CACHE_TIMEOUT', default=3600)  # 1 hour

# Quality and safety settings
LLM_MIN_QUALITY_SCORE = env.float('LLM_MIN_QUALITY_SCORE', default=0.6)
LLM_ENABLE_SAFETY_FILTER = env.bool('LLM_ENABLE_SAFETY_FILTER', default=True)

# Budget control settings
LLM_DAILY_SPEND_ALERT_CENTS = env.int('LLM_DAILY_SPEND_ALERT_CENTS', default=1000)  # Alert at $10/day
LLM_MONTHLY_SPEND_LIMIT_CENTS = env.int('LLM_MONTHLY_SPEND_LIMIT_CENTS', default=20000)  # $200/month limit

# Budget and Cost Control
KB_DAILY_BUDGET_LIMITS = {
    'embedding_tokens': env.int('KB_DAILY_EMBED_TOKEN_LIMIT', default=1_000_000),
    'embedding_chars': env.int('KB_DAILY_EMBED_CHAR_LIMIT', default=KB_DAILY_EMBED_LIMIT),
    'fetch_requests': env.int('KB_DAILY_FETCH_LIMIT', default=1000),
    'parse_requests': env.int('KB_DAILY_PARSE_LIMIT', default=1000)
}

# License and Content Security
KB_BLOCKED_LICENSE_PATTERNS = [
    r'proprietary',
    r'internal use only',
    r'confidential',
    r'trade secret',
    r'all rights reserved.*proprietary'
]

KB_ATTRIBUTION_PATTERNS = [
    r'creative commons',
    r'attribution required',
    r'cite as',
    r'reference as',
    r'cc by'
]

# Rate Limiting Configuration (Phase 2)
ONBOARDING_API_RATE_LIMIT_WINDOW = env.int('ONBOARDING_API_RATE_LIMIT_WINDOW', default=60)
ONBOARDING_API_MAX_REQUESTS = env.int('ONBOARDING_API_MAX_REQUESTS', default=30)

# LLM Provider Configuration
LLM_PROVIDER = env('LLM_PROVIDER', default='dummy')  # 'openai', 'anthropic', 'dummy'
LLM_MODEL = env('LLM_MODEL', default='dummy-model')
LLM_API_KEY = env('LLM_API_KEY', default='')

# Cost Tracking and Budget Controls
ENABLE_COST_TRACKING = env.bool('ENABLE_COST_TRACKING', default=True)
DAILY_COST_BUDGET_CENTS = env.int('DAILY_COST_BUDGET_CENTS', default=10000)  # $100

# PII Redaction Configuration
ENABLE_PII_REDACTION = env.bool('ENABLE_PII_REDACTION', default=True)
PII_REDACTION_PATTERNS = {}  # Custom patterns can be defined here
PII_ALLOWLISTED_FIELDS = {}  # Custom allowlisted fields

# Source Allowlist for External Lookups
ONBOARDING_SOURCE_ALLOWLIST = [
    'docs.python.org',
    'developer.mozilla.org',
    'djangoproject.com',
    'github.com'
]

# Alert Thresholds
ONBOARDING_ALERT_THRESHOLDS = {
    'daily_cost_cents': env.int('ALERT_DAILY_COST_CENTS', default=10000),
    'avg_latency_ms': env.int('ALERT_AVG_LATENCY_MS', default=30000),
    'error_rate_percent': env.float('ALERT_ERROR_RATE_PERCENT', default=10.0),
}

# Rate Limits by Resource Type
ONBOARDING_RATE_LIMITS = {
    'llm_calls': {
        'requests': {
            'daily': env.int('LLM_DAILY_REQUEST_LIMIT', default=100),
            'hourly': env.int('LLM_HOURLY_REQUEST_LIMIT', default=20)
        },
        'tokens': {
            'daily': env.int('LLM_DAILY_TOKEN_LIMIT', default=50000),
            'hourly': env.int('LLM_HOURLY_TOKEN_LIMIT', default=10000)
        },
        'cost': {
            'daily': env.int('LLM_DAILY_COST_LIMIT_CENTS', default=1000)
        }
    },
    'translations': {
        'requests': {
            'daily': env.int('TRANSLATION_DAILY_REQUEST_LIMIT', default=500),
            'hourly': env.int('TRANSLATION_HOURLY_REQUEST_LIMIT', default=100)
        },
        'characters': {
            'daily': env.int('TRANSLATION_DAILY_CHAR_LIMIT', default=100000),
            'hourly': env.int('TRANSLATION_HOURLY_CHAR_LIMIT', default=20000)
        }
    }
}

# LLM Cost Models (cents per 1K tokens)
LLM_COST_MODELS = {
    'openai': {
        'gpt-4': {'input_cost_per_1k': 3.0, 'output_cost_per_1k': 6.0},
        'gpt-3.5-turbo': {'input_cost_per_1k': 0.15, 'output_cost_per_1k': 0.2}
    },
    'anthropic': {
        'claude-3-opus': {'input_cost_per_1k': 1.5, 'output_cost_per_1k': 7.5},
        'claude-3-sonnet': {'input_cost_per_1k': 0.3, 'output_cost_per_1k': 1.5}
    },
    'dummy': {
        'dummy-model': {'input_cost_per_1k': 0.0, 'output_cost_per_1k': 0.0}
    }
}

# Rate Limiting Settings
ENABLE_RATE_LIMITING = True
RATE_LIMIT_WINDOW_MINUTES = 15
RATE_LIMIT_MAX_ATTEMPTS = 5
RATE_LIMIT_PATHS = [
    "/login/",
    "/accounts/login/",
    "/api/",
    "/reset-password/",
    "/password-reset/",
]

# Security Headers Settings
REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"
PERMISSIONS_POLICY = {
    "geolocation": "()",
    "camera": "()",
    "microphone": "()",
    "payment": "()",
    "usb": "()",
}

# Security Reporting
SECURITY_REPORT_URI = "/api/security-report/"
NEL_REPORT_URI = "/api/nel-report/"

# HSTS Settings - Always set when SSL is enabled
if env.bool("SECURE_SSL_REDIRECT", default=False):
    SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=31536000)  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Additional security headers (enabled via environment)
if env.bool("ENABLE_SECURITY_HEADERS", default=False):
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Content Security Policy (CSP) for XSS protection
if env.bool("ENABLE_SECURITY_HEADERS", default=False):
    CSP_DEFAULT_SRC = ("'self'",)
    CSP_SCRIPT_SRC = (
        "'self'",
        "*.googleapis.com",
        "*.gstatic.com",
    )
    CSP_STYLE_SRC = ("'self'", "*.googleapis.com", "*.gstatic.com")
    CSP_IMG_SRC = ("'self'", "data:", "*.googleapis.com", "*.gstatic.com")
    CSP_FONT_SRC = ("'self'", "*.googleapis.com", "*.gstatic.com")
    CSP_CONNECT_SRC = ("'self'",)
    CSP_FRAME_ANCESTORS = ("'none'",)

# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"

# Prevent clickjacking
X_FRAME_OPTIONS = "DENY"

# Force HTTPS for admin and sensitive areas
if env.bool("SECURE_SSL_REDIRECT", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_TLS = True


DATA_UPLOAD_MAX_MEMORY_SIZE = int(env("DATA_UPLOAD_MAX_MEMORY_SIZE"))
NOTEBOOK_ARGUMENTS = [
    "--ip",
    "192.168.1.254",
    "--port",
    "8002",
]


SITE_ID = 1
# JDBC_DRIVER_PATH = env('JDBC_DRIVER_PATH')


# Custom test runner to handle schema issues with TenantAwareModel
TEST_RUNNER = "apps.core.test_runner.TenantAwareTestRunner"

# Celery Configuration with Security Settings
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='django-db')

# SECURITY: Use JSON serialization to prevent code injection
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Additional security settings
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Celery Queue Configuration
CELERY_TASK_ROUTES = {
    'background_tasks.tasks.process_graphql_mutation_async': {'queue': 'django5_queue'},
    'background_tasks.tasks.*': {'queue': 'django5_queue'},
}

# For development without Redis/RabbitMQ
if DEBUG and env.bool("CELERY_TASK_ALWAYS_EAGER", default=False):
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

# CLIENT_DOMAINS configuration moved to environment variables for flexibility
# Default domains for backward compatibility, can be overridden via environment
_DEFAULT_CLIENT_DOMAINS = {
    "R_REDMINE": "redmine.youtility.in",
    "R_TOURTRAX": "redmine.youtility.in",
    "R_SUKHI": "redmine.youtility.in",
    "R_CAPGEMINI": "redmine.youtility.in",
    "D_SUKHI": "demo.youtility.in",
    "D_CAPGEMINI": "demo.youtility.in",
    "SUKHI": "sg.youtility.in",
    "D_TOURTRAX": "demo.youtility.in",
    "WTC": "intelliwiz2.youtility.in",
    "R_YTPLD": "redmine.youtility.in",
}

# Load CLIENT_DOMAINS from environment with fallback to defaults
# Format: CLIENT_DOMAINS_JSON='{"R_REDMINE": "custom.domain.com", "WTC": "new.domain.com"}'
# Or individual overrides: CLIENT_DOMAIN_R_REDMINE=custom.domain.com
CLIENT_DOMAINS = _DEFAULT_CLIENT_DOMAINS.copy()

# Option 1: Load from JSON string (preferred for bulk configuration)
import json
client_domains_json = env('CLIENT_DOMAINS_JSON', default='{}')
try:
    client_domains_override = json.loads(client_domains_json)
    if isinstance(client_domains_override, dict):
        CLIENT_DOMAINS.update(client_domains_override)
        logger.info(f"Updated CLIENT_DOMAINS with {len(client_domains_override)} environment overrides")
except (json.JSONDecodeError, TypeError) as e:
    logger.warning(f"Invalid CLIENT_DOMAINS_JSON format: {e}")

# Option 2: Load individual domain overrides (for single client customization)
# This allows setting CLIENT_DOMAIN_R_REDMINE=custom.domain.com
for client_key in list(_DEFAULT_CLIENT_DOMAINS.keys()):
    env_key = f'CLIENT_DOMAIN_{client_key}'
    domain_override = env(env_key, default=None)
    if domain_override:
        CLIENT_DOMAINS[client_key] = domain_override
        logger.info(f"Updated {client_key} domain to {domain_override} from {env_key}")

# Validate domains for security
def validate_client_domains(domains):
    """Validate client domains to prevent security issues."""
    import re
    valid_domains = {}
    domain_pattern = re.compile(r'^[a-zA-Z0-9][a-zA-Z0-9\-\.]*[a-zA-Z0-9]$')

    for client, domain in domains.items():
        if not isinstance(domain, str):
            logger.error(f"Invalid domain type for {client}: {type(domain)}")
            continue

        if not domain_pattern.match(domain):
            logger.error(f"Invalid domain format for {client}: {domain}")
            continue

        if len(domain) > 255:  # DNS domain length limit
            logger.error(f"Domain too long for {client}: {domain}")
            continue

        valid_domains[client] = domain

    return valid_domains

CLIENT_DOMAINS = validate_client_domains(CLIENT_DOMAINS)
logger.info(f"Validated {len(CLIENT_DOMAINS)} client domains")

BUCKET = "prod-attachment-sukhi-group"
TEMP_REPORTS_GENERATED = env("TEMP_REPORTS_GENERATED")
ONDEMAND_REPORTS_GENERATED = env("ONDEMAND_REPORTS_GENERATED")

MQTT_CONFIG = {
    "BROKER_ADDRESS": env("MQTT_BROKER_ADDRESS"),
    "broker_port": env.int("MQTT_BROKER_PORT"),
    "broker_userNAME": env("MQTT_BROKER_USERNAME"),
    "broker_password": env("MQTT_BROKER_PASSWORD"),
}



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = env("STATIC_ROOT")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "frontend/static"),
]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Static file finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
print("BASE_DIR", BASE_DIR)
print("STATICFILES_DIRS", STATICFILES_DIRS)
print("MEDIA_ROOT", MEDIA_ROOT)

# WhiteNoise configuration for development
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True  # Only for development


# ENABLE_RATE_LIMITING = True  # Removed duplicate - defined above at line 1046
RATE_LIMIT_WINDOW_MINUTES = 15
RATE_LIMIT_MAX_ATTEMPTS = 5

# Import local settings override if it exists
try:
    from .settings_local import *

    print("[SETTINGS] Local settings loaded successfully")
except ImportError:
    pass
RATE_LIMIT_PATHS = [
    "/",
    "/login/",
    "/accounts/login/",
    "/api/",
]  # Added root path for your login


# =============================================================================
# PERSONALIZATION AND EXPERIMENTATION SETTINGS
# =============================================================================

# Enable/Disable Personalization Features
ENABLE_ONBOARDING_LEARNING = env.bool('ENABLE_ONBOARDING_LEARNING', default=True)
ENABLE_ONBOARDING_EXPERIMENTS = env.bool('ENABLE_ONBOARDING_EXPERIMENTS', default=True)
ENABLE_ONBOARDING_PERSONALIZATION = env.bool('ENABLE_ONBOARDING_PERSONALIZATION', default=True)

# Learning System Configuration
LEARNING_ASYNC_PROCESSING = env.bool('LEARNING_ASYNC_PROCESSING', default=True)
LEARNING_BATCH_SIZE = env.int('LEARNING_BATCH_SIZE', default=100)
LEARNING_IMPLICIT_SIGNALS = env.bool('LEARNING_IMPLICIT_SIGNALS', default=True)
LEARNING_COST_TRACKING = env.bool('LEARNING_COST_TRACKING', default=True)
LEARNING_UPDATE_THRESHOLD = env.int('LEARNING_UPDATE_THRESHOLD', default=5)
LEARNING_FEATURE_CACHE_TIMEOUT = env.int('LEARNING_FEATURE_CACHE_TIMEOUT', default=300)

# Personalization Parameters
ONBOARDING_MAX_RECOMMENDATIONS = env.int('ONBOARDING_MAX_RECOMMENDATIONS', default=5)
ONBOARDING_DEFAULT_BUDGET_CENTS = env.int('ONBOARDING_DEFAULT_BUDGET_CENTS', default=1000)  # $10
ONBOARDING_ADAPTIVE_BUDGETING = env.bool('ONBOARDING_ADAPTIVE_BUDGETING', default=True)
ONBOARDING_MIN_CONFIDENCE_THRESHOLD = env.float('ONBOARDING_MIN_CONFIDENCE_THRESHOLD', default=0.3)

# Holdback and A/B Testing
ONBOARDING_LEARNING_HOLDBACK_PCT = env.float('ONBOARDING_LEARNING_HOLDBACK_PCT', default=10.0)
ONBOARDING_EXPERIMENT_HOLDBACK_PCT = env.float('ONBOARDING_EXPERIMENT_HOLDBACK_PCT', default=5.0)

# Token Budget Limits
TOKEN_BUDGET_MAKER_SIMPLE = env.int('TOKEN_BUDGET_MAKER_SIMPLE', default=500)
TOKEN_BUDGET_MAKER_COMPLEX = env.int('TOKEN_BUDGET_MAKER_COMPLEX', default=1500)
TOKEN_BUDGET_CHECKER = env.int('TOKEN_BUDGET_CHECKER', default=800)
MAX_CITATIONS_PER_REC = env.int('MAX_CITATIONS_PER_REC', default=5)

# Cost and Performance Limits
ONBOARDING_MAX_TOKENS_PER_REC = env.int('ONBOARDING_MAX_TOKENS_PER_REC', default=2000)
ONBOARDING_MIN_CONFIDENCE_FOR_CHECKER = env.float('ONBOARDING_MIN_CONFIDENCE_FOR_CHECKER', default=0.6)
ONBOARDING_DAILY_COST_CAP = env.int('ONBOARDING_DAILY_COST_CAP', default=10000)  # $100

# Two-person approval threshold (risk score 0.0-1.0)
ONBOARDING_TWO_PERSON_THRESHOLD = env.float('ONBOARDING_TWO_PERSON_THRESHOLD', default=0.7)
USER_HOURLY_BUDGET_CENTS = env.int('USER_HOURLY_BUDGET_CENTS', default=1000)  # $10/hour per user

# Caching Configuration
LLM_CACHE_TTL = env.int('LLM_CACHE_TTL', default=3600)  # 1 hour
LLM_MAX_CACHE_SIZE = env.int('LLM_MAX_CACHE_SIZE', default=10000)
CACHE_VERSION = env('CACHE_VERSION', default='1.0')

# Provider Configuration
DEFAULT_LLM_PROVIDER = env('DEFAULT_LLM_PROVIDER', default='gpt-3.5-turbo')

# Reranking Weights
RERANK_PERSONALIZATION_WEIGHT = env.float('RERANK_PERSONALIZATION_WEIGHT', default=0.4)
RERANK_CONSENSUS_WEIGHT = env.float('RERANK_CONSENSUS_WEIGHT', default=0.3)
RERANK_CITATION_WEIGHT = env.float('RERANK_CITATION_WEIGHT', default=0.2)
RERANK_COST_WEIGHT = env.float('RERANK_COST_WEIGHT', default=0.1)
RERANK_CACHE_TIMEOUT = env.int('RERANK_CACHE_TIMEOUT', default=300)

# Experiment Analysis Configuration
EXPERIMENT_ALPHA = env.float('EXPERIMENT_ALPHA', default=0.05)  # Significance level
EXPERIMENT_MIN_SAMPLE_SIZE = env.int('EXPERIMENT_MIN_SAMPLE_SIZE', default=30)
EXPERIMENT_MIN_EFFECT_SIZE = env.float('EXPERIMENT_MIN_EFFECT_SIZE', default=0.02)  # 2%
EXPERIMENT_MIN_POWER = env.float('EXPERIMENT_MIN_POWER', default=0.8)
EXPERIMENT_MIN_RUNTIME_HOURS = env.int('EXPERIMENT_MIN_RUNTIME_HOURS', default=48)
EXPERIMENT_BONFERRONI_CORRECTION = env.bool('EXPERIMENT_BONFERRONI_CORRECTION', default=True)

# Consensus Engine Configuration
ONBOARDING_APPROVE_THRESHOLD = env.float('ONBOARDING_APPROVE_THRESHOLD', default=0.7)
ONBOARDING_ESCALATE_THRESHOLD = env.float('ONBOARDING_ESCALATE_THRESHOLD', default=0.4)

# Multi-Armed Bandit Configuration
BANDIT_EPSILON = env.float('BANDIT_EPSILON', default=0.1)  # Exploration rate
BANDIT_MIN_SAMPLES = env.int('BANDIT_MIN_SAMPLES', default=10)

# Security and Anomaly Detection
ENABLE_PII_REDACTION = env.bool('ENABLE_PII_REDACTION', default=True)
PII_HASH_SALT = env('PII_HASH_SALT', default='change_me_in_production')
MAX_INTERACTIONS_PER_HOUR = env.int('MAX_INTERACTIONS_PER_HOUR', default=100)
MAX_EXPERIMENTS_PER_DAY = env.int('MAX_EXPERIMENTS_PER_DAY', default=10)

# Metrics and Monitoring
METRICS_FLUSH_INTERVAL = env.int('METRICS_FLUSH_INTERVAL', default=60)  # seconds
METRICS_BUFFER_SIZE = env.int('METRICS_BUFFER_SIZE', default=1000)

# Service Level Objectives (SLOs)
SLO_REC_LATENCY_P95 = env.int('SLO_REC_LATENCY_P95', default=5000)  # ms
SLO_REC_LATENCY_P50 = env.int('SLO_REC_LATENCY_P50', default=2000)  # ms
SLO_ACCEPTANCE_RATE_MIN = env.float('SLO_ACCEPTANCE_RATE_MIN', default=0.6)
SLO_ERROR_RATE_MAX = env.float('SLO_ERROR_RATE_MAX', default=0.05)
SLO_AVAILABILITY_MIN = env.float('SLO_AVAILABILITY_MIN', default=0.995)

# API Rate Limiting for Personalization Endpoints
INTERACTION_THROTTLE_RATE = env('INTERACTION_THROTTLE_RATE', default='100/hour')
EXPERIMENT_THROTTLE_RATE = env('EXPERIMENT_THROTTLE_RATE', default='50/hour')

# Feature Flags for Gradual Rollout
PERSONALIZATION_FEATURE_FLAGS = {
    'enable_preference_learning': env.bool('FF_PREFERENCE_LEARNING', default=True),
    'enable_cost_optimization': env.bool('FF_COST_OPTIMIZATION', default=True),
    'enable_experiment_assignments': env.bool('FF_EXPERIMENT_ASSIGNMENTS', default=True),
    'enable_smart_caching': env.bool('FF_SMART_CACHING', default=True),
    'enable_adaptive_budgeting': env.bool('FF_ADAPTIVE_BUDGETING', default=True),
    'enable_provider_routing': env.bool('FF_PROVIDER_ROUTING', default=True),
    'enable_hot_path_precompute': env.bool('FF_HOT_PATH_PRECOMPUTE', default=False),
    'enable_streaming_responses': env.bool('FF_STREAMING_RESPONSES', default=False),
    'enable_anomaly_detection': env.bool('FF_ANOMALY_DETECTION', default=True),
    'enable_audit_logging': env.bool('FF_AUDIT_LOGGING', default=True)
}

# Tenant-specific Overrides (if needed)
TENANT_PERSONALIZATION_OVERRIDES = env.json('TENANT_PERSONALIZATION_OVERRIDES', default={})

# Development/Testing Overrides
if DEBUG:
    # More permissive settings for development
    ONBOARDING_LEARNING_HOLDBACK_PCT = 0.0  # No holdback in dev
    EXPERIMENT_MIN_SAMPLE_SIZE = 5  # Lower requirements for testing
    BANDIT_EPSILON = 0.3  # More exploration in dev

    # Enable all feature flags for development testing
    for flag in PERSONALIZATION_FEATURE_FLAGS:
        PERSONALIZATION_FEATURE_FLAGS[flag] = True
