"""
Django settings for intelliwiz_config project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import logging
from datetime import datetime
import getpass
import environ

env = environ.Env()
import dj_database_url

ENVPATH = os.path.join(os.path.abspath("intelliwiz_config/envs"))

# ENVIRONMENT CONFIGURATION - Change this line to switch between environments:
# For development (insecure, easy to use):
# ENV_FILE = '.env.dev'
# For development with security testing:
# ENV_FILE = '.env.dev.secure'
# For current production:
# ENV_FILE = '.env.prod'
# For secure production:
# ENV_FILE = '.env.prod.secure'

ENV_FILE = ".env.dev.secure"  # <-- Change this line to switch environments
environ.Env.read_env(os.path.join(ENVPATH, ENV_FILE), overwrite=True)


HOST = env("HOST")
# GOOGLE MAP API KEY...
GOOGLE_MAP_SECRET_KEY = env("GOOGLE_MAP_SECRET_KEY")


# BULK IMPORT API KEY...
BULK_IMPORT_GOOGLE_DRIVE_API_KEY = env("BULK_IMPORT_GOOGLE_DRIVE_API_KEY")


def check_path(path):
    path = Path(path)
    if not os.path.exists(path):
        path.mkdir(parents=True, exist_ok=True)
    return bool(os.access(path, os.R_OK) and os.access(path, os.W_OK))


# Build paths inside the project like this: BASE_DIR / 'subdir'.p
BASE_DIR = Path(__file__).resolve().parent.parent


# Email Verification CONF...
def verified_callback(user):
    # When multiple users have the same email, verify all of them
    from apps.peoples.models import People
    import logging

    logger = logging.getLogger("django")

    # Get all users with this email
    users_with_email = People.objects.filter(email=user.email)
    logger.info(
        f"[VERIFY] Found {users_with_email.count()} users with email {user.email}"
    )

    # Verify all users with this email
    for u in users_with_email:
        if not u.isverified:
            logger.info(f"[VERIFY] Verifying user ID {u.id}, loginid: {u.loginid}")
            u.isverified = True
            u.is_staff = True
            u.save()

    # Also update the passed user object
    user.isverified = True
    user.is_staff = True
    user.save()


EMAIL_TOKEN_LIFE = 60**2
EMAIL_MAIL_TOKEN_LIFE = 60**2
EMAIL_VERIFIED_CALLBACK = verified_callback
EMAIL_MAIL_CALLBACK = verified_callback
EMAIL_FROM_ADDRESS = env("EMAIL_FROM_ADDRESS")
EMAIL_MAIL_SUBJECT = "Confirm your email"
EMAIL_MAIL_HTML = "email.html"
EMAIL_MAIL_PLAIN = "mail_body.txt"
CUSTOM_SALT = env("CUSTOM_SALT", default="django-email-verification-salt")

EMAIL_MAIL_PAGE_TEMPLATE = "email_verify.html"
EMAIL_PAGE_DOMAIN = env("EMAIL_PAGE_DOMAIN")
EMAIL_MULTI_USER = True  # optional (defaults to False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")
ENCRYPT_KEY = env("ENCRYPT_KEY")

SUPERADMIN_PASSWORD = env("SUPERADMIN_PASSWORD")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)
USE_L10N = False
ALLOWED_HOSTS = [
    "django5.youtility.in",
    "127.0.0.1:8005",
    "127.0.0.1",
    "localhost",
    "192.168.1.243",
]

# SENTRY CONFIGURATION - REMOVED

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    # third_party_apps
    "graphene_django",
    "graphene_gis",
    "django_email_verification",
    "import_export",
    "django_extensions",
    "django_select2",
    "django_filters",
    "graphql_jwt.refresh_token.apps.RefreshTokenConfig",
    "rest_framework",
    "django_celery_beat",
    "django_celery_results",
    "corsheaders",
    # local apps
    'apps.core',
    'apps.peoples',
    'apps.onboarding',
    'apps.tenants',
    'apps.attendance',
    'apps.activity',
    'apps.schedhuler',
    'apps.reminder',
    'apps.reports',
    'apps.service',
    'apps.y_helpdesk',
    'apps.work_order_management',
    'apps.mqtt',
    'apps.face_recognition',

    # third-party apps
    "django_cleanup.apps.CleanupConfig",
]

# Add debug toolbar only in DEBUG mode
if DEBUG:
    INSTALLED_APPS.append("debug_toolbar")

MIDDLEWARE = [
    #'apps.tenants.middlewares.TenantMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "apps.core.error_handling.CorrelationIDMiddleware",
    "apps.core.sql_security.SQLInjectionProtectionMiddleware",
    "apps.core.xss_protection.XSSProtectionMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "apps.onboarding.middlewares.TimezoneMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'apps.core.xss_protection.CSRFHeaderMiddleware',  # Temporarily disabled for CSS debugging
    "apps.core.error_handling.GlobalExceptionMiddleware",
]

# Add debug toolbar middleware only in DEBUG mode
if DEBUG:
    MIDDLEWARE.insert(2, "debug_toolbar.middleware.DebugToolbarMiddleware")

# CORS Configuration - Secure CORS settings
CORS_ALLOWED_ORIGINS = [
    "https://django5.youtility.in",
]

# Add localhost origins only in DEBUG mode
if DEBUG:
    CORS_ALLOWED_ORIGINS.extend(
        [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "http://localhost:8000",
            "http://127.0.0.1:8000",
        ]
    )

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://\w+\.youtility\.in$",  # Allow subdomains of youtility.in
]

CORS_ALLOW_CREDENTIALS = True  # Allow cookies to be included in CORS requests

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_EXPOSE_HEADERS = [
    "Content-Type",
    "X-CSRFToken",
]

CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# customize the message tags to match Bootstrap's CSS classes
from django.contrib.messages import constants as message_constants

MESSAGE_TAGS = {
    message_constants.DEBUG: "alert-info",
    message_constants.INFO: "alert-info",
    message_constants.SUCCESS: "alert-success",
    message_constants.WARNING: "alert-warning",
    message_constants.ERROR: "alert-danger",
}

ROOT_URLCONF = "intelliwiz_config.urls"

JINJA_TEMPLATES = os.path.join(BASE_DIR, "frontend/templates")
import jinja2

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "apps.peoples.context_processors.app_settings",
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
        },
    },
    # jinja2 configuration
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "DIRS": [JINJA_TEMPLATES],
        "APP_DIRS": True,
        "OPTIONS": {
            "extensions": [
                "jinja2.ext.loopcontrols",
            ],
            "autoescape": False,
            "auto_reload": True,
            "undefined": jinja2.StrictUndefined,
            "environment": "intelliwiz_config.jinja.env.JinjaEnvironment",
            "context_processors": [
                "apps.peoples.context_processors.app_settings",
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
        },
    },
]

from intelliwiz_config.settings_ia import apply_ia_settings

apply_ia_settings(locals())

WSGI_APPLICATION = "intelliwiz_config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/# databases
"""
NOTE: Client bucode should match the database alias name.
"""

# DATABASES = {
#     "default": {
#         "ENGINE": "django.contrib.gis.db.backends.postgis",
#         "NAME": "django5db",
#         "USER": "django5dbuser",
#         "PASSWORD": "!!sysadmin!!",
#         "HOST": "redmine.youtility.in",
#         "PORT": "5432",  # Native PostgreSQL port
#     }
# }
# DATABASE CONFIGURATION - Environment driven
DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "USER": env("DBUSER"),
        "NAME": env("DBNAME"),
        "PASSWORD": env("DBPASS"),
        "HOST": env("DBHOST"),
        "PORT": "5432",
        "CONN_MAX_AGE": 0,
    }
}


# SELECT2 CONF...
SELECT2_CACHE_BACKEND = "select2"
SELECT2_JS = ""
SELECT2_CSS = ""
SELECT2_I18N_PATH = "assets/plugins/custom/select2-4.x/js/i18n"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": "youtility4",
    },
    # Removed redis_session_cache - now using pure PostgreSQL sessions
    "select2": {
        "BACKEND": "apps.core.cache.materialized_view_select2.MaterializedViewSelect2Cache",
        "LOCATION": "",  # PostgreSQL connection used
        "OPTIONS": {
            "MAX_ENTRIES": 10000,
            "CULL_FREQUENCY": 3,
        },
        "TIMEOUT": 900,  # 15 minutes default timeout
        "KEY_PREFIX": "select2_mv",
    },
}


# SESSION SETTINGS - PostgreSQL-first approach (MD approved for 20ms trade-off)

SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Pure PostgreSQL sessions
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # close the session when user closes the browser
SESSION_COOKIE_AGE = 60**2
SESSION_SAVE_EVERY_REQUEST = True

# PostgreSQL session optimization
DATABASE_SESSION_OPTIMIZATIONS = {
    "USE_INDEX_ON_SESSION_KEY": True,
    "USE_INDEX_ON_EXPIRE_DATE": True,
    "ENABLE_SESSION_CLEANUP": True,
}


# CELERY SETTINGS - REMOVED (Replaced with PostgreSQL Task Queue)
# CELERY_BROKER_URL = env('CELERY_broker_url')
# result_backend = env("result_backend")
# CELERY_BEAT_SCHEDULER = env('CELERY_BEAT_SCHEDULER')
# accept_content = ['application/json']
# result_serializer = 'json'
# task_serializer = 'json'
# result_extended=True

# PostgreSQL Task Queue Configuration (replacement for Celery)
POSTGRESQL_TASK_QUEUE = {
    "DEFAULT_QUEUE": "default",
    "MAX_RETRIES": 3,
    "RETRY_DELAY": 60,
    "WORKER_CONCURRENCY": 4,
    "HEARTBEAT_INTERVAL": 30,
    "CLEANUP_INTERVAL": 86400,  # 24 hours
    "QUEUES": ["default", "high_priority", "email", "reports", "mqtt", "maintenance"],
}


# Cache time to live is 15 minutes.
CACHE_TTL = 60 * 1

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/# auth-password-validators

# PASSWORD VALIDATORS...
AUTH_PASSWORD_VALIDATORS = [
    # {
    #    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

USE_I18N = True

USE_TZ = True
TIME_ZONE = "UTC"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/# default-auto-field

# Media Files CONF..
MEDIA_ROOT = env("MEDIA_ROOT")
if not check_path(MEDIA_ROOT):
    raise ValueError(f"`{MEDIA_ROOT}` not readable and writable")

MEDIA_URL = "/youtility4_media/"
# DATETIME INPUTS CONF...
DATETIME_INPUT_FORMATS = [
    "%d-%b-%Y %H:%M:%S",  # 22-May-1998 13:01#
    "%Y-%m-%d %H:%M:%S",  # 1998-05-18 13:01:00
    "%d-%b-%Y %H:%M",
]
DATE_INPUT_FORMATS = [
    "%d-%b-%Y",
    "%d/%b/%Y",
    "%d/%m/%Y",
    "%Y-%m-%d",
    "%Y/%m/%d",
    "%Y-%m-%dT%H:%M:%S%z",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = env("STATIC_ROOT")

STATICFILES_DIRS = [os.path.join(BASE_DIR, "frontend/static")]


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/# default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DATABASE_ROUTERS = ["apps.tenants.middlewares.TenantDbRouter"]

# Media Files


AUTH_USER_MODEL = "peoples.People"
# AUTHENTICATION BACKENDS CONF...
AUTHENTICATION_BACKENDS = [
    "graphql_jwt.backends.JSONWebTokenBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# GRAPHENE CONF...
GRAPHENE = {
    # ...
    "ATOMIC_MUTATIONS": True,
    "SCHEMA": "apps.service.schema.schema",
    "MIDDLEWARE": [
        "graphql_jwt.middleware.JSONWebTokenMiddleware",
    ],
}

# GRAPHQL JWT CONF...
from datetime import timedelta

GRAPHQL_JWT = {
    "JWT_VERIFY_EXPIRATION": False,
    "JWT_REFRESH_EXPIRATION_DELTA": timedelta(days=2),
    # optional
    "JWT_LONG_RUNNING_REFRESH_TOKEN": True,
}

ADMINS = [
    ("wed_dev", "satyam.warghat@youtility.in"),
    ("wed_dev", "pankaj.pal@youtility.in"),
    ("wed_dev", "manohar.lagishetty@youtility.in"),
    ("business_manger", "namrata.shahid@youtility.in"),
    ("business_manager", "ashish.mhashilkar@youtility.in"),
]

username = getpass.getuser()

# username = "satyam"

LOGGER_PATH = f"/home/redmine/DJANGO5"

# LOGGER_PATH = '/app/logs'

import logging.config

LOGGING_CONFIG = None
LOGGING_CONFIG_ = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "coloured": {
            "()": "colorlog.ColoredFormatter",
            "format": "%(log_color)s %(asctime)s  %(levelname)-10s  from method: %(funcName)-32s  << %(message)s >>",
        },
        "plain": {
            "format": "%(asctime)s  %(levelname)-10s  from method: %(funcName)-32s  << %(message)s >>"
        },
    },
    "handlers": {
        "default": {
            "level": "INFO",
            "formatter": "coloured",
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",  # Default is stderr
        },
        "filelogs": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": f"{LOGGER_PATH}/youtility4_logs/youtility4.log",
            "maxBytes": 15728640,
            "backupCount": 10,
            "formatter": "plain",
        },
        "debuglogs": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": f"{LOGGER_PATH}/youtility4_logs/debug.log",
            "maxBytes": 15728640,
            "backupCount": 10,
            "formatter": "plain",
        },
        "serviceLogs": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": f"{LOGGER_PATH}/youtility4_logs/mobileservice.log",
            "maxBytes": 15728640,
            "backupCount": 10,
            "formatter": "plain",
        },
        "tracking_logs": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": f"{LOGGER_PATH}/youtility4_logs/tracking.log",
            "maxBytes": 15728640,
            "backupCount": 10,
            "formatter": "plain",
        },
        "message_qlogs": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": f"{LOGGER_PATH}/youtility4_logs/message_q.log",
            "maxBytes": 15728640,
            "backupCount": 10,
            "formatter": "plain",
        },
        "reportslog": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": f"{LOGGER_PATH}/youtility4_logs/reports.log",
            "maxBytes": 15728640,
            "backupCount": 10,
            "formatter": "plain",
        },
        "mail_admins": {
            "level": "CRITICAL",
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": True,
            "formatter": "plain",
        },
        "error_file_handler": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": f"{LOGGER_PATH}/youtility4_logs/errors.log",
            "maxBytes": 15728640,
            "backupCount": 10,
            "formatter": "plain",
        },
    },
    "loggers": {
        "": {  # root logger
            "handlers": ["default"],
            "level": "WARNING",
            "propagate": True,
        },
        "django": {
            "handlers": ["default", "filelogs"],
            "level": "INFO",
            "propagate": False,
        },
        "debug_logger": {
            "handlers": ["default", "debuglogs"],
            "level": "DEBUG",
            "propagate": False,
        },
        "mobile_service_log": {
            "handlers": ["default", "serviceLogs", "mail_admins"],
            "level": "DEBUG",
            "propagate": False,
        },
        "message_q": {
            "handlers": ["default", "message_qlogs", "mail_admins"],
            "level": "INFO",
            "propagate": False,
        },
        "tracking": {
            "handlers": ["default", "tracking_logs", "mail_admins"],
            "level": "INFO",
            "propagate": False,
        },
        "reports": {
            "handlers": ["default", "reportslog", "mail_admins"],
            "level": "DEBUG",
            "propagate": False,
        },
        "error_logger": {
            "handlers": ["default", "error_file_handler"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


def check_and_correct_path(path):
    if os.path.exists(path):
        if os.path.isdir(path):
            os.rmdir(path)  # Only works if the directory is empty
            # You might need more complex handling if the directory is not empty


# Example usage before setting up logging
check_and_correct_path(LOGGING_CONFIG_["handlers"]["filelogs"]["filename"])
check_and_correct_path(LOGGING_CONFIG_["handlers"]["serviceLogs"]["filename"])

logging.config.dictConfig(LOGGING_CONFIG_)

# LOGIN URL NAME...
LOGIN_URL = "login"


# DJANGO_IMPORT_EXPORT CONF...
IMPORT_EXPORT_USE_TRANSACTIONS = True

# DJANGO-EXTENSIONS CONF...
SHELL_PLUS_PRINT_SQL = True
GRAPH_MODELS = {
    "all_applications": True,
    "group_models": True,
}


# For Django Email Backend - AWS SES via SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")

# AWS SES SMTP Configuration
EMAIL_HOST = "email-smtp.us-east-1.amazonaws.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("AWS_SES_SMTP_USER")
EMAIL_HOST_PASSWORD = env("AWS_SES_SMTP_PASSWORD")

# For backward compatibility - many files use EMAIL_HOST_USER as sender email
# This is the actual email address that will be used as the sender
EMAIL_FROM_ADDRESS = env("DEFAULT_FROM_EMAIL")
DJANGO_SETTINGS_MODULE = "intelliwiz_config.settings"


# DJANGO TAGGIT CONF...
TAGGIT_CASE_INSENSITIVE = True


# SECURITY SETTINGS - Production-grade security configuration
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)

# CSP (Content Security Policy) Settings
CSP_ENABLE_NONCE = False  # Temporarily disabled while we allow unsafe-inline for styles
CSP_NONCE_LENGTH = 32
CSP_REPORT_ONLY = False  # Set to True for testing
CSP_REPORT_URI = "/api/csp-report/"
CSP_STORE_VIOLATIONS = True

# CSP Directives - Secure defaults without unsafe-inline
# Note: For development, we're temporarily allowing unsafe-inline for styles
# In production, convert all inline styles to external stylesheets or use nonces
CSP_DIRECTIVES = {
    "default-src": ["'self'"],
    "script-src": [
        "'self'",
        "https://fonts.googleapis.com",
        "https://ajax.googleapis.com",
        "https://cdn.jsdelivr.net",
        "https://cdnjs.cloudflare.com",
    ],
    "style-src": [
        "'self'",
        "'unsafe-inline'",
        "https://fonts.googleapis.com",
        "https://cdn.jsdelivr.net",
        "https://cdnjs.cloudflare.com",
    ],
    "img-src": ["'self'", "data:", "https:", "blob:"],
    "font-src": [
        "'self'",
        "data:",
        "https://fonts.googleapis.com",
        "https://fonts.gstatic.com",
        "https://cdn.jsdelivr.net",
        "https://cdnjs.cloudflare.com",
    ],
    "connect-src": ["'self'", "https:"],
    "frame-ancestors": ["'none'"],
    "base-uri": ["'self'"],
    "form-action": ["'self'"],
}

# API Authentication Settings
ENABLE_API_AUTH = True
API_AUTH_PATHS = ["/api/", "/graphql/"]
API_REQUIRE_SIGNING = False  # Set to True for high-security APIs

# Rate Limiting Settings
ENABLE_RATE_LIMITING = True
RATE_LIMIT_WINDOW_MINUTES = 15
RATE_LIMIT_MAX_ATTEMPTS = 5
RATE_LIMIT_PATHS = [
    "/login/",
    "/accounts/login/",
    "/api/",
    "/reset-password/",
    "/password-reset/",
]

# Security Headers Settings
REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"
PERMISSIONS_POLICY = {
    "geolocation": "()",
    "camera": "()",
    "microphone": "()",
    "payment": "()",
    "usb": "()",
}

# Security Reporting
SECURITY_REPORT_URI = "/api/security-report/"
NEL_REPORT_URI = "/api/nel-report/"

# HSTS Settings - Always set when SSL is enabled
if env.bool("SECURE_SSL_REDIRECT", default=False):
    SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=31536000)  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Additional security headers (enabled via environment)
if env.bool("ENABLE_SECURITY_HEADERS", default=False):
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Content Security Policy (CSP) for XSS protection
if env.bool("ENABLE_SECURITY_HEADERS", default=False):
    CSP_DEFAULT_SRC = ("'self'",)
    CSP_SCRIPT_SRC = (
        "'self'",
        "'unsafe-inline'",
        "'unsafe-eval'",
        "*.googleapis.com",
        "*.gstatic.com",
    )
    CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "*.googleapis.com", "*.gstatic.com")
    CSP_IMG_SRC = ("'self'", "data:", "*.googleapis.com", "*.gstatic.com")
    CSP_FONT_SRC = ("'self'", "*.googleapis.com", "*.gstatic.com")
    CSP_CONNECT_SRC = ("'self'",)
    CSP_FRAME_ANCESTORS = ("'none'",)

# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"

# Prevent clickjacking
X_FRAME_OPTIONS = "DENY"

# Force HTTPS for admin and sensitive areas
if env.bool("SECURE_SSL_REDIRECT", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_TLS = True


DATA_UPLOAD_MAX_MEMORY_SIZE = int(env("DATA_UPLOAD_MAX_MEMORY_SIZE"))
NOTEBOOK_ARGUMENTS = [
    "--ip",
    "192.168.1.254",
    "--port",
    "8002",
]


SITE_ID = 1
# JDBC_DRIVER_PATH = env('JDBC_DRIVER_PATH')


# Custom test runner to handle schema issues with TenantAwareModel
TEST_RUNNER = "apps.core.test_runner.TenantAwareTestRunner"

# Celery Configuration
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='django-db')

# Celery Queue Configuration
CELERY_TASK_ROUTES = {
    'background_tasks.tasks.process_graphql_mutation_async': {'queue': 'django5_queue'},
    'background_tasks.tasks.*': {'queue': 'django5_queue'},
}

# For development without Redis/RabbitMQ
if DEBUG and env.bool("CELERY_TASK_ALWAYS_EAGER", default=False):
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

CLIENT_DOMAINS = {
    "R_REDMINE": "redmine.youtility.in",
    "R_TOURTRAX": "redmine.youtility.in",
    "R_SUKHI": "redmine.youtility.in",
    "R_CAPGEMINI": "redmine.youtility.in",
    "D_SUKHI": "demo.youtility.in",
    "D_CAPGEMINI": "demo.youtility.in",
    "SUKHI": "sg.youtility.in",
    "D_TOURTRAX": "demo.youtility.in",
    "WTC": "intelliwiz2.youtility.in",
    "R_YTPLD": "redmine.youtility.in",
}

BUCKET = "prod-attachment-sukhi-group"
TEMP_REPORTS_GENERATED = env("TEMP_REPORTS_GENERATED")
ONDEMAND_REPORTS_GENERATED = env("ONDEMAND_REPORTS_GENERATED")

MQTT_CONFIG = {
    "BROKER_ADDRESS": env("MQTT_BROKER_ADDRESS"),
    "broker_port": env.int("MQTT_BROKER_PORT"),
    "broker_userNAME": env("MQTT_BROKER_USERNAME"),
    "broker_password": env("MQTT_BROKER_PASSWORD"),
}


# CELERY_TASK_ROUTES - REMOVED (Replaced with PostgreSQL Task Queue)
# Task routing is now handled by PostgreSQL Task Queue system
# All tasks use the queue_name field in TaskQueue model

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = env("STATIC_ROOT")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "frontend/static"),
]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Static file finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
print("BASE_DIR", BASE_DIR)
print("STATICFILES_DIRS", STATICFILES_DIRS)
print("MEDIA_ROOT", MEDIA_ROOT)

# WhiteNoise configuration for development
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True  # Only for development


ENABLE_RATE_LIMITING = True
RATE_LIMIT_WINDOW_MINUTES = 15
RATE_LIMIT_MAX_ATTEMPTS = 5

# Import local settings override if it exists
try:
    from .settings_local import *

    print("[SETTINGS] Local settings loaded successfully")
except ImportError:
    pass
RATE_LIMIT_PATHS = [
    "/",
    "/login/",
    "/accounts/login/",
    "/api/",
]  # Added root path for your login
