# Generated by Django 5.2.7 on 2025-11-09 10:20

import apps.peoples.models.base_model
import apps.y_helpdesk.managers
import apps.y_helpdesk.models.ticket_workflow
import concurrency.fields
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activity", "0002_initial"),
        ("client_onboarding", "0002_initial"),
        ("core_onboarding", "0001_initial"),
        ("peoples", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ("ticketno", models.CharField(max_length=200, null=True, unique=True)),
                ("ticketdesc", models.TextField()),
                ("comments", models.CharField(max_length=250, null=True)),
                (
                    "identifier",
                    models.CharField(
                        choices=[("REQUEST", "Request"), ("TICKET", "Ticket")],
                        default="TICKET",
                        max_length=50,
                        verbose_name="Identifier",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New"),
                            ("CANCELLED", "Cancel"),
                            ("RESOLVED", "Resolved"),
                            ("OPEN", "Open"),
                            ("ONHOLD", "On Hold"),
                            ("CLOSED", "Closed"),
                        ],
                        default="NEW",
                        max_length=50,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "original_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("te", "Telugu"),
                            ("es", "Spanish"),
                        ],
                        default="en",
                        help_text="Language in which the ticket was originally created",
                        max_length=10,
                        verbose_name="Original Language",
                    ),
                ),
                (
                    "ticketsource",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SYSTEMGENERATED", "New Generated"),
                            ("USERDEFINED", "User Defined"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("attachmentcount", models.IntegerField(null=True)),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="Sentiment score: 0=Very Negative, 5=Neutral, 10=Very Positive",
                        null=True,
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_negative", "Very Negative"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                            ("positive", "Positive"),
                            ("very_positive", "Very Positive"),
                        ],
                        help_text="Human-readable sentiment classification",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "emotion_detected",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detected emotions with scores: {anger: 0.8, frustration: 0.6, ...}",
                    ),
                ),
                (
                    "sentiment_analyzed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last sentiment analysis",
                        null=True,
                    ),
                ),
                (
                    "version",
                    concurrency.fields.VersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="activity.asset",
                    ),
                ),
                (
                    "assignedtogroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ticket_grps",
                        to="peoples.pgroup",
                    ),
                ),
                (
                    "assignedtopeople",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ticket_people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="client_onboarding.bt",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ticket_clients",
                        to="client_onboarding.bt",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="activity.location",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "performedby",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ticket_performedby",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="activity.questionset",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "ticketcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ticketcategory_types",
                        to="core_onboarding.typeassist",
                    ),
                ),
            ],
            options={
                "db_table": "ticket",
                "ordering": ["mdtz"],
                "get_latest_by": ["cdtz", "mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="File attachment",
                        max_length=500,
                        upload_to="helpdesk/attachments/%Y/%m/%d/",
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "content_type",
                    models.CharField(help_text="MIME type", max_length=100),
                ),
                (
                    "is_scanned",
                    models.BooleanField(
                        default=False,
                        help_text="Whether file has been scanned for viruses",
                    ),
                ),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Scan"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("error", "Scan Error"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "scan_details",
                    models.JSONField(
                        blank=True, help_text="Virus scan results", null=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("download_count", models.IntegerField(default=0)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="y_helpdesk.ticket",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_ticket_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Attachment",
                "verbose_name_plural": "Ticket Attachments",
                "db_table": "y_helpdesk_ticket_attachment",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketAuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of event (ticket_created, ticket_updated, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "event_category",
                    models.CharField(
                        choices=[
                            ("access", "Access Control"),
                            ("modification", "Data Modification"),
                            ("security", "Security Event"),
                            ("workflow", "Workflow Transition"),
                            ("escalation", "Escalation Event"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(help_text="Complete event details in JSON format"),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        help_text="Previous values for update events",
                        null=True,
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, help_text="New values for update events", null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integrity_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash for tamper detection",
                        max_length=64,
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of previous audit log entry (blockchain-style)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "retention_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Retention policy expiration date",
                        null=True,
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_audit_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="y_helpdesk.ticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Audit Log",
                "verbose_name_plural": "Ticket Audit Logs",
                "db_table": "y_helpdesk_audit_log",
                "ordering": ["-timestamp"],
                "permissions": [
                    ("view_audit_logs", "Can view audit logs"),
                    ("export_audit_logs", "Can export audit logs for compliance"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TicketWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "escalation_level",
                    models.IntegerField(
                        default=0, help_text="Current escalation level"
                    ),
                ),
                (
                    "is_escalated",
                    models.BooleanField(
                        default=False, help_text="Whether ticket has been escalated"
                    ),
                ),
                (
                    "escalation_count",
                    models.IntegerField(
                        default=0, help_text="Total number of escalations"
                    ),
                ),
                (
                    "last_escalated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When ticket was last escalated",
                        null=True,
                    ),
                ),
                (
                    "workflow_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        help_text="Current workflow status",
                        max_length=20,
                    ),
                ),
                (
                    "workflow_started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When workflow was initiated"
                    ),
                ),
                (
                    "workflow_completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When workflow was completed", null=True
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last activity timestamp"
                    ),
                ),
                (
                    "activity_count",
                    models.IntegerField(
                        default=0, help_text="Total number of activities"
                    ),
                ),
                (
                    "workflow_data",
                    models.JSONField(
                        default=apps.y_helpdesk.models.ticket_workflow.workflow_defaults,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Workflow history and metadata",
                    ),
                ),
                (
                    "response_time_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Time to first response in hours",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "resolution_time_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Time to resolution in hours",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        help_text="Related ticket for this workflow",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow",
                        to="y_helpdesk.ticket",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_workflow",
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EscalationMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("body", models.CharField(max_length=500, null=True)),
                ("level", models.IntegerField(blank=True, null=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MINUTE", "MINUTE"),
                            ("HOUR", "HOUR"),
                            ("DAY", "DAY"),
                            ("WEEK", "WEEK"),
                        ],
                        default="DAY",
                        max_length=10,
                    ),
                ),
                ("frequencyvalue", models.IntegerField(blank=True, null=True)),
                ("assignedfor", models.CharField(max_length=50)),
                ("notify", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "assignedgroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="escalation_grps",
                        to="peoples.pgroup",
                    ),
                ),
                (
                    "assignedperson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="escalation_people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="client_onboarding.bt",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="esc_clients",
                        to="client_onboarding.bt",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "escalationtemplate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="esc_types",
                        to="core_onboarding.typeassist",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="activity.job",
                        verbose_name="Job",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "escalationmatrix",
                "ordering": ["mdtz"],
                "get_latest_by": ["mdtz", "cdtz"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant", "job"], name="escmatrix_tenant_job_idx"
                    ),
                    models.Index(
                        fields=["tenant", "level"], name="escmatrix_tenant_level_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("frequencyvalue__gte", 0)),
                        name="frequencyvalue_gte_0_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("notify__isnull", True),
                            ("notify", ""),
                            (
                                "notify__regex",
                                "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
                            ),
                            _connector="OR",
                        ),
                        name="valid_notify_format",
                    ),
                ],
            },
            managers=[
                ("objects", apps.y_helpdesk.managers.EscalationMatrixManager()),
            ],
        ),
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "policy_id",
                    models.AutoField(
                        help_text="Unique policy identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "policy_name",
                    models.CharField(
                        help_text="Policy name (e.g., 'Standard Security SLA')",
                        max_length=255,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("P1", "Critical - P1"),
                            ("P2", "High - P2"),
                            ("P3", "Medium - P3"),
                            ("P4", "Low - P4"),
                        ],
                        help_text="Ticket priority level",
                        max_length=10,
                    ),
                ),
                (
                    "response_time_minutes",
                    models.IntegerField(
                        help_text="Target time for first response (in minutes)"
                    ),
                ),
                (
                    "resolution_time_minutes",
                    models.IntegerField(
                        help_text="Target time for resolution (in minutes)"
                    ),
                ),
                (
                    "escalation_threshold_minutes",
                    models.IntegerField(
                        help_text="Time before automatic escalation (in minutes)"
                    ),
                ),
                (
                    "exclude_weekends",
                    models.BooleanField(
                        default=True, help_text="Exclude weekends from SLA calculations"
                    ),
                ),
                (
                    "exclude_holidays",
                    models.BooleanField(
                        default=True, help_text="Exclude holidays from SLA calculations"
                    ),
                ),
                (
                    "business_hours_start",
                    models.TimeField(
                        default="09:00:00", help_text="Business day start time"
                    ),
                ),
                (
                    "business_hours_end",
                    models.TimeField(
                        default="18:00:00", help_text="Business day end time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Policy is active"),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Policy effective date",
                    ),
                ),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True, help_text="Policy expiration date", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Policy description"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Client (null = global policy)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_policies",
                        to="client_onboarding.bt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Policy",
                "verbose_name_plural": "SLA Policies",
                "db_table": "sla_policy",
                "ordering": ["priority", "client"],
                "indexes": [
                    models.Index(
                        fields=["client", "priority", "is_active"],
                        name="sla_policy_client__98872d_idx",
                    ),
                    models.Index(
                        fields=["priority", "is_active"],
                        name="sla_policy_priorit_0cf826_idx",
                    ),
                    models.Index(
                        fields=["effective_from", "effective_until"],
                        name="sla_policy_effecti_806afe_idx",
                    ),
                ],
                "unique_together": {("client", "priority")},
            },
        ),
        migrations.CreateModel(
            name="SLAPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        default="Ticket",
                        help_text="Type of item (Ticket, WorkOrder, etc.)",
                        max_length=50,
                    ),
                ),
                ("item_id", models.IntegerField(help_text="ID of the ticket/item")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "🟢 On Track"),
                            ("medium", "🟠 Soon"),
                            ("high", "🔴 Urgent"),
                        ],
                        default="low",
                        help_text="Priority level: low/medium/high",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.IntegerField(default=0, help_text="Risk score (0-100)"),
                ),
                (
                    "risk_factors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Why this needs attention: [{icon, message, severity}, ...]",
                    ),
                ),
                (
                    "suggested_actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="What to do: [{icon, text, action, priority}, ...]",
                    ),
                ),
                (
                    "is_acknowledged",
                    models.BooleanField(
                        default=False, help_text="User clicked 'I've got this'"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, help_text="When user acknowledged", null=True
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        auto_now=True, help_text="Last risk calculation"
                    ),
                ),
                (
                    "alert_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was sent", null=True
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who acknowledged",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="helpdesk_sla_predictions_acknowledged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this prediction",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="helpdesk_sla_prediction_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this prediction",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="helpdesk_sla_prediction_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priority Alert",
                "verbose_name_plural": "Priority Alerts",
                "db_table": "sla_prediction",
                "ordering": ["-confidence", "-last_checked"],
                "indexes": [
                    models.Index(
                        fields=["item_type", "item_id"],
                        name="sla_predict_item_ty_0dac6a_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "is_acknowledged"],
                        name="sla_predict_risk_le_2a73b6_idx",
                    ),
                    models.Index(
                        fields=["tenant", "risk_level"],
                        name="sla_predict_tenant__1ee764_idx",
                    ),
                    models.Index(
                        fields=["last_checked"], name="sla_predict_last_ch_264306_idx"
                    ),
                ],
                "unique_together": {("item_type", "item_id")},
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["tenant", "cdtz"], name="ticket_tenant_cdtz_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["tenant", "status"], name="ticket_tenant_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["tenant", "priority"], name="ticket_tenant_priority_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("tenant", "bu", "id", "client"), name="tenant_bu_id_uk"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketattachment",
            index=models.Index(
                fields=["ticket", "uploaded_at"], name="attachment_ticket_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketattachment",
            index=models.Index(
                fields=["uploaded_by", "uploaded_at"], name="attachment_user_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketattachment",
            index=models.Index(fields=["scan_status"], name="attachment_scan_idx"),
        ),
        migrations.AddIndex(
            model_name="ticketauditlog",
            index=models.Index(
                fields=["event_type", "timestamp"], name="audit_event_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketauditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="audit_user_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketauditlog",
            index=models.Index(
                fields=["ticket", "timestamp"], name="audit_ticket_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketauditlog",
            index=models.Index(
                fields=["tenant", "timestamp"], name="audit_tenant_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketauditlog",
            index=models.Index(
                fields=["severity_level", "timestamp"], name="audit_severity_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketworkflow",
            index=models.Index(
                fields=["escalation_level", "is_escalated"],
                name="ticket_work_escalat_bff3e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketworkflow",
            index=models.Index(
                fields=["workflow_status", "last_activity_at"],
                name="ticket_work_workflo_f0dc8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketworkflow",
            index=models.Index(
                fields=["ticket", "escalation_level"],
                name="ticket_work_ticket__05a4d2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketworkflow",
            constraint=models.CheckConstraint(
                condition=models.Q(("escalation_level__gte", 0)),
                name="escalation_level_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketworkflow",
            constraint=models.CheckConstraint(
                condition=models.Q(("escalation_count__gte", 0)),
                name="escalation_count_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketworkflow",
            constraint=models.CheckConstraint(
                condition=models.Q(("activity_count__gte", 0)),
                name="activity_count_non_negative",
            ),
        ),
    ]
