# Generated by Django 5.2.7 on 2025-11-09 10:20

import apps.peoples.models.base_model
import django.contrib.postgres.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HelpBotAnalytics",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "analytics_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("session_count", "Session Count"),
                            ("message_count", "Message Count"),
                            ("response_time", "Response Time"),
                            ("user_satisfaction", "User Satisfaction"),
                            ("knowledge_usage", "Knowledge Usage"),
                            ("error_rate", "Error Rate"),
                        ],
                        max_length=30,
                        verbose_name="Metric Type",
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        help_text="Numeric value of the metric", verbose_name="Value"
                    ),
                ),
                (
                    "dimension_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Breakdown dimensions (e.g., by category, user type, time period)",
                        verbose_name="Dimension Data",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date for this metric",
                        verbose_name="Date",
                    ),
                ),
                (
                    "hour",
                    models.IntegerField(
                        blank=True,
                        help_text="Hour of day (0-23) for hourly metrics",
                        null=True,
                        verbose_name="Hour",
                    ),
                ),
            ],
            options={
                "verbose_name": "HelpBot Analytics",
                "verbose_name_plural": "HelpBot Analytics",
                "db_table": "helpbot_analytics",
                "ordering": ["mdtz"],
                "get_latest_by": ["date", "cdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HelpBotContext",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "context_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "current_url",
                    models.URLField(
                        help_text="URL where user is seeking help",
                        verbose_name="Current URL",
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the current page",
                        max_length=200,
                        verbose_name="Page Title",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        blank=True,
                        help_text="Django app name (e.g., 'activity', 'peoples')",
                        max_length=50,
                        verbose_name="App Name",
                    ),
                ),
                (
                    "view_name",
                    models.CharField(
                        blank=True,
                        help_text="Django view name",
                        max_length=100,
                        verbose_name="View Name",
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        blank=True,
                        help_text="User's role/permission level",
                        max_length=50,
                        verbose_name="User Role",
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Current form data if user is on a form",
                        verbose_name="Form Data",
                    ),
                ),
                (
                    "error_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Error information if user encountered an error",
                        verbose_name="Error Context",
                    ),
                ),
                (
                    "user_journey",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Recent pages visited by the user",
                        verbose_name="User Journey",
                    ),
                ),
                (
                    "browser_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Browser and device information",
                        verbose_name="Browser Info",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this context was captured",
                        verbose_name="Timestamp",
                    ),
                ),
            ],
            options={
                "verbose_name": "HelpBot Context",
                "verbose_name_plural": "HelpBot Contexts",
                "db_table": "helpbot_context",
                "ordering": ["mdtz"],
                "get_latest_by": ["timestamp"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HelpBotFeedback",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "feedback_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                            ("incorrect", "Incorrect"),
                            ("incomplete", "Incomplete"),
                            ("suggestion", "Suggestion"),
                        ],
                        max_length=20,
                        verbose_name="Feedback Type",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Numeric rating (1-5)",
                        null=True,
                        verbose_name="Rating",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="User's detailed feedback",
                        null=True,
                        verbose_name="Comment",
                    ),
                ),
                (
                    "suggestion",
                    models.TextField(
                        blank=True,
                        help_text="User's suggestion for improvement",
                        null=True,
                        verbose_name="Suggestion",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Context when feedback was given",
                        verbose_name="Context Data",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this feedback has been processed for learning",
                        verbose_name="Is Processed",
                    ),
                ),
            ],
            options={
                "verbose_name": "HelpBot Feedback",
                "verbose_name_plural": "HelpBot Feedback",
                "db_table": "helpbot_feedback",
                "ordering": ["mdtz"],
                "get_latest_by": ["cdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HelpBotKnowledge",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "knowledge_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Human-readable title for this knowledge entry",
                        max_length=500,
                        verbose_name="Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The actual help content (markdown supported)",
                        verbose_name="Content",
                    ),
                ),
                (
                    "knowledge_type",
                    models.CharField(
                        choices=[
                            ("documentation", "Documentation"),
                            ("faq", "FAQ"),
                            ("tutorial", "Tutorial"),
                            ("api_reference", "API Reference"),
                            ("troubleshooting", "Troubleshooting"),
                            ("feature_guide", "Feature Guide"),
                            ("error_solution", "Error Solution"),
                        ],
                        default="documentation",
                        max_length=30,
                        verbose_name="Knowledge Type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("operations", "Operations"),
                            ("assets", "Assets"),
                            ("people", "People"),
                            ("helpdesk", "Help Desk"),
                            ("reports", "Reports"),
                            ("administration", "Administration"),
                            ("technical", "Technical"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Search tags and keywords",
                        size=None,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "related_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=500),
                        blank=True,
                        default=list,
                        help_text="Related application URLs or external links",
                        size=None,
                        verbose_name="Related URLs",
                    ),
                ),
                (
                    "search_keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Keywords that should trigger this knowledge",
                        size=None,
                        verbose_name="Search Keywords",
                    ),
                ),
                (
                    "embedding_vector",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        blank=True,
                        help_text="Vector embedding for semantic search",
                        null=True,
                        size=None,
                        verbose_name="Embedding Vector",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this knowledge has been accessed",
                        verbose_name="Usage Count",
                    ),
                ),
                (
                    "effectiveness_score",
                    models.FloatField(
                        default=0.5,
                        help_text="How effective this knowledge is based on user feedback (0.0 to 1.0)",
                        verbose_name="Effectiveness Score",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this knowledge entry is active and searchable",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        blank=True,
                        help_text="Original file path if imported from documentation",
                        max_length=500,
                        null=True,
                        verbose_name="Source File",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this knowledge was last updated",
                        verbose_name="Last Updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "HelpBot Knowledge",
                "verbose_name_plural": "HelpBot Knowledge",
                "db_table": "helpbot_knowledge",
                "ordering": ["mdtz"],
                "get_latest_by": ["last_updated", "mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HelpBotMessage",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "message_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user_text", "User Text"),
                            ("user_voice", "User Voice"),
                            ("bot_response", "Bot Response"),
                            ("system", "System Message"),
                            ("context", "Context Update"),
                        ],
                        max_length=20,
                        verbose_name="Message Type",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Raw message content (text or transcript)",
                        verbose_name="Content",
                    ),
                ),
                (
                    "rich_content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured content: links, code blocks, images, buttons",
                        verbose_name="Rich Content",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Technical metadata: confidence scores, processing time, sources",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "knowledge_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="References to knowledge sources used for this response",
                        verbose_name="Knowledge Sources",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI confidence in the response (0.0 to 1.0)",
                        null=True,
                        verbose_name="Confidence Score",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Time taken to generate the response",
                        null=True,
                        verbose_name="Processing Time (ms)",
                    ),
                ),
            ],
            options={
                "verbose_name": "HelpBot Message",
                "verbose_name_plural": "HelpBot Messages",
                "db_table": "helpbot_message",
                "ordering": ["cdtz"],
                "get_latest_by": ["cdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HelpBotSession",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("general_help", "General Help"),
                            ("feature_guide", "Feature Guide"),
                            ("troubleshooting", "Troubleshooting"),
                            ("api_docs", "API Documentation"),
                            ("tutorial", "Tutorial"),
                            ("onboarding", "Onboarding"),
                            ("security_facility", "Security & Facility Mentor"),
                        ],
                        default="general_help",
                        max_length=50,
                        verbose_name="Session Type",
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("waiting", "Waiting for Response"),
                            ("completed", "Completed"),
                            ("idle", "Idle"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Current State",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Current page context, user journey, and session metadata",
                        verbose_name="Context Data",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="User's preferred language for help content",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                (
                    "voice_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether voice interaction is enabled for this session",
                        verbose_name="Voice Enabled",
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of last user interaction",
                        verbose_name="Last Activity",
                    ),
                ),
                (
                    "total_messages",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of messages in this session",
                        verbose_name="Total Messages",
                    ),
                ),
                (
                    "satisfaction_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User satisfaction rating (1-5)",
                        null=True,
                        verbose_name="Satisfaction Rating",
                    ),
                ),
            ],
            options={
                "verbose_name": "HelpBot Session",
                "verbose_name_plural": "HelpBot Sessions",
                "db_table": "helpbot_session",
                "ordering": ["mdtz"],
                "get_latest_by": ["last_activity", "cdtz"],
                "abstract": False,
            },
        ),
    ]
