# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client_onboarding", "0003_initial"),
        ("helpbot", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="helpbotanalytics",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="helpbotanalytics",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="helpbotanalytics",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="helpbotcontext",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="helpbotcontext",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="helpbotcontext",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="helpbotcontext",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="helpbot_contexts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="helpbotfeedback",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="helpbotfeedback",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="helpbotfeedback",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="helpbotfeedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="helpbot_feedback",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="helpbotknowledge",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="helpbotknowledge",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="helpbotknowledge",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="helpbotmessage",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="helpbotmessage",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="helpbotmessage",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="helpbotfeedback",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="helpbot.helpbotmessage",
                verbose_name="Message",
            ),
        ),
        migrations.AddField(
            model_name="helpbotsession",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="helpbot_sessions",
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="helpbotsession",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="helpbotsession",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="helpbotsession",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="helpbotsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="helpbot_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="helpbotmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="helpbot.helpbotsession",
                verbose_name="Session",
            ),
        ),
        migrations.AddField(
            model_name="helpbotfeedback",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="helpbot.helpbotsession",
                verbose_name="Session",
            ),
        ),
        migrations.AddField(
            model_name="helpbotcontext",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contexts",
                to="helpbot.helpbotsession",
                verbose_name="Session",
            ),
        ),
        migrations.AddIndex(
            model_name="helpbotanalytics",
            index=models.Index(
                fields=["metric_type", "date"], name="hb_analytics_metric_dt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpbotanalytics",
            index=models.Index(
                fields=["date", "hour"], name="hb_analytics_date_hr_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="helpbotanalytics",
            unique_together={("metric_type", "date", "hour")},
        ),
        migrations.AddIndex(
            model_name="helpbotknowledge",
            index=models.Index(
                fields=["category", "knowledge_type"], name="hb_knowledge_cat_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpbotknowledge",
            index=models.Index(
                fields=["is_active", "effectiveness_score"],
                name="hb_knowledge_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="helpbotknowledge",
            index=models.Index(fields=["usage_count"], name="hb_knowledge_usage_idx"),
        ),
        migrations.AddIndex(
            model_name="helpbotsession",
            index=models.Index(
                fields=["user", "current_state"], name="helpbot_user_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpbotsession",
            index=models.Index(
                fields=["session_type", "last_activity"],
                name="helpbot_type_activity_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="helpbotsession",
            index=models.Index(fields=["last_activity"], name="helpbot_activity_idx"),
        ),
        migrations.AddIndex(
            model_name="helpbotmessage",
            index=models.Index(
                fields=["session", "cdtz"], name="helpbot_msg_session_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpbotmessage",
            index=models.Index(
                fields=["message_type", "cdtz"], name="helpbot_msg_type_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpbotfeedback",
            index=models.Index(
                fields=["session", "feedback_type"], name="hb_feedback_sess_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpbotfeedback",
            index=models.Index(
                fields=["is_processed", "cdtz"], name="hb_feedback_processed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpbotcontext",
            index=models.Index(
                fields=["user", "timestamp"], name="helpbot_context_user_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpbotcontext",
            index=models.Index(
                fields=["app_name", "view_name"], name="helpbot_context_app_view_idx"
            ),
        ),
    ]
