# Generated by Django 5.2.7 on 2025-11-09 10:20

import apps.peoples.models.base_model
import django.contrib.postgres.fields
import django.core.serializers.json
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AntiSpoofingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("TEXTURE_BASED", "Texture-based"),
                            ("MOTION_BASED", "Motion-based"),
                            ("DEPTH_BASED", "Depth-based"),
                            ("CHALLENGE_RESPONSE", "Challenge-Response"),
                            ("MULTI_MODAL", "Multi-modal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "liveness_threshold",
                    models.FloatField(
                        default=0.5, help_text="Threshold for liveness classification"
                    ),
                ),
                ("true_positive_rate", models.FloatField(blank=True, null=True)),
                ("false_positive_rate", models.FloatField(blank=True, null=True)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                (
                    "model_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "requires_motion",
                    models.BooleanField(
                        default=False,
                        help_text="Whether model requires motion detection",
                    ),
                ),
                (
                    "requires_user_interaction",
                    models.BooleanField(
                        default=False,
                        help_text="Whether model requires user interaction",
                    ),
                ),
                ("detection_count", models.BigIntegerField(default=0)),
                ("spoof_detections", models.BigIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Anti-Spoofing Model",
                "verbose_name_plural": "Anti-Spoofing Models",
                "db_table": "anti_spoofing_model",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BiometricAuditLog",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("operation_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("enrollment", "Biometric Enrollment"),
                            ("verification", "Biometric Verification"),
                            ("identification", "Biometric Identification"),
                            ("update", "Biometric Data Update"),
                            ("deletion", "Biometric Data Deletion"),
                            ("access", "Biometric Data Access"),
                        ],
                        max_length=50,
                    ),
                ),
                ("operation_success", models.BooleanField()),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        help_text="Operation processing time in milliseconds"
                    ),
                ),
                ("request_id", models.UUIDField(help_text="Unique request ID")),
                (
                    "session_id",
                    models.CharField(help_text="User session ID", max_length=255),
                ),
                (
                    "api_endpoint",
                    models.CharField(help_text="API endpoint called", max_length=255),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Error code if operation failed",
                        max_length=50,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message (sanitized, no PII)"
                    ),
                ),
                (
                    "consent_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether consent was validated before operation",
                    ),
                ),
                (
                    "retention_policy_applied",
                    models.BooleanField(
                        default=False, help_text="Whether retention policy was applied"
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric Audit Log",
                "verbose_name_plural": "Biometric Audit Logs",
                "db_table": "biometric_audit_log",
                "ordering": ["-operation_timestamp"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BiometricConsentLog",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("face_recognition", "Face Recognition"),
                            ("voice_recognition", "Voice Recognition"),
                            ("fingerprint", "Fingerprint"),
                            ("behavioral", "Behavioral Biometrics"),
                        ],
                        help_text="Type of biometric data",
                        max_length=50,
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False, help_text="Whether consent was given"
                    ),
                ),
                (
                    "consent_timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When consent was given or withdrawn",
                    ),
                ),
                (
                    "consent_method",
                    models.CharField(
                        help_text="How consent was obtained (e.g., 'mobile_app', 'web_portal')",
                        max_length=100,
                    ),
                ),
                (
                    "processing_purpose",
                    models.TextField(
                        help_text="Specific purpose for biometric processing (GDPR Article 5(1)(b))"
                    ),
                ),
                (
                    "data_retention_period",
                    models.IntegerField(
                        default=2555,
                        help_text="Data retention period in days (default: 7 years for BIPA)",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("enrollment", "Biometric Enrollment"),
                            ("verification", "Biometric Verification"),
                            ("identification", "Biometric Identification"),
                            ("update", "Biometric Data Update"),
                            ("deletion", "Biometric Data Deletion"),
                            ("access", "Biometric Data Access"),
                        ],
                        help_text="Type of biometric operation performed",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "operation_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the biometric operation was performed",
                        null=True,
                    ),
                ),
                (
                    "operation_success",
                    models.BooleanField(
                        default=True, help_text="Whether the operation succeeded"
                    ),
                ),
                (
                    "operation_details",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Additional operation metadata (no PII)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string"),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Correlation ID for request tracing",
                    ),
                ),
                (
                    "consent_withdrawn",
                    models.BooleanField(
                        default=False, help_text="Whether consent has been withdrawn"
                    ),
                ),
                (
                    "withdrawal_timestamp",
                    models.DateTimeField(
                        blank=True, help_text="When consent was withdrawn", null=True
                    ),
                ),
                (
                    "withdrawal_method",
                    models.CharField(
                        blank=True,
                        help_text="How consent was withdrawn",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric Consent Log",
                "verbose_name_plural": "Biometric Consent Logs",
                "db_table": "biometric_consent_log",
                "ordering": ["-consent_timestamp"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FaceEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "embedding_vector",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        help_text="Face embedding vector",
                        size=512,
                    ),
                ),
                (
                    "source_image_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "source_image_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "face_confidence",
                    models.FloatField(help_text="Confidence of face detection (0-1)"),
                ),
                (
                    "image_quality_score",
                    models.FloatField(
                        blank=True,
                        help_text="Quality score of source image (0-1)",
                        null=True,
                    ),
                ),
                ("extraction_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "face_landmarks",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Detected face landmarks",
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary embedding for the user",
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this embedding has been validated",
                    ),
                ),
                ("validation_score", models.FloatField(blank=True, null=True)),
                ("verification_count", models.IntegerField(default=0)),
                ("successful_matches", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Face Embedding",
                "verbose_name_plural": "Face Embeddings",
                "db_table": "face_embedding",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FaceQualityMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("image_path", models.CharField(max_length=500, unique=True)),
                ("image_hash", models.CharField(max_length=64, unique=True)),
                (
                    "overall_quality",
                    models.FloatField(help_text="Overall image quality score"),
                ),
                (
                    "sharpness_score",
                    models.FloatField(help_text="Image sharpness score"),
                ),
                (
                    "brightness_score",
                    models.FloatField(help_text="Brightness adequacy score"),
                ),
                (
                    "contrast_score",
                    models.FloatField(help_text="Contrast adequacy score"),
                ),
                (
                    "face_size_score",
                    models.FloatField(help_text="Face size adequacy score"),
                ),
                (
                    "face_pose_score",
                    models.FloatField(help_text="Face pose quality score"),
                ),
                (
                    "eye_visibility_score",
                    models.FloatField(help_text="Eye visibility score"),
                ),
                ("resolution_width", models.IntegerField()),
                ("resolution_height", models.IntegerField()),
                ("file_size_bytes", models.BigIntegerField()),
                ("face_detection_confidence", models.FloatField()),
                (
                    "landmark_quality",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Quality of detected landmarks",
                    ),
                ),
                ("analysis_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_model_version",
                    models.CharField(default="1.0", max_length=50),
                ),
                (
                    "quality_issues",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Identified quality issues",
                        size=None,
                    ),
                ),
                (
                    "improvement_suggestions",
                    models.JSONField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Suggestions for improvement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Quality Metrics",
                "verbose_name_plural": "Face Quality Metrics",
                "db_table": "face_quality_metrics",
            },
        ),
        migrations.CreateModel(
            name="FaceRecognitionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System Configuration"),
                            ("SECURITY", "Security Settings"),
                            ("PERFORMANCE", "Performance Settings"),
                            ("INTEGRATION", "Integration Settings"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "config_data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Configuration parameters",
                    ),
                ),
                (
                    "applies_to_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Location codes this configuration applies to",
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Configuration priority (lower = higher priority)",
                    ),
                ),
                ("last_validated", models.DateTimeField(blank=True, null=True)),
                (
                    "validation_errors",
                    models.JSONField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Configuration validation errors",
                    ),
                ),
                ("applied_count", models.IntegerField(default=0)),
                ("last_applied", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Face Recognition Configuration",
                "verbose_name_plural": "Face Recognition Configurations",
                "db_table": "face_recognition_config",
                "ordering": ["priority", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FaceRecognitionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("FACENET512", "FaceNet512"),
                            ("ARCFACE", "ArcFace"),
                            ("INSIGHTFACE", "InsightFace"),
                            ("ENSEMBLE", "Ensemble Model"),
                            ("CUSTOM", "Custom Model"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("TRAINING", "Training"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "similarity_threshold",
                    models.FloatField(
                        default=0.3,
                        help_text="Cosine distance threshold for face matching",
                    ),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(
                        default=0.7, help_text="Minimum confidence for face detection"
                    ),
                ),
                ("liveness_detection_enabled", models.BooleanField(default=True)),
                (
                    "liveness_threshold",
                    models.FloatField(
                        default=0.5, help_text="Threshold for liveness detection"
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, help_text="Model accuracy (0-1)", null=True
                    ),
                ),
                ("false_acceptance_rate", models.FloatField(blank=True, null=True)),
                ("false_rejection_rate", models.FloatField(blank=True, null=True)),
                ("processing_time_ms", models.FloatField(blank=True, null=True)),
                (
                    "model_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "weights_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("verification_count", models.BigIntegerField(default=0)),
                ("successful_verifications", models.BigIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "training_dataset_info",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Information about training dataset",
                    ),
                ),
                (
                    "hyperparameters",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Model hyperparameters",
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Recognition Model",
                "verbose_name_plural": "Face Recognition Models",
                "db_table": "face_recognition_model",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FaceVerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("verification_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Verification Successful"),
                            ("FAILED", "Verification Failed"),
                            ("ERROR", "Verification Error"),
                            ("REJECTED", "Rejected by Anti-spoofing"),
                            ("NO_FACE", "No Face Detected"),
                            ("MULTIPLE_FACES", "Multiple Faces Detected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        blank=True,
                        help_text="Similarity score (1 - cosine distance)",
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Overall confidence in verification",
                        null=True,
                    ),
                ),
                (
                    "liveness_score",
                    models.FloatField(
                        blank=True, help_text="Liveness detection score", null=True
                    ),
                ),
                ("spoof_detected", models.BooleanField(default=False)),
                (
                    "input_image_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "input_image_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("face_detection_confidence", models.FloatField(blank=True, null=True)),
                ("processing_time_ms", models.FloatField(blank=True, null=True)),
                ("model_load_time_ms", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "verification_metadata",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Detailed verification metadata",
                    ),
                ),
                (
                    "fraud_indicators",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Detected fraud indicators",
                        size=None,
                    ),
                ),
                (
                    "fraud_risk_score",
                    models.FloatField(
                        default=0.0, help_text="Calculated fraud risk score (0-1)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Verification Log",
                "verbose_name_plural": "Face Verification Logs",
                "db_table": "face_verification_log",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
    ]
