# Generated by Django 5.2.1 on 2025-09-04 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0003_initial'),
        ('face_recognition', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='antispoofingmodel',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antispoofingmodel',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antispoofingmodel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facequalitymetrics',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facequalitymetrics',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facerecognitionconfig',
            name='applies_to_users',
            field=models.ManyToManyField(blank=True, help_text='Users this configuration applies to (empty = all users)', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facerecognitionconfig',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facerecognitionconfig',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facerecognitionconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='facerecognitionmodel',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facerecognitionmodel',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facerecognitionmodel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='extraction_model',
            field=models.ForeignKey(help_text='Model used to extract this embedding', on_delete=django.db.models.deletion.PROTECT, to='face_recognition.facerecognitionmodel'),
        ),
        migrations.AddField(
            model_name='faceverificationlog',
            name='attendance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.peopleeventlog'),
        ),
        migrations.AddField(
            model_name='faceverificationlog',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faceverificationlog',
            name='matched_embedding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='face_recognition.faceembedding'),
        ),
        migrations.AddField(
            model_name='faceverificationlog',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faceverificationlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='faceverificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faceverificationlog',
            name='verification_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='face_recognition.facerecognitionmodel'),
        ),
        migrations.AddIndex(
            model_name='facequalitymetrics',
            index=models.Index(fields=['overall_quality', 'analysis_timestamp'], name='face_qualit_overall_d2d5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='facequalitymetrics',
            index=models.Index(fields=['image_hash'], name='face_qualit_image_h_0ff443_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['user', 'is_primary'], name='face_embedd_user_id_70e69c_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['extraction_model', 'is_validated'], name='face_embedd_extract_b44013_idx'),
        ),
        migrations.AddIndex(
            model_name='faceverificationlog',
            index=models.Index(fields=['user', 'verification_timestamp'], name='face_verifi_user_id_51693e_idx'),
        ),
        migrations.AddIndex(
            model_name='faceverificationlog',
            index=models.Index(fields=['result', 'verification_timestamp'], name='face_verifi_result_3bcf6c_idx'),
        ),
        migrations.AddIndex(
            model_name='faceverificationlog',
            index=models.Index(fields=['fraud_risk_score', 'spoof_detected'], name='face_verifi_fraud_r_55ac0b_idx'),
        ),
    ]
