# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("client_onboarding", "0002_initial"),
        ("core_onboarding", "0001_initial"),
        ("site_onboarding", "0001_initial"),
        ("tenants", "0001_initial"),
        ("y_helpdesk", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alertescalation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="alertescalation",
            name="escalated_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Original recipient who didn't respond",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalations_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertescalation",
            name="escalated_to",
            field=models.ForeignKey(
                help_text="Person escalated to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalations_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertescalation",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="alertescalation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="applies_to_shifts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Shifts this rule applies to (empty = all shifts)",
                related_name="alert_rules",
                to="client_onboarding.shift",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="applies_to_sites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sites this rule applies to (empty = all sites)",
                related_name="alert_rules",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="escalation_recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="People to escalate to if not acknowledged",
                related_name="alert_rule_escalations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="notification_recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="People to notify when this alert triggers",
                related_name="alert_rule_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="approvalaction",
            name="action_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Person who took this action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_approval_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="approvalaction",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="approvalaction",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="related_shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Shift related to this request",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="client_onboarding.shift",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="related_site",
            field=models.ForeignKey(
                blank=True,
                help_text="Site related to this request",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="related_ticket",
            field=models.ForeignKey(
                blank=True,
                help_text="Helpdesk ticket that triggered this request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_requests",
                to="y_helpdesk.ticket",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="requested_by",
            field=models.ForeignKey(
                help_text="Worker or supervisor who submitted request",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests_submitted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="requested_for",
            field=models.ForeignKey(
                blank=True,
                help_text="Worker who will benefit from approval (if different from requester)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests_for",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor who reviewed this request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_requests_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this approval request",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_approval_requests",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="approvalaction",
            name="approval_request",
            field=models.ForeignKey(
                help_text="Approval request this action belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="attendance.approvalrequest",
            ),
        ),
        migrations.AddField(
            model_name="attendanceaccesslog",
            name="impersonated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who impersonated another user (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="impersonated_attendance_access_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendanceaccesslog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="attendanceaccesslog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_access_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancealert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who acknowledged this alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts_acknowledged",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancealert",
            name="alert_rule",
            field=models.ForeignKey(
                help_text="Rule that triggered this alert",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="attendance.alertrule",
            ),
        ),
        migrations.AddField(
            model_name="attendancealert",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="attendancealert",
            name="escalated_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="People alert was escalated to",
                related_name="escalated_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancealert",
            name="related_ticket",
            field=models.ForeignKey(
                blank=True,
                help_text="Helpdesk ticket created for this alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_alerts",
                to="y_helpdesk.ticket",
            ),
        ),
        migrations.AddField(
            model_name="attendancealert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who resolved this alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts_resolved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancealert",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="attendancealert",
            name="triggered_for_site",
            field=models.ForeignKey(
                blank=True,
                help_text="Site this alert is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="attendancealert",
            name="triggered_for_worker",
            field=models.ForeignKey(
                blank=True,
                help_text="Worker this alert is about",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts_for",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancealert",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="alertescalation",
            name="alert",
            field=models.ForeignKey(
                help_text="Alert that was escalated",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalations",
                to="attendance.attendancealert",
            ),
        ),
        migrations.AddField(
            model_name="attendancephoto",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="attendancephoto",
            name="employee",
            field=models.ForeignKey(
                help_text="Employee in the photo",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancephoto",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="attendancephoto",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="autoapprovalrule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who created this rule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auto_approval_rules_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="autoapprovalrule",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="autoapprovalrule",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="auto_approval_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Auto-approval rule that was applied",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_requests",
                to="attendance.autoapprovalrule",
            ),
        ),
        migrations.AddField(
            model_name="consentpolicy",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="consentpolicy",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="consentpolicy",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="consentrequirement",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                help_text="Apply to specific BU (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_requirements_bu",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="consentrequirement",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Apply to specific client (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_requirements_client",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="consentrequirement",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="consentrequirement",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="consentrequirement",
            name="policy",
            field=models.ForeignKey(
                help_text="Policy that is required",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="attendance.consentpolicy",
            ),
        ),
        migrations.AddField(
            model_name="consentrequirement",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="employeeconsentlog",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="employeeconsentlog",
            name="employee",
            field=models.ForeignKey(
                help_text="Employee giving consent",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeeconsentlog",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="employeeconsentlog",
            name="policy",
            field=models.ForeignKey(
                help_text="Policy being consented to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consent_logs",
                to="attendance.consentpolicy",
            ),
        ),
        migrations.AddField(
            model_name="employeeconsentlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Manager assigned to investigate",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_fraud_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="employee",
            field=models.ForeignKey(
                help_text="Employee flagged for suspicious activity",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fraud_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_fraud_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_geofence_clients",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="bus",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="checkin_photo",
            field=models.ForeignKey(
                blank=True,
                help_text="Photo captured during clock-in",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkin_attendance_records",
                to="attendance.attendancephoto",
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="checkout_photo",
            field=models.ForeignKey(
                blank=True,
                help_text="Photo captured during clock-out",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkout_attendance_records",
                to="attendance.attendancephoto",
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="clients",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="geofence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core_onboarding.geofencemaster",
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="people",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="People",
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="peventtype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core_onboarding.typeassist",
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="client_onboarding.shift",
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="verifiedby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="verifiedpeoples",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verified By",
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="attendance_record",
            field=models.ForeignKey(
                help_text="Attendance record that triggered alert",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fraud_alerts",
                to="attendance.peopleeventlog",
            ),
        ),
        migrations.AddField(
            model_name="attendancephoto",
            name="attendance_record",
            field=models.ForeignKey(
                help_text="Attendance record this photo belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="attendance.peopleeventlog",
            ),
        ),
        migrations.AddField(
            model_name="attendanceaccesslog",
            name="attendance_record",
            field=models.ForeignKey(
                blank=True,
                help_text="Attendance record that was accessed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_logs",
                to="attendance.peopleeventlog",
            ),
        ),
        migrations.AddField(
            model_name="photoqualitythreshold",
            name="client",
            field=models.ForeignKey(
                help_text="Client this threshold applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_quality_thresholds",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this post",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="geofence",
            field=models.ForeignKey(
                blank=True,
                help_text="Geographic boundary for GPS validation at this post",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="attendance.geofence",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this post",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="required_certifications",
            field=models.ManyToManyField(
                blank=True,
                help_text="Certifications required to work this post",
                limit_choices_to={"tatype__tacode": "CERTIFICATION"},
                related_name="required_for_posts",
                to="core_onboarding.typeassist",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="shift",
            field=models.ForeignKey(
                help_text="Shift that operates this post",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="client_onboarding.shift",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="site",
            field=models.ForeignKey(
                help_text="Site where this post is located",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to site zone definition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="site_onboarding.onboardingzone",
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="post",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific duty station worker checked into (Phase 2)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="attendance.post",
            ),
        ),
        migrations.AddField(
            model_name="attendancealert",
            name="triggered_for_post",
            field=models.ForeignKey(
                blank=True,
                help_text="Post this alert is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="attendance.post",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="related_post",
            field=models.ForeignKey(
                blank=True,
                help_text="Post related to this request",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="attendance.post",
            ),
        ),
        migrations.AddField(
            model_name="postassignment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Manager who approved this assignment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor who created this assignment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postassignment",
            name="attendance_record",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to actual attendance check-in/out record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_post_assignment_links",
                to="attendance.peopleeventlog",
            ),
        ),
        migrations.AddField(
            model_name="postassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="postassignment",
            name="post",
            field=models.ForeignKey(
                help_text="Duty station where worker will be posted",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="attendance.post",
            ),
        ),
        migrations.AddField(
            model_name="postassignment",
            name="replaced_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="If this replaces another assignment, link to original",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replacement_assignments",
                to="attendance.postassignment",
            ),
        ),
        migrations.AddField(
            model_name="postassignment",
            name="shift",
            field=models.ForeignKey(
                help_text="Shift for this assignment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_assignments",
                to="client_onboarding.shift",
            ),
        ),
        migrations.AddField(
            model_name="postassignment",
            name="site",
            field=models.ForeignKey(
                help_text="Site (denormalized from post for query performance)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_assignments",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="postassignment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="postassignment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="postassignment",
            name="worker",
            field=models.ForeignKey(
                help_text="Worker assigned to this post",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="peopleeventlog",
            name="post_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to scheduled post assignment (Phase 2)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="attendance.postassignment",
            ),
        ),
        migrations.AddField(
            model_name="attendancealert",
            name="triggered_for_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Assignment this alert is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="attendance.postassignment",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="related_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="PostAssignment related to this request",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="attendance.postassignment",
            ),
        ),
        migrations.AddField(
            model_name="postorderacknowledgement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="postorderacknowledgement",
            name="post",
            field=models.ForeignKey(
                help_text="Post whose orders were acknowledged",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acknowledgements",
                to="attendance.post",
            ),
        ),
        migrations.AddField(
            model_name="postorderacknowledgement",
            name="post_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Assignment this acknowledgement is for (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_order_acknowledgements",
                to="attendance.postassignment",
            ),
        ),
        migrations.AddField(
            model_name="postorderacknowledgement",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="postorderacknowledgement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="postorderacknowledgement",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor who verified acknowledgement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_acknowledgements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postorderacknowledgement",
            name="worker",
            field=models.ForeignKey(
                help_text="Worker who acknowledged post orders",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_order_acknowledgements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncconflict",
            name="attendance_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_conflicts",
                to="attendance.peopleeventlog",
            ),
        ),
        migrations.AddField(
            model_name="syncconflict",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="syncconflict",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_conflicts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncconflict",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="syncconflict",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_sync_conflicts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncconflict",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tracking",
            name="people",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="People",
            ),
        ),
        migrations.AddField(
            model_name="userbehaviorprofile",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="userbehaviorprofile",
            name="employee",
            field=models.OneToOneField(
                help_text="Employee this profile belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_behavior_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userbehaviorprofile",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="userbehaviorprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["tenant", "active", "alert_type"], name="ar_active_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(fields=["tenant", "severity"], name="ar_severity_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalaction",
            index=models.Index(
                fields=["tenant", "approval_request", "action_at"],
                name="aa_request_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalaction",
            index=models.Index(
                fields=["tenant", "action_by", "action_at"], name="aa_actor_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertescalation",
            index=models.Index(
                fields=["tenant", "alert", "escalated_at"], name="ae_alert_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertescalation",
            index=models.Index(
                fields=["tenant", "escalated_to", "acknowledged"],
                name="ae_recipient_ack_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="autoapprovalrule",
            index=models.Index(fields=["tenant", "active"], name="aar_active_idx"),
        ),
        migrations.AddIndex(
            model_name="autoapprovalrule",
            index=models.Index(fields=["rule_code"], name="aar_code_idx"),
        ),
        migrations.AddIndex(
            model_name="consentpolicy",
            index=models.Index(
                fields=["tenant", "policy_type", "is_active"],
                name="cp_tenant_type_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consentpolicy",
            index=models.Index(fields=["effective_date"], name="cp_effective_date_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="consentpolicy",
            unique_together={("policy_type", "state", "version")},
        ),
        migrations.AddIndex(
            model_name="consentrequirement",
            index=models.Index(
                fields=["tenant", "is_active"], name="cr_tenant_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consentrequirement",
            index=models.Index(fields=["client"], name="cr_client_idx"),
        ),
        migrations.AddIndex(
            model_name="consentrequirement",
            index=models.Index(fields=["bu"], name="cr_bu_idx"),
        ),
        migrations.AddIndex(
            model_name="employeeconsentlog",
            index=models.Index(
                fields=["tenant", "employee", "status"],
                name="ecl_tenant_emp_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeeconsentlog",
            index=models.Index(
                fields=["tenant", "policy", "status"],
                name="ecl_tenant_policy_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeeconsentlog",
            index=models.Index(
                fields=["status", "expires_at"], name="ecl_status_expires_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeconsentlog",
            index=models.Index(fields=["granted_at"], name="ecl_granted_at_idx"),
        ),
        migrations.AddIndex(
            model_name="geofence",
            index=models.Index(
                fields=["tenant", "is_active"], name="geofence_tenant_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geofence",
            index=models.Index(fields=["tenant", "bu"], name="geofence_tenant_bu_idx"),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(
                fields=["tenant", "status"], name="fa_tenant_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(fields=["tenant", "employee"], name="fa_tenant_emp_idx"),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(
                fields=["severity", "status"], name="fa_severity_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(
                fields=["assigned_to", "status"], name="fa_assigned_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(
                fields=["detection_timestamp"], name="fa_detection_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancephoto",
            index=models.Index(
                fields=["tenant", "employee", "captured_at"],
                name="ap_tenant_emp_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancephoto",
            index=models.Index(
                fields=["tenant", "attendance_record"], name="ap_tenant_record_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancephoto",
            index=models.Index(fields=["delete_after"], name="ap_delete_after_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancephoto",
            index=models.Index(fields=["is_deleted"], name="ap_is_deleted_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancephoto",
            index=models.Index(fields=["validation_passed"], name="ap_validation_idx"),
        ),
        migrations.AddIndex(
            model_name="attendanceaccesslog",
            index=models.Index(
                fields=["tenant", "timestamp"], name="aal_tenant_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceaccesslog",
            index=models.Index(
                fields=["tenant", "user", "timestamp"], name="aal_tenant_user_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceaccesslog",
            index=models.Index(
                fields=["tenant", "attendance_record"], name="aal_tenant_record_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceaccesslog",
            index=models.Index(
                fields=["tenant", "action"], name="aal_tenant_action_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceaccesslog",
            index=models.Index(fields=["correlation_id"], name="aal_correlation_idx"),
        ),
        migrations.AddIndex(
            model_name="attendanceaccesslog",
            index=models.Index(fields=["is_suspicious"], name="aal_suspicious_idx"),
        ),
        migrations.AddIndex(
            model_name="attendanceaccesslog",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["timestamp"], name="aal_timestamp_brin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["tenant", "site", "shift", "active"],
                name="post_active_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["tenant", "site", "post_type"], name="post_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["tenant", "active", "coverage_required"],
                name="post_coverage_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["tenant", "risk_level"], name="post_risk_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={
                ("site", "post_code", "tenant"),
                ("site", "shift", "post_name", "tenant"),
            },
        ),
        migrations.AddIndex(
            model_name="postassignment",
            index=models.Index(
                fields=["tenant", "assignment_date", "site", "status"],
                name="pa_daily_site_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postassignment",
            index=models.Index(
                fields=["tenant", "worker", "assignment_date"],
                name="pa_worker_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postassignment",
            index=models.Index(
                fields=["tenant", "post", "assignment_date"], name="pa_post_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postassignment",
            index=models.Index(
                fields=["tenant", "status", "assignment_date"],
                name="pa_status_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postassignment",
            index=models.Index(
                fields=["tenant", "is_override", "assignment_date"],
                name="pa_override_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postassignment",
            unique_together={("worker", "post", "assignment_date", "shift", "tenant")},
        ),
        migrations.AddIndex(
            model_name="peopleeventlog",
            index=models.Index(fields=["tenant", "cdtz"], name="pel_tenant_cdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="peopleeventlog",
            index=models.Index(
                fields=["tenant", "people"], name="pel_tenant_people_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="peopleeventlog",
            index=models.Index(
                fields=["tenant", "datefor"], name="pel_tenant_datefor_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="peopleeventlog",
            index=models.Index(fields=["tenant", "bu"], name="pel_tenant_bu_idx"),
        ),
        migrations.AddIndex(
            model_name="peopleeventlog",
            index=models.Index(
                fields=["tenant", "people", "shift", "datefor"],
                name="pel_validation_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="peopleeventlog",
            index=models.Index(
                fields=["tenant", "bu", "datefor", "shift"], name="pel_site_shift_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="peopleeventlog",
            index=models.Index(
                fields=["tenant", "people", "punchouttime"], name="pel_rest_period_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="peopleeventlog",
            index=models.Index(
                fields=["tenant", "people", "datefor", "punchouttime"],
                name="pel_duplicate_check_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="peopleeventlog",
            index=models.Index(
                fields=["tenant", "fraud_score"], name="pel_fraud_score_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="peopleeventlog",
            index=models.Index(
                fields=["tenant", "is_archived", "datefor"],
                name="pel_archived_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="peopleeventlog",
            index=models.Index(
                fields=["tenant", "gps_purged"], name="pel_gps_purged_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancealert",
            index=models.Index(
                fields=["tenant", "status", "triggered_at"], name="aa_status_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancealert",
            index=models.Index(
                fields=["tenant", "severity", "status"], name="aa_severity_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancealert",
            index=models.Index(
                fields=["tenant", "triggered_for_site", "status"],
                name="aa_site_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancealert",
            index=models.Index(
                fields=["tenant", "triggered_for_worker", "status"],
                name="aa_worker_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancealert",
            index=models.Index(
                fields=["tenant", "alert_rule", "triggered_at"], name="aa_rule_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancealert",
            index=models.Index(
                fields=["tenant", "escalated", "status"], name="aa_escalated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["tenant", "status", "requested_at"], name="ar_status_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["tenant", "requested_by", "status"],
                name="ar_requester_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["tenant", "reviewed_by", "reviewed_at"],
                name="ar_reviewer_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["tenant", "expires_at", "status"], name="ar_expiration_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["tenant", "request_type", "status"], name="ar_type_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postorderacknowledgement",
            index=models.Index(
                fields=["tenant", "worker", "acknowledged_at"],
                name="poa_worker_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postorderacknowledgement",
            index=models.Index(
                fields=["tenant", "post", "post_orders_version"],
                name="poa_post_version_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postorderacknowledgement",
            index=models.Index(
                fields=["tenant", "acknowledgement_date", "is_valid"],
                name="poa_date_valid_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postorderacknowledgement",
            index=models.Index(
                fields=["tenant", "is_valid", "valid_until"], name="poa_validity_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postorderacknowledgement",
            unique_together={
                (
                    "worker",
                    "post",
                    "post_orders_version",
                    "acknowledgement_date",
                    "tenant",
                )
            },
        ),
        migrations.AddIndex(
            model_name="syncconflict",
            index=models.Index(fields=["tenant", "employee"], name="sc_tenant_emp_idx"),
        ),
        migrations.AddIndex(
            model_name="syncconflict",
            index=models.Index(fields=["detected_at"], name="sc_detected_idx"),
        ),
        migrations.AddIndex(
            model_name="syncconflict",
            index=models.Index(fields=["user_notified"], name="sc_notified_idx"),
        ),
        migrations.AddIndex(
            model_name="tracking",
            index=models.Index(
                fields=["people", "receiveddate"], name="tracking_people__1226ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tracking",
            index=models.Index(
                fields=["identifier", "receiveddate"],
                name="tracking_identif_903fb7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tracking",
            index=models.Index(fields=["deviceid"], name="tracking_devicei_7cf95b_idx"),
        ),
        migrations.AddIndex(
            model_name="userbehaviorprofile",
            index=models.Index(
                fields=["tenant", "employee"], name="ubp_tenant_emp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbehaviorprofile",
            index=models.Index(
                fields=["is_baseline_sufficient"], name="ubp_baseline_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbehaviorprofile",
            index=models.Index(fields=["baseline_updated_at"], name="ubp_updated_idx"),
        ),
    ]
