# Generated by Django 5.2.1 on 2025-11-03
# Migration to implement biometric template encryption for HIPAA compliance

from django.db import migrations
import apps.core.fields.encrypted_json_field
from django.core.serializers.json import DjangoJSONEncoder
import apps.attendance.models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_add_geofence_spatial_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleeventlog',
            name='peventlogextras',
            field=apps.core.fields.encrypted_json_field.EncryptedJSONField(
                default=apps.attendance.models.peventlog_json,
                encoder=DjangoJSONEncoder,
                help_text='Encrypted JSON field for face recognition, geofence, and verification data (biometric templates)',
                verbose_name='peventlogextras'
            ),
        ),
    ]
