# Generated by Django 5.2.1 on 2025-11-03
# Migration to add comprehensive audit logging for attendance access

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.contrib.postgres.operations import BrinIndexConcurrently


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_encrypt_biometric_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(
                    choices=[
                        ('ATTENDANCE_RECORD', 'Attendance Record'),
                        ('GEOFENCE', 'Geofence'),
                        ('ATTENDANCE_PHOTO', 'Attendance Photo'),
                        ('BIOMETRIC_TEMPLATE', 'Biometric Template'),
                        ('AUDIT_LOG', 'Audit Log'),
                    ],
                    help_text='Type of resource this policy applies to',
                    max_length=50,
                    unique=True
                )),
                ('retention_days', models.IntegerField(
                    default=2190,
                    help_text='Number of days to retain audit logs'
                )),
                ('archive_after_days', models.IntegerField(
                    default=730,
                    help_text='Number of days before archiving logs'
                )),
                ('is_active', models.BooleanField(
                    default=True,
                    help_text='Whether this policy is currently active'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit Log Retention Policy',
                'verbose_name_plural': 'Audit Log Retention Policies',
                'db_table': 'audit_log_retention_policy',
            },
        ),
        migrations.CreateModel(
            name='AttendanceAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(auto_now_add=True)),
                ('mdtz', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(default='default', max_length=100)),
                ('uuid', models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False,
                    help_text='Unique identifier for this audit log entry',
                    unique=True
                )),
                ('resource_type', models.CharField(
                    choices=[
                        ('ATTENDANCE_RECORD', 'Attendance Record'),
                        ('GEOFENCE', 'Geofence'),
                        ('ATTENDANCE_PHOTO', 'Attendance Photo'),
                        ('BIOMETRIC_TEMPLATE', 'Biometric Template'),
                        ('AUDIT_LOG', 'Audit Log'),
                    ],
                    default='ATTENDANCE_RECORD',
                    help_text='Type of resource accessed',
                    max_length=50
                )),
                ('resource_id', models.IntegerField(
                    blank=True,
                    help_text='ID of the resource accessed (for non-attendance resources)',
                    null=True
                )),
                ('action', models.CharField(
                    choices=[
                        ('VIEW', 'View Record'),
                        ('CREATE', 'Create Record'),
                        ('UPDATE', 'Update Record'),
                        ('DELETE', 'Delete Record'),
                        ('EXPORT', 'Export Records'),
                        ('APPROVE', 'Approve Record'),
                        ('REJECT', 'Reject Record'),
                        ('LOCK', 'Lock for Payroll'),
                        ('UNLOCK', 'Unlock Record'),
                        ('FACE_VERIFY', 'Face Recognition Verification'),
                        ('GPS_VALIDATE', 'GPS Location Validation'),
                        ('BULK_UPDATE', 'Bulk Update Records'),
                        ('BULK_DELETE', 'Bulk Delete Records'),
                    ],
                    help_text='Action performed on the resource',
                    max_length=50
                )),
                ('timestamp', models.DateTimeField(
                    db_index=True,
                    default=django.utils.timezone.now,
                    help_text='When the action was performed'
                )),
                ('duration_ms', models.IntegerField(
                    blank=True,
                    help_text='Duration of the operation in milliseconds',
                    null=True
                )),
                ('ip_address', models.GenericIPAddressField(
                    blank=True,
                    help_text='IP address of the client',
                    null=True
                )),
                ('user_agent', models.TextField(
                    blank=True,
                    help_text='User agent string from the request',
                    null=True
                )),
                ('request_path', models.CharField(
                    blank=True,
                    help_text='Request path (e.g., /api/v1/attendance/123/)',
                    max_length=500,
                    null=True
                )),
                ('http_method', models.CharField(
                    blank=True,
                    help_text='HTTP method (GET, POST, PUT, PATCH, DELETE)',
                    max_length=10,
                    null=True
                )),
                ('status_code', models.IntegerField(
                    blank=True,
                    help_text='HTTP status code of the response',
                    null=True
                )),
                ('correlation_id', models.CharField(
                    blank=True,
                    db_index=True,
                    help_text='Correlation ID for distributed tracing',
                    max_length=100,
                    null=True
                )),
                ('old_values', models.JSONField(
                    blank=True,
                    help_text='Previous values before update (for audit trail)',
                    null=True
                )),
                ('new_values', models.JSONField(
                    blank=True,
                    help_text='New values after update',
                    null=True
                )),
                ('notes', models.TextField(
                    blank=True,
                    help_text='Additional notes or context for this audit entry',
                    null=True
                )),
                ('is_suspicious', models.BooleanField(
                    db_index=True,
                    default=False,
                    help_text='Flag for suspicious access patterns'
                )),
                ('risk_score', models.IntegerField(
                    default=0,
                    help_text='Automated risk score (0-100) for this access'
                )),
                ('attendance_record', models.ForeignKey(
                    blank=True,
                    help_text='Attendance record that was accessed',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='access_logs',
                    to='attendance.peopleeventlog'
                )),
                ('impersonated_by', models.ForeignKey(
                    blank=True,
                    help_text='Admin user who impersonated another user (if applicable)',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='impersonated_attendance_access_logs',
                    to=settings.AUTH_USER_MODEL
                )),
                ('user', models.ForeignKey(
                    blank=True,
                    help_text='User who performed the action',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='attendance_access_logs',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Attendance Access Log',
                'verbose_name_plural': 'Attendance Access Logs',
                'db_table': 'attendance_access_log',
                'ordering': ['-timestamp'],
                'permissions': [
                    ('view_audit_log', 'Can view attendance audit logs'),
                    ('export_audit_log', 'Can export attendance audit logs'),
                    ('investigate_suspicious', 'Can investigate suspicious access'),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='attendanceaccesslog',
            index=models.Index(fields=['tenant', 'timestamp'], name='aal_tenant_time_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceaccesslog',
            index=models.Index(fields=['tenant', 'user', 'timestamp'], name='aal_tenant_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceaccesslog',
            index=models.Index(fields=['tenant', 'attendance_record'], name='aal_tenant_record_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceaccesslog',
            index=models.Index(fields=['tenant', 'action'], name='aal_tenant_action_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceaccesslog',
            index=models.Index(fields=['correlation_id'], name='aal_correlation_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceaccesslog',
            index=models.Index(fields=['is_suspicious'], name='aal_suspicious_idx'),
        ),
    ]
