# Generated by Django 5.2.1 on 2025-11-03
# Migration for GPS tracking and biometric consent management

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_add_audit_logging'),
        ('onboarding', '0001_initial'),  # Assuming onboarding migrations exist
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create ConsentPolicy model
        migrations.CreateModel(
            name='ConsentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cdtz', models.DateTimeField(auto_now_add=True)),
                ('mdtz', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(default='default', max_length=100)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('policy_type', models.CharField(
                    choices=[
                        ('GPS_TRACKING', 'GPS Location Tracking'),
                        ('BIOMETRIC_DATA', 'Biometric Data Collection'),
                        ('PHOTO_CAPTURE', 'Photo Capture'),
                        ('FACE_RECOGNITION', 'Face Recognition'),
                    ],
                    help_text='Type of consent being requested',
                    max_length=50
                )),
                ('state', models.CharField(
                    choices=[
                        ('FEDERAL', 'Federal (Default)'),
                        ('CA', 'California'),
                        ('LA', 'Louisiana'),
                        ('IL', 'Illinois (BIPA)'),
                        ('TX', 'Texas (CUBI)'),
                        ('WA', 'Washington'),
                        ('NY', 'New York'),
                    ],
                    default='FEDERAL',
                    help_text='State jurisdiction for this policy',
                    max_length=20
                )),
                ('version', models.CharField(help_text='Policy version (e.g., 1.0, 2.1)', max_length=20)),
                ('title', models.CharField(help_text='Policy title', max_length=255)),
                ('policy_text', models.TextField(help_text='Full policy text (HTML supported)')),
                ('summary', models.TextField(help_text='Plain language summary of the policy')),
                ('effective_date', models.DateField(help_text='Date this policy becomes effective')),
                ('expiration_date', models.DateField(
                    blank=True,
                    help_text='Date this policy expires (optional)',
                    null=True
                )),
                ('is_active', models.BooleanField(default=True, help_text='Whether this policy is currently active')),
                ('requires_signature', models.BooleanField(
                    default=True,
                    help_text='Whether digital signature is required'
                )),
                ('requires_written_consent', models.BooleanField(
                    default=False,
                    help_text='Whether written (not just electronic) consent is required'
                )),
            ],
            options={
                'db_table': 'consent_policy',
                'verbose_name': 'Consent Policy',
                'verbose_name_plural': 'Consent Policies',
                'ordering': ['-effective_date', '-version'],
            },
        ),
        # Create EmployeeConsentLog model
        migrations.CreateModel(
            name='EmployeeConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cdtz', models.DateTimeField(auto_now_add=True)),
                ('mdtz', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(default='default', max_length=100)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(
                    choices=[
                        ('PENDING', 'Pending Review'),
                        ('GRANTED', 'Consent Granted'),
                        ('REVOKED', 'Consent Revoked'),
                        ('EXPIRED', 'Consent Expired'),
                        ('DENIED', 'Consent Denied'),
                    ],
                    default='PENDING',
                    help_text='Current consent status',
                    max_length=20
                )),
                ('granted_at', models.DateTimeField(blank=True, help_text='When consent was granted', null=True)),
                ('granted_ip', models.GenericIPAddressField(
                    blank=True,
                    help_text='IP address where consent was granted',
                    null=True
                )),
                ('granted_user_agent', models.TextField(
                    blank=True,
                    help_text='User agent when consent was granted',
                    null=True
                )),
                ('signature_data', models.TextField(
                    blank=True,
                    help_text='Digital signature data (base64 encoded image or typed name)',
                    null=True
                )),
                ('signature_type', models.CharField(
                    blank=True,
                    choices=[('TYPED', 'Typed Name'), ('DRAWN', 'Drawn Signature'), ('ELECTRONIC', 'Electronic Acceptance')],
                    help_text='Type of signature provided',
                    max_length=20,
                    null=True
                )),
                ('written_consent_document', models.FileField(
                    blank=True,
                    help_text='Scanned written consent document (if required)',
                    null=True,
                    upload_to='consent_documents/%Y/%m/'
                )),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When consent was revoked', null=True)),
                ('revoked_reason', models.TextField(blank=True, help_text='Reason for consent revocation', null=True)),
                ('revoked_ip', models.GenericIPAddressField(
                    blank=True,
                    help_text='IP address where consent was revoked',
                    null=True
                )),
                ('expires_at', models.DateTimeField(blank=True, help_text='When consent expires (optional)', null=True)),
                ('notification_sent_at', models.DateTimeField(
                    blank=True,
                    help_text='When notification email was sent',
                    null=True
                )),
                ('reminder_sent_at', models.DateTimeField(
                    blank=True,
                    help_text='When reminder was sent (for pending consents)',
                    null=True
                )),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context', null=True)),
                ('employee', models.ForeignKey(
                    help_text='Employee giving consent',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='consent_logs',
                    to=settings.AUTH_USER_MODEL
                )),
                ('policy', models.ForeignKey(
                    help_text='Policy being consented to',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='consent_logs',
                    to='attendance.consentpolicy'
                )),
            ],
            options={
                'db_table': 'employee_consent_log',
                'verbose_name': 'Employee Consent Log',
                'verbose_name_plural': 'Employee Consent Logs',
                'ordering': ['-granted_at', '-cdtz'],
            },
        ),
        # Create ConsentRequirement model
        migrations.CreateModel(
            name='ConsentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cdtz', models.DateTimeField(auto_now_add=True)),
                ('mdtz', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(default='default', max_length=100)),
                ('role', models.CharField(
                    blank=True,
                    help_text='Apply to specific role (optional)',
                    max_length=100,
                    null=True
                )),
                ('state', models.CharField(
                    blank=True,
                    choices=[
                        ('FEDERAL', 'Federal (Default)'),
                        ('CA', 'California'),
                        ('LA', 'Louisiana'),
                        ('IL', 'Illinois (BIPA)'),
                        ('TX', 'Texas (CUBI)'),
                        ('WA', 'Washington'),
                        ('NY', 'New York'),
                    ],
                    help_text='Apply to employees in specific state (optional)',
                    max_length=20,
                    null=True
                )),
                ('is_mandatory', models.BooleanField(
                    default=True,
                    help_text='Whether consent is mandatory for matching employees'
                )),
                ('blocks_clock_in', models.BooleanField(
                    default=True,
                    help_text='Whether absence of consent blocks clock-in/out'
                )),
                ('grace_period_days', models.IntegerField(
                    default=0,
                    help_text='Days before consent becomes mandatory (0 = immediate)'
                )),
                ('reminder_days_before_expiration', models.IntegerField(
                    default=30,
                    help_text='Days before expiration to send reminder (0 = no reminder)'
                )),
                ('is_active', models.BooleanField(default=True, help_text='Whether this requirement is currently active')),
                ('bu', models.ForeignKey(
                    blank=True,
                    help_text='Apply to specific BU (optional)',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='consent_requirements_bu',
                    to='onboarding.bt'
                )),
                ('client', models.ForeignKey(
                    blank=True,
                    help_text='Apply to specific client (optional)',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='consent_requirements_client',
                    to='onboarding.bt'
                )),
                ('policy', models.ForeignKey(
                    help_text='Policy that is required',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='requirements',
                    to='attendance.consentpolicy'
                )),
            ],
            options={
                'db_table': 'consent_requirement',
                'verbose_name': 'Consent Requirement',
                'verbose_name_plural': 'Consent Requirements',
            },
        ),
        # Add indexes
        migrations.AddConstraint(
            model_name='consentpolicy',
            constraint=models.UniqueConstraint(
                fields=['policy_type', 'state', 'version'],
                name='unique_policy_version'
            ),
        ),
        migrations.AddIndex(
            model_name='consentpolicy',
            index=models.Index(fields=['tenant', 'policy_type', 'is_active'], name='cp_tenant_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='consentpolicy',
            index=models.Index(fields=['effective_date'], name='cp_effective_date_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeconsentlog',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='ecl_tenant_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeconsentlog',
            index=models.Index(fields=['tenant', 'policy', 'status'], name='ecl_tenant_policy_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeconsentlog',
            index=models.Index(fields=['status', 'expires_at'], name='ecl_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeconsentlog',
            index=models.Index(fields=['granted_at'], name='ecl_granted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrequirement',
            index=models.Index(fields=['tenant', 'is_active'], name='cr_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrequirement',
            index=models.Index(fields=['client'], name='cr_client_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrequirement',
            index=models.Index(fields=['bu'], name='cr_bu_idx'),
        ),
    ]
