# Generated by Django 5.2.1 on 2025-11-03
# Migration for photo capture on clock-in/out

from django.conf import settings
from django.db import migrations, models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_add_consent_management'),
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoQualityThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('min_quality_score', models.FloatField(default=0.5, help_text='Minimum quality score (0-1)')),
                ('min_width', models.IntegerField(default=480, help_text='Minimum image width in pixels')),
                ('min_height', models.IntegerField(default=480, help_text='Minimum image height in pixels')),
                ('max_file_size_kb', models.IntegerField(default=200, help_text='Maximum file size in kilobytes')),
                ('require_face_detection', models.BooleanField(default=True, help_text='Whether face must be detected in photo')),
                ('min_face_confidence', models.FloatField(default=0.8, help_text='Minimum face detection confidence (0-1)')),
                ('max_blur_threshold', models.FloatField(default=100.0, help_text='Maximum acceptable blur (Laplacian variance)')),
                ('min_brightness', models.IntegerField(default=50, help_text='Minimum brightness level (0-255)')),
                ('max_brightness', models.IntegerField(default=220, help_text='Maximum brightness level (0-255)')),
                ('photo_required_clock_in', models.BooleanField(default=True, help_text='Whether photo is required for clock-in')),
                ('photo_required_clock_out', models.BooleanField(default=False, help_text='Whether photo is required for clock-out')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this threshold configuration is active')),
                ('client', models.ForeignKey(
                    help_text='Client this threshold applies to',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='photo_quality_thresholds',
                    to='onboarding.bt'
                )),
            ],
            options={
                'db_table': 'photo_quality_threshold',
                'verbose_name': 'Photo Quality Threshold',
                'verbose_name_plural': 'Photo Quality Thresholds',
            },
        ),
        migrations.CreateModel(
            name='AttendancePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cdtz', models.DateTimeField(auto_now_add=True)),
                ('mdtz', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(default='default', max_length=100)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('photo_type', models.CharField(
                    choices=[('CLOCK_IN', 'Clock In Photo'), ('CLOCK_OUT', 'Clock Out Photo'), ('VERIFICATION', 'Additional Verification')],
                    help_text='When photo was captured',
                    max_length=20
                )),
                ('image', models.ImageField(help_text='Photo image stored in S3', max_length=500, upload_to='attendance_photos/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(
                    blank=True,
                    help_text='Thumbnail version (150x150)',
                    max_length=500,
                    null=True,
                    upload_to='attendance_photos/thumbnails/%Y/%m/%d/'
                )),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When photo was captured')),
                ('file_size_bytes', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('width', models.IntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('face_detected', models.BooleanField(default=False, help_text='Whether a face was detected in the photo')),
                ('face_count', models.IntegerField(default=0, help_text='Number of faces detected')),
                ('face_confidence', models.FloatField(blank=True, help_text='Face detection confidence score (0-1)', null=True)),
                ('quality_score', models.FloatField(blank=True, help_text='Overall photo quality score (0-1)', null=True)),
                ('quality_rating', models.CharField(
                    blank=True,
                    choices=[
                        ('EXCELLENT', 'Excellent'),
                        ('GOOD', 'Good'),
                        ('ACCEPTABLE', 'Acceptable'),
                        ('POOR', 'Poor'),
                        ('REJECTED', 'Rejected'),
                    ],
                    help_text='Photo quality rating',
                    max_length=20,
                    null=True
                )),
                ('is_blurry', models.BooleanField(default=False, help_text='Whether photo is too blurry')),
                ('is_dark', models.BooleanField(default=False, help_text='Whether photo is too dark')),
                ('brightness', models.FloatField(blank=True, help_text='Brightness level (0-255)', null=True)),
                ('matches_enrolled_template', models.BooleanField(default=False, help_text='Whether photo matches enrolled face template')),
                ('match_confidence', models.FloatField(blank=True, help_text='Face match confidence score (0-1)', null=True)),
                ('face_recognition_model', models.CharField(
                    blank=True,
                    help_text='Face recognition model used (Facenet512, VGGFace, etc.)',
                    max_length=50,
                    null=True
                )),
                ('validation_passed', models.BooleanField(default=False, help_text='Whether photo passed all quality checks')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation errors (if any)')),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Device information (model, OS, camera specs)')),
                ('gps_location', django.contrib.gis.db.models.fields.PointField(
                    blank=True,
                    geography=True,
                    help_text='GPS coordinates where photo was captured',
                    null=True,
                    srid=4326
                )),
                ('delete_after', models.DateTimeField(help_text='Auto-delete photo after this date (90-day retention)')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When photo was deleted', null=True)),
                ('attendance_record', models.ForeignKey(
                    help_text='Attendance record this photo belongs to',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='photos',
                    to='attendance.peopleeventlog'
                )),
                ('employee', models.ForeignKey(
                    help_text='Employee in the photo',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='attendance_photos',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'attendance_photo',
                'verbose_name': 'Attendance Photo',
                'verbose_name_plural': 'Attendance Photos',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancephoto',
            index=models.Index(fields=['tenant', 'employee', 'captured_at'], name='ap_tenant_emp_time_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancephoto',
            index=models.Index(fields=['tenant', 'attendance_record'], name='ap_tenant_record_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancephoto',
            index=models.Index(fields=['delete_after'], name='ap_delete_after_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancephoto',
            index=models.Index(fields=['is_deleted'], name='ap_is_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancephoto',
            index=models.Index(fields=['validation_passed'], name='ap_validation_idx'),
        ),
    ]
