# Generated by Django 5.2.1 on 2025-11-03
# Migration for archival tracking, fraud detection results, and photo references

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_add_photo_capture'),
    ]

    operations = [
        # Add photo reference fields
        migrations.AddField(
            model_name='peopleeventlog',
            name='checkin_photo',
            field=models.ForeignKey(
                blank=True,
                help_text='Photo captured during clock-in',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='checkin_attendance_records',
                to='attendance.attendancephoto'
            ),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='checkout_photo',
            field=models.ForeignKey(
                blank=True,
                help_text='Photo captured during clock-out',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='checkout_attendance_records',
                to='attendance.attendancephoto'
            ),
        ),

        # Add fraud detection fields
        migrations.AddField(
            model_name='peopleeventlog',
            name='fraud_score',
            field=models.FloatField(
                blank=True,
                db_index=True,
                help_text='Fraud detection composite score (0-1)',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='fraud_risk_level',
            field=models.CharField(
                blank=True,
                choices=[
                    ('MINIMAL', 'Minimal'),
                    ('LOW', 'Low'),
                    ('MEDIUM', 'Medium'),
                    ('HIGH', 'High'),
                    ('CRITICAL', 'Critical')
                ],
                help_text='Fraud risk level determined by ML models',
                max_length=20,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='fraud_anomalies',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of detected fraud anomalies with details'
            ),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='fraud_analyzed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When fraud analysis was performed',
                null=True
            ),
        ),

        # Add archival fields
        migrations.AddField(
            model_name='peopleeventlog',
            name='is_archived',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Whether record has been archived (>2 years old)'
            ),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When record was moved to archive',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='gps_purged',
            field=models.BooleanField(
                default=False,
                help_text='Whether GPS location data has been purged (>90 days)'
            ),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='gps_purged_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When GPS data was purged for privacy compliance',
                null=True
            ),
        ),

        # Add indexes for new fields
        migrations.AddIndex(
            model_name='peopleeventlog',
            index=models.Index(fields=['tenant', 'fraud_score'], name='pel_fraud_score_idx'),
        ),
        migrations.AddIndex(
            model_name='peopleeventlog',
            index=models.Index(fields=['tenant', 'is_archived', 'datefor'], name='pel_archived_date_idx'),
        ),
        migrations.AddIndex(
            model_name='peopleeventlog',
            index=models.Index(fields=['tenant', 'gps_purged'], name='pel_gps_purged_idx'),
        ),

        # Add migration for UserBehaviorProfile
        migrations.CreateModel(
            name='UserBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cdtz', models.DateTimeField(auto_now_add=True)),
                ('mdtz', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(default='default', max_length=100)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('baseline_created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_updated_at', models.DateTimeField(auto_now=True)),
                ('training_records_count', models.IntegerField(default=0)),
                ('is_baseline_sufficient', models.BooleanField(default=False)),
                ('typical_checkin_hour', models.IntegerField(blank=True, null=True)),
                ('typical_checkin_minute', models.IntegerField(blank=True, null=True)),
                ('checkin_time_variance_minutes', models.IntegerField(default=30)),
                ('typical_checkout_hour', models.IntegerField(blank=True, null=True)),
                ('typical_work_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('work_duration_variance_minutes', models.IntegerField(default=60)),
                ('typical_locations', models.JSONField(blank=True, default=list)),
                ('typical_geofences', django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(),
                    blank=True,
                    default=list,
                    size=None
                )),
                ('location_radius_meters', models.FloatField(default=500.0)),
                ('typical_devices', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=100),
                    blank=True,
                    default=list,
                    size=None
                )),
                ('device_change_tolerance', models.IntegerField(default=2)),
                ('typical_work_days', django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(),
                    blank=True,
                    default=list,
                    size=None
                )),
                ('typical_transport_modes', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=50),
                    blank=True,
                    default=list,
                    size=None
                )),
                ('anomaly_score_threshold', models.FloatField(default=0.7)),
                ('auto_block_threshold', models.FloatField(default=0.9)),
                ('total_checkins', models.IntegerField(default=0)),
                ('anomalies_detected', models.IntegerField(default=0)),
                ('false_positives', models.IntegerField(default=0)),
                ('detection_accuracy', models.FloatField(blank=True, null=True)),
                ('last_anomaly_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='behavior_profile',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'user_behavior_profile',
                'verbose_name': 'User Behavior Profile',
                'verbose_name_plural': 'User Behavior Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='userbehaviorprofile',
            index=models.Index(fields=['tenant', 'employee'], name='ubp_tenant_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorprofile',
            index=models.Index(fields=['is_baseline_sufficient'], name='ubp_baseline_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorprofile',
            index=models.Index(fields=['baseline_updated_at'], name='ubp_updated_idx'),
        ),

        # Add migration for FraudAlert
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cdtz', models.DateTimeField(auto_now_add=True)),
                ('mdtz', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(default='default', max_length=100)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('fraud_score', models.FloatField()),
                ('risk_score', models.IntegerField()),
                ('detection_timestamp', models.DateTimeField(default=timezone.now)),
                ('evidence', models.JSONField()),
                ('anomalies_detected', models.JSONField(default=list)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('investigation_notes', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('auto_blocked', models.BooleanField(default=False)),
                ('manager_notified', models.BooleanField(default=False)),
                ('employee_notified', models.BooleanField(default=False)),
                ('is_escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('employee', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='fraud_alerts',
                    to=settings.AUTH_USER_MODEL
                )),
                ('attendance_record', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='fraud_alerts',
                    to='attendance.peopleeventlog'
                )),
                ('assigned_to', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='assigned_fraud_alerts',
                    to=settings.AUTH_USER_MODEL
                )),
                ('resolved_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='resolved_fraud_alerts',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'fraud_alert',
                'verbose_name': 'Fraud Alert',
                'verbose_name_plural': 'Fraud Alerts',
                'ordering': ['-detection_timestamp'],
            },
        ),

        # Add migration for SyncConflict
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cdtz', models.DateTimeField(auto_now_add=True)),
                ('mdtz', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(default='default', max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('conflict_type', models.CharField(max_length=50)),
                ('detected_at', models.DateTimeField(default=timezone.now)),
                ('client_version', models.JSONField()),
                ('server_version', models.JSONField()),
                ('resolution', models.CharField(max_length=20)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('user_notified', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('attendance_record', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sync_conflicts',
                    to='attendance.peopleeventlog'
                )),
                ('employee', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sync_conflicts',
                    to=settings.AUTH_USER_MODEL
                )),
                ('resolved_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='resolved_sync_conflicts',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'sync_conflict',
                'verbose_name': 'Sync Conflict',
                'verbose_name_plural': 'Sync Conflicts',
            },
        ),

        # Add hysteresis field to Geofence
        migrations.AddField(
            model_name='geofence',
            name='hysteresis_meters',
            field=models.FloatField(
                default=1.0,
                help_text='Buffer zone in meters to prevent boundary flapping (configurable per geofence)'
            ),
        ),
    ]
