# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_testing", "0001_initial"),
        ("issue_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="regressionprediction",
            name="based_on_anomalies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Historical anomalies used for prediction",
                related_name="regression_predictions",
                to="issue_tracker.anomalysignature",
            ),
        ),
        migrations.AddField(
            model_name="semanticelement",
            name="baseline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="ai_testing.mlbaseline",
            ),
        ),
        migrations.AddField(
            model_name="testcoveragegap",
            name="anomaly_signature",
            field=models.ForeignKey(
                help_text="Anomaly that revealed this coverage gap",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverage_gaps",
                to="issue_tracker.anomalysignature",
            ),
        ),
    ]
