# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_testing", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testcoveragegap",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_coverage_gaps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testcoveragepattern",
            name="coverage_gaps",
            field=models.ManyToManyField(
                help_text="Coverage gaps that match this pattern",
                related_name="patterns",
                to="ai_testing.testcoveragegap",
            ),
        ),
        migrations.AddIndex(
            model_name="mlbaseline",
            index=models.Index(
                fields=["baseline_type", "platform"],
                name="ai_testing__baselin_b3a5aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlbaseline",
            index=models.Index(
                fields=["component_name", "app_version"],
                name="ai_testing__compone_8495f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlbaseline",
            index=models.Index(
                fields=["approval_status", "is_active"],
                name="ai_testing__approva_6134eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlbaseline",
            index=models.Index(
                fields=["visual_hash"], name="ai_testing__visual__f72e3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlbaseline",
            index=models.Index(
                fields=["validation_score", "semantic_confidence"],
                name="ai_testing__validat_f9fe56_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mlbaseline",
            unique_together={
                (
                    "baseline_type",
                    "component_name",
                    "test_scenario",
                    "platform",
                    "app_version",
                )
            },
        ),
        migrations.AddIndex(
            model_name="baselinecomparison",
            index=models.Index(
                fields=["baseline", "comparison_type"],
                name="ai_testing__baselin_f46353_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselinecomparison",
            index=models.Index(
                fields=["comparison_result", "compared_at"],
                name="ai_testing__compari_e16346_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselinecomparison",
            index=models.Index(
                fields=["difference_score", "ml_confidence"],
                name="ai_testing__differe_33fbd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselinecomparison",
            index=models.Index(
                fields=["human_validated", "human_agreement"],
                name="ai_testing__human_v_d013ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="regressionprediction",
            index=models.Index(
                fields=["app_version", "platform"],
                name="ai_testing__app_ver_fc35ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="regressionprediction",
            index=models.Index(
                fields=["prediction_type", "risk_level"],
                name="ai_testing__predict_cc2b75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="regressionprediction",
            index=models.Index(
                fields=["status", "predicted_at"], name="ai_testing__status_07650c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regressionprediction",
            index=models.Index(
                fields=["predicted_risk_score", "confidence_level"],
                name="ai_testing__predict_e4b824_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="regressionprediction",
            index=models.Index(
                fields=["target_release_date"], name="ai_testing__target__6634a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="semanticelement",
            index=models.Index(
                fields=["baseline", "element_type"],
                name="ai_testing__baselin_3c2f74_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="semanticelement",
            index=models.Index(
                fields=["interaction_type", "is_critical"],
                name="ai_testing__interac_eec1ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="semanticelement",
            index=models.Index(
                fields=["detection_confidence"], name="ai_testing__detecti_454a5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcoveragegap",
            index=models.Index(
                fields=["coverage_type", "priority"],
                name="ai_testing__coverag_dd52f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="testcoveragegap",
            index=models.Index(
                fields=["status", "identified_at"], name="ai_testing__status_d4ceb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcoveragegap",
            index=models.Index(
                fields=["confidence_score", "impact_score"],
                name="ai_testing__confide_f5f126_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="testcoveragegap",
            index=models.Index(
                fields=["anomaly_signature", "status"],
                name="ai_testing__anomaly_5e8fc4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="testcoveragegap",
            index=models.Index(
                fields=["assigned_to", "status"], name="ai_testing__assigne_2912cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcoveragegap",
            index=models.Index(
                fields=["recommended_framework"], name="ai_testing__recomme_80f0b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcoveragepattern",
            index=models.Index(
                fields=["pattern_type", "is_active"],
                name="ai_testing__pattern_bfc09f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="testcoveragepattern",
            index=models.Index(
                fields=["confidence_score", "occurrence_count"],
                name="ai_testing__confide_32a17e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="testcoveragepattern",
            index=models.Index(
                fields=["last_seen"], name="ai_testing__last_se_c82b22_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testcoveragepattern",
            unique_together={("pattern_type", "pattern_signature")},
        ),
    ]
