# Generated by Django 5.2.1 - Placeholder migration for site_onboarding
# This migration will be regenerated with `python manage.py makemigrations site_onboarding`
# once Django environment is available.

"""
Initial migration for site_onboarding bounded context.

This migration creates 9 models for site security audit management:

1. OnboardingSite - Client sites/locations
2. OnboardingZone - Subdivisions within sites
3. Asset - Equipment and infrastructure
4. Checkpoint - Patrol checkpoints
5. MeterPoint - Utility meter readings
6. SOP - Standard Operating Procedures
7. CoveragePlan - Security coverage planning
8. SitePhoto - Site imagery
9. SiteVideo - Site video content

All models extend EnhancedTenantModel for multi-tenancy support.

Dependencies:
- apps.tenants (for EnhancedTenantModel)
- apps.peoples (for People foreign key)
- apps.client_onboarding (for Bt foreign key)
"""

from django.conf import settings
from django.contrib.gis.db import models as gis_models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '__latest__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_onboarding', '0001_initial'),
    ]

    operations = [
        # ===============================================
        # SITE MODEL
        # ===============================================
        migrations.CreateModel(
            name='OnboardingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('bt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_onboarding.bt', related_name='sites')),
                ('name', models.CharField(max_length=200)),
                ('site_code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)),
                ('longitude', models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)),
                ('geofence', gis_models.PolygonField(null=True, blank=True)),
                ('site_manager', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True, blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'site_onboarding_site',
                'indexes': [
                    models.Index(fields=['tenant', 'bt', 'is_active']),
                    models.Index(fields=['site_code']),
                ],
            },
        ),

        # ===============================================
        # ZONE MODEL
        # ===============================================
        migrations.CreateModel(
            name='OnboardingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_onboarding.onboardingsite', related_name='zones')),
                ('name', models.CharField(max_length=200)),
                ('zone_code', models.CharField(max_length=50)),
                ('zone_type', models.CharField(max_length=50)),
                ('parent_zone', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='site_onboarding.onboardingzone', null=True, blank=True, related_name='sub_zones')),
                ('boundary', gis_models.PolygonField(null=True, blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'site_onboarding_zone',
                'indexes': [
                    models.Index(fields=['tenant', 'site', 'is_active']),
                ],
            },
        ),

        # ===============================================
        # ASSET MODEL
        # ===============================================
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_onboarding.onboardingsite', related_name='assets')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='site_onboarding.onboardingzone', null=True, blank=True, related_name='assets')),
                ('name', models.CharField(max_length=200)),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('asset_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', gis_models.PointField(null=True, blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'site_onboarding_asset',
                'indexes': [
                    models.Index(fields=['tenant', 'site', 'is_active']),
                    models.Index(fields=['asset_code']),
                ],
            },
        ),

        # ===============================================
        # CHECKPOINT MODEL
        # ===============================================
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_onboarding.onboardingsite', related_name='checkpoints')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='site_onboarding.onboardingzone', null=True, blank=True, related_name='checkpoints')),
                ('name', models.CharField(max_length=200)),
                ('checkpoint_code', models.CharField(max_length=50, unique=True)),
                ('location', gis_models.PointField(null=True, blank=True)),
                ('qr_code_data', models.CharField(max_length=500, blank=True)),
                ('nfc_tag_id', models.CharField(max_length=100, blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'site_onboarding_checkpoint',
                'indexes': [
                    models.Index(fields=['tenant', 'site', 'is_active']),
                    models.Index(fields=['checkpoint_code']),
                ],
            },
        ),

        # ===============================================
        # METER POINT MODEL
        # ===============================================
        migrations.CreateModel(
            name='MeterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_onboarding.onboardingsite', related_name='meter_points')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='site_onboarding.onboardingzone', null=True, blank=True, related_name='meter_points')),
                ('name', models.CharField(max_length=200)),
                ('meter_code', models.CharField(max_length=50, unique=True)),
                ('meter_type', models.CharField(max_length=50)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('location', gis_models.PointField(null=True, blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'site_onboarding_meter_point',
                'indexes': [
                    models.Index(fields=['tenant', 'site', 'is_active']),
                    models.Index(fields=['meter_code']),
                ],
            },
        ),

        # ===============================================
        # SOP MODEL
        # ===============================================
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_onboarding.onboardingsite', related_name='sops')),
                ('title', models.CharField(max_length=200)),
                ('sop_code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('version', models.CharField(max_length=20)),
                ('effective_date', models.DateField()),
                ('review_date', models.DateField(null=True, blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True, blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'site_onboarding_sop',
                'verbose_name': 'Standard Operating Procedure',
                'verbose_name_plural': 'Standard Operating Procedures',
                'indexes': [
                    models.Index(fields=['tenant', 'site', 'is_active']),
                    models.Index(fields=['sop_code']),
                ],
            },
        ),

        # ===============================================
        # COVERAGE PLAN MODEL
        # ===============================================
        migrations.CreateModel(
            name='CoveragePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_onboarding.onboardingsite', related_name='coverage_plans')),
                ('name', models.CharField(max_length=200)),
                ('plan_type', models.CharField(max_length=50)),
                ('coverage_area', gis_models.PolygonField(null=True, blank=True)),
                ('guard_count', models.IntegerField()),
                ('patrol_frequency', models.CharField(max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'site_onboarding_coverage_plan',
                'indexes': [
                    models.Index(fields=['tenant', 'site', 'is_active']),
                ],
            },
        ),

        # ===============================================
        # SITE MEDIA MODELS
        # ===============================================
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_onboarding.onboardingsite', related_name='photos')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='site_onboarding.onboardingzone', null=True, blank=True, related_name='photos')),
                ('image_path', models.CharField(max_length=500)),
                ('caption', models.TextField(blank=True)),
                ('location', gis_models.PointField(null=True, blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True, blank=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'site_onboarding_photo',
                'indexes': [
                    models.Index(fields=['tenant', 'site']),
                ],
            },
        ),

        migrations.CreateModel(
            name='SiteVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_onboarding.onboardingsite', related_name='videos')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='site_onboarding.onboardingzone', null=True, blank=True, related_name='videos')),
                ('video_path', models.CharField(max_length=500)),
                ('duration_seconds', models.IntegerField()),
                ('caption', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True, blank=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'site_onboarding_video',
                'indexes': [
                    models.Index(fields=['tenant', 'site']),
                ],
            },
        ),
    ]
