# Generated by Django 5.2.7 on 2025-11-09 10:20

import apps.peoples.models.base_model
import apps.site_onboarding.models.upload_utils
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client_onboarding", "0002_initial"),
        ("core_onboarding", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingSite",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "site_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("bank_branch", "Bank Branch"),
                            ("atm", "ATM"),
                            ("retail_store", "Retail Store"),
                            ("warehouse", "Warehouse"),
                            ("office", "Office"),
                            ("industrial", "Industrial Facility"),
                            ("mixed_use", "Mixed Use"),
                        ],
                        default="office",
                        max_length=50,
                        verbose_name="Site Type",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="Primary language for audit (ISO 639-1 code)",
                        max_length=10,
                        verbose_name="Audit Language",
                    ),
                ),
                (
                    "operating_hours_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Operating Hours Start"
                    ),
                ),
                (
                    "operating_hours_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Operating Hours End"
                    ),
                ),
                (
                    "primary_gps",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="Primary site coordinates",
                        null=True,
                        srid=4326,
                        verbose_name="Primary GPS Location",
                    ),
                ),
                (
                    "risk_profile",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Risk assessment: {overall_score, critical_zones, threat_vectors}",
                        verbose_name="Risk Profile",
                    ),
                ),
                (
                    "audit_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Audit Completed At"
                    ),
                ),
                (
                    "report_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Report Generated At"
                    ),
                ),
                (
                    "knowledge_base_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference to ingested KB document",
                        null=True,
                        verbose_name="Knowledge Base Document ID",
                    ),
                ),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_sites",
                        to="client_onboarding.bt",
                        verbose_name="Business Unit",
                    ),
                ),
                (
                    "conversation_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_site",
                        to="core_onboarding.conversationsession",
                        verbose_name="Conversation Session",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Site",
                "verbose_name_plural": "Onboarding Sites",
                "db_table": "site_onboarding_site",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CoveragePlan",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "plan_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "guard_posts",
                    models.JSONField(
                        default=list,
                        help_text="Posts: [{post_id, zone, position, duties, risk_level}]",
                        verbose_name="Guard Posts",
                    ),
                ),
                (
                    "shift_assignments",
                    models.JSONField(
                        default=list,
                        help_text="Shifts: [{shift_name, start_time, end_time, posts_covered, staffing}]",
                        verbose_name="Shift Assignments",
                    ),
                ),
                (
                    "patrol_routes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Routes: [{route_id, zones, frequency, checkpoints}]",
                        verbose_name="Patrol Routes",
                    ),
                ),
                (
                    "risk_windows",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="High-risk time periods: [{start, end, zones, mitigation}]",
                        verbose_name="Risk Windows",
                    ),
                ),
                (
                    "compliance_notes",
                    models.TextField(
                        blank=True,
                        help_text="Regulatory compliance considerations",
                        verbose_name="Compliance Notes",
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(
                        default="ai",
                        help_text="ai/manual/hybrid",
                        max_length=50,
                        verbose_name="Generated By",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_coverage_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_plan",
                        to="site_onboarding.onboardingsite",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coverage Plan",
                "verbose_name_plural": "Coverage Plans",
                "db_table": "site_onboarding_coverage_plan",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OnboardingZone",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "zone_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("gate", "Gate / Main Entrance"),
                            ("perimeter", "Perimeter / Boundary"),
                            ("entry_exit", "Entry/Exit Point"),
                            ("vault", "Vault / Strong Room"),
                            ("atm", "ATM Location"),
                            ("control_room", "Control Room / Security Office"),
                            ("parking", "Parking Area"),
                            ("loading_dock", "Loading Dock"),
                            ("emergency_exit", "Emergency Exit"),
                            ("asset_storage", "Asset Storage Area"),
                            ("cash_counter", "Cash Counter"),
                            ("server_room", "Server Room"),
                            ("reception", "Reception Area"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Zone Type",
                    ),
                ),
                (
                    "zone_name",
                    models.CharField(
                        help_text="Descriptive name for the zone",
                        max_length=200,
                        verbose_name="Zone Name",
                    ),
                ),
                (
                    "importance_level",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Importance Level",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("severe", "Severe"),
                            ("high", "High"),
                            ("moderate", "Moderate"),
                            ("low", "Low"),
                            ("minimal", "Minimal"),
                        ],
                        default="moderate",
                        max_length=20,
                        verbose_name="Risk Level",
                    ),
                ),
                (
                    "gps_coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="GPS Coordinates",
                    ),
                ),
                (
                    "coverage_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this zone requires guard coverage",
                        verbose_name="Coverage Required",
                    ),
                ),
                (
                    "compliance_notes",
                    models.TextField(
                        blank=True,
                        help_text="RBI/ASIS/ISO compliance requirements",
                        verbose_name="Compliance Notes",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="site_onboarding.onboardingsite",
                        verbose_name="Zone",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Zone",
                "verbose_name_plural": "Onboarding Zones",
                "db_table": "site_onboarding_zone",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MeterPoint",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "meter_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meter_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity Meter"),
                            ("water", "Water Meter"),
                            ("diesel", "Diesel/Fuel Meter"),
                            ("fire_pressure", "Fire Hydrant Pressure"),
                            ("logbook", "Manual Logbook"),
                            ("temperature", "Temperature Gauge"),
                            ("generator_hours", "Generator Hour Meter"),
                            ("ups_status", "UPS Status Panel"),
                            ("other", "Other Meter"),
                        ],
                        max_length=50,
                        verbose_name="Meter Type",
                    ),
                ),
                (
                    "meter_name",
                    models.CharField(max_length=200, verbose_name="Meter Name"),
                ),
                (
                    "reading_frequency",
                    models.CharField(
                        help_text="daily/weekly/monthly",
                        max_length=50,
                        verbose_name="Reading Frequency",
                    ),
                ),
                (
                    "reading_template",
                    models.JSONField(
                        default=dict,
                        help_text="Expected format: {unit, range, validation_rules}",
                        verbose_name="Reading Template",
                    ),
                ),
                (
                    "requires_photo_ocr",
                    models.BooleanField(
                        default=True, verbose_name="Requires Photo OCR"
                    ),
                ),
                (
                    "photo_example",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/meter_examples/",
                        verbose_name="Example Photo",
                    ),
                ),
                (
                    "sop_instructions",
                    models.TextField(
                        blank=True,
                        help_text="How to read and record this meter",
                        verbose_name="SOP Instructions",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_points",
                        to="site_onboarding.onboardingzone",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meter Point",
                "verbose_name_plural": "Meter Points",
                "db_table": "site_onboarding_meter_point",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Checkpoint",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "checkpoint_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "checkpoint_name",
                    models.CharField(max_length=200, verbose_name="Checkpoint Name"),
                ),
                (
                    "questions",
                    models.JSONField(
                        default=list,
                        help_text="Checklist questions: [{question, required, type}]",
                        verbose_name="Questions",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="hourly/shift/daily/weekly",
                        max_length=50,
                        verbose_name="Check Frequency",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        default="medium",
                        max_length=20,
                        verbose_name="Severity if Missed",
                    ),
                ),
                (
                    "template_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Link to compliance template",
                        null=True,
                        verbose_name="Template ID",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="site_onboarding.onboardingzone",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkpoint",
                "verbose_name_plural": "Checkpoints",
                "db_table": "site_onboarding_checkpoint",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "asset_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("camera", "CCTV Camera"),
                            ("dvr_nvr", "DVR/NVR"),
                            ("lighting", "Security Lighting"),
                            ("metal_detector", "Metal Detector"),
                            ("xray_machine", "X-Ray Machine"),
                            ("alarm_system", "Alarm System"),
                            ("access_reader", "Access Control Reader"),
                            ("biometric", "Biometric Device"),
                            ("intercom", "Intercom System"),
                            ("barrier_gate", "Barrier Gate"),
                            ("safe_vault", "Safe/Vault"),
                            ("fire_extinguisher", "Fire Extinguisher"),
                            ("fire_alarm", "Fire Alarm"),
                            ("emergency_light", "Emergency Lighting"),
                            ("other", "Other Asset"),
                        ],
                        max_length=50,
                        verbose_name="Asset Type",
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(max_length=200, verbose_name="Asset Name"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("needs_repair", "Needs Repair"),
                            ("not_installed", "Not Installed"),
                            ("planned", "Planned"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        default="operational",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Technical specs: {model, serial, resolution, coverage_area}",
                        verbose_name="Specifications",
                    ),
                ),
                (
                    "linked_photos",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        help_text="Photo IDs documenting this asset",
                        size=None,
                        verbose_name="Linked Photos",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="onboarding_asset_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="onboarding_asset_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_asset_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="site_onboarding.onboardingzone",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "site_onboarding_asset",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SitePhoto",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "photo_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.site_onboarding.models.upload_utils.upload_site_photo,
                        verbose_name="Image",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.site_onboarding.models.upload_utils.upload_site_photo_thumbnail,
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "gps_coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="GPS Coordinates",
                    ),
                ),
                (
                    "compass_direction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Direction in degrees (0-360)",
                        max_digits=5,
                        null=True,
                        verbose_name="Compass Direction",
                    ),
                ),
                (
                    "vision_analysis",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Google Vision API results",
                        verbose_name="Vision Analysis",
                    ),
                ),
                (
                    "detected_objects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Detected Objects",
                    ),
                ),
                (
                    "safety_concerns",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Safety Concerns",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="site_onboarding.onboardingsite",
                        verbose_name="Site",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_photos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="site_onboarding.onboardingzone",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Photo",
                "verbose_name_plural": "Site Photos",
                "db_table": "site_onboarding_photo",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteVideo",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "video_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        upload_to=apps.site_onboarding.models.upload_utils.upload_site_video,
                        verbose_name="Video File",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.site_onboarding.models.upload_utils.upload_site_video_thumbnail,
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duration (seconds)"
                    ),
                ),
                (
                    "gps_start",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="GPS at Start",
                    ),
                ),
                (
                    "gps_end",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="GPS at End",
                    ),
                ),
                (
                    "video_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Technical metadata: {resolution, codec, fps, size_bytes}",
                        verbose_name="Video Metadata",
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated transcript of audio track",
                        verbose_name="Transcript",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="site_onboarding.onboardingsite",
                        verbose_name="Site",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_videos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="site_onboarding.onboardingzone",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Video",
                "verbose_name_plural": "Site Videos",
                "db_table": "site_onboarding_video",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SOP",
            fields=[
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "sop_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sop_title",
                    models.CharField(max_length=300, verbose_name="SOP Title"),
                ),
                (
                    "purpose",
                    models.TextField(
                        help_text="Why this SOP is needed", verbose_name="Purpose"
                    ),
                ),
                (
                    "steps",
                    models.JSONField(
                        default=list,
                        help_text="Ordered steps: [{step_number, description, responsible_role}]",
                        verbose_name="Steps",
                    ),
                ),
                (
                    "staffing_required",
                    models.JSONField(
                        default=dict,
                        help_text="Non-cost staffing: {roles, count, schedule} - no pricing",
                        verbose_name="Staffing Required",
                    ),
                ),
                (
                    "compliance_references",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="RBI/ASIS/ISO citations: ['RBI Master Direction 2021', ...]",
                        size=None,
                        verbose_name="Compliance References",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="hourly/shift/daily/weekly/monthly/as_needed",
                        max_length=50,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "translated_texts",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Translations: {lang_code: {title, purpose, steps}}",
                        verbose_name="Translated Texts",
                    ),
                ),
                (
                    "escalation_triggers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Conditions requiring escalation",
                        verbose_name="Escalation Triggers",
                    ),
                ),
                (
                    "llm_generated",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this SOP was AI-generated",
                        verbose_name="LLM Generated",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset-specific SOP",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sops",
                        to="site_onboarding.asset",
                        verbose_name="Asset",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_sops",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sops",
                        to="site_onboarding.onboardingsite",
                        verbose_name="Site",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sops",
                        to="site_onboarding.onboardingzone",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Operating Procedure",
                "verbose_name_plural": "Standard Operating Procedures",
                "db_table": "site_onboarding_sop",
                "ordering": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="onboardingsite",
            index=models.Index(
                fields=["business_unit", "cdtz"], name="site_bu_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingsite",
            index=models.Index(
                fields=["site_type", "cdtz"], name="site_type_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coverageplan",
            index=models.Index(
                fields=["site", "approved_at"], name="coverage_site_approved_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingzone",
            index=models.Index(fields=["site", "zone_type"], name="zone_site_type_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingzone",
            index=models.Index(fields=["importance_level"], name="zone_importance_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingzone",
            index=models.Index(fields=["risk_level"], name="zone_risk_idx"),
        ),
        migrations.AddConstraint(
            model_name="onboardingzone",
            constraint=models.UniqueConstraint(
                fields=("site", "zone_name"), name="unique_zone_name_per_site"
            ),
        ),
        migrations.AddIndex(
            model_name="meterpoint",
            index=models.Index(
                fields=["zone", "meter_type"], name="meter_zone_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkpoint",
            index=models.Index(
                fields=["zone", "completed"], name="checkpoint_zone_complete_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["zone", "asset_type"], name="asset_zone_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["status"], name="asset_status_idx"),
        ),
        migrations.AddIndex(
            model_name="sitephoto",
            index=models.Index(fields=["zone", "cdtz"], name="photo_zone_time_idx"),
        ),
        migrations.AddIndex(
            model_name="sitephoto",
            index=models.Index(fields=["site", "cdtz"], name="photo_site_time_idx"),
        ),
        migrations.AddIndex(
            model_name="sitevideo",
            index=models.Index(fields=["zone", "cdtz"], name="video_zone_time_idx"),
        ),
        migrations.AddIndex(
            model_name="sitevideo",
            index=models.Index(fields=["site", "cdtz"], name="video_site_time_idx"),
        ),
        migrations.AddIndex(
            model_name="sop",
            index=models.Index(fields=["site", "zone"], name="sop_site_zone_idx"),
        ),
        migrations.AddIndex(
            model_name="sop",
            index=models.Index(fields=["asset"], name="sop_asset_idx"),
        ),
        migrations.AddIndex(
            model_name="sop",
            index=models.Index(
                fields=["llm_generated", "approved_at"], name="sop_gen_approved_idx"
            ),
        ),
    ]
