# Generated by Django 5.2.7 on 2025-11-09 10:20

import apps.client_onboarding.managers
import apps.client_onboarding.models.business_unit.bt_helpers
import apps.client_onboarding.models.scheduling
import apps.peoples.models.base_model
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.serializers.json
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, null=True)),
                ("bucode", models.CharField(max_length=30, verbose_name="Code")),
                (
                    "solid",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Sol ID"
                    ),
                ),
                (
                    "bupreferences",
                    models.JSONField(
                        blank=True,
                        default=apps.client_onboarding.models.business_unit.bt_helpers.bu_defaults,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="bupreferences",
                    ),
                ),
                ("buname", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "butree",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        null=True,
                        verbose_name="Bu Path",
                    ),
                ),
                ("enable", models.BooleanField(default=True, verbose_name="Enable")),
                (
                    "iswarehouse",
                    models.BooleanField(default=False, verbose_name="Warehouse"),
                ),
                (
                    "gpsenable",
                    models.BooleanField(default=False, verbose_name="GPS Enable"),
                ),
                (
                    "enablesleepingguard",
                    models.BooleanField(
                        default=False, verbose_name="Enable SleepingGuard"
                    ),
                ),
                (
                    "skipsiteaudit",
                    models.BooleanField(default=False, verbose_name="Skip SiteAudit"),
                ),
                (
                    "siincludes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=50),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Site Inclides",
                    ),
                ),
                (
                    "deviceevent",
                    models.BooleanField(default=False, verbose_name="Device Event"),
                ),
                (
                    "pdist",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        verbose_name="Permissible Distance",
                    ),
                ),
                (
                    "gpslocation",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="GPS Location",
                    ),
                ),
                ("isvendor", models.BooleanField(default=False, verbose_name="Vendor")),
                (
                    "isserviceprovider",
                    models.BooleanField(default=False, verbose_name="ServiceProvider"),
                ),
                (
                    "onboarding_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Context data for conversational onboarding process",
                        verbose_name="Onboarding Context",
                    ),
                ),
                (
                    "setup_confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI confidence score for the setup recommendations",
                        null=True,
                        verbose_name="Setup Confidence Score",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Unit",
                "verbose_name_plural": "Business Units",
                "db_table": "bt",
                "ordering": ["mdtz"],
                "get_latest_by": ["mdtz", "cdtz"],
                "abstract": False,
            },
            managers=[
                ("objects", apps.client_onboarding.managers.BtManager()),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "handsetname",
                    models.CharField(max_length=100, verbose_name="Handset Name"),
                ),
                ("modelname", models.CharField(max_length=50, verbose_name="Model")),
                (
                    "dateregistered",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date Registered",
                    ),
                ),
                (
                    "lastcommunication",
                    models.DateTimeField(
                        help_text="Last successful communication with device",
                        verbose_name="Last Communication",
                    ),
                ),
                (
                    "imeino",
                    models.CharField(
                        blank=True,
                        help_text="International Mobile Equipment Identity number",
                        max_length=15,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_imei",
                                message="IMEI must be exactly 15 digits",
                                regex="^\\d{15}$",
                            )
                        ],
                        verbose_name="IMEI No",
                    ),
                ),
                (
                    "phoneno",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone",
                                message="Phone number must be 9-15 digits",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Phone No",
                    ),
                ),
                (
                    "isdeviceon",
                    models.BooleanField(default=True, verbose_name="Is Device On"),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "db_table": "device",
                "ordering": ["mdtz"],
                "get_latest_by": ["mdtz", "cdtz"],
                "abstract": False,
            },
            managers=[
                ("objects", apps.client_onboarding.managers.DeviceManager()),
            ],
        ),
        migrations.CreateModel(
            name="DownTimeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Downtime Reason")),
                (
                    "starttime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Start"
                    ),
                ),
                (
                    "endtime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="End"
                    ),
                ),
            ],
            options={
                "verbose_name": "Downtime History",
                "verbose_name_plural": "Downtime Histories",
                "db_table": "downtime_history",
                "ordering": ["mdtz"],
                "get_latest_by": ["mdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("shiftname", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "shiftduration",
                    models.IntegerField(null=True, verbose_name="Shift Duration"),
                ),
                (
                    "peoplecount",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="People Count"
                    ),
                ),
                ("starttime", models.TimeField(verbose_name="Start time")),
                ("endtime", models.TimeField(verbose_name="End time")),
                (
                    "nightshiftappicable",
                    models.BooleanField(
                        default=True, verbose_name="Night Shift Applicable"
                    ),
                ),
                ("captchafreq", models.IntegerField(default=10, null=True)),
                ("enable", models.BooleanField(default=True, verbose_name="Enable")),
                (
                    "shift_data",
                    models.JSONField(
                        blank=True,
                        default=apps.client_onboarding.models.scheduling.shiftdata_json,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Extended shift configuration and metadata",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
                "db_table": "shift",
                "ordering": ["mdtz"],
                "get_latest_by": ["mdtz", "cdtz"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("startdate", models.DateField(verbose_name="Start Date")),
                ("enddate", models.DateField(verbose_name="End Date")),
                (
                    "terminateddate",
                    models.DateField(null=True, verbose_name="Terminated Date"),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Reason"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("In Active", "In Active")],
                        default="Active",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "istemporary",
                    models.BooleanField(default=False, verbose_name="Is Temporary"),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "subscription",
                "ordering": ["mdtz"],
                "abstract": False,
            },
            managers=[
                ("objects", apps.client_onboarding.managers.SubscriptionManger()),
            ],
        ),
    ]
