# Generated by Django 5.2.1 - Placeholder migration for client_onboarding
# This migration will be regenerated with `python manage.py makemigrations client_onboarding`
# once Django environment is available.

"""
Initial migration for client_onboarding bounded context.

This migration creates 4 models for client/business unit management:

1. Bt (Business Unit) - Client organization hierarchy
2. Shift - Work schedules and shift patterns
3. Device - Mobile/IoT device registration
4. Subscription - Client subscription and billing

All models extend EnhancedTenantModel for multi-tenancy support.

Dependencies:
- apps.tenants (for EnhancedTenantModel)
- apps.peoples (for People foreign key)
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '__latest__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ===============================================
        # BUSINESS UNIT MODEL
        # ===============================================
        migrations.CreateModel(
            name='Bt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('business_type', models.CharField(max_length=100)),
                ('parent_bt', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='client_onboarding.bt', null=True, blank=True, related_name='children')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True, blank=True)),
                ('address', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'client_onboarding_bt',
                'verbose_name': 'Business Unit',
                'verbose_name_plural': 'Business Units',
                'indexes': [
                    models.Index(fields=['tenant', 'is_active']),
                    models.Index(fields=['code']),
                ],
            },
        ),

        # ===============================================
        # SHIFT MODEL
        # ===============================================
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('bt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_onboarding.bt', related_name='shifts')),
                ('name', models.CharField(max_length=200)),
                ('shift_code', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(max_digits=5, decimal_places=2)),
                ('is_overnight', models.BooleanField(default=False)),
                ('days_of_week', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'client_onboarding_shift',
                'indexes': [
                    models.Index(fields=['tenant', 'bt', 'is_active']),
                ],
            },
        ),

        # ===============================================
        # DEVICE MODEL
        # ===============================================
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(max_length=50)),
                ('device_model', models.CharField(max_length=100, blank=True)),
                ('os_version', models.CharField(max_length=50, blank=True)),
                ('app_version', models.CharField(max_length=50, blank=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registration_token', models.CharField(max_length=500, blank=True)),
                ('last_active', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'client_onboarding_device',
                'indexes': [
                    models.Index(fields=['tenant', 'registered_by', 'is_active']),
                    models.Index(fields=['device_id']),
                ],
            },
        ),

        # ===============================================
        # SUBSCRIPTION MODEL
        # ===============================================
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('bt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_onboarding.bt', related_name='subscriptions')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_tier', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True, blank=True)),
                ('user_limit', models.IntegerField(null=True, blank=True)),
                ('features', models.JSONField(default=dict)),
                ('billing_cycle', models.CharField(max_length=50)),
                ('amount', models.DecimalField(max_digits=10, decimal_places=2)),
                ('currency', models.CharField(max_length=3, default='USD')),
                ('status', models.CharField(max_length=20, default='active')),
            ],
            options={
                'db_table': 'client_onboarding_subscription',
                'indexes': [
                    models.Index(fields=['tenant', 'bt', 'status']),
                    models.Index(fields=['end_date']),
                ],
            },
        ),
    ]
