# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client_onboarding", "0001_initial"),
        ("core_onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bt",
            name="butype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="bu_butypes",
                to="core_onboarding.typeassist",
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="bt",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="City location for NOC geographic drill-down",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bt_cities",
                to="core_onboarding.typeassist",
                verbose_name="City",
            ),
        ),
    ]
