# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client_onboarding", "0002_initial"),
        ("core_onboarding", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bt",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="bt",
            name="identifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="bu_idfs",
                to="core_onboarding.typeassist",
                verbose_name="Identifier",
            ),
        ),
        migrations.AddField(
            model_name="bt",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="bt",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="children",
                to="client_onboarding.bt",
                verbose_name="Belongs To",
            ),
        ),
        migrations.AddField(
            model_name="bt",
            name="siteincharge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="siteincharge",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Site Incharge",
            ),
        ),
        migrations.AddField(
            model_name="bt",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="State location for NOC geographic aggregation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bt_states",
                to="core_onboarding.typeassist",
                verbose_name="State",
            ),
        ),
        migrations.AddField(
            model_name="bt",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="lastloggedinuser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Logged In User",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="downtimehistory",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="downtimehistory",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="downtimehistory",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="bu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="shift_bu",
                to="client_onboarding.bt",
                verbose_name="Business Unit",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="shift_client",
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core_onboarding.typeassist",
                verbose_name="Designation",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="assignedhandset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="client_onboarding.device",
                verbose_name="Assigned Handset",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="bt",
            index=models.Index(fields=["mdtz"], name="bt_mdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="bt",
            index=models.Index(fields=["cdtz"], name="bt_cdtz_idx"),
        ),
        migrations.AddConstraint(
            model_name="bt",
            constraint=models.UniqueConstraint(
                fields=("bucode", "parent", "identifier"),
                name="bu_bucode_parent_identifier_uk",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["mdtz"], name="device_mdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["cdtz"], name="device_cdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="downtimehistory",
            index=models.Index(fields=["mdtz"], name="downtimehistory_mdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="downtimehistory",
            index=models.Index(fields=["cdtz"], name="downtimehistory_cdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(fields=["mdtz"], name="shift_mdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(fields=["cdtz"], name="shift_cdtz_idx"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                fields=("shiftname", "bu", "designation", "client"),
                name="shiftname_bu_desgn_client_uk",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["mdtz"], name="subscription_mdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["cdtz"], name="subscription_cdtz_idx"),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("startdate", "enddate", "client"),
                name="startdate_enddate_client_uk",
            ),
        ),
    ]
