# Generated by Django 5.2.7 on 2025-11-09 10:20

import apps.peoples.models.base_model
import apps.work_order_management.managers.approver_manager
import apps.work_order_management.managers.vendor_manager
import apps.work_order_management.managers.wom_details_manager
import apps.work_order_management.managers.work_order_manager
import apps.work_order_management.models.helpers
import concurrency.fields
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activity", "0002_initial"),
        ("client_onboarding", "0002_initial"),
        ("core_onboarding", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                (
                    "code",
                    models.CharField(max_length=50, null=True, verbose_name="Code"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "gpslocation",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="GPS Location",
                    ),
                ),
                ("enable", models.BooleanField(default=True, verbose_name="Enable")),
                ("mobno", models.CharField(max_length=15, verbose_name="Mob No")),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
                (
                    "show_to_all_sites",
                    models.BooleanField(
                        default=False, verbose_name="Applicable to all sites"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "bu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="vendor_bus",
                        to="client_onboarding.bt",
                        verbose_name="Site",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="vendor_clients",
                        to="client_onboarding.bt",
                        verbose_name="Client",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_onboarding.typeassist",
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "vendor company",
                "db_table": "vendor",
                "ordering": ["mdtz"],
                "abstract": False,
            },
            managers=[
                (
                    "objects",
                    apps.work_order_management.managers.vendor_manager.VendorManager(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Job Description"),
                ),
                (
                    "plandatetime",
                    models.DateTimeField(null=True, verbose_name="Plan date time"),
                ),
                (
                    "expirydatetime",
                    models.DateTimeField(null=True, verbose_name="Expiry date time"),
                ),
                (
                    "starttime",
                    models.DateTimeField(null=True, verbose_name="Start time"),
                ),
                ("endtime", models.DateTimeField(null=True, verbose_name="Start time")),
                (
                    "gpslocation",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="GPS Location",
                    ),
                ),
                (
                    "workstatus",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Assigned"),
                            ("RE_ASSIGNED", "Re-Assigned"),
                            ("COMPLETED", "Completed"),
                            ("INPROGRESS", "Inprogress"),
                            ("CANCELLED", "Cancelled"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ASSIGNED",
                        max_length=60,
                        null=True,
                        verbose_name="Job Status",
                    ),
                ),
                (
                    "seqno",
                    models.SmallIntegerField(null=True, verbose_name="Serial No."),
                ),
                (
                    "approvers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Approvers",
                    ),
                ),
                (
                    "verifiers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Verifiers",
                    ),
                ),
                (
                    "workpermit",
                    models.CharField(
                        choices=[
                            ("NOT_REQUIRED", "Not Required"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PENDING", "Pending"),
                        ],
                        default="NOT_REQUIRED",
                        max_length=35,
                        verbose_name="Work Permit",
                    ),
                ),
                (
                    "verifiers_status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUIRED", "Not Required"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=50,
                        verbose_name="Verifier Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                        ],
                        default="LOW",
                        max_length=50,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "performedby",
                    models.CharField(max_length=55, verbose_name="Performed By"),
                ),
                (
                    "alerts",
                    models.BooleanField(
                        default=False, null=True, verbose_name="Alerts"
                    ),
                ),
                (
                    "ismailsent",
                    models.BooleanField(default=False, verbose_name="Mail Sent"),
                ),
                ("isdenied", models.BooleanField(default=False, verbose_name="Denied")),
                (
                    "geojson",
                    models.JSONField(
                        default=apps.work_order_management.models.helpers.geojson,
                        null=True,
                        verbose_name="Geo Json",
                    ),
                ),
                (
                    "other_data",
                    models.JSONField(
                        default=apps.work_order_management.models.helpers.other_data,
                        null=True,
                        verbose_name="Other Data",
                    ),
                ),
                (
                    "attachmentcount",
                    models.IntegerField(default=0, verbose_name="Attachment Count"),
                ),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default="", max_length=50
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "wo_history",
                    models.JSONField(
                        default=apps.work_order_management.models.helpers.wo_history_json,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WO", "Work Order"),
                            ("WP", "Work Permit"),
                            ("SLA", "Service Level Agreement"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Identifier",
                    ),
                ),
                (
                    "remarks",
                    models.JSONField(blank=True, null=True, verbose_name="Remarks"),
                ),
                (
                    "version",
                    concurrency.fields.VersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="wo_assets",
                        to="activity.asset",
                        verbose_name="Asset",
                    ),
                ),
                (
                    "bu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="wo_bus",
                        to="client_onboarding.bt",
                        verbose_name="Site",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="wo_clients",
                        to="client_onboarding.bt",
                        verbose_name="Client",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="activity.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="work_order_management.wom",
                        verbose_name="Belongs to",
                    ),
                ),
                (
                    "qset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="activity.questionset",
                        verbose_name="QuestionSet",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "ticketcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core_onboarding.typeassist",
                        verbose_name="Notify Category",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="work_order_management.vendor",
                        verbose_name="Vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "work order management",
                "db_table": "wom",
                "ordering": ["mdtz"],
                "abstract": False,
            },
            managers=[
                (
                    "objects",
                    apps.work_order_management.managers.work_order_manager.WorkOrderManager(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WomDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("seqno", models.SmallIntegerField(verbose_name="SL #")),
                (
                    "answertype",
                    models.CharField(
                        choices=[
                            ("CHECKBOX", "Checkbox"),
                            ("DATE", "Date"),
                            ("DROPDOWN", "Dropdown"),
                            ("EMAILID", "Email Id"),
                            ("MULTILINE", "Multiline"),
                            ("NUMERIC", "Numeric"),
                            ("SIGNATURE", "Signature"),
                            ("SINGLELINE", "Single Line"),
                            ("TIME", "Time"),
                            ("RATING", "Rating"),
                            ("BACKCAMERA", "Back Camera"),
                            ("FRONTCAMERA", "Front Camera"),
                            ("PEOPLELIST", "People List"),
                            ("SITELIST", "Site List"),
                            ("NONE", "NONE"),
                            ("MULTISELECT", "Multi Select"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Answer Type",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        default="", max_length=250, null=True, verbose_name="Answer"
                    ),
                ),
                (
                    "isavpt",
                    models.BooleanField(
                        default=False, verbose_name="Attachement Required"
                    ),
                ),
                (
                    "avpttype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BACKCAMPIC", "Back Camera Pic"),
                            ("FRONTCAMPIC", "Front Camera Pic"),
                            ("AUDIO", "Audio"),
                            ("VIDEO", "Video"),
                            ("NONE", "NONE"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Attachment Type",
                    ),
                ),
                (
                    "options",
                    models.CharField(
                        blank=True, max_length=2000, null=True, verbose_name="Option"
                    ),
                ),
                (
                    "min",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, null=True, verbose_name="Min"
                    ),
                ),
                (
                    "max",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, null=True, verbose_name="Max"
                    ),
                ),
                (
                    "alerton",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Alert On"
                    ),
                ),
                (
                    "ismandatory",
                    models.BooleanField(default=True, verbose_name="Mandatory"),
                ),
                ("alerts", models.BooleanField(default=False, verbose_name="Alerts")),
                (
                    "attachmentcount",
                    models.IntegerField(default=0, verbose_name="Attachment count"),
                ),
                (
                    "version",
                    concurrency.fields.VersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "qset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="qset_answers",
                        to="activity.questionset",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="activity.question",
                        verbose_name="",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "wom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="work_order_management.wom",
                        verbose_name="Jobneed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wom Details",
                "db_table": "womdetails",
                "ordering": ["mdtz"],
                "abstract": False,
            },
            managers=[
                (
                    "objects",
                    apps.work_order_management.managers.wom_details_manager.WOMDetailsManager(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Approver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was created",
                        verbose_name="Created date",
                    ),
                ),
                (
                    "mdtz",
                    models.DateTimeField(
                        default=apps.peoples.models.base_model.now,
                        help_text="When this record was last modified",
                        verbose_name="Modified date",
                    ),
                ),
                (
                    "ctzoffset",
                    models.IntegerField(
                        default=-1,
                        help_text="User's timezone offset in minutes",
                        verbose_name="Timezone offset",
                    ),
                ),
                (
                    "approverfor",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            max_length=50,
                            verbose_name="Approver/Verifier For",
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "sites",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=50),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Sites",
                    ),
                ),
                (
                    "forallsites",
                    models.BooleanField(default=True, verbose_name="For all sites"),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        choices=[("APPROVER", "Approver"), ("VERIFIER", "Verifier")],
                        max_length=250,
                        null=True,
                        verbose_name="Approver/Verifier",
                    ),
                ),
                (
                    "bu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="client_onboarding.bt",
                        verbose_name="",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="approver_clients",
                        to="client_onboarding.bt",
                    ),
                ),
                (
                    "cuser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_cusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "muser",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_musers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "people",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approver",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this record",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "approver",
                "db_table": "approver",
                "ordering": ["mdtz"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant", "people"], name="approver_tenant_people_idx"
                    ),
                    models.Index(
                        fields=["tenant", "identifier"],
                        name="approver_tenant_identifier_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "people", "approverfor", "sites"),
                        name="tenant_people_approverfor_sites_uk",
                    )
                ],
            },
            managers=[
                (
                    "objects",
                    apps.work_order_management.managers.approver_manager.ApproverManager(),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["tenant", "cdtz"], name="vendor_tenant_cdtz_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["tenant", "enable"], name="vendor_tenant_enable_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code", "client"), name="tenant_code_client"
            ),
        ),
        migrations.AddIndex(
            model_name="wom",
            index=models.Index(fields=["tenant", "cdtz"], name="wom_tenant_cdtz_idx"),
        ),
        migrations.AddIndex(
            model_name="wom",
            index=models.Index(
                fields=["tenant", "workstatus"], name="wom_tenant_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wom",
            index=models.Index(
                fields=["tenant", "workpermit"], name="wom_tenant_permit_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wom",
            constraint=models.UniqueConstraint(
                fields=("tenant", "qset", "client", "id"), name="tenant_qset_client"
            ),
        ),
        migrations.AddIndex(
            model_name="womdetails",
            index=models.Index(
                fields=["tenant", "wom"], name="womdetails_tenant_wom_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="womdetails",
            index=models.Index(
                fields=["tenant", "question"], name="womdetails_tenant_question_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="womdetails",
            constraint=models.UniqueConstraint(
                fields=("tenant", "question", "wom"), name="tenant_question_client"
            ),
        ),
    ]
