# Generated by Django 5.2.7 on 2025-11-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client_onboarding", "0003_initial"),
        ("noc", "0001_initial"),
        ("noc_security_intelligence", "0001_initial"),
        ("peoples", "0001_initial"),
        ("tenants", "0001_initial"),
        ("work_order_management", "0001_initial"),
        ("y_helpdesk", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alertcluster",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="alertcluster",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="alertcluster",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="correlatedincident",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="correlatedincident",
            name="investigated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Investigator",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigated_incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correlatedincident",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="correlatedincident",
            name="person",
            field=models.ForeignKey(
                help_text="Person involved in incident",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correlated_incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correlatedincident",
            name="site",
            field=models.ForeignKey(
                help_text="Site where incident occurred",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correlated_incidents",
                to="client_onboarding.bt",
            ),
        ),
        migrations.AddField(
            model_name="correlatedincident",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="executableplaybook",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="executableplaybook",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="executableplaybook",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="incidentcontext",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="incidentcontext",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="incidentcontext",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindow",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific BU for maintenance (null = all BUs in client)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noc_maintenance_windows",
                to="client_onboarding.bt",
                verbose_name="Business Unit",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindow",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client for maintenance window (null = all clients)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindow",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindow",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindow",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindow",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="mlmodelmetrics",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="mlmodelmetrics",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nocalertevent",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="noc_alerts_acknowledged",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nocalertevent",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="noc_alerts_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nocalertevent",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noc_alerts",
                to="client_onboarding.bt",
                verbose_name="Business Unit",
            ),
        ),
        migrations.AddField(
            model_name="nocalertevent",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="nocalertevent",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nocalertevent",
            name="escalated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="noc_alerts_escalated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nocalertevent",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nocalertevent",
            name="parent_alert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_alerts",
                to="noc.nocalertevent",
                verbose_name="Parent Alert",
            ),
        ),
        migrations.AddField(
            model_name="nocalertevent",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="noc_alerts_resolved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nocalertevent",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="correlatedincident",
            name="related_alerts",
            field=models.ManyToManyField(
                blank=True,
                help_text="NOC alerts correlated with this incident",
                related_name="correlated_incidents",
                to="noc.nocalertevent",
            ),
        ),
        migrations.AddField(
            model_name="alertcluster",
            name="primary_alert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_for_cluster",
                to="noc.nocalertevent",
                verbose_name="Primary Alert",
            ),
        ),
        migrations.AddField(
            model_name="alertcluster",
            name="related_alerts",
            field=models.ManyToManyField(
                related_name="alert_clusters",
                to="noc.nocalertevent",
                verbose_name="Related Alerts",
            ),
        ),
        migrations.AddField(
            model_name="nocauditlog",
            name="actor",
            field=models.ForeignKey(
                help_text="User who performed the action",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actor",
            ),
        ),
        migrations.AddField(
            model_name="nocauditlog",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
                verbose_name="Tenant",
            ),
        ),
        migrations.AddField(
            model_name="nocdashboardconfig",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nocdashboardconfig",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nocdashboardconfig",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nocdashboardconfig",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noc_dashboard_config",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="noceventlog",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="noceventlog",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="noceventlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nocexporthistory",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nocexporthistory",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nocexporthistory",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nocexporthistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noc_export_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="nocexporttemplate",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nocexporttemplate",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nocexporttemplate",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nocexporttemplate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noc_export_templates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="nocexporthistory",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="noc.nocexporttemplate",
                verbose_name="Template Used",
            ),
        ),
        migrations.AddField(
            model_name="nocincident",
            name="alerts",
            field=models.ManyToManyField(
                help_text="Alerts grouped into this incident",
                related_name="incidents",
                to="noc.nocalertevent",
                verbose_name="Alerts",
            ),
        ),
        migrations.AddField(
            model_name="nocincident",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned To",
            ),
        ),
        migrations.AddField(
            model_name="nocincident",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="nocincident",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nocincident",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nocincident",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="noc_incidents",
                to="client_onboarding.bt",
                verbose_name="Site",
            ),
        ),
        migrations.AddField(
            model_name="nocincident",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nocincident",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="y_helpdesk.ticket",
                verbose_name="Linked Ticket",
            ),
        ),
        migrations.AddField(
            model_name="nocincident",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="work_order_management.wom",
                verbose_name="Linked Work Order",
            ),
        ),
        migrations.AddField(
            model_name="incidentcontext",
            name="incident",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrichment_context",
                to="noc.nocincident",
                verbose_name="Incident",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific business unit for drill-down",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noc_metrics",
                to="client_onboarding.bt",
                verbose_name="Business Unit",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot",
            name="client",
            field=models.ForeignKey(
                help_text="Root client business unit",
                on_delete=django.db.models.deletion.CASCADE,
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot",
            name="oic",
            field=models.ForeignKey(
                blank=True,
                help_text="Site officer in charge for filtering",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Officer in Charge",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot",
            name="pgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peoples.pgroup",
                verbose_name="People Group",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot1day",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noc_metrics_1day",
                to="client_onboarding.bt",
                verbose_name="Business Unit",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot1day",
            name="client",
            field=models.ForeignKey(
                help_text="Root client business unit",
                on_delete=django.db.models.deletion.CASCADE,
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot1day",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot1day",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot1day",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot1hour",
            name="bu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noc_metrics_1hour",
                to="client_onboarding.bt",
                verbose_name="Business Unit",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot1hour",
            name="client",
            field=models.ForeignKey(
                help_text="Root client business unit",
                on_delete=django.db.models.deletion.CASCADE,
                to="client_onboarding.bt",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot1hour",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot1hour",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot1hour",
            name="oic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Officer in Charge",
            ),
        ),
        migrations.AddField(
            model_name="nocmetricsnapshot1hour",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nocsavedview",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nocsavedview",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nocsavedview",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have access to this shared view",
                related_name="shared_noc_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Shared With",
            ),
        ),
        migrations.AddField(
            model_name="nocsavedview",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nocsavedview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noc_saved_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="nocscheduledexport",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="nocscheduledexport",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="nocscheduledexport",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="noc.nocexporttemplate",
                verbose_name="Export Template",
            ),
        ),
        migrations.AddField(
            model_name="nocscheduledexport",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="nocscheduledexport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noc_scheduled_exports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="playbookexecution",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved execution",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_playbook_executions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playbookexecution",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="playbookexecution",
            name="finding",
            field=models.ForeignKey(
                help_text="Finding that triggered this execution",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playbook_executions",
                to="noc_security_intelligence.auditfinding",
            ),
        ),
        migrations.AddField(
            model_name="playbookexecution",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="playbookexecution",
            name="playbook",
            field=models.ForeignKey(
                help_text="Playbook being executed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="noc.executableplaybook",
            ),
        ),
        migrations.AddField(
            model_name="playbookexecution",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="predictivealerttracking",
            name="alert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="predictive_tracking",
                to="noc.nocalertevent",
                verbose_name="Alert Created",
            ),
        ),
        migrations.AddField(
            model_name="predictivealerttracking",
            name="cuser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_cusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="predictivealerttracking",
            name="muser",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s_musers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="predictivealerttracking",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="executableplaybook",
            index=models.Index(
                fields=["tenant", "auto_execute", "is_active"],
                name="noc_executa_tenant__7b88b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="executableplaybook",
            index=models.Index(
                fields=["tenant", "is_active"], name="noc_executa_tenant__0246db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancewindow",
            index=models.Index(
                fields=["start_time", "end_time"], name="noc_maint_time_range"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancewindow",
            index=models.Index(
                fields=["client", "start_time"], name="noc_maint_client_start"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancewindow",
            index=models.Index(
                fields=["is_active", "start_time"], name="noc_maint_active"
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodelmetrics",
            index=models.Index(
                fields=["model_type", "-training_date"],
                name="noc_ml_mode_model_t_f8dfc1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodelmetrics",
            index=models.Index(
                fields=["model_type", "is_active"],
                name="noc_ml_mode_model_t_979cf0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodelmetrics",
            index=models.Index(
                fields=["is_active", "model_type", "-training_date"],
                name="noc_ml_mode_is_acti_161eeb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mlmodelmetrics",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("model_type",),
                name="unique_active_model_per_type",
            ),
        ),
        migrations.AddIndex(
            model_name="nocalertevent",
            index=models.Index(
                fields=["tenant", "status", "-cdtz"], name="noc_alert_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="nocalertevent",
            index=models.Index(fields=["correlation_id"], name="noc_alert_correlation"),
        ),
        migrations.AddIndex(
            model_name="nocalertevent",
            index=models.Index(fields=["dedup_key"], name="noc_alert_dedup"),
        ),
        migrations.AddIndex(
            model_name="nocalertevent",
            index=models.Index(
                fields=["-calculated_priority", "-cdtz"], name="noc_alert_priority"
            ),
        ),
        migrations.AddConstraint(
            model_name="nocalertevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["NEW", "ACKNOWLEDGED", "ASSIGNED"])),
                fields=("tenant", "dedup_key", "status"),
                name="noc_alert_unique_active",
            ),
        ),
        migrations.AddIndex(
            model_name="correlatedincident",
            index=models.Index(
                fields=["tenant", "person", "detected_at"],
                name="noc_correla_tenant__e07a28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correlatedincident",
            index=models.Index(
                fields=["tenant", "site", "detected_at"],
                name="noc_correla_tenant__282ac7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correlatedincident",
            index=models.Index(
                fields=["combined_severity", "investigated"],
                name="noc_correla_combine_60a765_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correlatedincident",
            index=models.Index(
                fields=["detected_at", "combined_severity"],
                name="noc_correla_detecte_c20334_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertcluster",
            index=models.Index(
                fields=["tenant", "is_active", "-last_alert_at"],
                name="noc_cluster_active",
            ),
        ),
        migrations.AddIndex(
            model_name="alertcluster",
            index=models.Index(
                fields=["cluster_signature"], name="noc_cluster_signature"
            ),
        ),
        migrations.AddIndex(
            model_name="alertcluster",
            index=models.Index(fields=["tenant", "-cdtz"], name="noc_cluster_tenant"),
        ),
        migrations.AddIndex(
            model_name="nocauditlog",
            index=models.Index(
                fields=["tenant", "created_at"], name="noc_audit_tenant_time"
            ),
        ),
        migrations.AddIndex(
            model_name="nocauditlog",
            index=models.Index(
                fields=["actor", "created_at"], name="noc_audit_actor_time"
            ),
        ),
        migrations.AddIndex(
            model_name="nocauditlog",
            index=models.Index(
                fields=["entity_type", "entity_id"], name="noc_audit_entity"
            ),
        ),
        migrations.AddIndex(
            model_name="noceventlog",
            index=models.Index(
                fields=["tenant", "-broadcast_at"],
                name="noc_event_l_tenant__d44565_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="noceventlog",
            index=models.Index(
                fields=["event_type", "-broadcast_at"],
                name="noc_event_l_event_t_29f07c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="noceventlog",
            index=models.Index(
                fields=["broadcast_at", "event_type"],
                name="noc_event_l_broadca_ae9072_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="noceventlog",
            index=models.Index(
                fields=["alert_id", "-broadcast_at"],
                name="noc_event_l_alert_i_4d6838_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="noceventlog",
            index=models.Index(
                fields=["finding_id", "-broadcast_at"],
                name="noc_event_l_finding_05298b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="noceventlog",
            index=models.Index(
                fields=["ticket_id", "-broadcast_at"],
                name="noc_event_l_ticket__bf9df6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nocexporttemplate",
            index=models.Index(
                fields=["tenant", "user"], name="noc_export__tenant__28191c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nocexporttemplate",
            index=models.Index(
                fields=["entity_type"], name="noc_export__entity__264d52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nocexporttemplate",
            index=models.Index(
                fields=["is_public"], name="noc_export__is_publ_b8dace_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nocexporttemplate",
            unique_together={("tenant", "user", "name")},
        ),
        migrations.AddIndex(
            model_name="nocexporthistory",
            index=models.Index(
                fields=["tenant", "user", "-cdtz"],
                name="noc_export__tenant__080517_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nocexporthistory",
            index=models.Index(
                fields=["entity_type"], name="noc_export__entity__b989ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nocexporthistory",
            index=models.Index(
                fields=["expires_at"], name="noc_export__expires_8d3bf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nocincident",
            index=models.Index(
                fields=["tenant", "state", "-cdtz"], name="noc_incident_tenant_state"
            ),
        ),
        migrations.AddIndex(
            model_name="nocincident",
            index=models.Index(
                fields=["client", "state"], name="noc_incident_client_state"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentcontext",
            index=models.Index(
                fields=["tenant", "cache_expires_at"], name="noc_ctx_tenant_exp"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentcontext",
            index=models.Index(fields=["incident"], name="noc_ctx_incident"),
        ),
        migrations.AddIndex(
            model_name="nocmetricsnapshot",
            index=models.Index(
                fields=["tenant", "client", "window_end"],
                name="noc_metric_tenant_client",
            ),
        ),
        migrations.AddIndex(
            model_name="nocmetricsnapshot",
            index=models.Index(
                fields=["tenant", "window_end"], name="noc_metric_tenant_time"
            ),
        ),
        migrations.AddIndex(
            model_name="nocmetricsnapshot",
            index=models.Index(
                fields=["city", "window_end"], name="noc_metric_city_time"
            ),
        ),
        migrations.AddIndex(
            model_name="nocmetricsnapshot",
            index=models.Index(
                fields=["state", "window_end"], name="noc_metric_state_time"
            ),
        ),
        migrations.AddIndex(
            model_name="nocmetricsnapshot",
            index=models.Index(
                fields=["oic", "window_end"], name="noc_metric_oic_time"
            ),
        ),
        migrations.AddIndex(
            model_name="nocmetricsnapshot1day",
            index=models.Index(
                fields=["tenant", "client", "date"], name="noc_1d_tenant_client"
            ),
        ),
        migrations.AddIndex(
            model_name="nocmetricsnapshot1day",
            index=models.Index(fields=["tenant", "date"], name="noc_1d_tenant_date"),
        ),
        migrations.AddIndex(
            model_name="nocmetricsnapshot1day",
            index=models.Index(fields=["computed_at"], name="noc_1d_computed"),
        ),
        migrations.AddConstraint(
            model_name="nocmetricsnapshot1day",
            constraint=models.UniqueConstraint(
                fields=("tenant", "client", "date"),
                name="unique_daily_snapshot_per_client",
            ),
        ),
        migrations.AddIndex(
            model_name="nocmetricsnapshot1hour",
            index=models.Index(
                fields=["tenant", "client", "window_start"], name="noc_1h_tenant_client"
            ),
        ),
        migrations.AddIndex(
            model_name="nocmetricsnapshot1hour",
            index=models.Index(
                fields=["tenant", "window_start"], name="noc_1h_tenant_time"
            ),
        ),
        migrations.AddIndex(
            model_name="nocmetricsnapshot1hour",
            index=models.Index(fields=["computed_at"], name="noc_1h_computed"),
        ),
        migrations.AddIndex(
            model_name="nocsavedview",
            index=models.Index(
                fields=["tenant", "user", "is_default"],
                name="noc_saved_v_tenant__196893_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nocsavedview",
            index=models.Index(
                fields=["is_shared"], name="noc_saved_v_is_shar_eeb522_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nocsavedview",
            index=models.Index(
                fields=["last_used_at"], name="noc_saved_v_last_us_b6b90a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nocsavedview",
            unique_together={("tenant", "user", "name")},
        ),
        migrations.AddIndex(
            model_name="nocscheduledexport",
            index=models.Index(
                fields=["tenant", "is_active", "next_run_at"],
                name="noc_schedul_tenant__1a2883_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nocscheduledexport",
            index=models.Index(
                fields=["schedule_type"], name="noc_schedul_schedul_523eec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playbookexecution",
            index=models.Index(
                fields=["tenant", "status", "-cdtz"],
                name="noc_playboo_tenant__d2fcd7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="playbookexecution",
            index=models.Index(
                fields=["playbook", "-cdtz"], name="noc_playboo_playboo_888859_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playbookexecution",
            index=models.Index(
                fields=["finding", "-cdtz"], name="noc_playboo_finding_bb7fe6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playbookexecution",
            index=models.Index(
                fields=["-started_at"], name="noc_playboo_started_21940b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="predictivealerttracking",
            index=models.Index(
                fields=["tenant", "prediction_type", "-predicted_at"],
                name="noc_predict_tenant_type",
            ),
        ),
        migrations.AddIndex(
            model_name="predictivealerttracking",
            index=models.Index(
                fields=["validation_deadline", "validated_at"],
                name="noc_predict_validation",
            ),
        ),
        migrations.AddIndex(
            model_name="predictivealerttracking",
            index=models.Index(
                fields=["prediction_type", "prediction_correct"],
                name="noc_predict_accuracy",
            ),
        ),
        migrations.AddIndex(
            model_name="predictivealerttracking",
            index=models.Index(
                fields=["confidence_bucket", "prediction_correct"],
                name="noc_predict_confidence",
            ),
        ),
    ]
